### ISSUE TITLE
Atendance View

### ISSUE THREAD

**Issue by afonsohfontes** [Alumian/CEPGP-Retail#1]
CEPGP is awesome, congratulations on your work. Any chance we might see an Attendance view on this addon? Like the one EPGP Attendance used to show us. https://www.wowace.com/projects/epgp-attendance

![image](https://user-images.githubusercontent.com/21039838/59943195-fc637780-9437-11e9-9537-a47a85feb4b4.png)

**Comment by Alumian** [comment]
Hi Afonsohfontes,
Thanks for the feedback and question. I'll look into the feasibility of this feature and get back to you, but I think it's a great idea!

**Comment by afonsohfontes** [comment]
I used to use EPGP Attendance back in WotLK. It is a great thing to add! All other todays attendance tracking methods out there don't count replaces for a raid. I have been using excel sheets to track attendance ever since EPGP Attendance got abandoned and it sucks :).

Thank you very much for considering adding this view. I am sure it will be of great help for the community.

**Comment by Alumian** [comment]
Do you know what information you would like displayed in this feature? Or would you like me to implement more or less what is shown in that screenshot?

**Comment by afonsohfontes** [comment]
In my opinion, there is no need to show EP, GP and PR, we have another view for that. It would be enough to have a list with everyone's attendance and the possibility to sort (or organize) by periods of 15 days instead of 30 days like the image shows.

EPGP Attendance (the one from the link) used to calculate the attendance percentage based on the viewer's log. The viewer always had 100% attendance and all others % were calculated based on (i believe) the total amount of EP earned in that period. If I missed one of the raids, I had to ask for a screenshot of this view from someone who didn't in order to get the real attendance.
So there is no big deal in not "correcting" this. This also happens in all other attendance tracking addons that I know of.

**Comment by Alumian** [comment]
Sounds good, I have do have concerns for the efficiency of the addon if I store too many records, so I might set an upper limit (which I will allow to be defined in the options menu). I'm thinking maybe like 3 months but I want to see how it impacts performance.
At this stage however, I do want you to know that I won't be able to implement this feature until the Classic launch. Reason being, I unfortunately don't have access to the beta and the stress test was really my only opportunity to do bug/feature testing. Since the current retail API is not 100% compatible with the new Classic API, I can't test it on retail. But I am happy to implement this feature for you.

**Comment by afonsohfontes** [comment]
Many thanks! If by any chance we have another stress test, I will be glad to help you debug the addon.

**Comment by Alumian** [comment]
No problem, actually now that you mention it I think there is one more stress test period Thursday - Friday the 18th and 19th of July, but I'm not sure if that's exclusive to EU or not. If it's not, then I'll definitely be working to add this feature during that period.

**Comment by afonsohfontes** [comment]
If the next stress comes to NA servers again, I will be more than happy to help you test whatever you need. Count me in.

**Comment by afonsohfontes** [comment]
Is there anything you wish me to test during this pre-launch event?

**Comment by Alumian** [comment]
Hey Afonso,
The only help I could really use is just signing a dummy guild charter since to be able to test a lot of features, I need to be in a guild.
I'll be playing on the Oceanic realm by the name Alorean if you're keen to help out. I'll be online in probably like 3.5 hours or so.

Thanks

**Comment by Alumian** [comment]
Hey @afonsohfontes are you around? Could use some signatures lol

**Comment by Alumian** [comment]
Hi @afonsohfontes,

My apologies but I haven't been able to implement your feature request during this final stress test as I ran out of time. I'll be sure to work on it after Classic WoW has been released and I'll keep this ticket open until then.

Thanks,
Alumian

**Comment by Alumian** [comment]
@afonsohfontes since the stress test was extended to Monday, I was able to sneak this feature in. It's not done yet to the extent that I wanted it at this stage, but I'll keep working on it until the stress test closes.
