### ISSUE TITLE
[Request] EPGP CSV Export

### ISSUE THREAD

**Issue by Bonkeybee** [Alumian/CEPGP-Retail#10]
I didn't see this in the documentation or during my brief skim through the code; It would be very helpful if we had a way to export the current EPGP data into a .csv file to be used in other applications (ex: website).

Example:
[player],[level],[class],[rank],[ep],[gp]
[player2],...

**Comment by Alumian** [comment]
Hey Bonkybee,

Thanks for submitting this request! I've actually had a lot of people ask me about this recently so yep I'll be implementing this.
I've already got a few ideas on how I want to approach this, currently I plan to give an option to export to either raw or hex depending on what you choose, but yeah I don't anticipate that it'll be difficult to do.
Currently I am in the middle of working on a different feature request which im almost done with but I can't resume development until classic launches, but don't worry you're in the queue.

Thanks,
Alumian

**Comment by Alumian** [comment]
Hey Bonkybee,
Sorry for the delay in having this implemented. In addition to maintaining this addon, I'm also running a raiding guild so at this stage I'm prioritising leveling. As soon as I hit 60 (Currently 40 at the time of writing this), I'll be prioritising implementing feature requests.

Thanks

**Comment by VivoSomnio** [comment]
WHAT?!?  Prioritizing enjoying the game over making features for others? How dare you??? ;-)

Although to be fair, you and your friends are supposed to be joining MY raiding guild.  For shame!

**Comment by VivoSomnio** [comment]
On a side note, any thoughts to making it so you're able to export the data as html as well?  Just curious, not really super high priority.

**Comment by Leandros** [comment]
It would be great if we could also export the items each raider has received in the current raid. We're using EQDKPlus to track our EPGP standings and entering everything manually is quite a bit of work.

**Comment by skombag** [comment]
want to bump this feature  , our guild needs this for website and extra bank awards we use a Spreadsheet for <3 would love to see any sort of export will make it work with whatever it is

**Comment by Alumian** [comment]
Hey everyone,
Sorry these features are taking so long to implement. Between leading my guild and raiding, a heap of unexpected bugs which didn't show up in small scale testing have popped up. Rest assured that I haven't forgotten about these feature requests and I'll get them implemented as soon as I can.
As for this feature, I've already written the XML for the window, but I did have to stop working on it abruptly due to a critical bug. So it's part way done at this stage :)

**Comment by Alumian** [comment]
Okay so now that I finally have a moment to breathe lol, I'm going to finish off this feature. So I've already finished the CSV formatting, @VivoSomnio can you show me an example of how you'd like it exported to html? When you say export it to HTML....XML comes to mind, which I can definitely do, I just wanted to clarify.

**Comment by Fluuse** [comment]
Would be nice if the exported logs could show who got which item, at the moment my guild mates can`t see who gets what in the 'Traffic'. Lots of them are new to EP/GP and that would make it more transparent and insuring that noone is cheating. Really liked the logs on the retail EPGP, where you could just log in, upload and share with the guild. I would really appreciate something like that.

**Comment by Alumian** [comment]
Hi Fluuse,
As that is a different feature from the original post, can you please submit a new feature request specifically for the traffic logs. As previously mentioned, I can't merge the roster and traffic logs as time data is not recorded in either one. This will have to be done as two independent exports.
