### ISSUE TITLE
[Bug] Standby list not being shared with assists

### ISSUE THREAD

**Issue by mykkenny** [Alumian/CEPGP-Retail#101]
**The Error**
N/A

**Describe the bug**
Players on my standby list (I was RL and ML) are not being shared with assists.

**To Reproduce**
Be raid leader & master looter, have at least one assist with addon. Have a player whisper you to be placed on standby, that information is not shared to assist.

**Comment by Alumian** [comment]
Resolved in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.6.
