### ISSUE TITLE
[Request] Global channels for reporting

### ISSUE THREAD

**Issue by esfdk** [Alumian/CEPGP-Retail#104]
As a loot master, I would like to have the CEPGP addon report EP/GP changes to a global channel (in my case, a channel joined through /join DauntlessEPGP).

This would prevent spam in guild or officer chat and keep it as an "opt-in" feature.

This isn't a high priority issue, though. :)

**Comment by Alumian** [comment]
Added in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.6
