### ISSUE TITLE
[Request]standardise the decay/inflation system

### ISSUE THREAD

**Issue by Jozh89** [Alumian/CEPGP-Retail#106]
Currently when doing a decay, putting -20 will give the guild +20%. and just "20" will will give the guild -20%.
If lowering ep or gp for a invidivual putting -20 will lower it.

is it possible for these functions to - is alwasy negative, and + always posative.

**Comment by mykkenny** [comment]
Isn't the -ve part from doing the weekly decay implicit in the word 'decay'?

**Comment by DeanAles** [comment]
Decay that word mean decay. You are requesting something weird.

**Comment by Alumian** [comment]
Made the text description slightly more informative in the next version.
