### ISSUE TITLE
[Bug]NOT working on Chinese client，please help us，we need this Addon

### ISSUE THREAD

**Issue by vincent427** [Alumian/CEPGP-Retail#107]
**Describe the bug**
Hi,I'm a guild president from China.Thanks for your addons,it made our  EPGP system worked.But it still have some problems.we really need you help.
When i run the addons with English Client,it works prefect.Except the order of "standby" doesnt work when any Chinese ID PM me.
When i turned my client back to Chinese,Most of automaticlly function doesnt work well,Only can do it Manually. such as it doesnt add Boss killing EP automatically. and doesnt assign the items and add GP by the addons etc.
I think i find out the cause,when any items or players using Chinese ID ,First word of their ID being ignore.
For Example,the addons replyme "error ‘国人‘ ’is not in the guild" when ID names "中国人" Pm me "standby".It ignore the first word "中".This thing may cause the addons work with wrong.

Thanks for your great work，Looking forward to your reply

**Comment by Alumian** [comment]
Hey Vincent,
Yeah I found this bug also with the Russian client. When ever I tried to convert strings to uppercase or lowercase, it would cut off the first character sometimes. I'll look into this to try and work out a solution. Also yes automatic EP isn't working for non-English clients because at the moment it works off boss names. I'm currently working on localising the client.

**Comment by Owersun** [comment]
There is a pull request with implemented localisation working on Russian client open from me. Check it out, it pretty easy to extend it to more languages and translate more things

**Comment by Alumian** [comment]
Yeah I saw that it looks great. Would you be able to drop me a message on discord sometime? Alumian#6465
Just wanted to ask about your code :)

**Comment by Owersun** [comment]
Sure, I've dropped you a note as OverSun#6008, I guess you have pretty big chat list opened ;)

**Comment by Alumian** [comment]
Localisation has been added in recent versions. Please try downloading 1.12.7 beta 3 from the CEPGP discord and let me know if the issue persists.

**Comment by Alumian** [comment]
Issue resolved in release 1.12.7.
