### ISSUE TITLE
[Bug] Restoring Standings does not work

### ISSUE THREAD

**Issue by gavin58582** [Alumian/CEPGP-Retail#109]
**The Error**
There is no Error message

**Describe the bug**
I cannot use a Saved Standings to restore to the Guild EPGP info.   I also cannot Export the Standings

**To Reproduce**
Put some EP and GP on different members.   Click Save Standings and type in test and save that setting.    
Click on Reset All EPGP Standings
Then go to Restore Standings, select the save standing test and click confirm twice.   

No Standings gets replaced in the Window.  Yet if you go into the player's Officer notes you will see information.

Also if you click on Export Standings the Export function does not work.  

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.

**Comment by Alumian** [comment]
The bug where it doesn't update in your CEPGP guild window is cosmetic. I have implemented a fix for that in next update. If you reload your UI that will fix it.
For it shuffling the EPGP standings, I have implemented a possible fix in the current beta.
When you say export isn't working, what isn't it doing? Are there errors? Does the window not show? Can you not interact with the window? Is it blank? Did you try again after reloading your UI?

**Comment by Alumian** [comment]
Also, as per the last section of the bug report, type /cep debug and copy and paste what it says into this report.

**Comment by gavin58582** [comment]
<details><summary>Debug Info</summary><br />
Version: 1.12.5<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br /><br />
<details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Lord Kri: True<br />
Emperor Vek'nilash: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Lady Blaumeux: True<br />
Highlord Mograine: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Teremus the Devourer: True<br />
Jin'do the Hexxer: True<br />
Baron Geddon: True<br />
Renataki: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
Bloodlord Mandokir: True<br />
Patchwerk: True<br />
Vaelastrasz the Corrupt: True<br />
Gluth: True<br />
Sapphiron: True<br />
Emeriss: True<br />
Onyxia: True<br />
Princess Yauj: True<br />
Kurinnaxx: True<br />
Shazzrah: True<br />
Ebonroc: True<br />
Battleguard Sartura: True<br />
Hakkar: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Viscidus: True<br />
Broodlord Lashlayer: True<br />
Ayamiss the Hunter: True<br />
Ragnaros: True<br />
Maexxna: True<br />
Ouro: True<br />
Vem: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Sir Zeliek: True<br />
Gahz'ranka: True<br />
Emperor Vek'lor: True<br />
High Priestess Arlokk: True<br />
Firemaw: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Lord Kri: 10<br />
Emperor Vek'nilash: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Lady Blaumeux: 15<br />
Highlord Mograine: 15<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Teremus the Devourer: 7<br />
Jin'do the Hexxer: 2<br />
Baron Geddon: 5<br />
Renataki: 2<br />
Sulfuron Harbinger: 5<br />
Gri'lek: 2<br />
Bloodlord Mandokir: 2<br />
Patchwerk: 12<br />
Vaelastrasz the Corrupt: 7<br />
Gluth: 12<br />
Sapphiron: 15<br />
Emeriss: 7<br />
Onyxia: 5<br />
Princess Yauj: 10<br />
Kurinnaxx: 3<br />
Shazzrah: 5<br />
Ebonroc: 7<br />
Battleguard Sartura: 10<br />
Hakkar: 3<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Viscidus: 10<br />
Broodlord Lashlayer: 7<br />
Ayamiss the Hunter: 3<br />
Ragnaros: 7<br />
Maexxna: 15<br />
Ouro: 10<br />
Vem: 10<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 7<br />
Magmadar: 5<br />
Sir Zeliek: 15<br />
Gahz'ranka: 2<br />
Emperor Vek'lor: 10<br />
High Priestess Arlokk: 2<br />
Firemaw: 7<br />
Chromaggus: 7<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
Officer: False<br />
Officer Alts: False<br />
Veteran: False<br />
Raider: False<br />
Member: False<br />
Alt: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
RANGED: 0.5<br />
THROWN: 0.5<br />
FEET: 0.75<br />
RELIC: 0.5<br />
RANGEDRIGHT: 0.5<br />
WEAPONOFFHAND: 0.5<br />
TRINKET: 0.75<br />
FINGER: 0.5<br />
CLOAK: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
LEGS: 1<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AuctionFaster<br />
CEPGP<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by gavin58582** [comment]
I click the Export to CSV button and I would think that the CSV would get exported to the World of warcraft classic install folder.  However the CSV is not there.  I even checked the Addon's Folder.

**Comment by Alumian** [comment]
Blizzard has blocked all I/O functionality for addons, so they are unable to produce new files. The export to CSV merely formats the information displayed in the window to a CSV format. I admit that this is not particularly obvious at the moment - I do plan to add additional formats which hopefully, will make this more obvious.

**Comment by gavin58582** [comment]
Ok so I would need to copy and paste that into my own csv file.   Ok Got it.   Thank you for your help.  I also did a reload ui and the restore standings works.

**Comment by gavin58582** [comment]
Also one more thing I use to use EPGP back in WOTLK.   When I would hover over an item it would tell me the GP cost of the item.  Does this addon do the same thing?

**Comment by Alumian** [comment]
Not a problem. You should join the discord and keep an eye on the beta versions that come out. I'm starting to delay my releases now because of the calamity that was version 1.12.0. that was a nightmare. All of my beta versions get posted to the discord first.

**Comment by Alumian** [comment]
Yeah I added gp values on tooltips recently. There's an option for it on page 2.

**Comment by Alumian** [comment]
Alright a potential fix has been implemented for scrambling the EPGP standings. Please download the latest beta version from the discord. I'm going to close this ticket and refer to #112 since that ticket is solely about the EPGP scrambling issue. Please refer to that ticket for future progress.
