### ISSUE TITLE
[Question] Standby Functionality

### ISSUE THREAD

**Issue by qrsu0203** [Alumian/CEPGP-Retail#11]
Hi, sorry if this was explained somewhere but I was unable to find an answer: Will the standby list track members who alt log somehow? Like say if we had officer notes on alts to tie them back to their mains can we grant them EP through the standby list even if they appear offline?

Thanks for all your hard work!

**Comment by Alumian** [comment]
Hey Qrsu0203,

Thanks for the question. So just a few points I want to touch down on just to clarify. You can't make additional notes in the officer notes while running CEPGP. The addon will misinterpret this as a malformed entry and salvage what it thinks is the EPGP value. Having said that, you can manually specify characters for the standby list and you can set it to award EP to offline players (there's a button in the options menu to do this). At this stage, you are unable to link a main and an alt together.

I hope that answered your question.

Thanks!

**Comment by qrsu0203** [comment]
Thanks for your quick response. It might be challenging to manage who should legitimately receive EP if they go offline to an alt -- will require a bit of coordination on my part I suppose. We're having a blast figuring out our ruleset and this was one of the items I was wondering.

Thanks for your response!
