### ISSUE TITLE
MinEP [Request]

### ISSUE THREAD

**Issue by DeanAles** [Alumian/CEPGP-Retail#110]
Hey Aluminian,

i think this feature is important in EPGP loot system, because after some raids with my mates, we have still new ones who wasnt in raid or they are new in guild and want to raid with us, but after 1hour they can loot first item and this is not fair for raiders with 350ep+.

For that was in days back MinEP standing
more info here: http://www.epgpweb.com/help/configuration

Ill appreciate that feature, because in loot table u see who had that minep standing who not, because who have white row have minep and who is not is under him and his row is grey.

**Comment by PibbzTV** [comment]
We worked around this exact issue by giving 25 GP (equal to 1 item and 5 base GP) to each member the first time they raid. It's manual, but it works wonderfully. This gives the new raiders much lower priority on their first raid, and they shouldnt be able to hog high-value loot from domo & rag in their first raid over veterans that have not recieved much loot lately. On the other hand, it doensnt exclude them from rolling like a Minimum EP system would do. It also evens out with the weekly decay, giving new raiders a smooth transition into raiding.

If the addon could have a "Starting GP" value for those first timers entering a raid with 0 EP, and a different value "Base GP" with regards to decay, this would be a neat way to solve issues like this.

**Comment by DeanAles** [comment]
If you give someone new GP for no reason it looks bad, but if u told them u must have atleast 300ep for be able need on everything sounds much better. 
You must work with what looks bad and what looks ok, because this sounds nicer if u tell someting like " u must reach something, than you will receive negative points, because " you give him oportunity show how much he want raiding (be prepared, waiting before instance when raid time is closer, be on standby)
Be guild master is not easy and you must do this psychologic stuff.

For me sounds much better have minEP than baseGP, i was using epgp more than 5years and this loot system works great.

**Comment by PibbzTV** [comment]
Yea that's what's great about it. It's so many different approaches to the same system :)
For us, the starting GP was the one that worked best :)

**Comment by Owersun** [comment]
You are missing main point of EPGP system then. Which is "decay after every raid". Which makes the situation of 350+ EP impossible, you need to kill ton of bosses each raid to gather that much.
This is exactly why the system is better than DKP - you cannot really store so much points noone can beat you. Same goes for newcomers. If you decay 10% of EPGP every raid the number is always somewhat sane even for long time members. And since gain is absolute it's pretty easy for newcomers to catch-up in few raids which is exactly the time they should see the first loot.

**Comment by PibbzTV** [comment]
> 
> 
> You are missing main point of EPGP system then. Which is "decay after every raid". Which makes the situation of 350+ EP impossible, you need to kill ton of bosses each raid to gather that much.
> This is exactly why the system is better than DKP - you cannot really store so much points noone can beat you. Same goes for newcomers. If you decay 10% of EPGP every raid the number is always somewhat sane even for long time members. And since gain is absolute it's pretty easy for newcomers to catch-up in few raids which is exactly the time they should see the first loot.

The problem the OP is discussing is happening with decay aswell tho. We have 20% deacay each week, 10 EP pr boss, and a base GP of 5 to encourage people to take loot because GP would decay faster that way.

After 8 bosses, the new guy would have 80 EP and 5 GP and a total PR of 16, which would give them pretty much whatever they wanted from Domo or Rag.

**Comment by DeanAles** [comment]
@Owersun this is not true, we are giving 
10ep/per hour (manualy)
10ep for being intime on spot, who will come after our start time is not able receive bonus (manualy)
first clean kill of onyxia 10ep (manualy)
boss kills > in future BWL bosses will give us more EP for kills (MC/Onyxia/BWL and so on = more EP)
and other bonus EP for raiders if they do what we want.
I am thinking about give raiders bonus of ep if everyone will be prepared for ragnaros with resist pots and other self buff and we will kill him much smoother.

If u dont give your raiders bonus ep, you dont inspired them, we have alot of causal players or newbies from retail and they dont understand they must have enchants, pots, flasks etc. and u must slowly pushing them, but not that hard and MC is great raid for doing it and teach them slowly with help from CLs.

Yes decay will be 1.11 and thats it. I dont understand what you mean. minEP was there for reason and u must set up minEP with common sense and dont setup minEP 300ep, this is nonse. After this month i know minEP will be around 150ep and next month maybe less we will see, but minEP is here for protecting your main raiders and showing to new raiders you must reach this to proove your allegiance to guild and dont give them negative points, guys this is non sense giving to new raiders GP, because GP is something like punish.

**Comment by PibbzTV** [comment]
> If you give someone new GP for no reason it looks bad
If everyone starts with 25 GP when they're about to start raiding, It's a feature, not a punishment. It's the same for everyone, thus no need to feel punished.

> Be guild master is not easy and you must do this psychologic stuff.
I know, I've been one for 15 years myself :)

**Comment by Alumian** [comment]
Implemented in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.6.

**Comment by DeanAles** [comment]
Thanks for implementing.

But now please we need see them under line after people who already had that minEP, because i dont see them if they need items and if noone want this item, they are not in list and i must manualy give them item and GP aswell. 
Please do line under people who have that minEP and under line will be that second wave who has not that minEP, but they are still in list :)

Thanks man!
You are rockstar!
