### ISSUE TITLE
[Bug] Intense lag when distributing EP for boss kills.

### ISSUE THREAD

**Issue by PibbzTV** [Alumian/CEPGP-Retail#111]
Using 1.12.5 release version. Everyone with the addon experienced a good old lagspike when EP was distributed for bosskills. Both for our own kills, and when our two other raids killed bosses.

**Comment by Alumian** [comment]
Possibly fixed in the latest beta version.

**Comment by miketonny** [comment]
we're having the exact same issue. where do we download the latest beta version? there's no beta releases after 1.12.5

**Comment by Alumian** [comment]
CEPGP support discord: https://discord.gg/7mG4GAr

**Comment by miketonny** [comment]
gotcha, ty, going to try it out tonite

**Comment by Alumian** [comment]
Resolved in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.6.

**Comment by PibbzTV** [comment]
This has never been truly resolved for us. Guild is 750 members, so its on the larger side.
Would be sweet if it could ignore all the Alts and socials when updating, as it would put way less stress on the update part. No idea if its possible or not, but I have to suggest it :)

**Comment by Alumian** [comment]
Okay well the problem was no one gave me feedback for almost a week after I suggested downloading the beta so I assumed it was fixed.

**Comment by PibbzTV** [comment]
Yes, true, and I'm sorry for that! I've tried numerous betas since then, and no love for the lag part :)
Betas tend to introduce new bugs tho, and with 3 raids at the same time, bugs can have a huge impact on our raids. So we've been sticking to 1.12.7 so far.

**Comment by Alumian** [comment]
> Betas tend to introduce new bugs
If problems weren't encountered, then there wouldn't be a need for beta.

> bugs can have a huge impact on our raids
As a guild leader and raid leader, I am fully aware of the impacts that bugs can have on a raid. The only difference is that my guild has no choice but to deal with it since I'm developing this addon.

The reality is, if you want your problems fixed, you have to be prepared to make an effort. There are measures in place to ensure that any miscalculations by the addon can easily be reverted such as the save/restore function. If you are not regularly making use of this function, you're shooting yourself in the foot. The bottom line is, don't submit a ticket without even bothering to submit the requested information such as /cepgp debug, go MIA for 2 months and then come back here and whine that it isn't fixed. Don't expect the world when you aren't prepared to put in the minimum effort to help me get it done and as this is not the place to be discussing the appropriateness of betas, feel free to take it up with me on discord. As of now, this ticket is locked.

**Comment by PibbzTV** [comment]
<details><summary>Debug Info</summary><br />
Version: 1.12.7<br />
Locale: enUS<br />
GP Formula: (4.83x(1.6^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x2<br />Base GP: 5<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 100<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: False<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: !standby<br /><br />
<details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Lord Kri: True<br />
Emperor Vek'nilash: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Lady Blaumeux: True<br />
Highlord Mograine: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Teremus the Devourer: True<br />
Chromaggus: True<br />
Baron Geddon: True<br />
Firemaw: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
High Priestess Arlokk: True<br />
Emperor Vek'lor: True<br />
Gahz'ranka: True<br />
Gluth: True<br />
Sapphiron: True<br />
Razorgore the Untamed: True<br />
Onyxia: True<br />
Princess Yauj: True<br />
Vem: True<br />
Shazzrah: True<br />
Ouro: True<br />
Battleguard Sartura: True<br />
Maexxna: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Ragnaros: True<br />
Ayamiss the Hunter: True<br />
Broodlord Lashlayer: True<br />
Viscidus: True<br />
Hakkar: True<br />
Ebonroc: True<br />
Kurinnaxx: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Sir Zeliek: True<br />
Vaelastrasz the Corrupt: True<br />
Patchwerk: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
Jin'do the Hexxer: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Lord Kri: 10<br />
Emperor Vek'nilash: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 10<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 10<br />
High Priest Venoxis: 2<br />
Gehennas: 10<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Lady Blaumeux: 15<br />
Highlord Mograine: 15<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Teremus the Devourer: 7<br />
Chromaggus: 7<br />
Baron Geddon: 10<br />
Firemaw: 7<br />
Sulfuron Harbinger: 10<br />
Gri'lek: 2<br />
High Priestess Arlokk: 2<br />
Emperor Vek'lor: 10<br />
Gahz'ranka: 2<br />
Gluth: 12<br />
Sapphiron: 15<br />
Razorgore the Untamed: 7<br />
Onyxia: 10<br />
Princess Yauj: 10<br />
Vem: 10<br />
Shazzrah: 10<br />
Ouro: 10<br />
Battleguard Sartura: 10<br />
Maexxna: 15<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 10<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Ragnaros: 10<br />
Ayamiss the Hunter: 3<br />
Broodlord Lashlayer: 7<br />
Viscidus: 10<br />
Hakkar: 3<br />
Ebonroc: 7<br />
Kurinnaxx: 3<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 10<br />
Sir Zeliek: 15<br />
Vaelastrasz the Corrupt: 7<br />
Patchwerk: 12<br />
Bloodlord Mandokir: 2<br />
Renataki: 2<br />
Jin'do the Hexxer: 2<br />
Garr: 10<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Matriarch: False<br />
Officer: False<br />
Veteran: False<br />
Member: False<br />
Social: False<br />
Alt: False<br />
Timeout: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 1.3<br />
NECK: 0.5<br />
HEAD: 0.8<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.1<br />
SHIELD: 0.6<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
SHOULDER: 0.6<br />
FEET: 0.5<br />
RANGED: 0.5<br />
EXCEPTION: 1<br />
WAIST: 0.5<br />
TRINKET: 0.75<br />
LEGS: 0.8<br />
HAND: 0.5<br />
ROBE: 1<br />
CHEST: 0.8<br />
FINGER: 0.6<br />
WEAPONOFFHAND: 1.1<br />
RANGEDRIGHT: 0.5<br />
RELIC: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
[The Eye of Divinity]: 48<br />
[Bindings of the Windseeker]: 36<br />
[Head of Onyxia]: 28<br />
[Mature Black Dragon Sinew]: 35<br />
[Bindings of the Windseeker]: 36<br />
[Ancient Petrified Leaf]: 35<br />
[Eye of Sulfuras]: 60<br />
</details>
<details><summary>Addons List</summary>
AdvancedOptions_Classic<br />
Auctionator<br />
AuctionValue<br />
AutoLoggerClassic<br />
BagBrother<br />
Bagnon<br />
BetterAlign<br />
BottomBar<br />
Chatter<br />
CEPGP<br />
ClassicAuraDurations<br />
ClassicThreatMeter<br />
DashingDismount<br />
Decursive<br />
Dominos<br />
Dominos_Encounter<br />
Dominos_Progress<br />
Dominos_Roll<br />
eCastingBar<br />
ExRT<br />
Grid2<br />
Grid2RaidDebuffs<br />
Grid2LDB<br />
GuildBankClassic<br />
HideXP<br />
honorspy<br />
ItemRack<br />
LunaUnitFrames<br />
Masque<br />
Masque_CleanIcons<br />
MikScrollingBattleText<br />
MissingTradeSkillsList<br />
NugRunning<br />
OmniCC<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
QuestIconDesaturation<br />
QuestFrameFixer<br />
RealMobHealth<br />
Recount<br />
SellJunk<br />
SharedMedia<br />
Spy<br />
TipTac<br />
TipTacItemRef<br />
TitanAttributesMulti<br />
TitanReputations<br />
TitanClassicAmmo<br />
TitanClassicBag<br />
TitanClassicClock<br />
TitanClassicGold<br />
TitanClassicLocation<br />
TitanClassicLootType<br />
TitanClassicPerformance<br />
TitanClassicRegen<br />
TitanClassicRepair<br />
TitanClassicVolume<br />
TitanClassicXP<br />
TitanClassic<br />
tullaRange<br />
VendorPrice<br />
WIM<br />
ZoomerBegone<br />
CharacterStatsClassic<br />
TradeSkillMaster<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Bonkeybee** [comment]
This issue still isn't fixed. You can see it happening to one of my members who is trying to PVP in AV while I change EP values for about 100 or so players. https://streamable.com/i52ab

**Comment by Alumian** [comment]
Refer to #121 as this is the same issue.
