### ISSUE TITLE
[Bug] EP reset for players on standby

### ISSUE THREAD

**Issue by jrydh** [Alumian/CEPGP-Retail#112]
**The Error**
During the raid, it was discovered that the two players that were on standby had had their EP reset to 0. I (as ML) did a reload during the raid at some point if that matters, but I checked that they were still on the standby list.

**Describe the bug**
The standby people should have gotten 50% EP gained according to our settings. Instead, they got their total EP set to 0. (GP was not reset.)

**To Reproduce**
Onyxia + MC raid, two players manually added to standby list, both offline at the start. After a few bosses, the bug had occurred.

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.5<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 50<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: False<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br /><br />
<details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Lord Kri: True<br />
Emperor Vek'nilash: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Lady Blaumeux: True<br />
Highlord Mograine: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Teremus the Devourer: True<br />
Jin'do the Hexxer: True<br />
Baron Geddon: True<br />
Renataki: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
Bloodlord Mandokir: True<br />
Patchwerk: True<br />
Vaelastrasz the Corrupt: True<br />
Gluth: True<br />
Sapphiron: True<br />
Emeriss: True<br />
Onyxia: True<br />
Princess Yauj: True<br />
Kurinnaxx: True<br />
Shazzrah: True<br />
Ebonroc: True<br />
Battleguard Sartura: True<br />
Hakkar: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Viscidus: True<br />
Broodlord Lashlayer: True<br />
Ayamiss the Hunter: True<br />
Ragnaros: True<br />
Maexxna: True<br />
Ouro: True<br />
Vem: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Sir Zeliek: True<br />
Gahz'ranka: True<br />
Emperor Vek'lor: True<br />
High Priestess Arlokk: True<br />
Firemaw: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Lord Kri: 10<br />
Emperor Vek'nilash: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Lady Blaumeux: 15<br />
Highlord Mograine: 15<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Teremus the Devourer: 7<br />
Jin'do the Hexxer: 2<br />
Baron Geddon: 5<br />
Renataki: 2<br />
Sulfuron Harbinger: 5<br />
Gri'lek: 2<br />
Bloodlord Mandokir: 2<br />
Patchwerk: 12<br />
Vaelastrasz the Corrupt: 7<br />
Gluth: 12<br />
Sapphiron: 15<br />
Emeriss: 7<br />
Onyxia: 5<br />
Princess Yauj: 10<br />
Kurinnaxx: 3<br />
Shazzrah: 5<br />
Ebonroc: 7<br />
Battleguard Sartura: 10<br />
Hakkar: 3<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Viscidus: 10<br />
Broodlord Lashlayer: 7<br />
Ayamiss the Hunter: 3<br />
Ragnaros: 7<br />
Maexxna: 15<br />
Ouro: 10<br />
Vem: 10<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 7<br />
Magmadar: 5<br />
Sir Zeliek: 15<br />
Gahz'ranka: 2<br />
Emperor Vek'lor: 10<br />
High Priestess Arlokk: 2<br />
Firemaw: 7<br />
Chromaggus: 7<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
Officer: False<br />
Raider: False<br />
Social: False<br />
Alt: False<br />
Trial: False<br />
Needs Rank: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
RANGED: 0.5<br />
THROWN: 0.5<br />
FEET: 0.75<br />
RELIC: 0.5<br />
RANGEDRIGHT: 0.5<br />
WEAPONOFFHAND: 0.5<br />
TRINKET: 0.75<br />
FINGER: 0.5<br />
CLOAK: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
LEGS: 1<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
Eye of Divinity: 71<br />
Tome of Tranquilizing Shot: 0<br />
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
Auctionator<br />
BagBrother<br />
Bagnon<br />
BetterVendorPrice<br />
ccc<br />
ClassTrainerPlus<br />
CEPGP<br />
Details<br />
Details_TinyThreat<br />
EavesDrop<br />
ExtendedCharacterStats<br />
FarmHud<br />
GatherMate2<br />
GatherMate_Sharing<br />
Guidelime<br />
Guidelime_Sage<br />
Memoria<br />
MissingBuffs<br />
ModernQuestWatch<br />
QuestLogEx<br />
RaidInviter<br />
VortexChat<br />
WeakAuras<br />
WeaponSwingTimer<br />
AddOnSkins<br />
SpeedyAutoLoot<br />
ElvUI<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Yeahhh..... I'm having issues with shuffling numbers.... Ive got an idea on how to fix it and I'm going to try to upload a new beta version to the support discord in the coming days.

**Comment by Alumian** [comment]
Okay I've implemented a failsafe which I hope has resolved this issue. Please join the CEPGP discord if you haven't already and grab the latest beta version.

**Comment by Alumian** [comment]
So far feedback has been positive regarding my solution. I'd like further feedback before I declare this resolved.

**Comment by jrydh** [comment]
Next raid is on Wednesday. I'll let you know.

**Comment by jrydh** [comment]
This seems to work with 1.12.6 beta 3.

**Comment by Alumian** [comment]
Fantastic, glad to hear it and thanks for letting me know :)

**Comment by Alumian** [comment]
Resolved in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.6.
