### ISSUE TITLE
[Bug]GP was not added after handling out loot on Gehennas

### ISSUE THREAD

**Issue by Naniq** [Alumian/CEPGP-Retail#113]
**Describe the bug**
So the issue we have seen is that two times now on Gehennas the loot that got distubuted did not get counted for as + GP for the user.
Last time here the information was - 
User name: Micom
Item name: Nightslayer Gloves

**To Reproduce**
I think this can be reproduced by simply killing the boss, and getting that specific item, however I am not sure, I do not remember what item dropped last time.

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.5<br />
GP Formula: (4.83x(1^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 100<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: False<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br /><br />
<details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Lord Kri: True<br />
Emperor Vek'nilash: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Lady Blaumeux: True<br />
Highlord Mograine: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Teremus the Devourer: True<br />
Chromaggus: True<br />
Baron Geddon: True<br />
Firemaw: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
High Priestess Arlokk: True<br />
Emperor Vek'lor: True<br />
Gahz'ranka: True<br />
Gluth: True<br />
Sapphiron: True<br />
Razorgore the Untamed: True<br />
Onyxia: True<br />
Princess Yauj: True<br />
Vem: True<br />
Shazzrah: True<br />
Ouro: True<br />
Battleguard Sartura: True<br />
Maexxna: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Ragnaros: True<br />
Ayamiss the Hunter: True<br />
Broodlord Lashlayer: True<br />
Viscidus: True<br />
Hakkar: True<br />
Ebonroc: True<br />
Kurinnaxx: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Sir Zeliek: True<br />
Vaelastrasz the Corrupt: True<br />
Patchwerk: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
Jin'do the Hexxer: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Lord Kri: 10<br />
Emperor Vek'nilash: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Lady Blaumeux: 15<br />
Highlord Mograine: 15<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Teremus the Devourer: 7<br />
Chromaggus: 7<br />
Baron Geddon: 5<br />
Firemaw: 7<br />
Sulfuron Harbinger: 5<br />
Gri'lek: 2<br />
High Priestess Arlokk: 2<br />
Emperor Vek'lor: 10<br />
Gahz'ranka: 2<br />
Gluth: 12<br />
Sapphiron: 15<br />
Razorgore the Untamed: 7<br />
Onyxia: 7<br />
Princess Yauj: 10<br />
Vem: 10<br />
Shazzrah: 5<br />
Ouro: 10<br />
Battleguard Sartura: 10<br />
Maexxna: 15<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Ragnaros: 7<br />
Ayamiss the Hunter: 3<br />
Broodlord Lashlayer: 7<br />
Viscidus: 10<br />
Hakkar: 3<br />
Ebonroc: 7<br />
Kurinnaxx: 3<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 5<br />
Sir Zeliek: 15<br />
Vaelastrasz the Corrupt: 7<br />
Patchwerk: 12<br />
Bloodlord Mandokir: 2<br />
Renataki: 2<br />
Jin'do the Hexxer: 2<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
Officer: False<br />
Officer Alt: False<br />
Raider: False<br />
Trial: False<br />
Social: False<br />
Alt: False<br />
Backup: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
RANGED: 0.5<br />
SHOULDER: 0.75<br />
FEET: 0.75<br />
LEGS: 1<br />
EXCEPTION: 1<br />
WAIST: 0.75<br />
TRINKET: 0.75<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1<br />
CLOAK: 0.5<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 0.5<br />
RANGEDRIGHT: 0.5<br />
RELIC: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
Auctionator<br />
BagBrother<br />
Bagnon<br />
BiSTracker<br />
CEPGP<br />
ClassicAuraDurations<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
ClassicGuildBank<br />
ClassicThreatMeter<br />
Details<br />
Details_TinyThreat<br />
FasterLooting<br />
Leatrix_Maps<br />
Leatrix_Plus<br />
LetMeCast<br />
LibStub<br />
OmniCC<br />
QuestLogEx<br />
RCLootCouncil_Classic<br />
RealMobHealth<br />
TidyPlates_ThreatPlates<br />
TitanClassicXP<br />
TitanClassic<br />
TomTom<br />
tullaRange<br />
TwitchEmotes<br />
VendorPrice<br />
WeakAuras<br />
WeaponSwingTimer<br />
+Wowhead_Looter<br />
YaHT<br />
DejaClassicStats<br />
TradeSkillMaster<br />
TradeSkillMaster_AppHelper<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Hi Naniq,
When you handed out the gloves, did you do it by the normal master loot method or did you give it out through the CEPGP window?

**Comment by Naniq** [comment]
Hey Alumian!

It was through the CEPGP window :)

**Comment by Alumian** [comment]
Okay so does it still award the item to the player? Also does it say anything in chat?

**Comment by PibbzTV** [comment]
I have experienced similar stuff, and I have a feeling it might be related to the recipient having moved too far away from the masterlooter. We experinced it twice yesterday, on Magmadar and Domo. Both times, the raid had moved on and I was the only one staying behind. 

He recieved the item, but was not charged any GP, and there was no notification in the guildchat. I did not see "player x recieved loot: Y" in the item  in the chat window either for those two occurences.

**Comment by Alumian** [comment]
It's not distance related. I've handed out loot from Domo while people are all the way over at Rag and not struck this issue and when I did this, loot messages didn't appear. Have you experienced this issue recently @PibbzTV? @Naniq?

**Comment by Naniq** [comment]
Hi!

Yes It happened again tonight, this time on Onyxia, handling out loot to
myself.
I clicked the window, "Give for GP", the window kept being up, and the item
was handed to me, no text in chat

**Comment by Naniq** [comment]
Hi!

Yes It happened again tonight, this time on Onyxia, handling out loot to myself.
I clicked the window, "Give for GP", the window kept being up, and the item was handed to me, no text in chat

**Comment by Alumian** [comment]
What locale is your client?

**Comment by Naniq** [comment]
English - Let me know any information I can provide and I will gladly do

**Comment by Alumian** [comment]
Has it only happened on those 2 occasions? Do you remember what items it happened in? Do They show in the traffic frame?

**Comment by Naniq** [comment]
Tonight: [Sapphiron Drape]
Target: Naniq

Orginal report:
User name: Micom
Item name: Nightslayer Gloves

They do not show in log,
HOWEVER I added 2 GP manually to myself aswell, that is NOT shown in the log, but my GP did increase

**Comment by Alumian** [comment]
Were you the loot master?

**Comment by Naniq** [comment]
Yes both times

**Comment by Alumian** [comment]
Can you try downloading the new version and seeing if the issue persists?

**Comment by Naniq** [comment]
Hey Alumian!

I currently have version: 1.12.6 - Is this the newest one (Twitch version)

**Comment by Alumian** [comment]
Ok - does the issue persist?

**Comment by Naniq** [comment]
Hi!

I will gladly tell you weds. when we have our next raid

**Comment by Naniq** [comment]
Hey!

This time with Shaman loot on Garr:

https://imgur.com/a/8q55oSI

**Comment by Alumian** [comment]
Did it happen for any other items? Can you please send me a screenshot of the full traffic frame showing item distribution?

**Comment by Alumian** [comment]
Naniq has advised that they're no longer using EPGP. No one else has reported this issue since this ticket was opened. Assuming it has been resolved.
