### ISSUE TITLE
[Request] Configure channel EP/GP changes are reported to

### ISSUE THREAD

**Issue by Bonkeybee** [Alumian/CEPGP-Retail#115]
The EPGP changes are by default reported to the guild channel. As GuildMaster and EPGP moderator I've actually been put on ignore by my guildies because of how spammy the addon can be when modifying EP manually.

Please add configurations for the various report features. I like reporting loot + GP gains to guild chat, but manual EP modification of 100+ members is too spammy and might belong better in officer chat or somewhere else.

Similar to #104

**Comment by Alumian** [comment]
You can type /cep setdefaultchannel channelname to change the default reporting channel. At this stage, only the stock channels are supported. I was actually thinking of changing this from being a command and shoving it into the options frame. I think it'd make more sense. But yeah you can already do that with the exception of resetting standings, which will always report to guild.
