### ISSUE TITLE
[Request] Special GP values for quest items (Onyxia Head)

### ISSUE THREAD

**Issue by Bonkeybee** [Alumian/CEPGP-Retail#116]
The itemlevel of the Onyxia Head quest item is 60, but the actual rewards from turning in the head are ilvl 74. It would make the GP calculation more accurate to calculate the GP from the item the quest rewards rather than the head itself.

**Comment by Bonkeybee** [comment]
This also effects other special items like the Ancient Petrified Leaf which is ilvl 71 but rewards 3 items, ilvl 75 ranged weapon, ilvl 75 bag, and ilvl75 2hand weapon

**Comment by Jozh89** [comment]
Just set them to a static value in the override Settings

**Comment by Alumian** [comment]
Yeah I'm inclined to agree with Jozh on this one. Since the change would apply to everyone, I'd much rather have it set to a safe default and guilds can override the item as they please.
