### ISSUE TITLE
[Bug][zh-CN Client] Error Encountered in Traffic Frame

### ISSUE THREAD

**Issue by woweichongzhen** [Alumian/CEPGP-Retail#119]
**The Error**
TMessage: Usage: local itemExists = C_Item.DoesItemExistByID(itemInfo)
Time: Sun Nov 3 20:15:41 2019
Count: 1
Stack: Usage: local itemExists = C_Item.DoesItemExistByID(itemInfo)
[C]: in function `DoesItemExistByID'
Interface\AddOns\CEPGP\Utility.lua:1633: in function `CEPGP_itemExists'
Interface\AddOns\CEPGP\Scrollbar.lua:514: in function `CEPGP_UpdateTrafficScrollBar'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2519: in function `ShowUIPanel'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: (*temporary) = "Usage: local itemExists = C_Item.DoesItemExistByID(itemInfo)"

**Describe the bug**
I use the zh-CN client. When I pick up items, i'll pop up the above error.

**Comment by Alumian** [comment]
Could you please download the new version and see if the issue occurs again?

**Comment by woweichongzhen** [comment]
It doesn't happen anymore.

**Comment by Alumian** [comment]
Thanks for letting me know :)
