### ISSUE TITLE
[Bug] The screen freezes when the guild member login to the server

### ISSUE THREAD

**Issue by Calender-86** [Alumian/CEPGP-Retail#121]
Нi, our guild has about 750 people, but only 40 of them have the CEPGP addon. We have a problem that everyone who has the add-on installed gets a screen freezes when another player’s login (doesnt matter addon is installed or not). We hope you can fix it soon or tell how to deal with it.

**Comment by PibbzTV** [comment]
We still have this aswell, not on login, but on bosskill. Even with the latest version.
Im almost certain it has to do with guild size. We have around 750 aswell.

Best way to fix it would be if we could ignore all the irrelevant ranks. We have like 500 people with alt or social rank that does not raid at all.

**Comment by Alumian** [comment]
I have written a possible solution for this issue. It will require extensive testing to ensure that it doesn't impact the accuracy of other CEPGP modules, but otherwise I'm optimistic. Please let me know if you're available to help me test this solution.

**Comment by Alumian** [comment]
Fixed in 1.12.9
