### ISSUE TITLE
[Bug] Boss kill Auto award in RU client don`t work

### ISSUE THREAD

**Issue by Solitaric** [Alumian/CEPGP-Retail#123]
Please add support this feature for RU game client

**Comment by Owersun** [comment]
apply this and you're going to be fine https://github.com/Alumian/CEPGP-Retail/pull/97

**Comment by Alumian** [comment]
Added in 1.12.7 beta 3.

**Comment by Alumian** [comment]
Fixed in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.7
