### ISSUE TITLE
[Bug] Nothing happens when I add GP to players

### ISSUE THREAD

**Issue by esfdk** [Alumian/CEPGP-Retail#125]
**The Error**
When I manually add GP to players, their GP does not change (but it does show it in the EPGP traffic log).

**Describe the bug**
Whenever I try to manually add GP to players, the traffic log seems to register that I have added GP, but their GP does not change. Adding EP works just fine.

**To Reproduce**
Open CEPGP by typing /cepgp show, click Guild, click player name, select GP, type 10 in "Add/subtract" and "test" in reason, click Confirm.

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.6<br />
Locale: enUS<br />
GP Formula: (4.83x(2.5^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 50<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br /><br />
<details><summary>Auto EP</summary>
High Priestess Jeklik: False<br />
Gothik the Harvester: False<br />
Buru the Gorger: False<br />
Wushoolay: False<br />
Lord Kri: False<br />
Emperor Vek'nilash: False<br />
Ossirian the Unscarred: False<br />
Golemagg the Incinerator: False<br />
Grand Widow Faerlina: False<br />
High Priestess Mar'li: False<br />
Majordomo Executus: False<br />
High Priest Venoxis: False<br />
Gehennas: False<br />
Taerar: False<br />
Ysondre: False<br />
Thane Korth'azz: False<br />
High Priest Thekal: False<br />
Noth the Plaguebringer: False<br />
Lethon: False<br />
Moam: False<br />
The Prophet Skeram: False<br />
Flamegor: False<br />
C'Thun: False<br />
General Rajaxx: False<br />
Princess Huhuran: False<br />
Thaddius: False<br />
Loatheb: False<br />
Lady Blaumeux: False<br />
Highlord Mograine: False<br />
Heigan the Unclean: False<br />
Azuregos: False<br />
Doom Lord Kazzak: False<br />
Teremus the Devourer: False<br />
Jin'do the Hexxer: False<br />
Baron Geddon: False<br />
Renataki: False<br />
Sulfuron Harbinger: False<br />
Gri'lek: False<br />
Bloodlord Mandokir: False<br />
Patchwerk: False<br />
Vaelastrasz the Corrupt: False<br />
Gluth: False<br />
Sapphiron: False<br />
Emeriss: False<br />
Onyxia: False<br />
Princess Yauj: False<br />
Kurinnaxx: False<br />
Shazzrah: False<br />
Ebonroc: False<br />
Battleguard Sartura: False<br />
Hakkar: False<br />
Kel'Thuzad: False<br />
Nefarian: False<br />
Fankriss the Unyielding: False<br />
Lucifron: False<br />
Anub'Rekhan: False<br />
Hazza'rah: False<br />
Viscidus: False<br />
Broodlord Lashlayer: False<br />
Ayamiss the Hunter: False<br />
Ragnaros: False<br />
Maexxna: False<br />
Ouro: False<br />
Vem: False<br />
Grobbulus: False<br />
Instructor Razuvious: False<br />
Razorgore the Untamed: False<br />
Magmadar: False<br />
Sir Zeliek: False<br />
Gahz'ranka: False<br />
Emperor Vek'lor: False<br />
High Priestess Arlokk: False<br />
Firemaw: False<br />
Chromaggus: False<br />
Garr: False<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Lord Kri: 10<br />
Emperor Vek'nilash: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Lady Blaumeux: 15<br />
Highlord Mograine: 15<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Teremus the Devourer: 7<br />
Jin'do the Hexxer: 2<br />
Baron Geddon: 5<br />
Renataki: 2<br />
Sulfuron Harbinger: 5<br />
Gri'lek: 2<br />
Bloodlord Mandokir: 2<br />
Patchwerk: 12<br />
Vaelastrasz the Corrupt: 7<br />
Gluth: 12<br />
Sapphiron: 15<br />
Emeriss: 7<br />
Onyxia: 5<br />
Princess Yauj: 10<br />
Kurinnaxx: 3<br />
Shazzrah: 5<br />
Ebonroc: 7<br />
Battleguard Sartura: 10<br />
Hakkar: 3<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Viscidus: 10<br />
Broodlord Lashlayer: 7<br />
Ayamiss the Hunter: 3<br />
Ragnaros: 7<br />
Maexxna: 15<br />
Ouro: 10<br />
Vem: 10<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 7<br />
Magmadar: 5<br />
Sir Zeliek: 15<br />
Gahz'ranka: 2<br />
Emperor Vek'lor: 10<br />
High Priestess Arlokk: 2<br />
Firemaw: 7<br />
Chromaggus: 7<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
Officer: False<br />
Officer Alt: False<br />
Core Raider: False<br />
Raider: False<br />
Social: False<br />
Alt: False<br />
Trial: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2.5<br />
NECK: 1<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.75<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 1<br />
HOLDABLE: 1<br />
RANGED: 0.75<br />
THROWN: 0.75<br />
FEET: 1<br />
RELIC: 0.75<br />
RANGEDRIGHT: 0.75<br />
WEAPONOFFHAND: 1.5<br />
TRINKET: 0.75<br />
FINGER: 0.75<br />
CLOAK: 0.75<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 1<br />
WAIST: 1<br />
EXCEPTION: 1<br />
LEGS: 1<br />
SHOULDER: 1<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
Auctionator<br />
BagBrother<br />
Bartender4<br />
BuyEmAllClassic<br />
CEPGP<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
Clique<br />
Combuctor<br />
Coordinates<br />
Details<br />
Details_TinyThreat<br />
eAlignClassic<br />
ExRT<br />
Grid2<br />
Grid2RaidDebuffs<br />
Grid2LDB<br />
Leatrix_Plus<br />
MikScrollingBattleText<br />
OmniCC<br />
OPie<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
Quartz<br />
QuestIconDesaturation<br />
QuestFrameFixer<br />
QuestLogEx<br />
RealMobHealth<br />
RollTrackerClassic<br />
SexyMap<br />
ShadowedUnitFrames<br />
TidyPlates_ThreatPlates<br />
WeakAuras<br />
WeaponSwingTimer<br />
+Wowhead_Looter<br />
DejaClassicStats<br />
CursorCompanion<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Oh uhh sorry about that lol. I was playing with the add GP function and I forgot to uncomment the line that actually makes the change. I'll upload the hotfix shortly.
