### ISSUE TITLE
[Request] Possibility to setup the loot responses to a specific channel

### ISSUE THREAD

**Issue by DeadlyGrandma** [Alumian/CEPGP-Retail#128]
Hey Alumian,

As quickly discussed on Discord, further to the implementation of a possibility to disable the loot answers in the raid chat I would like to know if we could keep such answers but select a specific chat channel other than /raid (ideally /officers) so that the raid dont see them but the officers do.

Many thanks in advance!
DG

**Comment by Alumian** [comment]
Added in beta 3.

**Comment by Alumian** [comment]
Added in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.7.
