### ISSUE TITLE
[Question] Set ilvl of quest items to reflect the reward

### ISSUE THREAD

**Issue by Gazler** [Alumian/CEPGP-Retail#129]
Currently the head of onyxia is ilvl 60, however the rewards are ilvl 74, perhaps the ilvl should be manually set to that of the quest rewards in https://github.com/Alumian/CEPGP-Retail/blob/23f2708ee934e188b60ebfed939beef7e3a15047/Utility.lua#L163

Happy to take this on if you agree.

**Comment by Alumian** [comment]
Since the head of Onyxia can yield either a neck, ring or trinket, it is up to the guild's discretion to set a permanent override for this item. Unfortunately since I cannot justify fixing the head to any one of those slots, this will remain unchanged at this time.

**Comment by Gazler** [comment]
@Alumian Just to clarify, the slot is already overridden to the neck, I am only proposing changing the ilvl to reflect the quest reward.

**Comment by Alumian** [comment]
Well there's egg on my face now, lol. Sorry about that, I must have misread your request. Not a problem, I'll go ahead and override that when I get home today.

**Comment by Alumian** [comment]
The correction has been made in beta v4 and it is now available on the CEPGP discord :)

**Comment by Alumian** [comment]
Added in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.7.
