### ISSUE TITLE
Notice Window Issue 

### ISSUE THREAD

**Issue by Konman916** [Alumian/CEPGP-Retail#133]
**The Error**
No error code. 

**Describe the bug**
Each time I log into WoW I receive the "Notice" that says, " thank you for Chooisng EPGP and is explaining to you about Officer Chat/notes will be used...etc. etc"  You have the option to pick "NOPE. Abort." or "Got it!".  Whenever I select "Got it!" the UI reloads and the same message continues to populate.  Over and Over again with no solution.  Reinstalled the Addon, nothing.  Reinstalled WoW.  Nothing.  Restarted entire CPU and game, still populates.  

**To Reproduce**
I just log in and it is there. 

**Debug Information**

**Comment by Alumian** [comment]
Is this your first time using this add-on or have you used it before? Do you know the version number that you're using?

**Comment by Konman916** [comment]
I have been using this for some time.  Started happening after an update.  Verizon 1.13.2

**Comment by Alumian** [comment]
Can you attach a screenshot of your addon folder including the directory?

**Comment by Konman916** [comment]
![Addons](https://user-images.githubusercontent.com/57867547/69014353-6e90a780-0957-11ea-85d7-116696f6be1e.png)

**Comment by Konman916** [comment]
![addon (2)](https://user-images.githubusercontent.com/57867547/69014357-72bcc500-0957-11ea-8099-53719d9d2671.png)

**Comment by Konman916** [comment]
Like this?

**Comment by Alumian** [comment]
Yeah okay.. that all looks fine. Sometimes an issue like this can be caused when the CEPGP folder is in lowercase but that doesn't look like that's the problem here. Can you please go to _classic_\WTF\Account\Accountname\SavedVariables\CEPGP.lua and upload that file here?

**Comment by Konman916** [comment]
Interesting when I click on "SavedVariables" it says it is not accessible as the "The file or directory is corrupted and unreadable.

**Comment by Alumian** [comment]
Well. That'll do it. Can you please delete that file and try again? Make sure your game is closed while you're attempting this. Full disclaimer, you will lose your CEPGP configuration by doing this including your GP formula, slot weights, traffic log, etc...

**Comment by Konman916** [comment]
So delete CEPGP File? or the shared Variables?

**Comment by Alumian** [comment]
Just the CEPGP file.

**Comment by Konman916** [comment]
Okay deleted the file.  Still can't click into SavedVariables.  Do I redownload the CEPGP?

**Comment by Alumian** [comment]
mmm can you clarify what you mean by you can't click into SavedVariables? I thought you meant you couldn't open the CEPGP.lua saved variables file.

**Comment by Konman916** [comment]
lassic\WTF\Account\Accountname\SavedVariables\CEPGP.lua

If I go to the part in this formula and click into "savedVariables" I get the message "the file or directory is corrupted and unreadable" 

and cant copy the File into the folder.   Does that make sense?

**Comment by Alumian** [comment]
Oh, are you just writing the path in manually or are you navigating to the path? You need to replace Accountname with the actual name of your account.

**Comment by Konman916** [comment]
I am manually navigating to the path.   Okay I changed the auto name it generated to my account name.  Should i try logging back in now?

**Comment by Alumian** [comment]
Can you drop me a message on discord? Alumian#6465
