### ISSUE TITLE
[Request] German translation

### ISSUE THREAD

**Issue by hbjose** [Alumian/CEPGP-Retail#134]
I can help with a german translation, if u want to.

**Comment by Alumian** [comment]
That'd be very much appreciated. Just copy paste one of the existing localisation files (i.e. ruRU.lua) and replace the locale and translations with the ones appropriate for you language. Could you please also send me the file when you're done?

**Comment by hbjose** [comment]
Of course.
Whats about the translation of the windows and the buttons? In the locales files are only the boss names and their translations.

**Comment by Alumian** [comment]
You can add any translations you'd like to the file :)
So just simply add it in the format of:
`L["StringinEnglish"] = "StringinGerman"`
So an example of this might be:
`L["Guild"] = Gilde` or `L["Raid"] = Überfall` depending on how accurate google translate is haha.

**Comment by hbjose** [comment]
ah nice. i ll try this later :)
