### ISSUE TITLE
[Request] Notification for players not meeting EP minimum

### ISSUE THREAD

**Issue by infernojack** [Alumian/CEPGP-Retail#139]
During raid tonight we had a member who did not have the minimum EP to bid on loot.  There was confusion as to why his bids were not going through, which we did solve, but it would be nice if there was a pop-up for the person explaining that they do not qualify to roll on loot due to min EP requirements, rather than their "main spec" returning no response.

**Comment by Alumian** [comment]
Implementation has now been released.
