### ISSUE TITLE
[REQUEST] Guild Ranks

### ISSUE THREAD

**Issue by nwardoh** [Alumian/CEPGP-Retail#14]
Hi,

We will be running 2 raids in classic and I would like to keep the pools separate. Can the add-on be configured to only look at particular ranks so we can, essentially, maintain 2 pools? Maybe something along the lines of GL, Officers1, and R1 ranks for my run and Officers2, and R2 ranks for the other run? In the rare event we have someone from the other run go with us I do not want them to be able to outbid my vets on their first run with us. Might sound harsh but it's the only fair way of doing it I think.

**Comment by Alumian** [comment]
Hi nwardoh,

When you say "look at particular ranks", what element of the add-on are you referring to?

**Comment by nwardoh** [comment]
I am looking for the storage and parsing of points and priority from the
officer notes.

**Comment by Alumian** [comment]
Do you mean like, operate as if GL/Officers1/R1 ranks were the only ranks in the guild for example? So if someone from Officer2 or R2 attended an R1 raid the addon would essentially pretend like they don't exist? Is that what you mean?

**Comment by nwardoh** [comment]
I’d like to be able to configure my addon and my raiders to config theirs
to treat it as if only those ranks existed and the second run people
configure theirs as if only their ranks existed.

**Comment by Alumian** [comment]
In response to your initial comment about players from the other group outbidding your vets on their first run, this addon isn't fully automatic. At the end of the day, the loot master gets to decide who gets the loot. The addon merely provides you with an interface for which loot system related information can be displayed and a helpful interface to easily distribute items. It is entirely up to you whether or not you would like to give the item to someone from your own group, or the other.
From what you've described, I'm not convinced that this feature would add sufficient value to the addon to warrant the amount of time required to implement this feature. I'm just not sure that this feature would be widely used. For this reason, I'm afraid at this time I have decided to not implement this feature.

Please feel free to submit other feature requests in the future.

Kind regards,
Alumian
