### ISSUE TITLE
[Bug] GP not reported when manually adding GP through raid window.

### ISSUE THREAD

**Issue by Carbohydron** [Alumian/CEPGP-Retail#141]
**The Error**
No error message.

**Describe the bug**
An item was accidentally given out outside of the CEPGP system. To correct, I manually clicked on the recipient's name in the raid window of CEPGP. I checked GP, entered the item's value, and listed the item as the reason. GP was applied and the event was tracked in EPGP traffic, however it was not reported in either reporting channels. This caused anxiety in the raid, as they didn't get a confirmation that the item was within the EPGP system.

**To Reproduce**
/cep show
Go to guild or raid window
Click on a member's name
Check the GP radio button
Enter a valid GP number
Enter any reason
Click confirm
Despite reporting channels set in options, no message is sent to either Raid or Guild

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.7<br />
Locale: enUS<br />
GP Formula: (4.83x(1^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x10<br />Base GP: 1<br />
Base GP Decay Factor: false<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
GUI for Loot: False<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: true<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: GUILD<br />
Loot Response Channel: RAID<br />
Minimum Threshold for Loot: 3<br />
Allow Force Sync: true, Chester Cheeto<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Lord Kri: True<br />
Emperor Vek'nilash: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Lady Blaumeux: True<br />
Highlord Mograine: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Teremus the Devourer: True<br />
Chromaggus: True<br />
Baron Geddon: True<br />
Firemaw: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
High Priestess Arlokk: True<br />
Emperor Vek'lor: True<br />
Gahz'ranka: True<br />
Gluth: True<br />
Sapphiron: True<br />
Razorgore the Untamed: True<br />
Onyxia: True<br />
Princess Yauj: True<br />
Vem: True<br />
Shazzrah: True<br />
Ouro: True<br />
Battleguard Sartura: True<br />
Maexxna: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Ragnaros: True<br />
Ayamiss the Hunter: True<br />
Broodlord Lashlayer: True<br />
Viscidus: True<br />
Hakkar: True<br />
Ebonroc: True<br />
Kurinnaxx: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Sir Zeliek: True<br />
Vaelastrasz the Corrupt: True<br />
Patchwerk: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
Jin'do the Hexxer: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Lord Kri: 10<br />
Emperor Vek'nilash: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 50<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 50<br />
High Priest Venoxis: 2<br />
Gehennas: 50<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Lady Blaumeux: 15<br />
Highlord Mograine: 15<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Teremus the Devourer: 7<br />
Chromaggus: 7<br />
Baron Geddon: 50<br />
Firemaw: 7<br />
Sulfuron Harbinger: 50<br />
Gri'lek: 2<br />
High Priestess Arlokk: 2<br />
Emperor Vek'lor: 10<br />
Gahz'ranka: 2<br />
Gluth: 12<br />
Sapphiron: 15<br />
Razorgore the Untamed: 7<br />
Onyxia: 50<br />
Princess Yauj: 10<br />
Vem: 10<br />
Shazzrah: 50<br />
Ouro: 10<br />
Battleguard Sartura: 10<br />
Maexxna: 15<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 50<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Ragnaros: 50<br />
Ayamiss the Hunter: 3<br />
Broodlord Lashlayer: 7<br />
Viscidus: 10<br />
Hakkar: 3<br />
Ebonroc: 7<br />
Kurinnaxx: 3<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 50<br />
Sir Zeliek: 15<br />
Vaelastrasz the Corrupt: 7<br />
Patchwerk: 12<br />
Bloodlord Mandokir: 2<br />
Renataki: 2<br />
Jin'do the Hexxer: 2<br />
Garr: 50<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Chester Cheeto: False<br />
Officer: False<br />
Veteran: False<br />
Seedless Member: False<br />
Member: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
RANGED: 0.5<br />
SHOULDER: 0.75<br />
FEET: 0.75<br />
LEGS: 1<br />
EXCEPTION: 1<br />
WAIST: 0.75<br />
TRINKET: 0.75<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1<br />
CLOAK: 0.5<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 0.5<br />
RANGEDRIGHT: 0.5<br />
RELIC: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
ArkInventory<br />
ArkInventoryRules<br />
ArkInventoryRules_Example<br />
ArkInventorySearch<br />
AtlasLootClassic<br />
BagBrother<br />
Bagnon<br />
Bartender4<br />
BlueShamans<br />
CEPGP<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
ClickLinks<br />
dashingDismount<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
FasterLooting<br />
GatherLite<br />
HealComm<br />
Immersion<br />
InFlight_Load<br />
ItemRack<br />
LargerMacroIconSelection<br />
Mapster<br />
MaxCam<br />
Plater<br />
Postal<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
QuestLogEx<br />
QuestXP<br />
RealMobHealth<br />
Recount<br />
ShadowedUnitFrames<br />
SunnArt<br />
TipTop<br />
TwitchEmotes<br />
WeaponSwingTimer<br />
XPTracker<br />
CharacterStatsClassic<br />
TradeSkillMaster<br />
TradeSkillMaster_AppHelper<br />
EZCoordinates<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by yinzl90** [comment]
I have the same experience, when adding pos/neg GP to someone for a specific reason through GUILD/RAID view, it is not reporting to any channel and executed silently. This is very bad experience since no one has any ideas what is going on. Even myself feel it is not happening until I double checked the GP value has been changed. BTW, the transaction view has the record correctly.

**Comment by Alumian** [comment]
Fixed in the next update.
