### ISSUE TITLE
EP Reset on Standby List

### ISSUE THREAD

**Issue by Magevossie** [Alumian/CEPGP-Retail#142]
For WoW Classic we use your addon for our raids and everything except the standby list works flawless.
We have it set so that players have to whisper !standby to the masterlooter to be added to the standby list. The percentage is set to "50" and we have the box checked to give the standby EP to offline players, in case they want to level an alt in the meanwhile.
However after the raid is finished, I check their EPGP to see if it has been working properly, and it reset their EP to 0. This has happened both this week and last weeks Molten Core raid, to multiple different members, all getting the same result, EP reset to 0. The EPGP traffic log shows that standby EP has been given out. Im using the most up to date version via the twitch app, version 1.13.2.

Id love to know how to fix this,
Thanks alot in advance.

**Comment by Alumian** [comment]
Version 1.13.2 was a typo version from a long time ago and I have no idea why it's still available on twitch considering I have removed that particular version from curse. The most recent stable release is 1.12.7. Download 1.12.7 and the issue will be resolved.

**Comment by Magevossie** [comment]
Did Molten Core today, the bug is still there. I misread the game version for the addon version. I was already using 1.12.7. Reinstalled it just to be sure, but yes, EP still reset to 0 on standby list.

**Comment by Alumian** [comment]
Since you didn't post your debug info I can't verify what version you were running at the time and this bug has not been reported by anyone else running a later version than the one you previously said you were using. If it happens again, open a new ticket and ensure that you use the bug report template since that has guidelines as to what information I need you to include.
