### ISSUE TITLE
One-handed weapon calculated as Off-hand

### ISSUE THREAD

**Issue by PetyaGulyas** [Alumian/CEPGP-Retail#143]
**The Error**
One-handed weapon GP calculation is incorrect as it should use the Weapon [1.5] slot weight instead of Off-hand Weapon slot weight [0.5].

**Describe the bug**
In the Utility.lua there is 2 row of code which converts One-hand weapon to Off-handed, which gives incorrect values for One-handed items such as 

- Thunderfury Blessed Blade of the Windseeker GP value of 40. -> should be 120 [1.5 multiplier]
- Brutality Blade GP value of 17

Incorrect code snippet:
- " if slot == "INVTYPE_WEAPON" then slot = "INVTYPE_WEAPONOFFHAND"; end "
at both row number 160 and 207

**To Reproduce**
Check any Off-hand weapon GP, use the given formula to calculate the GP value. Check Utility.lua for the Weapon slot weight, or the 
- http://www.epgpweb.com/help/gearpoints -> Basic values slot modifiers section.

**Comment by PetyaGulyas** [comment]
[Request] add the Weapon slot weight to Option window

**Comment by Alumian** [comment]
This has been implemented in the 1.12.8 beta and will be included in the next release.

**Comment by PetyaGulyas** [comment]
Thx, keep up the good work :)
