### ISSUE TITLE
[Request] Auto/Manual add raid EP to only Online/In raid instance members

### ISSUE THREAD

**Issue by yinzl90** [Alumian/CEPGP-Retail#147]
When I am adding raid EP, I mostly use it for gathering on time, and dissemble after all. However sometimes, there are people offline or not in the instance. So our solution is adding entire raid EP and then reduce them for those offline or out of the raid.

Another case is that after we down a boss, the boss ep is added automatically to all members in raid group, also to those offline/out of the raid instance. We have to either reduce them manually later on or remove them from the raid group and invite later on.

It will be very nice that there is a choice to check "Whether to add EP to offline members/not in instance members".

Thanks.

**Comment by Halekxx** [comment]
Hi guys... this feature would be greatly appreciated. :)
just posting here so i can keep track of it and a possible date of implementation

**Comment by ollema** [comment]
there is a plugin for that:

**CEPGP-Zone-Award**

> CEPGP Zone Award adds functionality to award raid wide EP to those who are both online and in the same zone as the player making the award. An additional check box can be found on the Raid Moderation window when awarding raid EPs which will enable this feature. Upon making the award messages (which can be suppressed) are sent highlighting those who did not qualify.

Source: [https://www.curseforge.com/wow/addons/cepgp-zone-award](https://www.curseforge.com/wow/addons/cepgp-zone-award)

**Comment by Alumian** [comment]
Closing this request as a plugin has been developed which supports this functionality.
