### ISSUE TITLE
[Request] Loot Announcement/Distribution from bag?

### ISSUE THREAD

**Issue by yinzl90** [Alumian/CEPGP-Retail#148]
We know that we have distribute items when looting bosses. However, sometimes in order to farm more efficiently, we may collect all drops in RL's inventory and kill all bosses first, and then distribute all drops together.

Can CEPGP support announce items and distribution calls for the items from inventory, giving GP and mock item distribution? (which will be traded face to face instead of distributed by API)

I think this will help more GUILD to use CEPGP

Thanks.
Z

**Comment by Alumian** [comment]
Thanks for the feature request. Due to the nature of how CEPGP awards GP on item distribution, this is not feasible. I will however be adding an option for item links when manually awarding GP which will achieve the same result. Please see ticket #132 for future updates on this matter.
