### ISSUE TITLE
[Request] Sandbox Mode

### ISSUE THREAD

**Issue by sostoked** [Alumian/CEPGP-Retail#15]
It would be nice to test the features of this add-on without having to be in a raid. Is it possible to create a sandbox mode that replicates an item drop and bid scenario or at least shows an example of what this looks like?

**Comment by Alumian** [comment]
Hi Sostoked,
At this stage you can achieve what you're asking, to some extent. If you type /cep debugmode then that enables what I use for development purposes, but it also achieves what you want to some degree. With debug mode turned on, you can announce loot of any rarity, but you can't actually distribute the item if it is junk, common or below the master loot threshold. Hence, from this mode, you won't be able to award GP for items that could not be master looted.

I seem to be getting a lot of questions recently about how to use the addon so I'm thinking, once I get some of the major bugs worked out and have some breathing room, then I'll make a guide for the addon. But as this feature would take a significant amount of time and not add value beyond what a guide could, unfortunately at this time I do not intend to implement this feature.

Please feel free to submit feature requests in future.
