### ISSUE TITLE
Ragnaros EP not added[Bug]

### ISSUE THREAD

**Issue by will5757** [Alumian/CEPGP-Retail#151]
The last 2 rag kills we've done didn't automatically award EP, not sure what went wrong but it works for every other boss and worked flawlessly up until last week.  The checkbox is still marked, i unchecked and rechecked it tonight but i'll have to wait for next week to see if that did anything

<details><summary>Debug Info</summary><br />
Version: 1.12.7<br />
Locale: enUS<br />
GP Formula: (4.83x(1.8^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x2<br />Base GP: 50<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 100<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: true<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: RAID<br />
Loot Response Channel: RAID<br />
Minimum Threshold for Loot: 3<br />
Allow Force Sync: true, Senior Officer<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Lord Kri: True<br />
Emperor Vek'nilash: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Lady Blaumeux: True<br />
Highlord Mograine: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Teremus the Devourer: True<br />
Chromaggus: True<br />
Baron Geddon: True<br />
Firemaw: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
High Priestess Arlokk: True<br />
Emperor Vek'lor: True<br />
Gahz'ranka: True<br />
Gluth: True<br />
Sapphiron: True<br />
Razorgore the Untamed: True<br />
Onyxia: True<br />
Princess Yauj: True<br />
Vem: True<br />
Shazzrah: True<br />
Ouro: True<br />
Battleguard Sartura: True<br />
Maexxna: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Ragnaros: True<br />
Ayamiss the Hunter: True<br />
Broodlord Lashlayer: True<br />
Viscidus: True<br />
Hakkar: True<br />
Ebonroc: True<br />
Kurinnaxx: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Sir Zeliek: True<br />
Vaelastrasz the Corrupt: True<br />
Patchwerk: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
Jin'do the Hexxer: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 20<br />
Gothik the Harvester: 120<br />
Buru the Gorger: 30<br />
Wushoolay: 20<br />
Lord Kri: 100<br />
Emperor Vek'nilash: 100<br />
Ossirian the Unscarred: 40<br />
Golemagg the Incinerator: 50<br />
Grand Widow Faerlina: 120<br />
High Priestess Mar'li: 20<br />
Majordomo Executus: 50<br />
High Priest Venoxis: 20<br />
Gehennas: 50<br />
Taerar: 70<br />
Ysondre: 70<br />
Thane Korth'azz: 150<br />
High Priest Thekal: 20<br />
Noth the Plaguebringer: 120<br />
Lethon: 70<br />
Moam: 30<br />
The Prophet Skeram: 100<br />
Flamegor: 70<br />
C'Thun: 120<br />
General Rajaxx: 30<br />
Princess Huhuran: 100<br />
Thaddius: 150<br />
Loatheb: 150<br />
Lady Blaumeux: 150<br />
Highlord Mograine: 150<br />
Heigan the Unclean: 120<br />
Azuregos: 70<br />
Doom Lord Kazzak: 70<br />
Teremus the Devourer: 70<br />
Chromaggus: 70<br />
Baron Geddon: 50<br />
Firemaw: 70<br />
Sulfuron Harbinger: 50<br />
Gri'lek: 20<br />
High Priestess Arlokk: 20<br />
Emperor Vek'lor: 100<br />
Gahz'ranka: 20<br />
Gluth: 120<br />
Sapphiron: 150<br />
Razorgore the Untamed: 70<br />
Onyxia: 50<br />
Princess Yauj: 100<br />
Vem: 100<br />
Shazzrah: 50<br />
Ouro: 100<br />
Battleguard Sartura: 100<br />
Maexxna: 150<br />
Kel'Thuzad: 150<br />
Nefarian: 100<br />
Fankriss the Unyielding: 100<br />
Lucifron: 50<br />
Anub'Rekhan: 120<br />
Hazza'rah: 20<br />
Ragnaros: 70<br />
Ayamiss the Hunter: 30<br />
Broodlord Lashlayer: 70<br />
Viscidus: 100<br />
Hakkar: 30<br />
Ebonroc: 70<br />
Kurinnaxx: 30<br />
Grobbulus: 120<br />
Instructor Razuvious: 120<br />
Emeriss: 70<br />
Magmadar: 50<br />
Sir Zeliek: 150<br />
Vaelastrasz the Corrupt: 70<br />
Patchwerk: 120<br />
Bloodlord Mandokir: 20<br />
Renataki: 20<br />
Jin'do the Hexxer: 20<br />
Garr: 50<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
Senior Officer: False<br />
Officer: False<br />
Officer Alt: False<br />
Raider: False<br />
Craftsmen: False<br />
Alt: False<br />
Member: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
RANGED: 0.5<br />
SHOULDER: 0.75<br />
FEET: 0.75<br />
LEGS: 1<br />
EXCEPTION: 1<br />
WAIST: 0.75<br />
TRINKET: 0.75<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1<br />
CLOAK: 0.5<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 0.5<br />
RANGEDRIGHT: 0.5<br />
RELIC: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
Ring of spell power : 40<br />
Brutality blade : 40<br />
Quick strike ring : 40<br />
Talisman of ephemeral power : 50<br />
Striker's mark : 40<br />
Mana igniting cord : 50<br />
Vis'kag the bloodletter : 75<br />
Choker of the fire lord : 40<br />
Perdition's blade : 81<br />
Azuresong mageblade : 90<br />
Tome of tranquilizing shot : 0<br />
Band of accuria : 40<br />
The Eye of Divinity: 72<br />
Sorcerous dagger : 45<br />
</details>
<details><summary>Addons List</summary>
AdvancedInterfaceOptions<br />
Atlas<br />
Atlas_ClassicWoW<br />
Atlas_DungeonLocs<br />
Atlas_Transportation<br />
AtlasLootClassic<br />
Auctionator<br />
BetterVendorPrice<br />
CEPGP<br />
ClassicGuildBank<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
ExtendedCharacterStats<br />
GatherMate2<br />
InFlight_Load<br />
ItemRack<br />
Leatrix_Plus<br />
LibStub<br />
LibClassicDurations<br />
NameplateSCT<br />
QuestAnnounce<br />
ReturnBuffTracker<br />
WeakAuras<br />
WIM<br />
ElvUI<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Owersun** [comment]
After last adjustments to wow client log range there is an issue that you don't sense mobs dying farther than 50 yards. Are you ML/EPGP master range class? Did he stand far away from the boss? Try to approach the boss as close as possible just before the kill

**Comment by jrydh** [comment]
We also did not get automatic EP for Ragnaros yesterday. I was the ML and I'm a warlock, but Shadowbolt range is less than 50 yards, so I should have seen it.

**Comment by will5757** [comment]
I'm a mage, so max range is like 36 yards

**Comment by Alumian** [comment]
Hi Will, apologies for not getting back to you sooner. Has the issue occurred since you posted this report?

**Comment by will5757** [comment]
nah, you fixed it a while back.  Something about the addon communicating
with other players addon i think? (we require all raiders to run the addon,
makes lot simpler)

thanks a ton for you hard work, this addon has really made it
comparatively easy to run loot for our guild.

**Comment by Alumian** [comment]
Thanks for the update and I'm glad my addon has helped you out ^^
