### ISSUE TITLE
[Bug] 410/100=4.09  and  510/100=5.09 ???

### ISSUE THREAD

**Issue by Se7enMuting** [Alumian/CEPGP-Retail#152]
using 1.12.7.
Please see the pictures below:
why 410/100=4.09  and  510/100=5.09 ???

![310](https://user-images.githubusercontent.com/889925/70308988-7309fb00-1847-11ea-96b7-0a18b873d1fc.png)
![410](https://user-images.githubusercontent.com/889925/70308990-73a29180-1847-11ea-8833-70dfa132f77a.png)
![510](https://user-images.githubusercontent.com/889925/70308991-73a29180-1847-11ea-8c0b-fb3e96688353.png)
![610](https://user-images.githubusercontent.com/889925/70308992-743b2800-1847-11ea-9b52-58d9d2782e04.png)

**Comment by Se7enMuting** [comment]
I fround :
if
`math.floor((tonumber(EP)/tonumber(GP))*100)/100`
change to
`math.floor((tonumber(EP)*100/tonumber(GP)))/100`
then
410/100=4.1 and 510/100=5.1  right

**Comment by Alumian** [comment]
Implemented this change in beta 1.
