### ISSUE TITLE
[Request] twink linked to main char

### ISSUE THREAD

**Issue by Solitaric** [Alumian/CEPGP-Retail#154]
**Describe the feature you'd like to see in this addon**
Player “warmonger” have twink “noobheal”  (^_^)  so for indicating twink we replace officer note “noobheal” to @warmonger
@ (or any other) system symbol for addon to mark what this char is twink and address to main char

with this 
And in all adding/decreasing EP/GP it does with main char officers note
Decay function must ignore all char with @ symbol

it VERY helps

**Comment by Alumian** [comment]
Unfortunately the request behaviour will require a significant rework of core modules in the add-on and will provide little benefit where you could just use public notes instead. I will be adding in support to link Alta, please keep an eye on #33 for updates.
