### ISSUE TITLE
[Request] More Options Within Loot Distribution

### ISSUE THREAD

**Issue by Jh16** [Alumian/CEPGP-Retail#156]
**Describe the feature you'd like to see in this addon**
Within the Loot Distribution you have just one button that helps with distributing loot. I think it would be good to have a few more.

- **Main Spec** - _you already have so ignore this line_
- **Off Spec** - _when used it gives a percentage off from original GP price, perhaps a new setting within the options to determine the percentage off_
- **Bank** - _awards set player item but only charging 0 GP, in traffic it says banked and to who. perhaps another setting to have an array of desired character names to be assigned as the bank. if first name isn't there check for the second and so on._
- **D/E** - _awards set player item but only charging 0 GP, in traffic it says D/E and to who. same kind of situation as bank._

Personally I think with these added selections will make the addon much easier to use. Since currently when having to call for Off Spec we would have to click back through the Loot Distribution and change the GP value then announce it again. Unfortunately it would also continue to say for Main Spec in the raid announcement.

Thanks again

**Comment by Alumian** [comment]
Thanks for the feature request. This feature has already been implemented in the 1.12.8 beta and currently has an existing ticket open (see #23)
