### ISSUE TITLE
[Bug] Loot responses not being posted to raid channel

### ISSUE THREAD

**Issue by cather-kurinaxx** [Alumian/CEPGP-Retail#157]
**The Error**
What was the error message you received?
- No error

**Describe the bug**
- Loot responses when someone whispers !need are not being sent to raid channel as with previous betas

**To Reproduce**
How can this bug be reproduced?
I have setup a test raid and set loot to poor quality and tested with a few players in the guild. When whispering !need it shows up properly in the loot distro window but no callout goes to raid channel

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.

<details><summary>Debug Info</summary><br />
Version: 1.12.8.beta-6<br />
Locale: enUS<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1<br />
Base GP Decay Factor: false<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: False<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: !standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 0<br />
Allow Force Sync: false, Dad<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Lord Kri: True<br />
Emperor Vek'nilash: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Lady Blaumeux: True<br />
Highlord Mograine: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Firemaw: True<br />
Baron Geddon: True<br />
Jin'do the Hexxer: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
Renataki: True<br />
Bloodlord Mandokir: True<br />
Patchwerk: True<br />
Vaelastrasz the Corrupt: True<br />
Sapphiron: True<br />
Onyxia: True<br />
Emeriss: True<br />
Princess Yauj: True<br />
Vem: True<br />
Shazzrah: True<br />
Kurinnaxx: True<br />
Battleguard Sartura: True<br />
Ebonroc: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Hakkar: True<br />
Viscidus: True<br />
Broodlord Lashlayer: True<br />
Ayamiss the Hunter: True<br />
Maexxna: True<br />
Ragnaros: True<br />
Ouro: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Sir Zeliek: True<br />
Gluth: True<br />
Emperor Vek'lor: True<br />
Gahz'ranka: True<br />
High Priestess Arlokk: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Lord Kri: 10<br />
Emperor Vek'nilash: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 200<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 200<br />
High Priest Venoxis: 2<br />
Gehennas: 200<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Lady Blaumeux: 15<br />
Highlord Mograine: 15<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Firemaw: 7<br />
Baron Geddon: 200<br />
Jin'do the Hexxer: 2<br />
Sulfuron Harbinger: 200<br />
Gri'lek: 2<br />
Renataki: 2<br />
Bloodlord Mandokir: 2<br />
Patchwerk: 12<br />
Vaelastrasz the Corrupt: 7<br />
Sapphiron: 15<br />
Onyxia: 200<br />
Emeriss: 7<br />
Princess Yauj: 10<br />
Vem: 10<br />
Shazzrah: 200<br />
Kurinnaxx: 3<br />
Battleguard Sartura: 10<br />
Ebonroc: 7<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 200<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Hakkar: 3<br />
Viscidus: 10<br />
Broodlord Lashlayer: 7<br />
Ayamiss the Hunter: 3<br />
Maexxna: 15<br />
Ragnaros: 250<br />
Ouro: 10<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 7<br />
Magmadar: 200<br />
Sir Zeliek: 15<br />
Gluth: 12<br />
Emperor Vek'lor: 10<br />
Gahz'ranka: 2<br />
High Priestess Arlokk: 2<br />
Chromaggus: 7<br />
Garr: 200<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Dad: True<br />
Other Dad: True<br />
Officer: True<br />
Raider: True<br />
Member: True<br />
Initiate: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
THROWN: 0.5<br />
RELIC: 0.5<br />
RANGEDRIGHT: 0.5<br />
TRINKET: 0.75<br />
WEAPONOFFHAND: 0.5<br />
FINGER: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
LEGS: 1<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
ArkInventory<br />
ArkInventoryRules<br />
ArkInventorySearch<br />
Atlas<br />
Atlas_ClassicWoW<br />
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
BagBrother<br />
BeanCounter<br />
CEPGP<br />
Classic Quest Log<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
Enchantrix-Barker<br />
ExRT<br />
GatherMate2<br />
GTFO<br />
Masque<br />
Masque_Caith<br />
MikScrollingBattleText<br />
Peggle<br />
RealMobHealth<br />
Recount<br />
SamyTotemTimers<br />
SlideBar<br />
Stubby<br />
!Swatter<br />
VendorPrice<br />
CharacterStatsClassic<br />
ElvUI_BenikUI_Classic<br />
ElvUI<br />
Wardrobe<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>
![Capture](https://user-images.githubusercontent.com/58753346/70576011-c8ab1400-1b75-11ea-9a92-f98f5f3b573e.PNG)

**Comment by Alumian** [comment]
Thanks for speaking with me Cather, as discussed, we've produced a solution and it will be included in the 1.12.8 release.

**Comment by Alumian** [comment]
Resolved in the 1.12.8 release.
