### ISSUE TITLE
No automatic GP given out with loot. 

### ISSUE THREAD

**Issue by VidyaViking** [Alumian/CEPGP-Retail#164]
Since the latest update GP is no longer awarded when loot is handed out. Several lootmasters tried, also 1 person had the old version and it still worked. Tried updating and didn't work anymore.

**Comment by VidyaViking** [comment]
Started working randomly after some bosses...

**Comment by Alumian** [comment]
Resubmit your ticket using the bug report template and ensure that you include the dump from /cep debug.
