### ISSUE TITLE
[Request] Off-Spec Support

### ISSUE THREAD

**Issue by Kirbstomp** [Alumian/CEPGP-Retail#165]
Requesting the addition of several features that would better facilitate the distribution of items for Off Spec:
- Update Options page to contain a second Response Keyboard field for Off Spec purposes (i.e. !off).
- Update Distribution page to see Main Spec (on top) and Off Spec (bottom)  
- Update Options page to include an Off Spec modifier percentage (for instance a user could set it to 0%, 50%, etc.), if the item is awarded via the Off Spec Distribution list, then this percentage is used in the final calculation.

Love the addon so far, making EPGP a lot easier for the guild!

**Comment by Alumian** [comment]
Hey Kirb, thanks for submitting this feature request. This request has already been submitted but the title isn't super descriptive. I'll update that for the requester. Please keep an eye on #161.

**Comment by Kirbstomp** [comment]
Oops, you're right!  I missed that one, will keep an eye out for any
updates on it.  Thanks for the quick response!
