### ISSUE TITLE
[Request] Add a 'share' or 'sync' button against each traffic entry

### ISSUE THREAD

**Issue by mykkenny** [Alumian/CEPGP-Retail#167]
A 'share' or 'sync' button, transmits it to your usual channel (raid, guild, etc) and anyones addon listening can parse the timestamp, giver, receiver, see if it is a match against any of their own entries and if not import it

**Comment by Mominejaz** [comment]
This for classic would be awesome!

**Comment by will5757** [comment]
Seconded, i've been playing around with the idea of asking for some sort of syncing for the epgp traffic page.

**Comment by Alumian** [comment]
Implemented in 1.12.15.
