### ISSUE TITLE
[Request]Translation of Chinese and HTML requirements

### ISSUE THREAD

**Issue by zmmcyzmmcy** [Alumian/CEPGP-Retail#168]
hello，Alumain
I translated part of the content into Chinese, and I added it in the evening.
I made a suggestion on curse before, please add html to export function T-T

[zhCN.lua.zip](https://github.com/Alumian/CEPGP-Retail/files/4001608/zhCN.lua.zip)

**Comment by zmmcyzmmcy** [comment]
Fixed some boss translations.

There are two questions:

1. Which boss is the edge of madness in Zul'Gurub

2. The translation in zhcn.lua cannot replace the text on the button?

[zhCN.zip](https://github.com/Alumian/CEPGP-Retail/files/4002491/zhCN.zip)

**Comment by Alumian** [comment]
The Edge of Madness consists of 4 bosses:
- Hazza'rah
- Gri'lek
- Renataki
- Wushoolay

I will start implementing translations for buttons soon.

**Comment by zmmcyzmmcy** [comment]
[zhCN.zip](https://github.com/Alumian/CEPGP-Retail/files/4183850/zhCN.zip)

add buttons translations

**Comment by Alumian** [comment]
![image](https://user-images.githubusercontent.com/24452898/74429781-b5872e00-4eaf-11ea-8fa5-9b5ee0d51e19.png)
Looks good! Thanks heaps for the contribution!

**Comment by zmmcyzmmcy** [comment]
[zhCN.zip](https://github.com/Alumian/CEPGP-Retail/files/4217436/zhCN.zip)

update for 1.12.10 beta1
