### ISSUE TITLE
[Bug] Excessive Import Requests Result in Disconnection

### ISSUE THREAD

**Issue by Boomdead123** [Alumian/CEPGP-Retail#169]
**Describe the bug**

If you spam import someone elses settings in the addon you can kick people offline dcing them from the game

**Comment by Alumian** [comment]
What version are you using? Do you mean literally spamming the import settings button or do you mean force sync?

**Comment by Boomdead123** [comment]
Current version of the addon and all you have to do is type someones name into the import settings box and spam it and they will dc

**Comment by Alumian** [comment]
Which version is the current version? I've had people tell me they're running version 1.13.3 which isn't a thing.

**Comment by Boomdead123** [comment]
1.12.8-hotfix 2

**Comment by Boomdead123** [comment]
should be able to fix it by limiting import requests to a certain amount.

**Comment by Alumian** [comment]
Yeah I've got an idea about how I can approach this.

**Comment by Alumian** [comment]
Just in future, can you please ensure that you follow the bug template and include your /cep debug dump? In future I will be closing tickets without action if that information is not included. Also giving your bug report a title helps distinguish it from others.

**Comment by Alumian** [comment]
Fixed in the next beta.

**Comment by Alumian** [comment]
Resolved in 1.12.9.
