### ISSUE TITLE
GP is not being rewarded when distributing loot via the CEPGP addon [Bug] 

### ISSUE THREAD

**Issue by TheGreekOne** [Alumian/CEPGP-Retail#175]
**The Error**
In the chat I am getting a message that says "X is not eligible" or something to that effect.  I will update this with the exact verbiage.  

**Describe the bug**
When we loot a boss the Loot Distribution window opens, as expected.  We are using the GUI for distribution so everyone clicks the appropriate button and then I select the player with the highest PR.  

When I am distributing the loot I get a message in chat that says "X is not on the eligible list" or something to that effect.  But even still the loot is put in their bag.  From the ML perspective it looks like it was never distributed so I have had to check with the recipient over voice comms to make sure they got it.  

I will work to replicate the bug and get a SS.

**To Reproduce**
This has happened for multiple raids now.  We are doing nothing different but only began after the most recent hotfix.

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.  I will update this report with this info.

**Comment by Alumian** [comment]
Hey GreekOne,
Has this issue occurred since posting this report?

**Comment by Alumian** [comment]
No further reports of this issue have been received. Assuming this has been resolved.

**Comment by Alumian** [comment]
Implementation has now been released.
