### ISSUE TITLE
[Bug] Traffic Entries Not Being Shared

### ISSUE THREAD

**Issue by clamm1** [Alumian/CEPGP-Retail#176]
**The Error**
What was the error message you received?
The traffic log is not updating fully for all raid members, only the ML.  GP/EP values are correct.
**Describe the bug**
The traffic log is not updating fully for all raid members, only the ML.  GP/EP values are correct.  Can guild control settings affect this at all?
**To Reproduce**
How can this bug be reproduced?
Verified with 25 people their logs do not match and there are multiple versions from the same raid.
**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.

**Comment by Alumian** [comment]
> Debug Information
Type /cepgp debug and copy and paste the information into this bug report.

Please attach your CEPGP debug info here.

**Comment by Alumian** [comment]
No further communication received and debug info has still not been dumped. Assuming the issue has been resolved.
