### ISSUE TITLE
[Request] View traffic for individual player

### ISSUE THREAD

**Issue by Mysmonstret** [Alumian/CEPGP-Retail#181]
The traffic log is an important part of the addon, for accountability and transparence. However people are often interested in the gains of others, and have a hard time finding individuals in a long list. 

I suggest being able to click a player in the guild and/or raid list and bring up their individual traffic history.

**Comment by Alumian** [comment]
Hi Mysmonstret, thanks for your feature request. At this stage you are able to do this simply by entering the player's name into the search bar. If the player's name is found **anywhere** in an entry, you will see it.
Thanks!
