### ISSUE TITLE
[Bug] auto add raid ep have no effect

### ISSUE THREAD

**Issue by rxcxj77** [Alumian/CEPGP-Retail#184]
**The Error**
no error message

**Describe the bug**
I've checked auto award for mc/onyxia , but it didn't work. Why is that.Is it because of insufficient permissions or other reasons?

**To Reproduce**

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.8.release-hotfix2<br />
Locale: zhCN<br />
GP Formula: (4.83x(1^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1<br />
Base GP Decay Factor: false<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
GUI for Loot: False<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: false<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 2<br />
Allow Force Sync: false, 合道<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
管理者埃克索图斯: True<br />
Emperor Vek'nilash: True<br />
Ossirian the Unscarred: True<br />
鲁西弗隆: True<br />
克洛玛古斯: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
狂野的拉佐格尔: True<br />
Majordomo Executus: True<br />
Gahz'ranka: True<br />
加尔: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
沙斯拉尔: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Renataki: True<br />
The Prophet Skeram: True<br />
Gluth: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
焚化者古雷曼格: True<br />
堕落的瓦拉斯塔兹: True<br />
Thaddius: True<br />
Loatheb: True<br />
奥妮克希亚: True<br />
Lady Blaumeux: True<br />
Chromaggus: True<br />
Flamegor: True<br />
Firemaw: True<br />
Emperor Vek'lor: True<br />
Highlord Mograine: True<br />
Ebonroc: True<br />
Ragnaros: True<br />
奈法利安: True<br />
费尔默: True<br />
Heigan the Unclean: True<br />
Razorgore the Untamed: True<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
Bloodlord Mandokir: True<br />
萨弗隆先驱者: True<br />
Ayamiss the Hunter: True<br />
Vaelastrasz the Corrupt: True<br />
基赫纳斯: True<br />
High Priestess Arlokk: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
Broodlord Lashlayer: True<br />
迦顿男爵: True<br />
Kurinnaxx: True<br />
拉格纳罗斯: True<br />
Princess Yauj: True<br />
Azuregos: True<br />
埃博诺克: True<br />
High Priest Thekal: True<br />
Vem: True<br />
Shazzrah: True<br />
Hakkar: True<br />
Battleguard Sartura: True<br />
Ouro: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Lord Kri: True<br />
玛格曼达: True<br />
Viscidus: True<br />
Moam: True<br />
Maexxna: True<br />
弗莱格尔: True<br />
Baron Geddon: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Sir Zeliek: True<br />
High Priest Venoxis: True<br />
Patchwerk: True<br />
Sapphiron: True<br />
勒什雷尔: True<br />
Jin'do the Hexxer: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
管理者埃克索图斯: 8<br />
Emperor Vek'nilash: 10<br />
Ossirian the Unscarred: 4<br />
鲁西弗隆: 8<br />
克洛玛古斯: 7<br />
Golemagg the Incinerator: 8<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
狂野的拉佐格尔: 7<br />
Majordomo Executus: 8<br />
Gahz'ranka: 2<br />
加尔: 8<br />
Gehennas: 8<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
沙斯拉尔: 8<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Renataki: 2<br />
The Prophet Skeram: 10<br />
Gluth: 12<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
焚化者古雷曼格: 8<br />
堕落的瓦拉斯塔兹: 7<br />
Chromaggus: 15<br />
Thaddius: 15<br />
Loatheb: 15<br />
奥妮克希亚: 10<br />
Lady Blaumeux: 15<br />
Flamegor: 15<br />
Firemaw: 15<br />
Emperor Vek'lor: 10<br />
Ragnaros: 8<br />
Highlord Mograine: 15<br />
Ebonroc: 15<br />
奈法利安: 10<br />
Razorgore the Untamed: 15<br />
费尔默: 7<br />
Heigan the Unclean: 12<br />
Bloodlord Mandokir: 2<br />
Onyxia: 10<br />
Doom Lord Kazzak: 7<br />
Ayamiss the Hunter: 3<br />
萨弗隆先驱者: 8<br />
Vaelastrasz the Corrupt: 15<br />
High Priestess Arlokk: 2<br />
基赫纳斯: 8<br />
Broodlord Lashlayer: 15<br />
Sulfuron Harbinger: 8<br />
Gri'lek: 2<br />
Kurinnaxx: 3<br />
迦顿男爵: 8<br />
拉格纳罗斯: 8<br />
Princess Yauj: 10<br />
Azuregos: 7<br />
埃博诺克: 7<br />
High Priest Thekal: 2<br />
Vem: 10<br />
Lord Kazzak: 7<br />
Shazzrah: 8<br />
Hakkar: 3<br />
Battleguard Sartura: 10<br />
Ouro: 10<br />
Kel'Thuzad: 15<br />
Nefarian: 15<br />
Fankriss the Unyielding: 10<br />
Lucifron: 8<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Lord Kri: 10<br />
玛格曼达: 8<br />
Viscidus: 10<br />
Moam: 3<br />
Maexxna: 15<br />
Baron Geddon: 8<br />
弗莱格尔: 7<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 8<br />
Sir Zeliek: 15<br />
High Priest Venoxis: 2<br />
Patchwerk: 12<br />
Sapphiron: 15<br />
勒什雷尔: 7<br />
Jin'do the Hexxer: 2<br />
Garr: 8<br />
</details>
<details><summary>Standby Guild Ranks</summary>
合道: False<br />
EPGP管理: False<br />
职业队长: False<br />
拓荒团: False<br />
二团: False<br />
筑基: False<br />
小黑屋: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
SHOULDER: 0.75<br />
LEGS: 1<br />
EXCEPTION: 1<br />
TRINKET: 0.75<br />
WAIST: 0.75<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 0.5<br />
RANGEDRIGHT: 0.5<br />
RELIC: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
CChatNotifier<br />
CEPGP<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
ExRT<br />
Fizzle<br />
Leatrix_Maps<br />
LetMeCast<br />
MerInspect<br />
!MoncaiCompare<br />
oHWell<br />
Poisoner<br />
RangeDisplay<br />
RealMobHealth<br />
ShestakUI<br />
ShestakUI_Config<br />
TinyTooltip<br />
WeakAuras<br />
CharacterStatsClassic<br />
vBar<br />
EZQuest<br />
alaChat_Classic<br />
DamageEx<br />
DBM-Core<br />
DBM-StatusBarTimers<br />
DBM-VPVV<br />
DBM-DefaultSkin<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Thanks for submitting this bug report. It looks like the boss names have been converted to match your locale in your saved variables, which is unintentional behaviour. I'll look into this.

**Comment by Alumian** [comment]
Could you please provide the following information:
- Was the loot method set to master loot during this raid?
- Were you the loot master?
- Are you able to edit officer notes?
- How many bosses did this happen on?

**Comment by rxcxj77** [comment]
Thanks for your reply.

Loot method is master loot.
I'm not the loot master.
I can edit officer notes.
All bosses.

Next raid, i will transfer loot master and try again.

**Comment by Alumian** [comment]
Was your loot master using CEPGP?

**Comment by rxcxj77** [comment]
Yes, but that guy's addon is zhCN.
And not the latest version, so unable to confirm the cause of the problem.

**Comment by Alumian** [comment]
Okay that's very likely the problem. Localisation was only added in recent versions. Can you please confirm what version they're using? Type /cep version.

**Comment by rxcxj77** [comment]
Yes.

<details><summary>Debug Info</summary><br />
Version: 1.12.7<br />
Locale: zhCN<br />
GP Formula: (4.83x(1^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1<br />
Base GP Decay Factor: false<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
GUI for Loot: False<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: false<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 2<br />
Allow Force Sync: false, 合道<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
管理者埃克索图斯: True<br />
Emperor Vek'nilash: True<br />
Ossirian the Unscarred: True<br />
鲁西弗隆: True<br />
克洛玛古斯: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
狂野的拉佐格尔: True<br />
Majordomo Executus: True<br />
Gahz'ranka: True<br />
加尔: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
沙斯拉尔: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Renataki: True<br />
The Prophet Skeram: True<br />
Gluth: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
焚化者古雷曼格: True<br />
堕落的瓦拉斯塔兹: True<br />
Thaddius: True<br />
Loatheb: True<br />
奥妮克希亚: True<br />
Lady Blaumeux: True<br />
Chromaggus: True<br />
Flamegor: True<br />
Firemaw: True<br />
Emperor Vek'lor: True<br />
Ebonroc: True<br />
Highlord Mograine: True<br />
Ragnaros: True<br />
奈法利安: True<br />
费尔默: True<br />
Heigan the Unclean: True<br />
Razorgore the Untamed: True<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
Bloodlord Mandokir: True<br />
萨弗隆先驱者: True<br />
Ayamiss the Hunter: True<br />
Vaelastrasz the Corrupt: True<br />
Baron Geddon: True<br />
Sulfuron Harbinger: True<br />
High Priestess Arlokk: True<br />
Gri'lek: True<br />
Broodlord Lashlayer: True<br />
迦顿男爵: True<br />
Kurinnaxx: True<br />
拉格纳罗斯: True<br />
Princess Yauj: True<br />
Azuregos: True<br />
埃博诺克: True<br />
High Priest Thekal: True<br />
Vem: True<br />
Shazzrah: True<br />
Hakkar: True<br />
Battleguard Sartura: True<br />
Ouro: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Lord Kri: True<br />
玛格曼达: True<br />
Viscidus: True<br />
Moam: True<br />
Maexxna: True<br />
弗莱格尔: True<br />
基赫纳斯: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Sir Zeliek: True<br />
High Priest Venoxis: True<br />
Patchwerk: True<br />
Sapphiron: True<br />
勒什雷尔: True<br />
Jin'do the Hexxer: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
管理者埃克索图斯: 8<br />
Emperor Vek'nilash: 10<br />
Ossirian the Unscarred: 4<br />
鲁西弗隆: 8<br />
克洛玛古斯: 7<br />
Golemagg the Incinerator: 8<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
狂野的拉佐格尔: 7<br />
Majordomo Executus: 8<br />
Gahz'ranka: 2<br />
加尔: 8<br />
Gehennas: 8<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
沙斯拉尔: 8<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Renataki: 2<br />
The Prophet Skeram: 10<br />
Gluth: 12<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
焚化者古雷曼格: 8<br />
堕落的瓦拉斯塔兹: 7<br />
Chromaggus: 15<br />
Thaddius: 15<br />
Loatheb: 15<br />
奥妮克希亚: 10<br />
Lady Blaumeux: 15<br />
Flamegor: 15<br />
Firemaw: 15<br />
Emperor Vek'lor: 10<br />
Ragnaros: 8<br />
Highlord Mograine: 15<br />
Ebonroc: 15<br />
奈法利安: 10<br />
Razorgore the Untamed: 15<br />
费尔默: 7<br />
Heigan the Unclean: 12<br />
Bloodlord Mandokir: 2<br />
Onyxia: 10<br />
Doom Lord Kazzak: 7<br />
Ayamiss the Hunter: 3<br />
萨弗隆先驱者: 8<br />
Vaelastrasz the Corrupt: 15<br />
Sulfuron Harbinger: 8<br />
Baron Geddon: 8<br />
Broodlord Lashlayer: 15<br />
High Priestess Arlokk: 2<br />
Gri'lek: 2<br />
Kurinnaxx: 3<br />
迦顿男爵: 8<br />
拉格纳罗斯: 8<br />
Princess Yauj: 10<br />
Azuregos: 7<br />
埃博诺克: 7<br />
High Priest Thekal: 2<br />
Vem: 10<br />
Lord Kazzak: 7<br />
Shazzrah: 8<br />
Hakkar: 3<br />
Battleguard Sartura: 10<br />
Ouro: 10<br />
Kel'Thuzad: 15<br />
Nefarian: 15<br />
Fankriss the Unyielding: 10<br />
Lucifron: 8<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Lord Kri: 10<br />
玛格曼达: 8<br />
Viscidus: 10<br />
Moam: 3<br />
Maexxna: 15<br />
基赫纳斯: 8<br />
弗莱格尔: 7<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 8<br />
Sir Zeliek: 15<br />
High Priest Venoxis: 2<br />
Patchwerk: 12<br />
Sapphiron: 15<br />
勒什雷尔: 7<br />
Jin'do the Hexxer: 2<br />
Garr: 8<br />
</details>
<details><summary>Standby Guild Ranks</summary>
合道: False<br />
EPGP管理: False<br />
职业队长: False<br />
拓荒团: False<br />
二团: False<br />
筑基: False<br />
小黑屋: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
SHOULDER: 0.75<br />
LEGS: 1<br />
EXCEPTION: 1<br />
TRINKET: 0.75<br />
WAIST: 0.75<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 0.5<br />
RANGEDRIGHT: 0.5<br />
RELIC: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
CChatNotifier<br />
CEPGP<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
ExRT<br />
Fizzle<br />
Leatrix_Maps<br />
LetMeCast<br />
MerInspect<br />
!MoncaiCompare<br />
oHWell<br />
Poisoner<br />
RangeDisplay<br />
RealMobHealth<br />
ShestakUI<br />
ShestakUI_Config<br />
TinyTooltip<br />
WeakAuras<br />
CharacterStatsClassic<br />
vBar<br />
EZQuest<br />
alaChat_Classic<br />
DamageEx<br />
DBM-Core<br />
DBM-StatusBarTimers<br />
DBM-VPVV<br />
DBM-DefaultSkin<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
I'm pretty sure there was a compatibility issue with localisation in that version. Get your loot master to update and see if the issue happens again.

**Comment by rxcxj77** [comment]
Okay.
Thanks a lot.

**Comment by Alumian** [comment]
Hi rxcxj77, did the issue happen again?

**Comment by rxcxj77** [comment]
Hi Alumain.
This week, I am loot master  and auto award can now be used.
And there seems to be a little bit of a problem , MC number 1-9 is normal but 10 auto award didn't work.
onyxia is normal.

**Comment by Alumian** [comment]
So Ragnaros didn't work?

**Comment by rxcxj77** [comment]
Yes.

**Comment by Alumian** [comment]
Ok that's a known issue which I hope it's resolved in the next version.

**Comment by rxcxj77** [comment]
Okay, Thanks.
