### ISSUE TITLE
[Request]Whether decimal point can be reserved in use decay feature.

### ISSUE THREAD

**Issue by rxcxj77** [Alumian/CEPGP-Retail#185]
Decimal point not reserved when i decay guild EP/GP. 
example:
Member a GP is 6.
Member b GP is 5.
Decay 20%. 
A GP is 4.
B GP is 4.
It doesn't seem fair. Whether decimal point can be reserved?

**Comment by Alumian** [comment]
CEPGP does not support decimal places.

**Comment by cyrilbrugman** [comment]
Hi @rxcxj77 you can overcome this by increasing the EPGP mutliplier (MOD) if you set it to 1000x you will have less issues. you can look at my pull request to see the difference. 
https://github.com/Alumian/CEPGP-Retail/pull/177
