### ISSUE TITLE
[Question] how to manage multiple raid team within same guild

### ISSUE THREAD

**Issue by luozm** [Alumian/CEPGP-Retail#186]
**Please describe your question below**
Hi,
Thanks for your wonderful addon first! I'm new to epgp and this addon, I'm wondering how to manage multiple raid team within the same guild?

Best,
Brian

**Comment by Alumian** [comment]
Hey Brian, thanks for your question. You should be able to run multiple raid teams without any problems. Each player has their own independent EPGP standings so if they're in different teams that's totally fine. Just remember that if you use the decay EPGP function then it will affect the whole guild, not just one raid team.
I hope that helps!
