### ISSUE TITLE
Domo always award EPs even if auto EPs is turned off

### ISSUE THREAD

**Issue by jackie0100** [Alumian/CEPGP-Retail#187]
So our guild have turned auto award EPs off due to the huge lag spike it causes, as we have 2 raids going simutaniously, however, we're still earning EPs automatically whenever the raid kills domo, I've made sure to check multiple time if auto EP for domo is turned off which it is, I've also tried to turn it on and do the fight with same result and lastly I've tried to turn it off again and onoff before domo but still it doesn't work.

**Comment by Alumian** [comment]
Please attach your /CEPGP debug dump. Also in future, please submit tickets using one of the given templates.

**Comment by jackie0100** [comment]
Sorry, felt most of those question in the form were trivial and would just cause redundancy

Debug:

<details><summary>Debug Info</summary><br />
Version: 1.12.8.release-hotfix2<br />
Locale: enUS<br />
GP Formula: (1x(6.32^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x0.187<br />Base GP: 100<br />
Base GP Decay Factor: true<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: true<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 2<br />
Allow Force Sync: false, Guildmaster<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Lord Kri: True<br />
Emperor Vek'nilash: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: False<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Majordomo Executus: False<br />
High Priest Venoxis: True<br />
Gehennas: False<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Lady Blaumeux: True<br />
Highlord Mograine: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Firemaw: True<br />
Baron Geddon: False<br />
Chromaggus: True<br />
Sulfuron Harbinger: False<br />
Gri'lek: True<br />
High Priestess Arlokk: True<br />
Gahz'ranka: True<br />
Emperor Vek'lor: True<br />
Gluth: True<br />
Sapphiron: True<br />
Onyxia: False<br />
Razorgore the Untamed: True<br />
Princess Yauj: True<br />
Vem: True<br />
Shazzrah: False<br />
Ouro: True<br />
Battleguard Sartura: True<br />
Ragnaros: False<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: False<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Maexxna: True<br />
Ayamiss the Hunter: True<br />
Broodlord Lashlayer: True<br />
Viscidus: True<br />
Hakkar: True<br />
Ebonroc: True<br />
Kurinnaxx: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: False<br />
Sir Zeliek: True<br />
Vaelastrasz the Corrupt: True<br />
Patchwerk: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
Jin'do the Hexxer: True<br />
Garr: False<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Lord Kri: 10<br />
Emperor Vek'nilash: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Lady Blaumeux: 15<br />
Highlord Mograine: 15<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Firemaw: 7<br />
Baron Geddon: 5<br />
Chromaggus: 7<br />
Sulfuron Harbinger: 5<br />
Gri'lek: 2<br />
High Priestess Arlokk: 2<br />
Gahz'ranka: 2<br />
Emperor Vek'lor: 10<br />
Gluth: 12<br />
Sapphiron: 15<br />
Onyxia: 8<br />
Razorgore the Untamed: 7<br />
Princess Yauj: 10<br />
Vem: 10<br />
Shazzrah: 5<br />
Ouro: 10<br />
Battleguard Sartura: 10<br />
Ragnaros: 7<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Maexxna: 15<br />
Ayamiss the Hunter: 3<br />
Broodlord Lashlayer: 7<br />
Viscidus: 10<br />
Hakkar: 3<br />
Ebonroc: 7<br />
Kurinnaxx: 3<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 5<br />
Sir Zeliek: 15<br />
Vaelastrasz the Corrupt: 7<br />
Patchwerk: 12<br />
Bloodlord Mandokir: 2<br />
Renataki: 2<br />
Jin'do the Hexxer: 2<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guildmaster: False<br />
Officer: False<br />
Class Master: False<br />
Officer Alt: False<br />
Oldtimer: False<br />
Raider: False<br />
Trial Raider: False<br />
Member: False<br />
Alt char: False<br />
Recruit: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 1.4<br />
NECK: 0.75<br />
HEAD: 0.8<br />
WEAPON: 1.2<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.2<br />
SHIELD: 1<br />
HOLDABLE: 0.75<br />
CLOAK: 0.75<br />
FEET: 0.7<br />
SHOULDER: 0.75<br />
LEGS: 0.9<br />
EXCEPTION: 1<br />
TRINKET: 0.75<br />
WAIST: 0.6<br />
HAND: 0.7<br />
ROBE: 1<br />
CHEST: 1<br />
FINGER: 0.75<br />
WEAPONOFFHAND: 1.2<br />
RANGEDRIGHT: 0.7<br />
RELIC: 0.75<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
[Seal of the Archmagus]: 2<br />
[Mature Black Dragon Sinew]: 40<br />
[Ancient Petrified Leaf]: 40<br />
[The Eye of Divinity]: 55<br />
[Fireproof Cloak]: 3<br />
[Head of Onyxia]: 35<br />
[Flamewaker Legplates]: 5<br />
[Ring of Binding]: 2<br />
[Fireguard Shoulders]: 1<br />
[Shadowstrike]: 1<br />
[Crimson Shocker]: 2<br />
[Essence of the Pure Flame]: 2<br />
[Shard of the Flame]: 1<br />
[Eskhandar's Collar]: 3<br />
[Manastorm Leggings]: 2<br />
</details>
<details><summary>Addons List</summary>
Atlas<br />
Atlas_ClassicWoW<br />
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
Auctionator<br />
auc-cheap-searcher<br />
Bagnon<br />
Bartender4<br />
BeanCounter<br />
CEPGP<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
ClassicThreatMeter<br />
CT_BuffMod<br />
CT_Core<br />
CT_ExpenseHistory<br />
CT_Library<br />
CT_Timer<br />
Decursive<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
Dismounter<br />
Enchantrix-Barker<br />
ExRT<br />
ExtendedCharacterStats<br />
GatherLite<br />
Get Spheres - Classic<br />
InFlight_Load<br />
JumpCounter<br />
Mapster<br />
MarketWatcher<br />
MobInfo2-Classic<br />
OmniCC<br />
Peggle<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
QuestCompletist<br />
RareAware<br />
Scrap<br />
SexyMap<br />
SilverRareElites<br />
SilverDragon<br />
SilverDragon_Classic<br />
SlideBar<br />
Stubby<br />
!Swatter<br />
TitanAttributesMulti<br />
TitanProfessionsMulti<br />
TitanClassicReagentTracker<br />
TitanReputations<br />
TitanClassicAmmo<br />
TitanClassicBag<br />
TitanClassicClock<br />
TitanClassicGold<br />
TitanClassicLocation<br />
TitanClassicLootType<br />
TitanClassicPerformance<br />
TitanClassicRegen<br />
TitanClassicRepair<br />
TitanClassicVolume<br />
TitanClassicXP<br />
TitanClassic<br />
TriviaBot<br />
WeakAuras<br />
WIM<br />
ZPerl<br />
ZPerl_ArcaneBar<br />
ZPerl_PartyPet<br />
ZPerl_Party<br />
ZPerl_PlayerBuffs<br />
ZPerl_PlayerPet<br />
ZPerl_Player<br />
ZPerl_RaidAdmin<br />
ZPerl_RaidFrames<br />
ZPerl_RaidHelper<br />
ZPerl_RaidPets<br />
ZPerl_TargetTarget<br />
ZPerl_Target<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Thanks for supplying that info and no worries. Not too sure why this would be occurring, but I will say that in 1.12.9 which will be release prior to the BWL launch, I've rewritten the boss kill detection system and it's far simpler and more accurate now.
So at this stage I want to say that it's fixed in the next update, but will monitor this.

**Comment by Alumian** [comment]
Hi Jackie,

Could you please confirm if this issue has been resolved in 1.12.9?

**Comment by jackie0100** [comment]
Sadly I am no longer in that guild and I'm sadly no longer using the addon, so sadly I can't provide further information, I'm sorry

**Comment by Alumian** [comment]
Assuming that this is resolved. Will review later if the issue persists.

**Comment by Alumian** [comment]
Implementation has now been released.
