### ISSUE TITLE
[Bug] The item weight for One-Handed weapon is not synced

### ISSUE THREAD

**Issue by jackie0100** [Alumian/CEPGP-Retail#188]
first of all thanks for adding one-handed weapon weight to the addon it is very useful but some how if I have a guildie trying to sync the addon to mine it does not sync this specific field and most be changed manually.

**Comment by Nuroduas** [comment]
I am seeing quit a few settings that do not appear to be getting synced.

**Comment by Alumian** [comment]
Just to clarify, when you say it's not syncing, do you mean that doesn't change when you import from a player? Or do you mean that changing the one hand slot weight doesn't affect GP values when changed?

**Comment by jackie0100** [comment]
Sadly I am no longer in that guild and I'm sadly no longer using the addon, so sadly I can't provide further information, I'm sorry

**Comment by Alumian** [comment]
No problem. I believe that this issue has been resolved in recent versions. Thanks for submitting this report :)

**Comment by Alumian** [comment]
Implementation has now been released.
