### ISSUE TITLE
[Bug] Import standings with characters not in guild anymore stops the import halfway through

### ISSUE THREAD

**Issue by Ragaroah** [Alumian/CEPGP-Retail#189]
**The Error**
No error message, import screen halts and need to /reload to fix it

**Describe the bug**
When you import an old backup with characters that are no longer in the guild, the import fails.

**To Reproduce**
Bulk import standings with 1 character no longer in the guild.

**Debug Information**
Sorry, I have none from when this occured. Can get it if you want.

**Comment by Alumian** [comment]
Resolved in #235
