### ISSUE TITLE
[Request] Manual 'Raid' Start

### ISSUE THREAD

**Issue by Bonkeybee** [Alumian/CEPGP-Retail#19]
At the moment the addon only supports context-sensitive activation, meaning you can really only use this addon for raids. Our guild is on a RP server and we have several external events that happen as a raid-group but outside a raid.

It would useful to be able to start a 'raid' without actually entering MC in order to control the addon such as giving EP for everyone in the raid-group and utilize the stand-by list.

At the moment this can only be done manually through manual edits of the EP/GP values (not practical in a large guild).

**Comment by skombag** [comment]
This has been given support in the latest updates - can now award EP GP to raid members and standbys properly to support large groups.
