### ISSUE TITLE
[Request] Allow whispers with custom keywords to be used in conjunction with the GUI loot options

### ISSUE THREAD

**Issue by Ragaroah** [Alumian/CEPGP-Retail#192]
It would be nice if we could set keywords to be allowed being whispered to the masterlooter to have people pick a certain option, such as !mainspec, !offspec, !major, !minor, !IneedthisbecauseIwanttofeelpretty, or anything else.

This in case someone's addon isn't working/not installed, or for any pugs that might join your raids.

**Comment by Nuroduas** [comment]
I would second this.  It seems hard to get people to load add-ons.  Having a whisper response to the loot master would allow for people to send a selection for loot without the need for the add-on.  This is done for information on standings and the standby list already.

**Comment by Se7enMuting** [comment]
I'm in a hurry to need this function！！！

**Comment by Alumian** [comment]
Implementation has now been released.
