### ISSUE TITLE
[Bug] EP Not Being Auto Awarded on Non-English Clients

### ISSUE THREAD

**Issue by Alumian** [Alumian/CEPGP-Retail#195]
**Impacted Versions: 1.12.9 Beta 3 and newer (including 1.12.9 release) (Non-English locale clients ONLY)**

**Describe the bug**
When an encounter is defeated, despite having auto award enabled, EP is not awarded. This is caused by an issue with the ENCOUNTER_END event such that arg 2 of the payload returns "* whereas it should return the localised boss name.
The following screenshot was captured on a zhCN client at Majordomo Executus.
![ENCOUNTER_END](https://user-images.githubusercontent.com/24452898/74126612-7b5a2a00-4c2c-11ea-80d0-8fbc409f1f71.PNG)

A bug report has been submitted to Blizzard. Currently the only workaround is to manually award EP for each boss encounter.

**Comment by Ishkenito** [comment]
Yeah, Russian clients don't autoaward

**Comment by Alumian** [comment]
Resolved in beta 1.
