### ISSUE TITLE
New office note format

### ISSUE THREAD

**Issue by Vinneg** [Alumian/CEPGP-Retail#196]
Hi! Thanks for the addon and all it features!
I made addon, that helps roll Onyxia bag. One of it feature - is to add bonus rolls based on Onyxia kills attendance. Just like EPGP addon i want to store bonuses in guild officer notes.
So I think to store EPGP values as cep{DD,DD} and mine bonuses as obm{DD}. So, CEPGP can find its part of officer notes and rewrite only cep{DD,DD} part.
I made fork https://github.com/Vinneg/CEPGP-Retail and branch https://github.com/Vinneg/CEPGP-Retail/tree/officer-notes.
Tested all officer notes updates except Restore Standings feature (Save Standings work as planned).

Can you, please, merge my feature?

Thanks in advance!

**Comment by Vinneg** [comment]
Created pull request https://github.com/Alumian/CEPGP-Retail/pull/199

**Comment by Alumian** [comment]
Hi Vinneg, thank you for your contribution. This is not a change that I'm interested in making to the core addon. However, if this is functionality that you feel would be a positive change, I recommend that you produce it as a plugin for CEPGP.

**Comment by Vinneg** [comment]
Hi Alumian!
Sad to hear so. But how should plugin looks like? I suppose, i have to overwrite/hook 9 functions and 1 frame. And after that i have to carry all changes in original function, am I wrong?

**Comment by Alumian** [comment]
Yeah so as you've said, just overwrite the functions with your own. You should also run CEPGP_addPlugin when your plugin initialises to ensure that it is registered as a plugin.

`function CEPGP_addPlugin(plugin, iPanel, enabled, func) -- Addon name, interface panel, enabled status, function to toggle enabled status`
