### ISSUE TITLE
[Bug] Guild List Fails to Initialise on Interface Load

### ISSUE THREAD

**Issue by jackie0100** [Alumian/CEPGP-Retail#197]
**The Error**
What was the error message you received?

```
Popup message:
Date: 2020-02-12 19:19:11
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\CEPGP\Utility.lua line 1211:
   attempt to index field '?' (a nil value)
Debug:
   [C]: ?
   CEPGP\Utility.lua:1211: CEPGP_tSort()
   CEPGP\Scrollbar.lua:298: CEPGP_UpdateGuildScrollBar()
   CEPGP\Utility.lua:400: CEPGP_populateFrame()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  auccheapsearcher, v20191013-retail
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v8.1.0
  Bagnon, v8.3.4
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CEPGP, v
  ClassicCastbars, vv1.2.5
  ClassicCastbarsOptions, v
  ClassicThreatMeter, v1.10
  CTBuffMod, v8.3.0.3
  CTCore, v8.3.0.1
  CTExpenseHistory, v8.3.0.1
  CTLibrary, v8.3.0.3
  CTTimer, v8.2.0.1
  DBMCore, v1.13.33
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dismounter, v1.2.1
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4110
  ExtendedCharacterStats, v2.1.4
  GatherLite, v2.0.1
  GetSpheresClassic, v0.1
  InFlightLoad, v1.13.005
  Informant, v8.2.6374 (SwimmingSeadragon)
  JumpCounter, v1.2
  Mapster, v1.8.5
  MarketWatcher, v2.3.1c
  MobInfo2Classic, v11302.04
  OmniCC, v8.3.5
  Peggle, v2.2.6
  Prat30, v3.7.50
  Prat30Libraries, v
  QuestCompletist, v109.25
  Questie, v5.7.0
  RareAware, v1.0
  Scrap, v8.3.0
  SexyMap, vv5-classic
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SilverRareElites, v1.0.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanAttributesMulti, v1.1
  TitanClassic, v1.2.0.11303
  TitanClassicAmmo, v1.2.0.11303
  TitanClassicBag, v1.2.0.11303
  TitanClassicClock, v1.2.0.11303
  TitanClassicGold, v1.2.0.11303
  TitanClassicLocation, v1.2.0.11303
  TitanClassicLootType, v1.2.0.11303
  TitanClassicPerformance, v1.2.0.11303
  TitanClassicReagentTracker, v1.13.2 (1.0.8)
  TitanClassicRegen, v1.2.0.11303
  TitanClassicRepair, v1.2.0.11303
  TitanClassicVolume, v1.2.0.11303
  TitanClassicXP, v1.2.0.11303
  TitanProfessionsMulti, v1.4
  TitanReputations, vv1.1-classic
  TriviaBot, v2.9.0
  WeakAuras, v2.16.5
  WIM, v3.8.5
  ZPerl, v5.9.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=ad2)
```

**Describe the bug**
Happens every time I start the game or reload UI, the guild list comes up after a while (may be due to our guild size?)

**To Reproduce**
Open cepgp show, click the guild button (may only happen in huge guilds)

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.

<details><summary>Debug Info</summary><br />
Version: 1.12.9 release<br />
Locale: enUS<br />
GP Formula: (1x(6.32^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x0.187<br />Base GP: 100<br />
Base GP Decay Factor: true<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: true<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 2<br />
Allow Force Sync: false, Guildmaster<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: False<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Twin Emperors: True<br />
Majordomo Executus: False<br />
High Priest Venoxis: True<br />
Gehennas: False<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Heigan the Unclean: True<br />
Sapphiron: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Gluth: True<br />
Baron Geddon: False<br />
Sulfuron Harbinger: False<br />
Gri'lek: True<br />
Vaelastrasz the Corrupt: True<br />
Jin'do the Hexxer: True<br />
Renataki: True<br />
Bloodlord Mandokir: True<br />
Gahz'ranka: True<br />
Onyxia: False<br />
Shazzrah: False<br />
Emeriss: True<br />
Battleguard Sartura: True<br />
Ouro: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: False<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Ragnaros: False<br />
Kurinnaxx: True<br />
Viscidus: True<br />
Hakkar: True<br />
Maexxna: True<br />
The Four Horsemen: True<br />
Broodlord Lashlayer: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: False<br />
Patchwerk: True<br />
High Priestess Arlokk: True<br />
Firemaw: True<br />
Chromaggus: True<br />
Garr: False<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Silithid Royalty: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Twin Emperors: 10<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 7<br />
Heigan the Unclean: 12<br />
Sapphiron: 15<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Gluth: 12<br />
Baron Geddon: 5<br />
Sulfuron Harbinger: 5<br />
Gri'lek: 2<br />
Vaelastrasz the Corrupt: 7<br />
Jin'do the Hexxer: 2<br />
Renataki: 2<br />
Bloodlord Mandokir: 2<br />
Gahz'ranka: 2<br />
Onyxia: 8<br />
Shazzrah: 5<br />
Emeriss: 7<br />
Battleguard Sartura: 10<br />
Ouro: 10<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Ragnaros: 7<br />
Kurinnaxx: 3<br />
Viscidus: 10<br />
Hakkar: 3<br />
Maexxna: 15<br />
The Four Horsemen: 15<br />
Broodlord Lashlayer: 7<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 7<br />
Magmadar: 5<br />
Patchwerk: 12<br />
High Priestess Arlokk: 2<br />
Firemaw: 7<br />
Chromaggus: 7<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guildmaster: False<br />
Officer: False<br />
Raidleader: False<br />
Officer Alt: False<br />
Oldtimer: False<br />
Raider: False<br />
Trial Raider: False<br />
Member: False<br />
Alt char: False<br />
Recruit: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 1.4<br />
NECK: 0.75<br />
HEAD: 0.8<br />
WEAPON: 1.2<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.2<br />
SHIELD: 1<br />
HOLDABLE: 0.75<br />
CLOAK: 0.75<br />
FEET: 0.7<br />
THROWN: 0.5<br />
RELIC: 0.75<br />
RANGEDRIGHT: 0.7<br />
TRINKET: 0.75<br />
WEAPONOFFHAND: 1.2<br />
FINGER: 0.75<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.7<br />
WAIST: 0.6<br />
EXCEPTION: 1<br />
LEGS: 0.9<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
[Ashkandi, Greatsword of the Brotherhood]: 40<br />
[Essence of the Pure Flame]: 2<br />
[Mature Black Dragon Sinew]: 40<br />
[Ancient Petrified Leaf]: 40<br />
[Fireproof Cloak]: 3<br />
[Head of Onyxia]: 35<br />
[Bracers of Arcane Accuracy]: 32<br />
[Chromatically Tempered Sword]: 60<br />
[Spineshatter]: 24<br />
[Mantle of the Blackwing Cabal]: 38<br />
[Dragon's Touch]: 24<br />
[Helm of Endless Rage]: 48<br />
[Archimtiros' Ring of Reckoning]: 24<br />
[Eskhandar's Collar]: 3<br />
[Flamewaker Legplates]: 5<br />
[Rune of Metamorphosis]: 6<br />
[Ring of Binding]: 2<br />
[Dragonbreath Hand Cannon]: 20<br />
[Ringo's Blizzard Boots]: 34<br />
[Drake Fang Talisman]: 50<br />
[Manastorm Leggings]: 2<br />
[Ring of Blackrock]: 34<br />
[Arcane Infused Gem]: 6<br />
[Drake Talon Cleaver]: 64<br />
[Chromatic Boots]: 42<br />
[Crimson Shocker]: 2<br />
[Black Ash Robe]: 8<br />
[Circle of Applied Force]: 24<br />
[Taut Dragonhide Gloves]: 18<br />
[Ashjre'thul, Crossbow of Smiting]: 70<br />
[Rejuvenating Gem]: 50<br />
[Draconic Avenger]: 8<br />
[Boots of Pure Thought]: 36<br />
[Crul'shorukh, Edge of Chaos]: 60<br />
[Heartstriker]: 20<br />
[Fireguard Shoulders]: 1<br />
[Seal of the Archmagus]: 2<br />
[Head of Nefarian]: 55<br />
[Drake Talon Pauldrons]: 46<br />
[Shadowstrike]: 1<br />
[The Eye of Divinity]: 55<br />
[Doom's Edge]: 44<br />
[Shard of the Flame]: 1<br />
[Venomous Totem]: 8<br />
[Aegis of Preservation]: 6<br />
</details>
<details><summary>Addons List</summary>
Atlas<br />
Atlas_ClassicWoW<br />
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
Auctionator<br />
auc-cheap-searcher<br />
Bagnon<br />
Bartender4<br />
BeanCounter<br />
CEPGP<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
ClassicThreatMeter<br />
CT_BuffMod<br />
CT_Core<br />
CT_ExpenseHistory<br />
CT_Library<br />
CT_Timer<br />
Decursive<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
Dismounter<br />
Enchantrix-Barker<br />
ExRT<br />
ExtendedCharacterStats<br />
GatherLite<br />
Get Spheres - Classic<br />
InFlight_Load<br />
JumpCounter<br />
Mapster<br />
MarketWatcher<br />
MobInfo2-Classic<br />
OmniCC<br />
Peggle<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
QuestCompletist<br />
RareAware<br />
Scrap<br />
SexyMap<br />
SilverRareElites<br />
SilverDragon<br />
SilverDragon_Classic<br />
SlideBar<br />
Stubby<br />
!Swatter<br />
TitanAttributesMulti<br />
TitanProfessionsMulti<br />
TitanClassicReagentTracker<br />
TitanReputations<br />
TitanClassicAmmo<br />
TitanClassicBag<br />
TitanClassicClock<br />
TitanClassicGold<br />
TitanClassicLocation<br />
TitanClassicLootType<br />
TitanClassicPerformance<br />
TitanClassicRegen<br />
TitanClassicRepair<br />
TitanClassicVolume<br />
TitanClassicXP<br />
TitanClassic<br />
TriviaBot<br />
WeakAuras<br />
WIM<br />
ZPerl<br />
ZPerl_ArcaneBar<br />
ZPerl_PartyPet<br />
ZPerl_Party<br />
ZPerl_PlayerBuffs<br />
ZPerl_PlayerPet<br />
ZPerl_Player<br />
ZPerl_RaidAdmin<br />
ZPerl_RaidFrames<br />
ZPerl_RaidHelper<br />
ZPerl_RaidPets<br />
ZPerl_TargetTarget<br />
ZPerl_Target<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Hey Jackie, thanks for the bug report. Are you on Discord? Could you drop me a message so I can work through this with you?

**Comment by Alumian** [comment]
Having issues reproducing this issue in 1.12.10. I'm going to mark this as fixed for now and review this later if it persists.

**Comment by Alumian** [comment]
Implementation has now been released.
