### ISSUE TITLE
[Question] How does this addon handle Decay?

### ISSUE THREAD

**Issue by PibbzTV** [Alumian/CEPGP-Retail#2]
**Please describe your question below**
I don't see any options to handle decay with this addon, like configuring decay % and so on.
Is it able to? If so, where?

**Comment by Alumian** [comment]
Hi Pibbz,
If you go /cep show and click on the Guild button then you should be able to see a Guild Decay button at the bottom of the frame. The addon does not have an automatic decay, you need to do it manually. You will only be able to see the button if you are able to modify officer notes.

**Comment by Alumian** [comment]
I hope this has answered your question. If you have any other questions, a technical issue or feature request, please submit a new ticket.

Thanks,
Alumian
