### ISSUE TITLE
[Question] how to check the reward list for adding EP to a raid team

### ISSUE THREAD

**Issue by luozm** [Alumian/CEPGP-Retail#204]
**Please describe your question below**
Hi,

I'm working on backup the EPGP record to google sheet to verify everyone's EPGP. However, when checking the traffic records in "CEPGP.lua", idk how to see the entire rewarded list for an adding EP to raid record. How can I do that? Is that possible in the current addon? If not, do you have any idea how to implement this? I can write the actual code for it.

BTW, do you have any idea how to backup EPGP traffic record to an external file? Currently, I'm thinking of writing another program to monitor diff of "CEPGP.lua" file after every raid activity.

Thanks a lot! Look forward to you thoughts!

Best,
Brian

**Comment by Alumian** [comment]
Hi Brian,

Thanks for the question. Unfortunately what you're looking for isn't available just yet. There is currently a feature request open for this, so keep an eye on ticket #205.
