### ISSUE TITLE
Option to toggle EPGP control using public notes. [request]

### ISSUE THREAD

**Issue by afonsohfontes** [Alumian/CEPGP-Retail#207]
Hello, my guild is running two different EPGP systems, one for BWL and another for MC & Ony. It would be great to have an option (or a second addon?) to toggle controlling EPGP from officer note or public note.

**Comment by afonsohfontes** [comment]
Up

**Comment by Alumian** [comment]
Hi Afonso,

Unfortunately, this option carries too much risk where configuration conflicts between players are possible.
For example: If officers are able to modify EPGP and one officer has this option turned on whereas the others have it turned off. This would essentially cause the addon to overwrite both the public and officer notes and misread values. Unfortunately, at this stage I am not looking to implement this feature.
