### ISSUE TITLE
[BUG] Override and Force Sync

### ISSUE THREAD

**Issue by Lolvalid** [Alumian/CEPGP-Retail#208]
Hello,

The Error:
When attempting to force sync it seems the add-on will not update a removed override to also be removed.
Example(s) : 
[This works]
Brutality Blade has a manual override for 35GP
Brutality Blade has been updated manual override to 50 GP.  
After force sync, guild members will receive the new 50GP price over ride and will reflect in the add-on.

[This doesn't work]

Brutality Blade has a manual override for 35GP.
Brutality Blade has been updated, and the manual override is removed or deleted, returning to base cost for the Guild Master.
After force sync, guild members will still see the manual override for 35GP

Game Version: 1.13.3
Allow forced sync is checked, and is working. Items that had an override but the override value was changed were updated, but the ones that had been removed were not removed.

**Comment by Alumian** [comment]
Hi lolvalid,

Thanks for your report. This has been fixed in the next update.

**Comment by Alumian** [comment]
Implementation has now been released.
