### ISSUE TITLE
Error message when opening "guild" tab[Bug]

### ISSUE THREAD

**Issue by infernojack** [Alumian/CEPGP-Retail#211]
Often when I open cepgp and go to "guild" I get an error message that doesn't affect anything with the addon.  

<details><summary>Debug Info</summary><br />
Version: 1.12.9 release<br />
Locale: enUS<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 100<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 100<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: true<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 100<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 3<br />
Allow Force Sync: true, GM<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: False<br />
Gothik the Harvester: True<br />
Buru the Gorger: False<br />
Wushoolay: False<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: False<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: False<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: False<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: False<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: False<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: False<br />
The Edge of Madness: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: False<br />
Ebonroc: True<br />
The Twin Emperors: True<br />
Heigan the Unclean: True<br />
Sapphiron: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Baron Geddon: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: False<br />
Vaelastrasz the Corrupt: True<br />
Chromaggus: True<br />
Gluth: True<br />
Firemaw: True<br />
Gahz'ranka: False<br />
Renataki: False<br />
Razorgore the Untamed: True<br />
Onyxia: True<br />
Lord Kazzak: True<br />
Shazzrah: True<br />
Battleguard Sartura: True<br />
Ouro: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: False<br />
Ragnaros: True<br />
Maexxna: True<br />
Viscidus: True<br />
Hakkar: False<br />
Broodlord Lashlayer: True<br />
The Four Horsemen: True<br />
Kurinnaxx: False<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Patchwerk: True<br />
High Priestess Arlokk: False<br />
Bloodlord Mandokir: False<br />
Jin'do the Hexxer: False<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Silithid Royalty: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Twin Emperors: 10<br />
Majordomo Executus: 6<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 10<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
The Edge of Madness: 2<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
The Silithid Royalty: 10<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 10<br />
The Twin Emperors: 10<br />
Heigan the Unclean: 12<br />
Sapphiron: 15<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Baron Geddon: 5<br />
Sulfuron Harbinger: 5<br />
Gri'lek: 2<br />
Vaelastrasz the Corrupt: 10<br />
Chromaggus: 10<br />
Gluth: 12<br />
Firemaw: 10<br />
Gahz'ranka: 2<br />
Renataki: 2<br />
Razorgore the Untamed: 10<br />
Onyxia: 6<br />
Lord Kazzak: 7<br />
Shazzrah: 5<br />
Battleguard Sartura: 10<br />
Ouro: 10<br />
Kel'Thuzad: 15<br />
Nefarian: 15<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Ragnaros: 7<br />
Maexxna: 15<br />
Viscidus: 10<br />
Hakkar: 3<br />
Broodlord Lashlayer: 10<br />
The Four Horsemen: 15<br />
Kurinnaxx: 3<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 5<br />
Patchwerk: 12<br />
High Priestess Arlokk: 2<br />
Bloodlord Mandokir: 2<br />
Jin'do the Hexxer: 2<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
GM: False<br />
Officer: False<br />
Officer alt: False<br />
Raider: False<br />
Recruit: False<br />
Member: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
SHOULDER: 0.75<br />
LEGS: 1<br />
EXCEPTION: 1<br />
TRINKET: 0.75<br />
WAIST: 0.75<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 0.5<br />
RANGEDRIGHT: 0.5<br />
RELIC: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
Dark Heart Pants: 100<br />
[Boots of Prophecy]: 36<br />
[Felheart Gloves]: 36<br />
Mendicant's Slippers: 120<br />
Netherwind Mantle: 120<br />
Head of Broodlord Lashlayer: 96<br />
Netherwind Boots: 96<br />
Breastplate of Ten Storms: 144<br />
[Belt of Might]: 24<br />
Nightmare Blade: 108<br />
Dragonstalker Belt: 96<br />
[Rune of Metamorphosis]: 0<br />
[Dragonstalker's Greaves]: 96<br />
Stormrage Boots: 96<br />
[Nemesis Leggings]: 96<br />
Fel Infused Leggings: 162<br />
Dragonstalker Guantlets: 96<br />
Judgement Sabatons: 96<br />
[Core Hound Tooth]: 96<br />
[Brutality Blade]: 84<br />
[Sash of Whispered Secrets]: 48<br />
[Band of Accuria]: 144<br />
[Rejuvenating Gem]: 348<br />
Blazefury Medallion: 48<br />
Earthfury Bracers: 24<br />
[Nightslayer Gloves]: 36<br />
[Ancient Petrified Leaf]: 50<br />
[Fire Runed Grimoire]: 36<br />
[Nightslayer Chestpiece]: 48<br />
Ancient Corroded Leggings: 84<br />
Malignant Footguards: 36<br />
Crul'shoruk, Edge of Chaos: 300<br />
[Cenarion Bracers]: 24<br />
[Archimtiros' Ring of Reckoning]: 60<br />
[Red Dragonscale Protector]: 96<br />
Bloodfang Boots: 96<br />
[Breastplate of Wrath]: 112<br />
[Robes of Prophecy]: 24<br />
Nemesis Boots: 96<br />
Earthfury Helmet: 36<br />
Infernal Headcage: 72<br />
Emerald Dragonfang: 108<br />
[Drillborer Disk]: 72<br />
[Shimmering Geta]: 72<br />
[Gloves of Rapid Evolution]: 36<br />
Fang of the Mystics: 108<br />
[Deep Earth Spaulders]: 60<br />
Dragonstalker's Spaulders: 120<br />
Earthfury Vestments: 48<br />
[Netherwind Pants]: 96<br />
[Venomous Totem]: 0<br />
[Draconic Avenger]: 48<br />
Earthfury Gauntlets: 36<br />
[Vambraces of Prophecy]: 48<br />
Dragonstalker Helm: 120<br />
Dragonstalker Bracers: 84<br />
[Head of Nefarian]: 168<br />
[Cenarion Gloves]: 36<br />
[Heartstriker]: 108<br />
[Felheart Pants]: 36<br />
[Essence Gatherer]: 36<br />
[Pauldrons of Might]: 36<br />
[Sapphiron Drape]: 60<br />
Bloodfang Gloves: 96<br />
[Drake Fang Talisman]: 348<br />
[Helm of Wrath]: 120<br />
[Wristguards of Stability]: 24<br />
[Lok'amir il Romathis]: 276<br />
[Vis'kag the Bloodletter]: 96<br />
Dragonheart Necklace: 60<br />
[Nightslayer Boots]: 36<br />
Spauldrons of Transcendence: 120<br />
[Black Ash Robe]: 36<br />
[Felheart Bracers]: 24<br />
Lawbringer Legplates: 36<br />
[Bindings of the Windseeker]: 250<br />
[Heavy Dark Iron Ring]: 90<br />
Earthfury Belt: 24<br />
[Cloak of the Brood Lord]: 120<br />
[Sabatons of Might]: 36<br />
Mish'undare: 288<br />
Dragonbone Wristguards: 48<br />
[Shard of the Flame]: 36<br />
Netherwind Regalia: 84<br />
Epaulets of Ten Storms: 120<br />
[Mind Quickening Gem]: 144<br />
[Sorcerous Dagger]: 48<br />
Epualets of Ten Storms: 120<br />
Netherwind Robes: 144<br />
Maladath: 276<br />
Breastplate of Wrath  : 144<br />
Unmelting Ice Girdle: 72<br />
Netherwind Gloves: 96<br />
[Legplates of Might]: 36<br />
[Draconic Maul]: 36<br />
[Lawbringer Gauntlets]: 36<br />
Belt of Ten Storms: 96<br />
[Eskhandar's Collar]: 48<br />
[Aurastone Hammer]: 66<br />
Netherwind Belt: 96<br />
Earthfury Epaulets: 36<br />
[Arcanist Belt]: 24<br />
Dragonstalker Legguards: 96<br />
Spauldrons of Wrath: 120<br />
[Leggings of Transcendence]: 96<br />
Green Dragonskin Cloak: 72<br />
Robes of Transcendence: 112<br />
[Giantstalker's Belt]: 24<br />
Bloodfang Chestpiece: 144<br />
Unnatural Leather Spaulders: 72<br />
Crystal Adorned Crown: 120<br />
[Dragonfang Blade]: 132<br />
[Giantstalker's Gloves]: 36<br />
[Bracelets of Wrath]: 84<br />
[Spinal Reaper]: 72<br />
Hibernating Crystal: 156<br />
[Gauntlets of Might]: 36<br />
[Emberweave Leggings]: 36<br />
[Shadowstrike]: 24<br />
[Cloak of Draconic Might]: 72<br />
[Cloak of the Shrouded Mists]: 60<br />
Earthfury Legguards: 36<br />
[Legplates of Ten Storms]: 96<br />
[Giantstalker's Bracers]: 24<br />
[Head of Onyxia]: 112<br />
[Cenarion Vestments]: 48<br />
[Chromatically Tempered Sword]: 300<br />
Empyrean Demolisher: 60<br />
Breasplate of Ten Storms: 112<br />
Black Bark Wristbands: 60<br />
Gauntlets of the Shining Light: 20<br />
[Helm of Endless Rage]: 132<br />
[Nightslayer Pants]: 36<br />
[Shadow Wing Focus Staff]: 156<br />
[Boots of Pure Thought]: 144<br />
[Styleen's Impeding Scarab]: 240<br />
Guantlets of Ten Storms: 96<br />
[Bloodfang Belt]: 96<br />
[Staff of Dominance]: 84<br />
[Claw of the Black Drake]: 156<br />
[Legguards of the Fallen Crusader]: 72<br />
[Lawbringer Bracers]: 24<br />
[Helm of the Lifegiver]: 24<br />
[Helmet of Ten Storms]: 120<br />
[Girdle of Prophecy]: 24<br />
[Salamander Scale Pants]: 131<br />
[Onslaught Girdle]: 112<br />
[Belt of Transcendence]: 96<br />
[Giantstalker's Leggings]: 36<br />
[Boots of Transcendence]: 96<br />
[Sabatons of Wrath]: 96<br />
[Chromatic Boots]: 252<br />
[Wild Growth Spaulders]: 131<br />
[Herald of Woe]: 60<br />
Typhoon: 36<br />
Eskhandar's Left Claw: 60<br />
[Nemesis Belt]: 96<br />
Bloodfang Spaulders: 120<br />
[Arcanist Gloves]: 36<br />
Ring of the Unliving: 72<br />
[Sabatons of the Flamewalker]: 36<br />
[Helm of Might]: 36<br />
[Gauntlets of Wrath]: 96<br />
[Cenarion Spaulders]: 36<br />
[Cauterizing Band]: 131<br />
[Arcanist Mantle]: 36<br />
[Nemesis Bracers]: 84<br />
[Elementium Reinforced Bulwark]: 216<br />
[Arcanist Leggings]: 36<br />
[Doom's Edge]: 96<br />
[Halo of Transcendence]: 120<br />
Mature Blue Dragon Sinew: 0<br />
Polished Ironwood Crossbow: 84<br />
[Ashkandi, Greatsword of the Brotherhood]: 240<br />
[Angelista's Grasp]: 120<br />
[Mature Black Dragon Sinew]: 0<br />
[Choker of Enlightenment]: 24<br />
[Malfurion's Blessed Bulwark]: 240<br />
[Arcanist Crown]: 36<br />
[Azuresong Mageblade]: 96<br />
[Gutgore Ripper]: 44<br />
[The Eye of Shadow]: 0<br />
[Fireguard Shoulders]: 72<br />
[Circlet of Prophecy]: 36<br />
[Girdle of the Fallen Crusader]: 60<br />
[Gloves of Prophecy]: 36<br />
[Empowered Leggings]: 288<br />
[Tome of Tranquilizing Shot]: 0<br />
[Staff of the Shadow Flame]: 300<br />
Acid Inscribed Pauldrons: 72<br />
[Pendant of the Fallen Dragon]: 84<br />
[Black Brood Pauldrons]: 48<br />
[Netherwind Crown]: 120<br />
[Legplates of Wrath]: 96<br />
Nemesis Gloves: 96<br />
[Band of Dark Dominion]: 120<br />
[Bloodfang Hood]: 120<br />
Circlet of Restless Dreams: 96<br />
[Ring of Binding]: 72<br />
[Nemesis Spaulders]: 120<br />
[Arcanist Robes]: 48<br />
[Giantstalker's Breastplate]: 48<br />
[Judgement Legplates]: 96<br />
[Flameguard Gauntlets]: 42<br />
[Manastorm Leggings]: 24<br />
[Shard of the Scale]: 108<br />
[Arcanist Bindings]: 24<br />
Amberseal Keeper: 72<br />
[Blastershot Launcher]: 68<br />
[Therazane's Link]: 108<br />
[Ebony Flame Gloves]: 120<br />
[Elementium Threaded Cloak]: 96<br />
Judgement Spaulders: 120<br />
[Bindings of Transcendence]: 84<br />
[Dragonstalker's Helm]: 120<br />
[Prestor's Talisman of Connivery]: 252<br />
Waistband of Wrath: 96<br />
[Nightslayer Shoulder Pads]: 36<br />
Snowblind Shoes: 112<br />
[Natural Alignment Crystal]: 0<br />
[Taut Dragonhide Shoulderpads]: 132<br />
[Lawbringer Helm]: 36<br />
[Band of Forced Concentration]: 276<br />
Bracers of Wrath: 84<br />
[Cenarion Leggings]: 36<br />
[Stormrage Cover]: 120<br />
[The Untamed Blade]: 108<br />
[Mantle of Prophecy]: 36<br />
Handguards of Transcendence: 96<br />
Boots of the Endless Moor: 72<br />
Greaves of Ten Storms: 96<br />
[Shroud of Pure Thought]: 192<br />
[Lawbringer Boots]: 36<br />
Hammer of Bestial Fury: 96<br />
[Ashjre'thul, Crossbow of Smiting]: 360<br />
[Nightslayer Bracelets]: 24<br />
[Boots of the Shadow Flame]: 268<br />
[Pants of Prophecy]: 36<br />
[Essence of the Pure Flame]: 36<br />
[Earthshaker]: 36<br />
[Nemesis Robes]: 144<br />
Deviate Growth Cap: 162<br />
[Interlaced Shadow Jerkin]: 12<br />
[Spineshatter]: 60<br />
[Breastplate of Might]: 48<br />
[Bracers of Arcane Accuracy]: 240<br />
Eskhandar's Right Claw: 48<br />
[Aged Core Leather Gloves]: 36<br />
[Robe of Volatile Power]: 126<br />
[Cenarion Belt]: 24<br />
[Netherwind Bindings]: 120<br />
[Gloves of the Hypnotic Flame]: 48<br />
[Crown of Destruction]: 120<br />
[Claw of Chromaggus]: 216<br />
[Ancient Cornerstone Grimoire]: 36<br />
[Striker's Mark]: 120<br />
Dragonstalker's Breasplate: 112<br />
[Dragonstalker's Bracers]: 84<br />
[Core Forged Greaves]: 36<br />
[Cenarion Boots]: 36<br />
Gauntlets of Ten Storms: 96<br />
[Stormrage Pauldrons]: 120<br />
Dragonstalker Greaves: 96<br />
[Earthfury Boots]: 36<br />
[Dragonstalker's Gauntlets]: 96<br />
[Arcanist Boots]: 36<br />
[Felheart Horns]: 36<br />
Doomhide Gauntlets: 60<br />
Blacklight Bracer: 36<br />
Acid Inscribed Greaves: 72<br />
[Bloodfang Pants]: 96<br />
[Judgement Crown]: 120<br />
[Taut Dragonhide Belt]: 72<br />
[Nemesis Skullcap]: 120<br />
Nightmare Engulfed Object: 72<br />
[Dragonbreath Hand Cannon]: 144<br />
Strangely Glyphed Legplates: 36<br />
[Felheart Belt]: 24<br />
[Eye of Sulfuras]: 250<br />
Cold Snap: 92<br />
[The Eye of Divinity]: 50<br />
[Drake Talon Pauldrons]: 156<br />
[Nightslayer Belt]: 24<br />
[Mana Igniting Cord]: 84<br />
Dragonstalker Breastplate: 144<br />
Dragonstalker's Belt: 96<br />
[Magma Tempered Boots]: 24<br />
Boots of Fright: 72<br />
[Scrolls of Blinding Light]: 48<br />
[Felheart Slippers]: 36<br />
[Bracers of Might]: 24<br />
[Giantstalker's Helmet]: 36<br />
[Bracers of Ten Storms]: 84<br />
Trance Stone: 60<br />
[Giantstalker's Boots]: 36<br />
Judgement Breastplate: 144<br />
[Dragon's Blood Cape]: 48<br />
[Firemaw's Clutch]: 132<br />
Judgement Guantlets: 96<br />
Leggings of Arcane Supremacy: 72<br />
Gloves of Delusional Power: 120<br />
[Dragonstalker's Legguards]: 96<br />
Choker of the Firelord: 126<br />
[Seal of the Archmagus]: 24<br />
Ring of Entropy: 36<br />
Flayed Doomguard Belt: 48<br />
[Pauldrons of Wrath]: 120<br />
Mindtear Band: 60<br />
[Bloodfang Bracers]: 84<br />
[Judgement Bindings]: 84<br />
Dragonspur Wraps: 48<br />
[Pure Elementium Band]: 276<br />
[Mantle of the Blackwing Cabal]: 216<br />
Staff of Rampant Growth: 120<br />
Leggings of the Demented Mind: 96<br />
[Stormrage Bracers]: 84<br />
[Lawbringer Spaulders]: 36<br />
Drape of Benediction: 36<br />
[Ring of Spell Power]: 131<br />
Jade Inlaid Vestments: 108<br />
[Finkle's Lava Dredger]: 36<br />
[Nightslayer Cover]: 36<br />
[Flamewaker Legplates]: 72<br />
[The Black Book]: 0<br />
Dragonstalker Spaulders: 120<br />
[Stormrage Handguards]: 96<br />
[Stormrage Belt]: 96<br />
Eskhandar's Pelt: 36<br />
Belt of the Dark Bog: 72<br />
[Lawbringer Chestguard]: 48<br />
[Ringo's Blizzard Boots]: 144<br />
Puissant Cape: 156<br />
[Obsidian Edged Blade]: 42<br />
[Stormrage Legguards]: 96<br />
[Deathbringer]: 96<br />
Pauldrons of Transcendence: 120<br />
Felheart Robes: 48<br />
[Fireproof Cloak]: 24<br />
[Arcane Infused Gem]: 0<br />
[Drake Talon Cleaver]: 96<br />
[Cenarion Helm]: 36<br />
[Felheart Shoulder Pads]: 36<br />
[Circle of Applied Force]: 120<br />
[Quick Strike Ring]: 108<br />
[Medallion of Steadfast Might]: 108<br />
Judgement Gauntlets: 96<br />
Robes of Transendence: 144<br />
[Ring of Blackrock]: 156<br />
[Taut Dragonhide Gloves]: 60<br />
[Lifegiving Gem]: 156<br />
[Talisman of Ephemeral Power]: 108<br />
[Neltharion's Tear]: 348<br />
[Wristguards of True Flight]: 84<br />
[Band of Sulfuras]: 72<br />
[Malistar's Defender]: 48<br />
[Cloak of Firemaw]: 84<br />
[Giantstalker's Epaulets]: 36<br />
[Judgement Belt]: 96<br />
[Bonereaver's Edge]: 84<br />
[Perdition's Blade]: 120<br />
[Dragon's Touch]: 96<br />
[Stormrage Chestguard]: 144<br />
Lawbringer Belt: 24<br />
[Crimson Shocker]: 72<br />
[Aegis of Preservation]: 0<br />
</details>
<details><summary>Addons List</summary>
Atlas<br />
Atlas_ClassicWoW<br />
AtlasLootClassic<br />
Auctionator<br />
BeanCounter<br />
CEPGP<br />
Enchantrix-Barker<br />
ExtendedCharacterStats<br />
FiveSecondRule<br />
FloTotemBar<br />
Grid2<br />
Grid2RaidDebuffs<br />
Grid2LDB<br />
ItemRack<br />
KillTrack<br />
Leatrix_Plus<br />
LetMeCast<br />
LinkWrangler<br />
MageButtons<br />
NugComboBar<br />
NugEnergy<br />
Perl_ArcaneBar<br />
Perl_CombatDisplay<br />
Perl_Config<br />
Perl_Focus<br />
Perl_Party<br />
Perl_Party_Pet<br />
Perl_Party_Target<br />
Perl_Player<br />
Perl_Player_Pet<br />
Perl_Target<br />
Perl_Target_Target<br />
PortalMage<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
Recount<br />
Scrap<br />
ShowMeMyHeal<br />
SlideBar<br />
Stubby<br />
!Swatter<br />
TitanClassicAmmo<br />
TitanClassicBag<br />
TitanClassicClock<br />
TitanClassicGold<br />
TitanClassicLocation<br />
TitanClassicLootType<br />
TitanClassicPerformance<br />
TitanClassicRegen<br />
TitanClassicRepair<br />
TitanClassicVolume<br />
TitanClassicXP<br />
TitanClassic<br />
VendorPrice<br />
WeaponSwingTimer<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Implementation has now been released.
