### ISSUE TITLE
Multiple lines for people in "Raid" tab[Bug]

### ISSUE THREAD

**Issue by infernojack** [Alumian/CEPGP-Retail#212]
**The Error**
What was the error message you received?

No error message

**Describe the bug**

People showing multiple times on "raid" tab.  I have 4 at the most, someone in guild showed 15 of the same person.

**To Reproduce**
How can this bug be reproduced?

Open raid tab.  /reload fixed.

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.

![image](https://user-images.githubusercontent.com/58101750/75600738-05492600-5a68-11ea-9465-5ab2a29b359b.png)

**Comment by Alumian** [comment]
Implementation has now been released.
