### ISSUE TITLE
[Bug] Classic - Manual GP editing shows differently for guild members vs editor (officer)

### ISSUE THREAD

**Issue by Athikalaka** [Alumian/CEPGP-Retail#213]
**The Error**
Manually edited GP values shown in the EPGP Traffic shows up differently to the guild members. Officer who made the manual GP change, has the correct Before/After GP values.

**Describe the bug**
Officer created a GP reversal (subtraction of value 704)
GP Before Value: 1810 - GP After Value: 1106 - His EPGP Traffic entry looks correct
Guild members check EPGP traffic and read comment of GP 704 subtraction but see:
GP Before Value: 402 - GP After Value: 1810 - Our entries show 1810-704-704=402

If we check the normal Raid/Guild table, the GP is correct with 1106

**To Reproduce**
Officer to create a GP reversal (subtract GP) and guild to verify in the traffic entry

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.9 release<br />
Locale: enUS<br />
GP Formula: (4.83x(5.5^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 500<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 100<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: False<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: false<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 4<br />
Allow Force Sync: true, Guild Master<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: False<br />
Gothik the Harvester: False<br />
Buru the Gorger: False<br />
Wushoolay: False<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: False<br />
Golemagg the Incinerator: False<br />
Grand Widow Faerlina: False<br />
High Priestess Mar'li: False<br />
Twin Emperors: True<br />
Majordomo Executus: False<br />
High Priest Venoxis: False<br />
Gehennas: False<br />
Taerar: False<br />
Ysondre: False<br />
Thane Korth'azz: False<br />
High Priest Thekal: False<br />
Noth the Plaguebringer: False<br />
Lethon: False<br />
Moam: False<br />
The Prophet Skeram: False<br />
Flamegor: False<br />
C'Thun: False<br />
General Rajaxx: False<br />
Princess Huhuran: False<br />
Thaddius: False<br />
Loatheb: False<br />
Ayamiss the Hunter: False<br />
Ebonroc: False<br />
Heigan the Unclean: False<br />
Gluth: False<br />
Azuregos: False<br />
Doom Lord Kazzak: False<br />
Sulfuron Harbinger: False<br />
Baron Geddon: False<br />
High Priestess Arlokk: False<br />
Gri'lek: False<br />
Renataki: False<br />
Jin'do the Hexxer: False<br />
Firemaw: False<br />
Vaelastrasz the Corrupt: False<br />
Gahz'ranka: False<br />
Sapphiron: False<br />
Shazzrah: False<br />
Emeriss: False<br />
Battleguard Sartura: False<br />
Onyxia: False<br />
Kel'Thuzad: False<br />
Nefarian: False<br />
Fankriss the Unyielding: False<br />
Lucifron: False<br />
Anub'Rekhan: False<br />
Hazza'rah: False<br />
Kurinnaxx: False<br />
Ragnaros: False<br />
Hakkar: False<br />
Broodlord Lashlayer: False<br />
Maexxna: False<br />
The Four Horsemen: True<br />
Ouro: False<br />
Grobbulus: False<br />
Instructor Razuvious: False<br />
Razorgore the Untamed: False<br />
Magmadar: False<br />
Patchwerk: False<br />
Viscidus: False<br />
Bloodlord Mandokir: False<br />
Chromaggus: False<br />
Garr: False<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Silithid Royalty: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Twin Emperors: 10<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 7<br />
Heigan the Unclean: 12<br />
Gluth: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Sulfuron Harbinger: 5<br />
Baron Geddon: 5<br />
High Priestess Arlokk: 2<br />
Gri'lek: 2<br />
Renataki: 2<br />
Jin'do the Hexxer: 2<br />
Firemaw: 7<br />
Vaelastrasz the Corrupt: 7<br />
Gahz'ranka: 2<br />
Sapphiron: 15<br />
Shazzrah: 5<br />
Emeriss: 7<br />
Battleguard Sartura: 10<br />
Onyxia: 5<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Kurinnaxx: 3<br />
Ragnaros: 7<br />
Hakkar: 3<br />
Broodlord Lashlayer: 7<br />
Maexxna: 15<br />
The Four Horsemen: 15<br />
Ouro: 10<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 7<br />
Magmadar: 5<br />
Patchwerk: 12<br />
Viscidus: 10<br />
Bloodlord Mandokir: 2<br />
Chromaggus: 7<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
GM Alt: False<br />
Officer: False<br />
Officer Alt: False<br />
Core Raider: False<br />
Raider: False<br />
Trial: False<br />
Shit Tier: False<br />
Veteran: False<br />
Socials & Alts: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
THROWN: 0.5<br />
RELIC: 0.5<br />
RANGEDRIGHT: 0.5<br />
TRINKET: 0.75<br />
WEAPONOFFHAND: 0.5<br />
FINGER: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
LEGS: 1<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
Atlas<br />
Atlas_Battlegrounds<br />
Atlas_ClassicWoW<br />
Atlas_DungeonLocs<br />
AtlasLootClassic<br />
Auctionator<br />
CEPGP<br />
Details<br />
Details_TinyThreat<br />
ExRT<br />
GatherMate2<br />
InFlight_Load<br />
ItemRack<br />
MikScrollingBattleText<br />
NauticusClassic<br />
NeatPlates<br />
NeatPlatesHub<br />
NeatPlatesWidgets<br />
NeatPlates_Alvara<br />
NeatPlates_Graphite<br />
NeatPlates_Grey<br />
NeatPlates_Neon<br />
NeatPlates_Quatre<br />
NeatPlates_Roth<br />
NeatPlates_Slim_Horizontal<br />
NeatPlates_Slim_Vertical<br />
NeatPlates_BlizzardPlates<br />
NeatPlates_ClassicPlates<br />
NeatPlates_Simple<br />
NeatPlates_Renaitre<br />
RollTrackerClassic<br />
Spy<br />
TotemTimers<br />
VuhDo<br />
VuhDoOptions<br />
WeakAuras<br />
WIM<br />
CharacterStatsClassic<br />
TradeSkillMaster<br />
TradeSkillMaster_AppHelper<br />
ElvUI<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Hi Athikalaka,

Thanks for your report. I have fixed this for the next release.
