### ISSUE TITLE
Cannot see any guild member[Bug]

### ISSUE THREAD

**Issue by antiimage** [Alumian/CEPGP-Retail#214]
**The Error**
```
3x CEPGP\Utility.lua:1023: attempt to index field '?' (a nil value)
CEPGP\Utility.lua:1023: in function CEPGP_tSort
CEPGP\Scrollbar.lua:298: in function CEPGP_UpdateGuildScrollBar
CEPGP\Utility.lua:345: in function CEPGP_populateFrame
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>
```

**Describe the bug**
cannot see any guild member in my guild, cannot see their epgp via officer note just fine.

**To Reproduce**
unknown

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.8.release-hotfix2<br />
Locale: zhTW<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 10<br />
Base GP Decay Factor: true<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: False<br />
Loot Response Keyphrase: 4<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 5<br />
Reporting Channel: Raid<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 3<br />
Allow Force Sync: false, 店小二<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
鲁西弗隆: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
加尔: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
焚化者古雷曼格: True<br />
Thaddius: True<br />
Loatheb: True<br />
奥妮克希亚: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
萨弗隆先驱者: True<br />
Vaelastrasz the Corrupt: True<br />
Jin'do the Hexxer: True<br />
Baron Geddon: True<br />
沙斯拉尔: True<br />
High Priestess Arlokk: True<br />
Gri'lek: True<br />
Renataki: True<br />
迦顿男爵: True<br />
Sulfuron Harbinger: True<br />
基赫纳斯: True<br />
Bloodlord Mandokir: True<br />
Sapphiron: True<br />
Emeriss: True<br />
Onyxia: True<br />
Ouro: True<br />
Shazzrah: True<br />
Kurinnaxx: True<br />
Battleguard Sartura: True<br />
Ragnaros: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Hakkar: True<br />
玛格曼达: True<br />
Viscidus: True<br />
Broodlord Lashlayer: True<br />
Maexxna: True<br />
The Four Horsemen: True<br />
Firemaw: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Gluth: True<br />
Gahz'ranka: True<br />
Patchwerk: True<br />
管理者埃克索图斯: True<br />
拉格纳罗斯: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Silithid Royalty: 10<br />
Ossirian the Unscarred: 4<br />
鲁西弗隆: 5<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Twin Emperors: 10<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 2<br />
加尔: 5<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 10<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
焚化者古雷曼格: 5<br />
Thaddius: 15<br />
Loatheb: 15<br />
奥妮克希亚: 5<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 10<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
萨弗隆先驱者: 5<br />
Vaelastrasz the Corrupt: 10<br />
Jin'do the Hexxer: 2<br />
Baron Geddon: 5<br />
沙斯拉尔: 5<br />
High Priestess Arlokk: 2<br />
Gri'lek: 2<br />
Renataki: 2<br />
迦顿男爵: 5<br />
Sulfuron Harbinger: 5<br />
基赫纳斯: 5<br />
Bloodlord Mandokir: 2<br />
Sapphiron: 15<br />
Emeriss: 7<br />
Onyxia: 5<br />
Ouro: 10<br />
Shazzrah: 5<br />
Kurinnaxx: 3<br />
Battleguard Sartura: 10<br />
Ragnaros: 7<br />
Kel'Thuzad: 15<br />
Nefarian: 15<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Hakkar: 3<br />
玛格曼达: 5<br />
Viscidus: 10<br />
Broodlord Lashlayer: 10<br />
Maexxna: 15<br />
The Four Horsemen: 15<br />
Firemaw: 10<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 10<br />
Magmadar: 5<br />
Gluth: 12<br />
Gahz'ranka: 2<br />
Patchwerk: 12<br />
管理者埃克索图斯: 5<br />
拉格纳罗斯: 7<br />
Chromaggus: 10<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
店小二: False<br />
副会: False<br />
DKP团管理: False<br />
EPGP团管理: False<br />
大姐姐: False<br />
炊事班: False<br />
CL团员: False<br />
DKP团员: False<br />
EPGP团员: False<br />
忍著吧: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
THROWN: 0.5<br />
RELIC: 0.5<br />
RANGEDRIGHT: 0.5<br />
TRINKET: 0.75<br />
WEAPONOFFHAND: 0.5<br />
FINGER: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
LEGS: 1<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
[克盧梭洛克恩，混亂之刃]: 85<br />
[巨龍復仇者]: 25<br />
[瑪拉達斯，黑龍軍團的符文之劍]: 65<br />
[火焰之王的項圈]: 35<br />
[阿什坎迪，兄弟會之劍]: 150<br />
[狂野肩鎧]: 35<br />
[緊繃的龍皮腰帶]: 50<br />
[死亡召喚者]: 45<br />
[暗影烈焰法杖]: 150<br />
[多彩長靴]: 80<br />
Ancient Petrified Leaf: 50<br />
[衝擊腰帶]: 35<br />
[源力之環]: 35<br />
[脊骨收割者]: 60<br />
[迅擊戒指]: 35<br />
[黑曜石之刃]: 30<br />
[塞拉贊恩之鍊]: 35<br />
[思維加速寶石]: 60<br />
[芬克的熔岩挖掘器]: 30<br />
[暗影之擊]: 15<br />
[黑龍之書]: 15<br />
[火喉之握]: 45<br />
[短暫能量護符]: 35<br />
[斯泰林的甲蟲殼]: 150<br />
[祕法能量寶石]: 10<br />
[熱砂泡沫啤酒]: 80<br />
[暗影之翼]: 50<br />
[悲哀使者]: 35<br />
[普瑞斯托的陰謀飾物]: 85<br />
[龍王披風]: 65<br />
[殘忍利刃]: 40<br />
[法術能量之戒]: 35<br />
[恢復寶石]: 150<br />
[龍息手持火炮]: 25<br />
[龍類統御之戒]: 60<br />
[瑪法里恩的祝福]: 60<br />
[紅龍防護者]: 75<br />
[疾速進化手套]: 20<br />
[巫術匕首]: 15<br />
[鑽孔蟲之碟]: 35<br />
Head of Onyxia: 35<br />
[光環石錘]: 40<br />
[盲目光芒卷軸]: 40<br />
[末日之刃]: 30<br />
[龍血斗篷]: 20<br />
[削骨之刃]: 75<br />
[緊繃的龍皮護肩]: 50<br />
[血腥撕裂者]: 25<br />
[密蘇達爾，奪魂者的頭飾]: 85<br />
[龍人之槌]: 25<br />
[毀滅之刃]: 45<br />
[克洛瑪古斯之爪]: 75<br />
[黑石之戒]: 20<br />
[黑龍肩鎧]: 15<br />
[暗影烈焰長靴]: 85<br />
[埃瑟利蘇爾，懲戒之弩]: 150<br />
[速射強弓]: 35<br />
[祕法精準護腕]: 80<br />
[毒性圖騰]: 15<br />
[無盡怒氣頭盔]: 25<br />
[林格的暴風雪長靴]: 60<br />
[純源質指環]: 85<br />
[多彩之劍]: 75<br />
[交織暗影外衣]: 15<br />
[黑翼襯肩]: 60<br />
[巨龍之觸]: 20<br />
[緊繃的龍皮手套]: 45<br />
[環霧披風]: 35<br />
[瑪利斯達爾防禦者]: 25<br />
[艾斯卡達爾的右爪]: 25<br />
[燃魔腰帶]: 35<br />
[源質絲線披風]: 45<br />
[穩固護腕]: 35<br />
[埃古雷亞指環]: 35<br />
[灼燒指環]: 35<br />
[墮落十字軍腿甲]: 60<br />
[龍牙飾物]: 150<br />
[薩弗拉斯指環]: 15<br />
[變形符文]: 65<br />
[龍爪肩鎧]: 35<br />
[奈法利安的頭顱]: 65<br />
[真龍護腕]: 25<br />
[狂野之刃]: 35<br />
[穩固之力勳章]: 25<br />
[黑焰手套]: 60<br />
[碧空之歌]: 55<br />
[擊心者]: 25<br />
[古代熔火皮手套]: 22<br />
[屠龍大師之戒]: 35<br />
[龍鱗碎片]: 37<br />
[震地者]: 15<br />
[洛卡米爾·伊洛曼希斯]: 100<br />
[熔火犬牙]: 40<br />
[碎脊者]: 30<br />
[黑龍之爪]: 65<br />
[火焰符文魔典]: 20<br />
[黑灰長袍]: 15<br />
[爆擊獵槍]: 25<br />
[純淨思想長靴]: 70<br />
[阿基迪羅斯的清算之戒]: 65<br />
[生命寶石]: 50<br />
[火喉披風]: 35<br />
[純淨思想斗篷]: 50<br />
[奈薩里奧之淚]: 180<br />
[專注指環]: 80<br />
[安潔莉絲塔之握]: 50<br />
[沉重的黑鐵戒指]: 25<br />
[源質壁壘]: 75<br />
[龍牙之刃]: 30<br />
[龍爪巨斧]: 50<br />
[庇護者]: 10<br />
[飛龍披風]: 35<br />
[放血者維斯卡格]: 45<br />
[薩菲隆斗篷]: 25<br />
[強能護腿]: 70<br />
[神聖之眼]: 50<br />
[奧妮克希亞的頭顱]: 35<br />
</details>
<details><summary>Addons List</summary>
CEPGP<br />
honorspy<br />
NugEnergy<br />
WeakAuras<br />
WeaponSwingTimer<br />
!!!EaseAddonController<br />
Leatrix_Plus<br />
XIV_Databar<br />
ShinyBuffs<br />
TinyTooltip<br />
BlizzMove<br />
BlueShamans<br />
CharacterStatsClassic<br />
ls_Toasts<br />
ColorPickerPlus<br />
tullaRange<br />
OPie<br />
Dominos<br />
Dominos_Progress<br />
Dominos_Roll<br />
MonkeyQuest<br />
MonkeyQuestLog<br />
MonkeyLibrary<br />
MonkeyBuddy<br />
Questie<br />
QuestC<br />
Immersion<br />
SmartQuest<br />
QuestFrameFixer<br />
QuestIconDesaturation<br />
ClassicAuraDurations<br />
UnitFramesPlus<br />
UnitFramesPlus_Cooldown<br />
EasyFrames<br />
RangeDisplay<br />
TomTom<br />
Leatrix_Maps<br />
Atlas<br />
Atlas_Transportation<br />
Atlas_ClassicWoW<br />
HandyNotes<br />
MBB<br />
SexyMap<br />
SilverDragon<br />
SilverDragon_Classic<br />
DJBags<br />
Combuctor<br />
BagBrother<br />
zz_itemsdb<br />
YouGotMail<br />
Postal<br />
AtlasLootClassic<br />
Wardrobe<br />
MerInspect<br />
Spy<br />
NameplateCooldowns<br />
Details<br />
Details_TinyThreat<br />
MikScrollingBattleText<br />
EnhBloodlust<br />
GTFO<br />
Quartz<br />
CombatTime<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
NameplateSCT<br />
xanSoundAlerts<br />
MeepMerp<br />
TidyPlates_ThreatPlates<br />
TargetNameplateIndicator<br />
SilverPlateTweaks<br />
Talented<br />
Talented_Data<br />
SheepMonitor<br />
RogueHelper<br />
TotemTimers<br />
NugComboBar<br />
QuickTargets<br />
RollTrackerClassic<br />
ExRT<br />
VuhDo<br />
VuhDoOptions<br />
AdvancedInterfaceOptions<br />
OmniCC<br />
AutoActionCam<br />
Align<br />
CastCursor<br />
ReloadUIHotkey<br />
!BugGrabber<br />
BugSack<br />
TinyChat<br />
FriendListColors<br />
Favorites<br />
WIM<br />
DBM-Core<br />
DBM-RealUI<br />
DBM-StatusBarTimers<br />
DBM-VPYike<br />
DBM-CountPack-Overwatch<br />
DBM-DefaultSkin<br />
ExtVendorUI_Classic<br />
Accountant_Classic<br />
BuyEmAll<br />
Skillet-Classic<br />
GatherMate2<br />
GigaAutoResourcesTracker<br />
AuctionFaster<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Update your addon and let me know if the issue persists.

**Comment by antiimage** [comment]
yes, still here, cannot see any guild member

**Comment by Alumian** [comment]
Can you please confirm what version you're running now?

**Comment by antiimage** [comment]
i can see people in my raid but still cannot see players in guild.

**Comment by antiimage** [comment]
1.12.9

**Comment by Alumian** [comment]
Ok can you please post the error message you're getting now?

**Comment by antiimage** [comment]
the debug message or error message

**Comment by Alumian** [comment]
Not sure what you mean by debug message. Just post both

**Comment by antiimage** [comment]
62x CEPGP\Utility.lua:1211: attempt to index field '?' (a nil value)
CEPGP\Utility.lua:1211: in function `CEPGP_tSort'
CEPGP\Scrollbar.lua:298: in function `CEPGP_UpdateGuildScrollBar'
CEPGP\Utility.lua:400: in function `CEPGP_populateFrame'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>

**Comment by antiimage** [comment]
or u need the /cep debug informtaion

**Comment by Alumian** [comment]
Oh, no just the error message is fine. That issue has been reported to me - people have said that it is happening very rarely to them. Try reloading your UI. That might fix it this time. I'm working on a fix for it in 1.12.10.

**Comment by antiimage** [comment]
yeah, /reload doesnt work for me.

**Comment by antiimage** [comment]
or is there anyway to reloard UI?

**Comment by antiimage** [comment]
nope, still not working. :(

**Comment by Alumian** [comment]
When did the issue start happening? Did it happen after you updated the addon or just kinda out of the blue?

**Comment by antiimage** [comment]
out of no where. i guess when i type /cep show, i typed /cep shoaw or somthing, just miss spelling, then i cannot see any guild member, it fix for a while when i can see only a few people, then all disappeared again.

**Comment by Alumian** [comment]
So the issue just started happening randomly one day?

**Comment by antiimage** [comment]
just today, after raid

**Comment by Alumian** [comment]
Alright well if it just happened without updating the addon then I'd recommend just doing a clean reinstall.
Go to ..\Interface\AddOns and delete CEPGP. Then go to ..\WTF\Account\<Accountname>\SavedVariables and delete CEPGP.lua and CEPGP.lua.bak.
Just be aware that by deleting CEPGP.lua, you'll lose your addon settings, traffic logs, any saved records, attendance logs, etc...

Once you've deleted those files, redownload the addon, ideally from curse/twitch and reinstall it.

**Comment by antiimage** [comment]
what about the guild EPGP, do i still have it on file? can i restore old standings after that?

**Comment by Alumian** [comment]
The actual guild standings are stored in officer notes, so they won't change. Once you reinstall the addon I do recommend that you use the 'save standings' feature to make a backup.

**Comment by antiimage** [comment]
i still have the same problem :(((

**Comment by antiimage** [comment]
nvm, it fixed, just lost all data, thanks

**Comment by Alumian** [comment]
So it's working now?

**Comment by antiimage** [comment]
it's working but i cannot see some of the guild members.

**Comment by Alumian** [comment]
Is the issue the same as it was before?

**Comment by antiimage** [comment]
before it's all members are gone, now, just some of them. i hope it fixed itself tmr, going to sleep. thanks a lot, please leave this ticket open, i will update tmr

**Comment by antiimage** [comment]
and when i click on the tab such as class, it doesnt sort like before. i dont know what is going on, gonna leave it for tmr. :(

**Comment by Alumian** [comment]
Ok sure. Let me know how it goes tomorrow.

**Comment by antiimage** [comment]
i am so sorry, everything goes back as before when I restarted the game.... really need an undate on this.bug me for 4 hours already.

**Comment by antiimage** [comment]
288x CEPGP\Utility.lua:1211: attempt to index field '?' (a nil value)
CEPGP\Utility.lua:1211: in function `CEPGP_tSort'
CEPGP\Scrollbar.lua:298: in function `CEPGP_UpdateGuildScrollBar'
CEPGP\Utility.lua:400: in function `CEPGP_populateFrame'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>

Locals:
t = <table> {
 257 = <table> {
 }
 258 = <table> {
 }
 259 = <table> {
 }

**Comment by antiimage** [comment]
still this kind of bug, do u think i need to reinstall wow?

**Comment by antiimage** [comment]
like delete the game and reinstall it?

**Comment by Alumian** [comment]
Nah don't uninstall your game. I'm not sure why this issue is impacting you so much because the other people that reported it said it was very rare for them. I'll keep looking into this.

**Comment by antiimage** [comment]
Message: Interface\AddOns\CEPGP\Utility.lua:1211: attempt to index field '?' (a nil value)
Time: Thu Mar  5 19:35:27 2020
Count: 1
Stack: Interface\AddOns\CEPGP\Utility.lua:1211: attempt to index field '?' (a nil value)
Interface\AddOns\CEPGP\Utility.lua:1211: in function `CEPGP_tSort'
Interface\AddOns\CEPGP\Scrollbar.lua:298: in function `CEPGP_UpdateGuildScrollBar'
Interface\AddOns\CEPGP\Utility.lua:400: in function `CEPGP_populateFrame'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>

Locals: t = <table> {
 257 = <table> {
 }
 258 = <table> {
 }
 259 = <table> {
 }
 260 = <table> {
 }
 261 = <table> {
 }
 262 = <table> {
 }
 263 = <table> {
 }
 264 = <table> {
 }
 265 = <table> {
 }
 266 = <table> {
 }
 267 = <table> {
 }
 268 = <table> {
 }
 269 = <table> {
 }
 270 = <table> {
 }
 271 = <table> {
 }
 272 = <table> {
 }
 273 = <table> {
 }
 274 = <table> {
 }
 275 = <table> {
 }
 276 = <table> {
 }
 277 = <table> {
 }
 278 = <table> {
 }
 279 = <table> {
 }
 280 = <table> {
 }
 281 = <table> {
 }
 282 = <table> {
 }
 283 = <table> {
 }
 284 = <table> {
 }
 285 = <table> {
 }
 286 = <table> {
 }
 287 = <table> {
 }
 288 = <table> {
 }
 289 = <table> {
 }
 290 = <table> {
 }
 291 = <table> {
 }
 292 = <table> {
 }
 293 = <table> {
 }
 294 = <table> {
 }
 295 = <table> {
 }
 296 = <table> {
 }
 297 = <table> {
 }
 298 = <table> {
 }
 299 = <table> {
 }
 300 = <table> {
 }
 301 = <table> {
 }
 302 = <table> {
 }
 303 = <table> {
 }
 304 = <table> {
 }
 305 = <table> {
 }
 306 = <table> {
 }
 307 = <table> {
 }
 308 = <table> {
 }
 309 = <table> {
 }
 310 = <table> {
 }
 311 = <table> {
 }
 312 = <table> {
 }
 313 = <table> {
 }
 314 = <table> {
 }
 315 = <table> {
 }
 316 = <table> {
 }
 317 = <table> {
 }
 318 = <table> {
 }
 319 = <table> {
 }
 320 = <table> {
 }
 321 = <table> {
 }
 322 = <table> {
 }
 323 = <table> {
 }
 324 = <table> {
 }
 325 = <table> {
 }
 326 = <table> {
 }
 327 = <table> {
 }
 328 = <table> {
 }
 329 = <table> {
 }
 330 = <table> {
 }
 331 = <table> {
 }
 332 = <table> {
 }
 333 = <table> {
 }
 334 = <table> {
 }
 335 = <table> {
 }
 336 = <table> {
 }
 337 = <table> {
 }
 338 = <table> {
 }
 339 = <table> {
 }
 340 = <table> {
 }
 341 = <table> {
 }
 342 = <table> {
 }
 343 = <table> {
 }
 344 = <table> {
 }
 345 = <table> {
 }
 346 = <table> {
 }
 347 = <table> {
 }
 348 = <table> {
 }
 349 = <table> {
 }
 350 = <table> {
 }
 351 = <table> {
 }
 352 = <table> {
 }
 353 = <table> {
 }
 354 = <table> {
 }
 355 = <table> {
 }
 356 = <table> {
 }
 357 = <table> {
 }
 358 = <table> {
 }
 359 = <table> {
 }
 360 = <table> {
 }
 361 = <table> {
 }
 362 = <table> {
 }
 363 = <table> {
 }
 364 = <table> {
 }
 365 = <table> {
 }
 366 = <table> {
 }
 367 = <table> {
 }
 368 = <table> {
 }
 369 = <table> {
 }
}
index = 4
t2 = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {

**Comment by antiimage** [comment]
it is always the lua error appears which i dont undertand what is it

**Comment by antiimage** [comment]
i tried deleted my wow and reinstall the whole thing, still the same problem. also the same problem within my guild. everyone gets the same kind of error.

**Comment by antiimage** [comment]
Message: Interface\AddOns\CEPGP\Utility.lua:1211: attempt to index field '?' (a nil value)
Time: Fri Mar  6 07:37:14 2020

**Comment by antiimage** [comment]
so we did raid today, we can see everyone in raid just fine, the problem is the announcement has a 2 minutes delay. we cannot properly use the system for loot cause it take too long to respnse. please try to fix the bug before our next raid day on 3/9/2020 :(

**Comment by Alumian** [comment]
I'll try my best but I can't promise anything.

**Comment by Alumian** [comment]
Are you on the CEPGP discord?

**Comment by antiimage** [comment]
is the problem ' field "?" '

**Comment by antiimage** [comment]
i have that discord wanna me come?

**Comment by antiimage** [comment]
i cannot join the discord. i can see all the message there

**Comment by Alumian** [comment]
Add me to friends. Alumian#6465

**Comment by antiimage** [comment]
added you

**Comment by Alumian** [comment]
Issue was caused by players that had transferred realm. They had -realmname suffix at the end of their name and was causing duplicate entries in the guild list, thus inflating the number provided from GetNumGuildMembers, thus making it inaccurate. It appears that kicking and reinviting these players to the guild has resolved this issue.
