### ISSUE TITLE
[Bug] Exception loop when in Guild view

### ISSUE THREAD

**Issue by Donki-50** [Alumian/CEPGP-Retail#216]
**The Error**
Message: Interface\AddOns\CEPGP\Scrollbar.lua:395: bad argument #1 to 'upper' (string expected, got nil)
Time: Fri Mar 20 21:22:12 2020
Count: 174
Stack: Interface\AddOns\CEPGP\Scrollbar.lua:395: bad argument #1 to 'upper' (string expected, got nil)
[C]: ?
[C]: in function `upper'
Interface\AddOns\CEPGP\Scrollbar.lua:395: in function `CEPGP_UpdateRaidScrollBar'
Interface\AddOns\CEPGP\Utility.lua:709: in function <Interface\AddOns\CEPGP\Utility.lua:694>
Interface\AddOns\CEPGP\Utility.lua:770: in function <Interface\AddOns\CEPGP\Utility.lua:715>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: 

**Describe the bug**
It happens every once in a while when viewing standings under Guild view.

**To Reproduce**
I cannot reproduce it, it appears to occur randomly.

**Debug Information**

<details><summary>Debug Info</summary><br />
Version: 1.12.9 release<br />
Locale: enUS<br />
GP Formula: (4.83x(2.5^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 20<br />
Base GP Decay Factor: true<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 50<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: true<br />
Full Raid Loot Visibility: true<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 200<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 4<br />
Allow Force Sync: false, x<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Vaelastrasz the Corrupt: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Heigan the Unclean: True<br />
Moam: True<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
High Priestess Arlokk: True<br />
Baron Geddon: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
Sapphiron: True<br />
Jin'do the Hexxer: True<br />
Azuregos: True<br />
Firemaw: True<br />
Gahz'ranka: True<br />
Ouro: True<br />
Shazzrah: True<br />
Emeriss: True<br />
Battleguard Sartura: True<br />
Ysondre: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Lethon: True<br />
Ragnaros: True<br />
Maexxna: True<br />
Broodlord Lashlayer: True<br />
Hakkar: True<br />
The Four Horsemen: True<br />
Kurinnaxx: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Viscidus: True<br />
Gluth: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Ragnaros: 20<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Kurinnaxx: 3<br />
Golemagg the Incinerator: 10<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 15<br />
High Priest Venoxis: 2<br />
Gehennas: 10<br />
Taerar: 7<br />
Vaelastrasz the Corrupt: 20<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Bloodlord Mandokir: 2<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Sapphiron: 15<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 20<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Onyxia: 15<br />
Ouro: 10<br />
Baron Geddon: 10<br />
Sulfuron Harbinger: 10<br />
Gri'lek: 2<br />
Hakkar: 3<br />
Renataki: 2<br />
Jin'do the Hexxer: 2<br />
Gothik the Harvester: 12<br />
High Priestess Arlokk: 2<br />
Gluth: 12<br />
Shazzrah: 10<br />
Flamegor: 20<br />
Battleguard Sartura: 10<br />
Emeriss: 7<br />
Kel'Thuzad: 15<br />
Nefarian: 40<br />
Fankriss the Unyielding: 10<br />
Lucifron: 10<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Ossirian the Unscarred: 4<br />
Gahz'ranka: 2<br />
Lethon: 7<br />
Broodlord Lashlayer: 20<br />
Maexxna: 15<br />
Ysondre: 7<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 20<br />
Magmadar: 10<br />
Patchwerk: 12<br />
Viscidus: 10<br />
Firemaw: 20<br />
Chromaggus: 30<br />
Garr: 10<br />
</details>
<details><summary>Standby Guild Ranks</summary>
x: True<br />
xx: True<br />
xxx: True<br />
xxxx: False<br />
xxxxx: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
THROWN: 0.5<br />
RELIC: 0.5<br />
RANGEDRIGHT: 0.5<br />
TRINKET: 0.75<br />
WEAPONOFFHAND: 0.5<br />
LEGS: 1<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
FINGER: 0.5<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
BagBrother<br />
Bagnon<br />
Bartender4<br />
CEPGP<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
Details<br />
Details_TinyThreat<br />
GatherMate2<br />
GTFO<br />
HealBot<br />
HealBot_Data<br />
HealBot_en<br />
HealBot_Options<br />
honorspy<br />
ItemRack<br />
Leatrix_Maps<br />
Masque<br />
Masque_Stylo<br />
Masque_Qhil<br />
OmniCC<br />
Pawn<br />
PitBull4<br />
Plater<br />
SexyMap<br />
ThreatClassic2<br />
!TotemModFix<br />
VendorPrice<br />
WeakAuras<br />
CharacterStatsClassic<br />
TradeSkillMaster<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Implementation has now been released.
