### ISSUE TITLE
Show count down timer on loot distribution window [Request]

### ISSUE THREAD

**Issue by Nuroduas** [Alumian/CEPGP-Retail#217]
When configuring the Loot GUI options there is an auto pass timer that can be set.  I have not observed that this feature shows a timer anywhere to the users.
1. It would be helpful if the timer counts down on the loot pop up for players so that they see they have a time limit to make a selection.
2. It would be helpful if the timer would count down on the Loot Distribution window so that the Master Looter knows how much time is left for players to make a selection.

Overall this would be beneficial to speed up loot distribution and let players know they have to make a selection in a specific amount of time.

**Comment by Alumian** [comment]
This timer is already present on the popup window when an item is announced, however it is not present on the loot distribution frame. I'll add it in there.

**Comment by Alumian** [comment]
Resolved in 1.12.15.
