### ISSUE TITLE
Show Players who don't meet minimum EP [Request]

### ISSUE THREAD

**Issue by Nuroduas** [Alumian/CEPGP-Retail#219]
We are using a minimum EP requirement before players are eligible to get gear.  I have noticed that when they get the popup and click I am seeing a message from the Addon that says they are interested but the do not show in loot distribution.  I would be helpful if they did show up there maybe with a special indicator that they do not meet the minimum EP requirement.  If everyone in a class has a piece of loot and more than 1 person in the raid can use it but doesn't meet requirements we now have to go look at them manually to determine their PR.

**Comment by Alumian** [comment]
Currently available in beta versions.

**Comment by Alumian** [comment]
Implementation has now been released.
