### ISSUE TITLE
Search Function for guild view & Filter for ranks [Request]

### ISSUE THREAD

**Issue by Vucien** [Alumian/CEPGP-Retail#220]
**Describe the feature you'd like to see in this addon**
Thankyou for the fantastic addon. 

There any possibility of getting a search function on member lists for guild and raid? We have a guild bank donation system that provides extra EP, so we have to manually add it each week. A search function on the guild list to add EP would speed things up MASSIVELY.

Equally in order to reduce the number of players to load and clutter through, it would bve fantastic if we could have a filter for this list to exclude/include specific ranks.

Thanks again!

**Comment by Alumian** [comment]
Implemented in 1.13.0.
