### ISSUE TITLE
[Bug] micro freezes when guild member logs on.

### ISSUE THREAD

**Issue by Droolster** [Alumian/CEPGP-Retail#221]
**The Error**
System freezes up for around 0.3 seconds when guild member logs on.

**Describe the bug**
Multiple players report their systems freezing during raids and normal world when another guild member logs in. This is happening in a large guild of 900+ members. 

**To Reproduce**
Some players have it all the time, some never. No clear path to reproduce.

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.
Will expand on this as I talk to people who have the issue.
Droolster has:
<details><summary>Debug Info</summary><br />
Version: 1.12.9 release<br />
Locale: enUS<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: False<br />
Standby Percent: 100<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: true<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 104<br />
Reporting Channel: Raid<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 4<br />
Allow Force Sync: true, Officer<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Vaelastrasz the Corrupt: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Heigan the Unclean: True<br />
Gluth: True<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
Sulfuron Harbinger: True<br />
Baron Geddon: True<br />
Viscidus: True<br />
Gri'lek: True<br />
Azuregos: True<br />
Jin'do the Hexxer: True<br />
Moam: True<br />
Firemaw: True<br />
Sapphiron: True<br />
Ouro: True<br />
Shazzrah: True<br />
Emeriss: True<br />
Battleguard Sartura: True<br />
Ysondre: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Lethon: True<br />
Ragnaros: True<br />
Maexxna: True<br />
Broodlord Lashlayer: True<br />
Hakkar: True<br />
The Four Horsemen: True<br />
Kurinnaxx: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Patchwerk: True<br />
High Priestess Arlokk: True<br />
Gahz'ranka: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 20<br />
Ragnaros: 70<br />
Buru the Gorger: 30<br />
Wushoolay: 20<br />
Kurinnaxx: 30<br />
Golemagg the Incinerator: 50<br />
Grand Widow Faerlina: 120<br />
High Priestess Mar'li: 20<br />
Majordomo Executus: 50<br />
High Priest Venoxis: 20<br />
Gehennas: 50<br />
Taerar: 70<br />
Vaelastrasz the Corrupt: 70<br />
High Priest Thekal: 20<br />
Noth the Plaguebringer: 120<br />
Bloodlord Mandokir: 20<br />
Moam: 30<br />
The Prophet Skeram: 100<br />
Sapphiron: 150<br />
C'Thun: 120<br />
General Rajaxx: 30<br />
Princess Huhuran: 100<br />
Thaddius: 150<br />
Loatheb: 150<br />
Ayamiss the Hunter: 30<br />
Ebonroc: 70<br />
Heigan the Unclean: 120<br />
Azuregos: 70<br />
Doom Lord Kazzak: 7<br />
Firemaw: 70<br />
Ouro: 100<br />
Baron Geddon: 50<br />
Viscidus: 100<br />
Gri'lek: 20<br />
Hakkar: 30<br />
Gothik the Harvester: 120<br />
Jin'do the Hexxer: 20<br />
Onyxia: 50<br />
Sulfuron Harbinger: 50<br />
Renataki: 20<br />
Shazzrah: 50<br />
Flamegor: 70<br />
Battleguard Sartura: 100<br />
Emeriss: 70<br />
Kel'Thuzad: 150<br />
Nefarian: 100<br />
Fankriss the Unyielding: 100<br />
Lucifron: 50<br />
Anub'Rekhan: 120<br />
Hazza'rah: 20<br />
Ossirian the Unscarred: 40<br />
Gahz'ranka: 20<br />
Lethon: 70<br />
Broodlord Lashlayer: 70<br />
Maexxna: 150<br />
Ysondre: 70<br />
Grobbulus: 120<br />
Instructor Razuvious: 120<br />
Razorgore the Untamed: 70<br />
Magmadar: 50<br />
Patchwerk: 120<br />
High Priestess Arlokk: 20<br />
Gluth: 120<br />
Chromaggus: 70<br />
Garr: 50<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
Officer: False<br />
Veteran: False<br />
Member: False<br />
Raider: False<br />
Alt: False<br />
Newbie: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
THROWN: 0.5<br />
RELIC: 0.5<br />
RANGEDRIGHT: 0.5<br />
TRINKET: 0.75<br />
WEAPONOFFHAND: 0.5<br />
LEGS: 1<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
FINGER: 0.5<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
Auctionator<br />
BagBrother<br />
Bagnon<br />
Bartender4<br />
CEPGP<br />
ClassicAuraDurations<br />
Decursive<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
ExoLink<br />
ExoLink_BIS<br />
ExtendedCharacterStats<br />
GFW_DisenchantPredictor<br />
GatherLite<br />
GroupBulletinBoard<br />
GTFO<br />
InFlight_Load<br />
Leatrix_Maps<br />
Misspelled<br />
MizusRaidTracker<br />
ModernTargetFrame<br />
zz_Money<br />
MoveAnything<br />
OmniCC<br />
Pawn<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
Profession_Assistance_Classic<br />
Recount<br />
SellableItemDrops<br />
SellJunk<br />
SimpleDing<br />
SmallBlizRaidFrames<br />
TellMeWhen<br />
ThreatClassic2<br />
TitanClassicAmmo<br />
TitanClassicBag<br />
TitanClassicClock<br />
TitanClassicGold<br />
TitanClassicLocation<br />
TitanClassicLootType<br />
TitanClassicPerformance<br />
TitanClassicRegen<br />
TitanClassicRepair<br />
TitanClassicVolume<br />
TitanClassicXP<br />
TitanClassic<br />
VendorPrice<br />
WhereToGatherClassic<br />
CharacterStatsClassic<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
I've added a new feature which will be available in the next beta to let you adjust the polling rate of the add-on. This should fix the issue, but I'll leave this ticket open for the time being.

**Comment by Alumian** [comment]
Implementation has now been released.
