### ISSUE TITLE
[Request] Problem selecting text for Export Standings

### ISSUE THREAD

**Issue by Droolster** [Alumian/CEPGP-Retail#222]
**The Error**
No error message. Text cannot be selected without extra actions.

**Describe the bug**
When exporting the CEGP standing using the 'Export Standings" button, the text presented is already selected. This suggests that it can be copied directly, however, using control-c actives the character screen. The text must be de-selected then re-selected before it can be copied.

**To Reproduce**
1. type /cep show
2. open Guild view
3. click Export Standing
4. hit crtl-c

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.
No relevant debug info

**Comment by Alumian** [comment]
I have added a button which will force the text to highlight for you. This should assist with this issue. This will be available in the next update.
