### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by RyanBrinch** [Alumian/CEPGP-Retail#224]
**The Error**
What was the error message you received? None

**Describe the bug**
Essentially my add-on is up to date and the same one that my guild uses. The problem is that my add-on is not recording anything during our raids. Everyone is listed with 0 ep / 1 gp all the way down the list. I can still see all guild members as well as EPGP Traffic. In addition when i whisper officers in the guild they also respond with 0 ep / 1 gp.

**To Reproduce**
How can this bug be reproduced?

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.
<details><summary>Debug Info</summary><br />
Version: 1.12.9 release<br />
Locale: enUS<br />
GP Formula: (4.83x(2.5^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 50<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 106<br />
Reporting Channel: Officer<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 4<br />
Allow Force Sync: false, Social<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Vaelastrasz the Corrupt: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Heigan the Unclean: True<br />
Sapphiron: True<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
Firemaw: True<br />
Baron Geddon: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
Gluth: True<br />
Chromaggus: True<br />
Gahz'ranka: True<br />
High Priestess Arlokk: True<br />
Moam: True<br />
Ouro: True<br />
Shazzrah: True<br />
Razorgore the Untamed: True<br />
Battleguard Sartura: True<br />
Ysondre: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Lethon: True<br />
Kurinnaxx: True<br />
Broodlord Lashlayer: True<br />
Hakkar: True<br />
Maexxna: True<br />
The Four Horsemen: True<br />
Ragnaros: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Viscidus: True<br />
Azuregos: True<br />
Jin'do the Hexxer: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Ragnaros: 14<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Silithid Royalty: 10<br />
Kurinnaxx: 3<br />
Golemagg the Incinerator: 10<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Twin Emperors: 10<br />
Majordomo Executus: 12<br />
High Priest Venoxis: 2<br />
Gehennas: 10<br />
Taerar: 7<br />
Vaelastrasz the Corrupt: 20<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Bloodlord Mandokir: 2<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Sapphiron: 15<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 20<br />
Heigan the Unclean: 12<br />
Renataki: 2<br />
Onyxia: 12<br />
Doom Lord Kazzak: 7<br />
Sulfuron Harbinger: 10<br />
Baron Geddon: 10<br />
Viscidus: 10<br />
Gri'lek: 2<br />
Firemaw: 20<br />
Chromaggus: 20<br />
Gluth: 12<br />
High Priestess Arlokk: 2<br />
Azuregos: 7<br />
Flamegor: 20<br />
Shazzrah: 10<br />
Razorgore the Untamed: 20<br />
Battleguard Sartura: 10<br />
Ossirian the Unscarred: 4<br />
Kel'Thuzad: 15<br />
Nefarian: 30<br />
Fankriss the Unyielding: 10<br />
Lucifron: 10<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Gahz'ranka: 2<br />
Ysondre: 7<br />
Broodlord Lashlayer: 20<br />
Maexxna: 15<br />
Hakkar: 3<br />
The Four Horsemen: 15<br />
Lethon: 7<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 10<br />
Patchwerk: 12<br />
Ouro: 10<br />
Gothik the Harvester: 12<br />
Jin'do the Hexxer: 2<br />
Garr: 10<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Social: True<br />
High Council: True<br />
Officer: True<br />
Raider: True<br />
Trial: False<br />
Raider Alt: False<br />
Social: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2.5<br />
NECK: 0.75<br />
HEAD: 1.25<br />
WEAPON: 0.75<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.75<br />
SHIELD: 0.75<br />
HOLDABLE: 0.75<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
SHOULDER: 1<br />
EXCEPTION: 1<br />
FINGER: 0.75<br />
TRINKET: 1.5<br />
WAIST: 0.5<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1.25<br />
LEGS: 1.25<br />
WEAPONOFFHAND: 0.75<br />
RANGEDRIGHT: 0.75<br />
RELIC: 0.75<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
BeanCounter<br />
CEPGP<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
eCastingBar<br />
Enchantrix-Barker<br />
ExtendedCharacterStats<br />
HealBot<br />
HealBot_Data<br />
HealBot_en<br />
HealBot_Options<br />
honorspy<br />
InFlight_Load<br />
orbSellAndRepair<br />
Recount<br />
ShadowedUnitFrames<br />
SlideBar<br />
Stubby<br />
!Swatter<br />
ThreatClassic2<br />
ThreatMeterQuery<br />
Threatrack<br />
TitanClassicAmmo<br />
TitanClassicBag<br />
TitanClassicClock<br />
TitanClassicGold<br />
TitanClassicLocation<br />
TitanClassicLootType<br />
TitanClassicPerformance<br />
TitanClassicRegen<br />
TitanClassicRepair<br />
TitanClassicVolume<br />
TitanClassicXP<br />
TitanClassic<br />
TomTom<br />
VendorPrice<br />
WeakAuras<br />
WeaponSwingTimer<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
What rank are you? It sounds like the guild permissions haven't been configured correctly. If you whisper officers and they reply with 0 EP / 1 GP and you're certain that that is incorrect then that means that they can't view officer notes. Could you please confirm?

**Comment by RyanBrinch** [comment]
The guild has been using the add-on for quite some time without any issues. I was able to whisper someone to get my info to work. Looks like that was the issue with getting my own report. So what I'm gathering is that I cant keep a record in my own add-on during raids is because I'm a lower rank as of now. I will keep an eye on the issue and let you know if that doesn't fix it. I was asking around last night and no one was able to help me out so i appreciate the quick response.

**Comment by RyanBrinch** [comment]
issue resolved. it was the rank.
