### ISSUE TITLE
[Request] Sync traffic between all users

### ISSUE THREAD

**Issue by roastbeeef** [Alumian/CEPGP-Retail#227]
It seems like the traffic is only stored for people that were online at the point of the transaction - can there be a method added to synchronise this between players so that everyone has a full picture?

thanks

**Comment by Droolster** [comment]
Just to complicate things, this has to be able to deal with a guild having more than one Master Looter.

**Comment by thowt** [comment]
+1
We are raiding multiple riad groups - different days. So nobody have all traffic right now to check what happened.
And now with ZG opened it will be even more difficult.

Feature to sync whole list or just merge will be very useful.

**Comment by nickedgar** [comment]
+1 especially with ZG and Ony splits

**Comment by Alumian** [comment]
This feature is currently in beta testing.

**Comment by Alumian** [comment]
Resolved in 1.12.15.
