### ISSUE TITLE
[Request]Other Buttons in GUI and Council(Players with Edit Officer Notes)

### ISSUE THREAD

**Issue by chikoba** [Alumian/CEPGP-Retail#23]
Hello,

the last Update was with the "Mainspecc" and "Pass" Button or?

I miss the button "Offspecc", "Minor Upgrade" and "Styleneed".

And we have in Loot 5 Council Member wenn anybody press need only i can see wich one was that, but i think its better when all people that can edit the officer note the the needed people and not only the pm.

sorry for my english :(

greetz and good work for now!

**Comment by Alumian** [comment]
Hi Chikoba,

Thanks for the feature request. I do plan to implement additional buttons, just as you are used to, but as this is now considered a quality of life improvement, it won't be implemented for a while as there are more urgent requests that I need to clear first.

Thanks

**Comment by Alumian** [comment]
What I was thinking of doing was having 2 roll buttons customisable. I know that EPGP LootMaster supported more than 2 but I was thinking I could split the loot distribution window into 2 sub frames stacked ontop of each other. Do you think more than 2 customisable buttons will be needed?

**Comment by westlakem** [comment]
@Alumian could you just "rank" the responses by what they selected?  This is kinda a deal breaker for using this addon, as we would like to be able to do "main spec" "main spec stat stick" "offspec" "DE" "Pass", etc.  I understand that may be a UI challenge, but we really do need more than 2 options.

Also, my LUA is a bit rusty, but since I would love to use this addon for our raids I would really like to have this implemented in the coming weeks

**Comment by westlakem** [comment]
To add, i would also like to distribute for 1/2 the GP value (for example) for offspec.  Customization on the "Distributing Item" screen where it says "Give for GP, Give for Free" would be nice as well.

**Comment by Alumian** [comment]
@westlakem can you please submit a separate feature request for that? Thanks

**Comment by westlakem** [comment]
@Alumian No problem, i can open a new one for the 1/2GP thing... Do you need any help with the "multiple options" thing?  After looking at the code I don't think it would be too hard to do.

**Comment by esfdk** [comment]
I'd like to chime in and suggest that instead of two seperate scrollframes, another column (Response)  could be added to the screen and then order the responses depending on a user defined 
hierarchy. 

Thanks for all the hard work!

**Comment by Alumian** [comment]
Alright, I've managed to write this into the existing distribution frame. This request has been implemented in a highly experimental build, but if you would like to help me test it, it's available on the CEPGP discord under #beta-testing.

**Comment by Alumian** [comment]
Implemented in the 1.12.8 release.
