### ISSUE TITLE
Initial/Min GP stuck at 1 [Bug]

### ISSUE THREAD

**Issue by scarecr0w12** [Alumian/CEPGP-Retail#231]
**The Error**
Initial/Minimum Player GP stuck at 1, unable to change, does not save

**Describe the bug**
Initial GP in GP management set as 1, changing to any other value does not save the value put, and resets to 1.

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.10 Open Beta 7.6<br />
Locale: enUS<br />
GP Formula: (20x(2.1^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 100<br />
Base GP Decay Factor: false<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 20<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: true, 100<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 4<br />
Allow Force Sync: false, Guild Master<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Vaelastrasz the Corrupt: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
The Edge of Madness: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
The Twin Emperors: True<br />
Heigan the Unclean: True<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
Sulfuron Harbinger: True<br />
Baron Geddon: True<br />
Viscidus: True<br />
Gri'lek: True<br />
Gluth: True<br />
Jin'do the Hexxer: True<br />
Azuregos: True<br />
Sapphiron: True<br />
Moam: True<br />
Gahz'ranka: True<br />
Emeriss: True<br />
Shazzrah: True<br />
Ouro: True<br />
Battleguard Sartura: True<br />
Ysondre: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Lethon: True<br />
Ragnaros: True<br />
Broodlord Lashlayer: True<br />
Hakkar: True<br />
Maexxna: True<br />
The Four Horsemen: True<br />
Kurinnaxx: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Patchwerk: True<br />
High Priestess Arlokk: True<br />
Firemaw: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Ragnaros: 20<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Kurinnaxx: 3<br />
Golemagg the Incinerator: 10<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 15<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Vaelastrasz the Corrupt: 7<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Bloodlord Mandokir: 2<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Sapphiron: 15<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
The Edge of Madness: 2<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
The Silithid Royalty: 10<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 7<br />
Heigan the Unclean: 12<br />
Renataki: 2<br />
Onyxia: 15<br />
Doom Lord Kazzak: 7<br />
Ouro: 10<br />
Baron Geddon: 10<br />
Viscidus: 10<br />
Gri'lek: 2<br />
Firemaw: 7<br />
Jin'do the Hexxer: 2<br />
Gluth: 12<br />
Sulfuron Harbinger: 10<br />
Azuregos: 7<br />
Flamegor: 7<br />
Shazzrah: 10<br />
Emeriss: 7<br />
Battleguard Sartura: 10<br />
Ossirian the Unscarred: 4<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Gahz'ranka: 2<br />
Lethon: 7<br />
Hakkar: 3<br />
Broodlord Lashlayer: 7<br />
Maexxna: 15<br />
The Four Horsemen: 15<br />
Ysondre: 7<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 7<br />
Magmadar: 5<br />
Patchwerk: 12<br />
High Priestess Arlokk: 2<br />
Gothik the Harvester: 12<br />
Chromaggus: 7<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guild Master: True<br />
Officer: True<br />
Officer Alt: True<br />
Guild Bank: True<br />
Raider: True<br />
Raider Alt: True<br />
Member: True<br />
Initiate: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
THROWN: 0.5<br />
RELIC: 0.5<br />
RANGEDRIGHT: 0.5<br />
TRINKET: 0.75<br />
WEAPONOFFHAND: 0.5<br />
LEGS: 1<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
FINGER: 0.56<br />
EXCEPTION: 1<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
ACP<br />
Armory<br />
Atlas<br />
Atlas_ClassicWoW<br />
Atlas_DungeonLocs<br />
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
AuctionDB<br />
BagBrother<br />
Bagnon<br />
BeanCounter<br />
Carbonite<br />
Carbonite.Notes<br />
Carbonite.Quests<br />
CEPGP<br />
ClassicGuildLaunchProfiler<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
ClassicGuildBank<br />
Dismounter<br />
Enchantrix-Barker<br />
EPGP-Classic<br />
ExRT<br />
ExtendedCharacterStats<br />
GatherMate2<br />
GBankClassic<br />
Grail<br />
GroupCalendar<br />
GuildLotteryRaffle<br />
Guild_Roster_Manager<br />
GuildBankClassic<br />
HealBot<br />
HealBot_Data<br />
HealBot_en<br />
HealBot_Options<br />
IceHUD<br />
LFG113<br />
LibStub<br />
MobHealthClassic<br />
OmniCC<br />
PallyPower<br />
Pawn<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
RaidMemberList<br />
RollTrackerClassic<br />
SlideBar<br />
Stubby<br />
!Swatter<br />
TitanReputations<br />
TitanClassicMail<br />
TitanClassicAmmo<br />
TitanClassicBag<br />
TitanClassicClock<br />
TitanClassicGold<br />
TitanClassicGuild<br />
TitanClassicLocation<br />
TitanClassicLootType<br />
TitanClassicPerformance<br />
TitanClassicRegen<br />
TitanClassicRepair<br />
TitanSocial<br />
TitanClassicVolume<br />
TitanClassicXP<br />
TitanClassic<br />
WIM<br />
+Wowhead_Looter<br />
GuildTooltip<br />
GuildHelperClassic<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
FastGuildInvite<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by scarecr0w12** [comment]
Was able to get it to save, but it required that i input the new value, hit enter, console reload, then do that 3 more times for it to actually Show a value of 100 (Or any value other than 1)

**Comment by Alumian** [comment]
Issue appears to be resolved with new release.
