### ISSUE TITLE
[Request] Separate Wands and Other Ranged Weapons

### ISSUE THREAD

**Issue by markus101** [Alumian/CEPGP-Retail#232]
**Describe the feature you'd like to see in this addon**

For Classic would it be possible to have different GP values for wands and other ranged weapons? Our guild charges different values for wands than we do for all other ranged weapons and currently our officers are refunding GP after awarding the item, which works, but could be better.

**Comment by Alumian** [comment]
Added in the next version.

**Comment by Alumian** [comment]
Implementation has now been released.
