### ISSUE TITLE
Mat Item GP Calculation [Request] 

### ISSUE THREAD

**Issue by scarecr0w12** [Alumian/CEPGP-Retail#233]
Separate GP calculation for Mat items such as Lava Cores, Fiery Cores, Ect. The current calculation over prices those types of items. Knowing that you can manually set item prices, having an automated calculation would be far simpler for the users.

**Comment by Alumian** [comment]
Hi Scarecr0w12,

I'm not sure that many guilds 1) distribute their crafting materials among their members and 2) use EPGP as their distribution method for those items. For the amount of resources required to implement this feature, I'm not certain that it would add obvious value to the addon. Unfortunately, I do not plan to implement this feature and I kindly ask you to make use of the override list instead.
