### ISSUE TITLE
[Bug]Loot Distribution Keyphrase Alt Change Delays Loot Announcement

### ISSUE THREAD

**Issue by Jh16** [Alumian/CEPGP-Retail#234]
**The Error**
What was the error message you received?
Don't receive an error message. But this message pops up: CEPGP: This item will be announced in a moment. Please wait and keep the loot window open.
![loottimestamps](https://user-images.githubusercontent.com/5688177/79048500-164a9280-7be3-11ea-9f50-630257ed45ed.JPG)

**Describe the bug**

When I change the Keyphrase Alternative within the Loot Distribution options to something else. (other than the default need or greed for Main Spec/Off Spec) the above chat message is printed and loot is never announced (it just announced it after 5 minutes of waiting...). When I change the Keyphrases back to the default, it announces the loot.
I can't have 39 people wait up to 5 minutes for loot to be announced.

**To Reproduce**
How can this bug be reproduced?
Classic EPGP Options -> Loot Distribution -> Response 1 Keyphrase Alternative: !ms -> Response 2 Keyphrase Alternative: !os
Set Minimum Threshold for Auto Show: Poor
Kill a mob while in raid and as ML. Try to announce said loot and just wait.

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.
<details><summary>Debug Info</summary><br />
Version: 1.12.10 Release<br />
Locale: enUS<br />
GP Formula: (1x(1^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1000<br />
Base GP Decay Factor: false<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
GUI for Loot: False<br />
Loot Response Keyphrase: !bid<br />
Standby EP Whisper Keyphrase: !standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 2<br />
Allow Force Sync: false, RegaNam Pgpe<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: False<br />
Gothik the Harvester: False<br />
Buru the Gorger: False<br />
Wushoolay: False<br />
Silithid Royalty: False<br />
Ossirian the Unscarred: False<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: False<br />
High Priestess Mar'li: False<br />
Twin Emperors: False<br />
Majordomo Executus: True<br />
High Priest Venoxis: False<br />
Gehennas: True<br />
Taerar: False<br />
Ysondre: False<br />
Thane Korth'azz: False<br />
High Priest Thekal: False<br />
Noth the Plaguebringer: False<br />
Lethon: False<br />
Moam: False<br />
The Prophet Skeram: False<br />
Flamegor: True<br />
C'Thun: False<br />
General Rajaxx: False<br />
The Edge of Madness: False<br />
Princess Huhuran: False<br />
Thaddius: False<br />
Loatheb: False<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: False<br />
Ebonroc: True<br />
Firemaw: True<br />
Heigan the Unclean: False<br />
Azuregos: False<br />
Doom Lord Kazzak: False<br />
High Priestess Arlokk: False<br />
Baron Geddon: True<br />
Viscidus: False<br />
Gri'lek: False<br />
The Twin Emperors: True<br />
Chromaggus: True<br />
Vaelastrasz the Corrupt: True<br />
Gahz'ranka: False<br />
Renataki: False<br />
Bloodlord Mandokir: False<br />
Razorgore the Untamed: True<br />
Shazzrah: True<br />
Sapphiron: False<br />
Battleguard Sartura: False<br />
Onyxia: False<br />
Kel'Thuzad: False<br />
Nefarian: True<br />
Fankriss the Unyielding: False<br />
Lucifron: True<br />
Anub'Rekhan: False<br />
Hazza'rah: False<br />
Ouro: False<br />
Ragnaros: True<br />
Hakkar: False<br />
Maexxna: False<br />
Broodlord Lashlayer: True<br />
The Four Horsemen: False<br />
Kurinnaxx: False<br />
Grobbulus: False<br />
Instructor Razuvious: False<br />
Emeriss: False<br />
Magmadar: True<br />
Patchwerk: False<br />
Sulfuron Harbinger: True<br />
Gluth: False<br />
Jin'do the Hexxer: False<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 0<br />
Gothik the Harvester: 0<br />
Buru the Gorger: 0<br />
Wushoolay: 0<br />
Silithid Royalty: 0<br />
Ossirian the Unscarred: 0<br />
Golemagg the Incinerator: 500<br />
Grand Widow Faerlina: 0<br />
High Priestess Mar'li: 0<br />
Twin Emperors: 0<br />
Majordomo Executus: 500<br />
High Priest Venoxis: 0<br />
Gehennas: 500<br />
Taerar: 0<br />
Ysondre: 0<br />
Thane Korth'azz: 0<br />
High Priest Thekal: 0<br />
Noth the Plaguebringer: 0<br />
Lethon: 0<br />
Moam: 0<br />
The Prophet Skeram: 0<br />
Flamegor: 1000<br />
C'Thun: 0<br />
General Rajaxx: 0<br />
The Edge of Madness: 0<br />
Princess Huhuran: 0<br />
Thaddius: 0<br />
Loatheb: 0<br />
The Silithid Royalty: 0<br />
Ayamiss the Hunter: 0<br />
Ebonroc: 1000<br />
Vaelastrasz the Corrupt: 1000<br />
Heigan the Unclean: 0<br />
Sulfuron Harbinger: 500<br />
Azuregos: 0<br />
Doom Lord Kazzak: 0<br />
Baron Geddon: 500<br />
High Priestess Arlokk: 0<br />
Gri'lek: 0<br />
The Twin Emperors: 0<br />
Chromaggus: 1000<br />
Gahz'ranka: 0<br />
Sapphiron: 0<br />
Firemaw: 1000<br />
Bloodlord Mandokir: 0<br />
Razorgore the Untamed: 1000<br />
Onyxia: 0<br />
Lord Kazzak: 0<br />
Kurinnaxx: 0<br />
Battleguard Sartura: 0<br />
Ragnaros: 1000<br />
Kel'Thuzad: 0<br />
Nefarian: 1000<br />
Fankriss the Unyielding: 0<br />
Lucifron: 500<br />
Anub'Rekhan: 0<br />
Hazza'rah: 0<br />
Shazzrah: 500<br />
Broodlord Lashlayer: 1000<br />
Viscidus: 0<br />
Maexxna: 0<br />
Hakkar: 0<br />
The Four Horsemen: 0<br />
Ouro: 0<br />
Grobbulus: 0<br />
Instructor Razuvious: 0<br />
Emeriss: 0<br />
Magmadar: 500<br />
Patchwerk: 0<br />
Renataki: 0<br />
Gluth: 0<br />
Jin'do the Hexxer: 0<br />
Garr: 500<br />
</details>
<details><summary>Standby Guild Ranks</summary>
GM BITCHES: False<br />
Guild Master: False<br />
Officer: False<br />
RegaNam Pgpe: False<br />
Monster Raider: False<br />
Raider: False<br />
Monster: False<br />
ALT: False<br />
Trial: False<br />
Muted: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 0<br />
NECK: 0<br />
HEAD: 0<br />
WEAPON: 0<br />
WRIST: 0<br />
WEAPONMAINHAND: 0<br />
SHIELD: 0<br />
HOLDABLE: 0<br />
CLOAK: 0<br />
SHOULDER: 0<br />
FEET: 0<br />
LEGS: 0<br />
EXCEPTION: 0<br />
WAIST: 0<br />
TRINKET: 0<br />
WAND: 0<br />
HAND: 0<br />
ROBE: 0<br />
CHEST: 0<br />
RELIC: 0<br />
WEAPONOFFHAND: 0<br />
FINGER: 0<br />
RANGED: 0<br />
THROWN: 0<br />
</details>
<details><summary>Override List</summary>
[Cenarion Spaulders]: 1200<br />
[Boots of Prophecy]: 1200<br />
[Felheart Gloves]: 1200<br />
[Netherwind Belt]: 4000<br />
[Girdle of the Fallen Crusader]: 4000<br />
[Elementium Threaded Cloak]: 3400<br />
[Primalist's Linked Legguards]: 5000<br />
[Arcanist Leggings]: 1200<br />
[Lawbringer Bracers]: 0<br />
[Bloodfang Chestpiece]: 5000<br />
[Judgement Sabatons]: 0<br />
[Rune of Metamorphosis]: 3600<br />
[Dragonstalker's Greaves]: 4000<br />
[Judgement Legplates]: 0<br />
[Nemesis Leggings]: 3200<br />
[Stormrage Boots]: 4000<br />
[Earthfury Bracers]: 200<br />
[Core Hound Tooth]: 3000<br />
[Brutality Blade]: 2400<br />
[Sash of Whispered Secrets]: 1600<br />
[Band of Accuria]: 4800<br />
[Rejuvenating Gem]: 10600<br />
[Handguards of Transcendence]: 3200<br />
[Crul'shorukh, Edge of Chaos]: 3000<br />
[Netherwind Gloves]: 4000<br />
[Nightslayer Gloves]: 1200<br />
[Ancient Petrified Leaf]: 3600<br />
[Fire Runed Grimoire]: 1200<br />
[Nightslayer Chestpiece]: 1600<br />
[Waistband of Wrath]: 4000<br />
[Bloodfang Belt]: 4000<br />
[Dragon's Touch]: 4600<br />
[Cenarion Bracers]: 200<br />
[Archimtiros' Ring of Reckoning]: 2800<br />
[Red Dragonscale Protector]: 2800<br />
[Earthfury Vestments]: 1600<br />
[Sabatons of Wrath]: 4000<br />
[Robes of Prophecy]: 1600<br />
[Ring of Blackrock]: 8400<br />
[Drillborer Disk]: 2400<br />
[Shimmering Geta]: 4000<br />
[Gloves of Rapid Evolution]: 800<br />
[Dragonstalker's Belt]: 4000<br />
[Deep Earth Spaulders]: 1000<br />
[Cloak of Firemaw]: 4000<br />
[Netherwind Pants]: 3200<br />
[Venomous Totem]: 3600<br />
[Taut Dragonhide Gloves]: 4000<br />
[Fireproof Cloak]: 400<br />
[Vambraces of Prophecy]: 200<br />
[Mantle of Prophecy]: 1200<br />
[Judgement Spaulders]: 0<br />
[Head of Nefarian]: 5200<br />
[Cenarion Gloves]: 1200<br />
[Heartstriker]: 3000<br />
[Felheart Pants]: 1200<br />
[Essence Gatherer]: 1600<br />
[Pauldrons of Might]: 1200<br />
[Drake Fang Talisman]: 4200<br />
[Wristguards of Stability]: 1200<br />
[Lok'amir il Romathis]: 4200<br />
[Perdition's Blade]: 4000<br />
[Girdle of Prophecy]: 200<br />
[Eskhandar's Right Claw]: 1600<br />
[Black Ash Robe]: 4000<br />
[Felheart Bracers]: 200<br />
[Lifegiving Gem]: 3600<br />
[Bindings of the Windseeker]: 200<br />
[Heavy Dark Iron Ring]: 3000<br />
[Earthfury Boots]: 1200<br />
[Cloak of the Brood Lord]: 5600<br />
[Giantstalker's Helmet]: 1200<br />
[Shard of the Flame]: 400<br />
[Bonereaver's Edge]: 3800<br />
[Mind Quickening Gem]: 3600<br />
[Sorcerous Dagger]: 1600<br />
[Bracers of Ten Storms]: 2800<br />
[Legplates of Might]: 1200<br />
[Draconic Maul]: 2000<br />
[Lawbringer Gauntlets]: 0<br />
[Arcanist Gloves]: 1200<br />
[Aurastone Hammer]: 1800<br />
[Lawbringer Belt]: 0<br />
[Earthfury Legguards]: 1200<br />
[Leggings of Transcendence]: 3200<br />
[Giantstalker's Belt]: 200<br />
[Primalist's Linked Waistguard]: 4000<br />
[Dragonfang Blade]: 4200<br />
[Giantstalker's Gloves]: 1200<br />
[Bracelets of Wrath]: 2800<br />
[Spinal Reaper]: 2600<br />
[Gauntlets of Might]: 1200<br />
[Emberweave Leggings]: 4000<br />
[Shadowstrike]: 0<br />
[Cloak of Draconic Might]: 4000<br />
[Cloak of the Shrouded Mists]: 2000<br />
[Legplates of Ten Storms]: 3200<br />
[Giantstalker's Bracers]: 200<br />
[Cenarion Vestments]: 1600<br />
[Chromatically Tempered Sword]: 4200<br />
[Gutgore Ripper]: 1200<br />
[Helm of Endless Rage]: 5000<br />
[Netherwind Robes]: 5000<br />
[Felheart Belt]: 200<br />
[Shadow Wing Focus Staff]: 6000<br />
[Boots of Pure Thought]: 7800<br />
[Styleen's Impeding Scarab]: 3600<br />
[Wild Growth Spaulders]: 3600<br />
[Staff of Dominance]: 2000<br />
[Claw of the Black Drake]: 2100<br />
[Helm of the Lifegiver]: 800<br />
[Salamander Scale Pants]: 3000<br />
[Onslaught Girdle]: 4800<br />
[Giantstalker's Leggings]: 1200<br />
[Chromatic Boots]: 4800<br />
[Herald of Woe]: 5000<br />
[Lawbringer Legplates]: 0<br />
[Mish'undare, Circlet of the Mind Flayer]: 10000<br />
[The Black Book]: 3600<br />
[Elementium Reinforced Bulwark]: 5600<br />
[Felheart Robes]: 1600<br />
[The Untamed Blade]: 5000<br />
[Ashkandi, Greatsword of the Brotherhood]: 7000<br />
[Choker of Enlightenment]: 800<br />
[Malfurion's Blessed Bulwark]: 5000<br />
[Arcanist Crown]: 1200<br />
[Head of the Broodlord Lashlayer]: 4000<br />
[Fireguard Shoulders]: 400<br />
[Pendant of the Fallen Dragon]: 3400<br />
[Gloves of Prophecy]: 1200<br />
[Empowered Leggings]: 10000<br />
[Staff of the Shadow Flame]: 150000<br />
[Black Brood Pauldrons]: 4800<br />
[Gauntlets of Ten Storms]: 4000<br />
[Band of Dark Dominion]: 3400<br />
[Nemesis Spaulders]: 4000<br />
[Arcanist Robes]: 1600<br />
[Giantstalker's Breastplate]: 1600<br />
[Flameguard Gauntlets]: 1400<br />
[Manastorm Leggings]: 400<br />
[Blastershot Launcher]: 1400<br />
[Earthfury Gauntlets]: 1200<br />
[Ebony Flame Gloves]: 4800<br />
[Bloodfang Boots]: 4000<br />
[Bindings of Transcendence]: 2800<br />
[Prestor's Talisman of Connivery]: 5600<br />
[Netherwind Boots]: 4000<br />
[Legguards of the Fallen Crusader]: 5000<br />
[Natural Alignment Crystal]: 3600<br />
[Taut Dragonhide Shoulderpads]: 4000<br />
[Lawbringer Helm]: 0<br />
[Band of Forced Concentration]: 6200<br />
[Cenarion Leggings]: 1200<br />
[Crown of Destruction]: 4000<br />
[Arcanist Boots]: 1200<br />
[Lawbringer Boots]: 0<br />
[Ashjre'thul, Crossbow of Smiting]: 5000<br />
[Nightslayer Bracelets]: 200<br />
[Pants of Prophecy]: 1200<br />
[Essence of the Pure Flame]: 800<br />
[Earthshaker]: 1200<br />
[Nemesis Robes]: 5000<br />
[Pure Elementium Band]: 5600<br />
[Interlaced Shadow Jerkin]: 7000<br />
[Bracers of Arcane Accuracy]: 5600<br />
[Aged Core Leather Gloves]: 1600<br />
[Subterranean Cape]: 200<br />
[Striker's Mark]: 4000<br />
[Netherwind Bindings]: 2800<br />
[Earthfury Helmet]: 1200<br />
[Claw of Chromaggus]: 6400<br />
[Bloodfang Spaulders]: 4000<br />
[Head of Nefarian]: 5200<br />
[Breastplate of Wrath]: 5000<br />
[Dragonstalker's Bracers]: 2800<br />
[Core Forged Greaves]: 400<br />
[Cenarion Boots]: 1200<br />
[Boots of Transcendence]: 4000<br />
[Stormrage Pauldrons]: 4000<br />
[Breastplate of Ten Storms]: 5000<br />
[Dragonstalker's Breastplate]: 5000<br />
[Taut Dragonhide Belt]: 5400<br />
[Stormrage Chestguard]: 5000<br />
[Cursed Felblade]: 200<br />
[Robes of Transcendence]: 5000<br />
[Cauterizing Band]: 2800<br />
[Epaulets of Ten Storms]: 4000<br />
[Crimson Shocker]: 100<br />
[Pauldrons of Transcendence]: 4000<br />
[Nemesis Gloves]: 4000<br />
[Arcanist Mantle]: 1200<br />
[Dragonstalker's Gauntlets]: 4000<br />
[Gauntlets of Wrath]: 4000<br />
[Stormrage Handguards]: 4000<br />
[Bloodfang Gloves]: 4000<br />
[Eye of Sulfuras]: 400<br />
[Scrolls of Blinding Light]: 0<br />
[Seal of the Archmagus]: 400<br />
[Drake Talon Pauldrons]: 4800<br />
[Nightslayer Belt]: 200<br />
[Breastplate of Might]: 1600<br />
[Circle of Applied Force]: 2800<br />
[Felheart Horns]: 1200<br />
[Magma Tempered Boots]: 0<br />
[Greaves of Ten Storms]: 4000<br />
[Sabatons of the Flamewalker]: 1200<br />
[Felheart Slippers]: 1200<br />
[Bracers of Might]: 200<br />
[Judgement Breastplate]: 0<br />
[Angelista's Grasp]: 5400<br />
[Tome of Tranquilizing Shot]: 0<br />
[Drake Talon Cleaver]: 5000<br />
[Arcane Infused Gem]: 3600<br />
[Dragon's Blood Cape]: 1600<br />
[Firemaw's Clutch]: 11600<br />
[Band of Sulfuras]: 1600<br />
[Nemesis Boots]: 4000<br />
[Nemesis Belt]: 4000<br />
[Dragonstalker's Spaulders]: 4000<br />
[Belt of Transcendence]: 4000<br />
[Helm of Might]: 1200<br />
[Therazane's Link]: 4000<br />
[Stormrage Bracers]: 2800<br />
[Pauldrons of Wrath]: 4000<br />
[Dragonstalker's Legguards]: 3200<br />
[Bloodfang Bracers]: 2800<br />
[Doom's Edge]: 2200<br />
[Nemesis Bracers]: 2800<br />
[Finkle's Lava Dredger]: 800<br />
[Mantle of the Blackwing Cabal]: 8600<br />
[The Eye of Divinity]: 3000<br />
[Crystalline Cuffs]: 200<br />
[Maladath, Runed Blade of the Black Flight]: 4700<br />
[Lawbringer Spaulders]: 0<br />
[Circlet of Prophecy]: 1200<br />
[Earthfury Epaulets]: 1200<br />
[Bindings of the Windseeker]: 200<br />
[Boots of the Shadow Flame]: 4800<br />
[Nightslayer Cover]: 1200<br />
[Flamewaker Legplates]: 400<br />
[Nightslayer Shoulder Pads]: 1200<br />
[Ring of Spell Power]: 1200<br />
[Judgement Gauntlets]: 0<br />
[Stormrage Belt]: 4000<br />
[Draconic Avenger]: 5000<br />
[Gloves of the Hypnotic Flame]: 400<br />
[Lawbringer Chestguard]: 0<br />
[Ringo's Blizzard Boots]: 4000<br />
[Shroud of Pure Thought]: 5600<br />
[Obsidian Edged Blade]: 2000<br />
[Stormrage Legguards]: 3200<br />
[Arcanist Bindings]: 200<br />
[Legplates of Wrath]: 3200<br />
[Judgement Bindings]: 0<br />
[Mana Igniting Cord]: 2800<br />
[Earthfury Belt]: 200<br />
[Netherwind Mantle]: 4000<br />
[Cenarion Helm]: 1200<br />
[Felheart Shoulder Pads]: 1200<br />
[Belt of Ten Storms]: 4000<br />
[Nightslayer Pants]: 1200<br />
[Belt of Might]: 200<br />
[Bloodfang Pants]: 3200<br />
[Robe of Volatile Power]: 2800<br />
[Cenarion Belt]: 200<br />
[Nightslayer Boots]: 1200<br />
[Dragonbreath Hand Cannon]: 1600<br />
[Talisman of Ephemeral Power]: 3600<br />
[Neltharion's Tear]: 7800<br />
[Wristguards of True Flight]: 2800<br />
[Arcanist Belt]: 200<br />
[Malistar's Defender]: 1400<br />
[Quick Strike Ring]: 3600<br />
[Giantstalker's Epaulets]: 1200<br />
[Judgement Belt]: 0<br />
[Choker of the Fire Lord]: 4200<br />
[Sabatons of Might]: 1200<br />
[Azuresong Mageblade]: 2800<br />
[Giantstalker's Boots]: 1200<br />
[Spineshatter]: 500<br />
[Medallion of Steadfast Might]: 3600<br />
[Aegis of Preservation]: 3600<br />
</details>
<details><summary>Addons List</summary>
AdiBags<br />
AdvancedInterfaceOptions<br />
AFK_fullscreen<br />
AnnoyingPopupRemover<br />
AntiDaze<br />
Atlas<br />
Atlas_ClassicWoW<br />
AtlasLootClassic<br />
Auctionator<br />
AuctionSold<br />
AutoTrackQuests<br />
AutoResClassic<br />
autoScaleRaid<br />
BagFreeSpaceCounter<br />
BetterVendorPrice<br />
BigWigs<br />
BiSTracker<br />
BlueShamans<br />
BuffOwner<br />
CivilianWarning<br />
ClassTrainerPlus<br />
CEPGP<br />
ClassicGoldTracker<br />
ClassicLootAssistant<br />
Classic Quest Log<br />
ClassicAggroHighlight<br />
ClassicAuraDurations<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
ClassicCodex<br />
ClassicHunterPetInfo<br />
ClassicProfessionFilter<br />
ClassicRaidAssist<br />
CraftCooldown<br />
DeathLUL<br />
Details<br />
Details_EncounterDetails<br />
Details_RaidCheck<br />
Details_Streamer<br />
Details_TinyThreat<br />
Details_Vanguard<br />
Doom_CooldownPulse<br />
ExRT<br />
Farmer<br />
Focused<br />
GatherMate2<br />
GatherNotify<br />
GBankClassic<br />
GroupCalendar<br />
GTFO<br />
Guidelime<br />
Guidelime_JoanaGuideHorde1-60<br />
Guild_Roster_Manager<br />
GuildBankClassic<br />
HHTD<br />
HelmHide<br />
idTip<br />
ImprovedLootFrame<br />
ImprovedRaidFrameStatusText<br />
InFlight_Load<br />
InstanceCounter<br />
ItemRack<br />
ItemTooltipProfessionIcons<br />
KHunterTimers<br />
Leatrix_Maps<br />
Leatrix_Plus<br />
Leatrix_Tunes<br />
LetMeCast<br />
LinkWrangler<br />
MacroTalkClassic<br />
MaxCam<br />
Memoria<br />
MBB<br />
MobInfo2-Classic<br />
ModernTargetFrame<br />
MonkeySpeed<br />
NauticusClassic<br />
NeatPlates<br />
NeatPlatesHub<br />
NeatPlatesWidgets<br />
NeatPlates_Alvara<br />
NeatPlates_Graphite<br />
NeatPlates_Grey<br />
NeatPlates_Neon<br />
NeatPlates_Quatre<br />
NeatPlates_Roth<br />
NeatPlates_Slim_Horizontal<br />
NeatPlates_Slim_Vertical<br />
NeatPlates_BlizzardPlates<br />
NeatPlates_ClassicPlates<br />
NeatPlates_Simple<br />
NeatPlates_Renaitre<br />
Necrosis<br />
NefHunterHelper<br />
NovaWorldBuffs<br />
OmniCC<br />
oRA3<br />
orbSellAndRepair<br />
PetXP<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
out of range 1.3<br />
QuestIconDesaturation<br />
Quester<br />
QuestFrameFixer<br />
QuickTargets<br />
Remindr<br />
RepHelper_Classic<br />
RosterFilter<br />
Sheepdog<br />
SimplyGInv<br />
SoulSort<br />
Spy<br />
StickyTargetClassic<br />
TellMeWhen<br />
ThreatClassic2<br />
TinyTooltip<br />
TrackingEye<br />
TrackingSwitcher<br />
TradeSkillWhisperLookup<br />
TranqRotate<br />
unitscan<br />
WaterDispenser<br />
WeakAuras<br />
WeaponSwingTimer<br />
WhatsTraining<br />
WIM<br />
XandY<br />
XckMasterLootAdvanced<br />
XPTracker<br />
YouGotMail<br />
CharacterStatsClassic<br />
TradeSkillMaster<br />
TradeSkillMaster_AppHelper<br />
SpeedyAutoLoot<br />
XTranqManager<br />
Restocker<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
BAM_advanced<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Found that the poll rate was set too high and so was taking 5 minutes to run initial scans of the guild roster. Issue resolved.
