### ISSUE TITLE
[Bug] Error sorting by RANK in raid attendance

### ISSUE THREAD

**Issue by scarecr0w12** [Alumian/CEPGP-Retail#237]
**The Error**
What was the error message you received?
```Date: 2020-04-12 02:55:34
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\CEPGP\Utility.lua line 1500:
   attempt to compare nil with number
Debug:
   CEPGP\Utility.lua:1500: CEPGP_tSort()
   CEPGP\Scrollbar.lua:885: CEPGP_UpdateAttendanceScrollBar()
   CEPGP\Utility.lua:1651: CEPGP_setCriteria()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
t = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
}
index = 12
(for index) = 1
(for limit) = 39
(for step) = 1
x = 1
(for index) = 7
(for limit) = 39
(for step) = 1
z = 7
(*temporary) = 0
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11304
  ACP, v3.5.7 
  Armory, vv1.7.0
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasDungeonLocs, vv1.47.00.11303.00
  AtlasLootClassic, vv1.4.8
  AtlasLootClassicData, vv1.4.8
  AtlasLootClassicDungeonsAndRaids, vv1.4.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AuctionDB, vv1.02.01
  BagBrother, v
  Bagnon, v8.3.5
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CallbackHandler10, v
  CensusPlusClassic, vv0.8.4
  CEPGP, v
  ClassicCastbars, vv1.3.3
  ClassicCastbarsOptions, v
  ClassicGuildBank, v1.3
  DBMCore, v1.13.42
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dismounter, v1.2.1
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4110
  ExtendedCharacterStats, v2.2.1
  FloTotemBar, v
  GatherMate2, v1.45.5
  GBankClassic, v0.902
  Grail, v109
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v33302
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v33302
  GroupCalendar, v
  GuildRosterManager, v1.871
  GuildBankClassic, v1.0.1
  GuildHelperClassic, v0.2.4
  GuildLotteryRaffle, v3.1.20
  GuildTooltip, v2.13.12
  HealBot, v1.13.4.3
  HealBotData, v1.13.4.3
  HealBoten, v1.13.4.3
  HealBotExtraSkins, v1.13.4.3
  HealBotOptions, v1.13.4.3
  IceHUD, v1.12.11
  Informant, v8.2.6374 (SwimmingSeadragon)
  LFG113, v
  LibStub, v
  MobHealthClassic, v4
  OmniCC, v8.3.5
  PallyPower, vv1.1o-classic
  Pawn, v2.3.24
  Prat30, v3.7.50
  Prat30Libraries, v
  RollTrackerClassic, v2.21
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.2.2.11304
  TitanClassicAmmo, v1.2.2.11304
  TitanClassicBag, v1.2.2.11304
  TitanClassicClock, v1.2.2.11304
  TitanClassicGold, v1.2.2.11304
  TitanClassicGuild, v1.0.0.3
  TitanClassicLocation, v1.2.2.11304
  TitanClassicLootType, v1.2.2.11304
  TitanClassicMail, v1.0.0.1
  TitanClassicPerformance, v1.2.2.11304
  TitanClassicRegen, v1.2.2.11304
  TitanClassicRepair, v1.2.2.11304
  TitanClassicVolume, v1.2.2.11304
  TitanClassicXP, v1.2.2.11304
  TitanReputations, vv1.1-classic
  TitanSocial, v1.13.3
  WIM, v3.8.8
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=9f1)

```
**Describe the bug**
Opening raid attendance, and selecting a specific snapshot (The only one i have includes "Non guild members") and then sorting by rank, caueses the previously mentioned error. This clears the entire snapshots list, leaving the "Guild list" option able to view still by filtering by guild list. Requires a reload of the ui to see snapshot again.

**To Reproduce**
Type /cep show>Click guild>Click "Raid Attendance"> Select a specific date snapshot>Click Filter option> Click "RANK" in sort

**Debug Information**
`<details><summary>Debug Info</summary><br />
Version: 1.12.10 Release<br />
Locale: enUS<br />
GP Formula: (17.213x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 100<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: False<br />
Standby Percent: 20<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
GUI for Loot: True<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: true<br />
Full Raid Loot Visibility: true<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: true, 100<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 4<br />
Allow Force Sync: true, Guild Master<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Vaelastrasz the Corrupt: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
The Edge of Madness: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Moam: True<br />
Heigan the Unclean: True<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
Viscidus: True<br />
Baron Geddon: True<br />
High Priestess Arlokk: True<br />
Gri'lek: True<br />
The Twin Emperors: True<br />
Chromaggus: True<br />
Firemaw: True<br />
Sulfuron Harbinger: True<br />
Azuregos: True<br />
Gahz'ranka: True<br />
Razorgore the Untamed: True<br />
Shazzrah: True<br />
Ouro: True<br />
Battleguard Sartura: True<br />
Ysondre: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Kurinnaxx: True<br />
Ragnaros: True<br />
Maexxna: True<br />
Hakkar: True<br />
Broodlord Lashlayer: True<br />
The Four Horsemen: True<br />
Lethon: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Sapphiron: True<br />
Gluth: True<br />
Jin'do the Hexxer: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Ragnaros: 20<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Kurinnaxx: 3<br />
Golemagg the Incinerator: 10<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 15<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Vaelastrasz the Corrupt: 7<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Bloodlord Mandokir: 2<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Sapphiron: 15<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
The Edge of Madness: 2<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
The Silithid Royalty: 10<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 7<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Onyxia: 15<br />
Doom Lord Kazzak: 7<br />
Viscidus: 10<br />
Baron Geddon: 10<br />
High Priestess Arlokk: 2<br />
Gri'lek: 2<br />
Renataki: 2<br />
Chromaggus: 7<br />
Gothik the Harvester: 12<br />
Ouro: 10<br />
Gluth: 12<br />
Flamegor: 7<br />
Shazzrah: 10<br />
Razorgore the Untamed: 7<br />
Battleguard Sartura: 10<br />
Ossirian the Unscarred: 4<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Gahz'ranka: 2<br />
Ysondre: 7<br />
Maexxna: 15<br />
Hakkar: 3<br />
Broodlord Lashlayer: 7<br />
The Four Horsemen: 15<br />
Lethon: 7<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 5<br />
Patchwerk: 12<br />
Sulfuron Harbinger: 10<br />
Firemaw: 7<br />
Jin'do the Hexxer: 2<br />
Garr: 5<br />
</details>
<details><summary>Standby Guild Ranks</summary>
Guild Master: True<br />
Officer: True<br />
Officer Alt: True<br />
Guild Bank: True<br />
Raider: True<br />
Raider Alt: True<br />
Member: True<br />
Initiate: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
SHOULDER: 0.75<br />
FEET: 0.75<br />
RELIC: 0.5<br />
FINGER: 0.56<br />
WAIST: 0.75<br />
TRINKET: 0.75<br />
WAND: 0.5<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1<br />
LEGS: 1<br />
WEAPONOFFHAND: 0.5<br />
EXCEPTION: 1<br />
RANGED: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
[Arcanite Bar]: 30<br />
Richteous Orb: 10<br />
[Lava Core]: 10<br />
[Arcane Crystal]: 20<br />
[Fiery Core]: 10<br />
</details>
<details><summary>Addons List</summary>
ACP<br />
Armory<br />
Atlas<br />
Atlas_ClassicWoW<br />
Atlas_DungeonLocs<br />
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
AuctionDB<br />
BagBrother<br />
Bagnon<br />
BeanCounter<br />
Carbonite<br />
Carbonite.Notes<br />
Carbonite.Quests<br />
CensusPlusClassic<br />
CEPGP<br />
ClassicGuildLaunchProfiler<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
ClassicGuildBank<br />
Dismounter<br />
Enchantrix-Barker<br />
EPGP-Classic<br />
ExRT<br />
ExtendedCharacterStats<br />
FloTotemBar<br />
GatherMate2<br />
GBankClassic<br />
Grail<br />
GroupCalendar<br />
GuildLotteryRaffle<br />
Guild_Roster_Manager<br />
GuildBankClassic<br />
HealBot<br />
HealBot_Data<br />
HealBot_en<br />
HealBot_Options<br />
IceHUD<br />
LFG113<br />
LibStub<br />
MobHealthClassic<br />
OmniCC<br />
PallyPower<br />
Pawn<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
RollTrackerClassic<br />
SlideBar<br />
Stubby<br />
!Swatter<br />
TitanReputations<br />
TitanClassicMail<br />
TitanClassicAmmo<br />
TitanClassicBag<br />
TitanClassicClock<br />
TitanClassicGold<br />
TitanClassicGuild<br />
TitanClassicLocation<br />
TitanClassicLootType<br />
TitanClassicPerformance<br />
TitanClassicRegen<br />
TitanClassicRepair<br />
TitanSocial<br />
TitanClassicVolume<br />
TitanClassicXP<br />
TitanClassic<br />
Wholly<br />
WIM<br />
+Wowhead_Looter<br />
GuildTooltip<br />
GuildHelperClassic<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
FastGuildInvite<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>`

**Comment by scarecr0w12** [comment]
secondary error that pops up behind first.

```
Date: 2020-04-12 03:01:40
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\CEPGP\Utility.lua line 1500:
   attempt to compare two nil values
Debug:
   CEPGP\Utility.lua:1500: CEPGP_tSort()
   CEPGP\Scrollbar.lua:309: CEPGP_UpdateGuildScrollBar()
   CEPGP\Utility.lua:879:
      CEPGP\Utility.lua:871
   CEPGP\Utility.lua:951:
      CEPGP\Utility.lua:906
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
t = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
 88 = <table> {
 }
 89 = <table> {
 }
 90 = <table> {
 }
 91 = <table> {
 }
}
index = 12
(for index) = 1
(for limit) = 91
(for step) = 1
x = 1
(for index) = 2
(for limit) = 91
(for step) = 1
z = 2
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare two nil values"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11304
  ACP, v3.5.7 
  Armory, vv1.7.0
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasDungeonLocs, vv1.47.00.11303.00
  AtlasLootClassic, vv1.4.8
  AtlasLootClassicData, vv1.4.8
  AtlasLootClassicDungeonsAndRaids, vv1.4.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AuctionDB, vv1.02.01
  BagBrother, v
  Bagnon, v8.3.5
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CallbackHandler10, v
  CensusPlusClassic, vv0.8.4
  CEPGP, v
  ClassicCastbars, vv1.3.3
  ClassicCastbarsOptions, v
  ClassicGuildBank, v1.3
  DBMCore, v1.13.42
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dismounter, v1.2.1
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4110
  ExtendedCharacterStats, v2.2.1
  FloTotemBar, v
  GatherMate2, v1.45.5
  GBankClassic, v0.902
  Grail, v109
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v33302
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v33302
  GroupCalendar, v
  GuildRosterManager, v1.871
  GuildBankClassic, v1.0.1
  GuildHelperClassic, v0.2.4
  GuildLotteryRaffle, v3.1.20
  GuildTooltip, v2.13.12
  HealBot, v1.13.4.3
  HealBotData, v1.13.4.3
  HealBoten, v1.13.4.3
  HealBotExtraSkins, v1.13.4.3
  HealBotOptions, v1.13.4.3
  IceHUD, v1.12.11
  Informant, v8.2.6374 (SwimmingSeadragon)
  LFG113, v
  LibStub, v
  MobHealthClassic, v4
  OmniCC, v8.3.5
  PallyPower, vv1.1o-classic
  Pawn, v2.3.24
  Prat30, v3.7.50
  Prat30Libraries, v
  RollTrackerClassic, v2.21
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.2.2.11304
  TitanClassicAmmo, v1.2.2.11304
  TitanClassicBag, v1.2.2.11304
  TitanClassicClock, v1.2.2.11304
  TitanClassicGold, v1.2.2.11304
  TitanClassicGuild, v1.0.0.3
  TitanClassicLocation, v1.2.2.11304
  TitanClassicLootType, v1.2.2.11304
  TitanClassicMail, v1.0.0.1
  TitanClassicPerformance, v1.2.2.11304
  TitanClassicRegen, v1.2.2.11304
  TitanClassicRepair, v1.2.2.11304
  TitanClassicVolume, v1.2.2.11304
  TitanClassicXP, v1.2.2.11304
  TitanReputations, vv1.1-classic
  TitanSocial, v1.13.3
  WIM, v3.8.8
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=9f1)


```

**Comment by Alumian** [comment]
Resolved in the next update.
