### ISSUE TITLE
[Request] Guild Bank

### ISSUE THREAD

**Issue by scarecr0w12** [Alumian/CEPGP-Retail#239]
Since Classic does not have a bank like retail, many guild use alt characters to Store guild items and currency for use in raids or similar. One major hurdle for guilds, such as mine, is storage and distribution of raid items, and in some situations, the accrual of GP points for those items.

Something I'd like to see is the addition of a "Guild Bank" so other members of the guild can see what is currently stored, The GP Value, and even the Purchase of those items via the addon, similar to loot distribution in a raid.

The feature would have the possible abilities:

- Scan, Store and share contents of a specified Guild Bank Character
- Mark items "non-tradable"
- Allow the "Bid" for an item within the bank for either its assigned or Manually set GP Value.
- Allow characters to send items to guild bank, and track what is received by the guild bank. 
-- For example, The addon "ClassicGuildBank" allows one character to send items to the guild bank. The addon tracks who the sender was based on a String in the Subject line corresponding the sending character.
-- Based on setlist of items, EP values can be added to Characters for "Donations", Such as a guildmember donating a High-end mat or Gold to the guild bank. A set amount of EP can be added to that character.
- Allow transparent tracking of Guild members requesting items, and the possibility of a timeframe needed to pass before the item is given to the requesting player, so others can bid as well for said item. Example: Player A Request Tier1 BOE, 6 Hours must elapse before the item is given, Players C and D also want to Bid, Player C bids MS and Player D bids OS, Ect.

**Comment by Alumian** [comment]
Hi Scarecr0w12,

Unfortunately I feel that this is a bit out of scope of the addon. It's a great idea for a plugin but I do not plan to implement this as a core feature.
