### ISSUE TITLE
[Bug] Timer error at first login

### ISSUE THREAD

**Issue by jrydh** [Alumian/CEPGP-Retail#240]
**The Error**
Message: Interface\SharedXML\C_TimerAugment.lua:30: Usage: C_Timer.After(seconds, func)
Time: Mon Apr 13 12:28:57 2020
Count: 1
Stack: Interface\SharedXML\C_TimerAugment.lua:30: Usage: C_Timer.After(seconds, func)
[C]: in function `After'
Interface\SharedXML\C_TimerAugment.lua:30: in function `NewTicker'
Interface\AddOns\CEPGP\Utility.lua:897: in function `CEPGP_rosterUpdate'
Interface\AddOns\CEPGP\Core.lua:231: in function `CEPGP_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = nil
(*temporary) = <function> defined @Interface\SharedXML\C_TimerAugment.lua:14

**Describe the bug**
The above error message, and the listing in CEPGP was empty.

**To Reproduce**
This occurred on first login after updating from 1.12.09 to 1.12.11 Release. After UI reload, the error disappeared. It did not reappear again after relogging.

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.

<details><summary>Debug Info</summary><br />
Version: 1.12.11 Release<br />
Locale: enUS<br />
Poll Rate: 0.0001<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 50<br />
Base GP Decay Factor: true<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 50<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 2<br />
Allow Force Sync: false, Guild Master<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: False<br />
Gothik the Harvester: True<br />
Buru the Gorger: False<br />
Wushoolay: False<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: False<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: False<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: False<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: False<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: False<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: False<br />
The Edge of Madness: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: False<br />
Ebonroc: True<br />
Bloodlord Mandokir: False<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Firemaw: True<br />
Baron Geddon: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: False<br />
Gahz'ranka: False<br />
Chromaggus: True<br />
Vaelastrasz the Corrupt: True<br />
High Priestess Arlokk: False<br />
Gluth: True<br />
Renataki: False<br />
Razorgore the Untamed: True<br />
Shazzrah: True<br />
Onyxia: True<br />
Battleguard Sartura: True<br />
Ouro: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: False<br />
Viscidus: True<br />
Kurinnaxx: False<br />
Maexxna: True<br />
Broodlord Lashlayer: True<br />
Hakkar: False<br />
The Four Horsemen: True<br />
Ragnaros: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Sapphiron: True<br />
The Twin Emperors: True<br />
Jin'do the Hexxer: False<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 0<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 0<br />
Wushoolay: 0<br />
Silithid Royalty: 10<br />
Ossirian the Unscarred: 0<br />
Golemagg the Incinerator: 1<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 0<br />
Twin Emperors: 10<br />
Majordomo Executus: 1<br />
High Priest Venoxis: 0<br />
Gehennas: 1<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 0<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 0<br />
The Prophet Skeram: 10<br />
Flamegor: 6<br />
C'Thun: 12<br />
General Rajaxx: 0<br />
The Edge of Madness: 2<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
The Silithid Royalty: 10<br />
Ayamiss the Hunter: 0<br />
Ebonroc: 6<br />
Bloodlord Mandokir: 0<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Firemaw: 6<br />
Baron Geddon: 1<br />
Sulfuron Harbinger: 1<br />
Gri'lek: 0<br />
Gahz'ranka: 0<br />
Chromaggus: 6<br />
Vaelastrasz the Corrupt: 6<br />
High Priestess Arlokk: 0<br />
Gluth: 12<br />
Renataki: 0<br />
Razorgore the Untamed: 6<br />
Shazzrah: 1<br />
Onyxia: 1<br />
Battleguard Sartura: 10<br />
Ouro: 10<br />
Kel'Thuzad: 15<br />
Nefarian: 8<br />
Fankriss the Unyielding: 10<br />
Lucifron: 1<br />
Anub'Rekhan: 12<br />
Hazza'rah: 0<br />
Viscidus: 10<br />
Kurinnaxx: 0<br />
Maexxna: 15<br />
Broodlord Lashlayer: 6<br />
Hakkar: 0<br />
The Four Horsemen: 15<br />
Ragnaros: 1<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 1<br />
Patchwerk: 12<br />
Sapphiron: 15<br />
The Twin Emperors: 10<br />
Jin'do the Hexxer: 0<br />
Garr: 1<br />
</details>
<details><summary>Loot Button Configuration</summary>
Loot Button 1<br />State: Enabled<br />Button Text: Need (BWL)<br />Discount: 0%<br />Keyphrase Alternative: Need<br /><br />Loot Button 2<br />State: Enabled<br />Button Text: Need (MC/Ony)<br />Discount: 50%<br />Keyphrase Alternative: Greed<br /><br />Loot Button 3<br />State: Enabled<br />Button Text: Off spec<br />Discount: 100%<br />Keyphrase Alternative: Disenchant<br /><br />Loot Button 4<br />State: Enabled<br />Button Text: Fun/collection<br />Discount: 100%<br />Keyphrase Alternative: Minor<br /><br /></details><details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
Officer: False<br />
Raider: False<br />
Officer Alt: False<br />
Social: False<br />
Alt: False<br />
Trial: False<br />
Needs Rank: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1<br />
SHIELD: 1<br />
HOLDABLE: 1<br />
CLOAK: 0.5<br />
SHOULDER: 0.75<br />
FEET: 0.75<br />
LEGS: 1<br />
EXCEPTION: 1<br />
WAIST: 0.75<br />
TRINKET: 1.5<br />
WAND: 0.5<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1<br />
RELIC: 0.5<br />
WEAPONOFFHAND: 1<br />
FINGER: 1<br />
RANGED: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
[Ashjre'thul, Crossbow of Smiting]: 75<br />
[The Eye of Divinity]: 71<br />
[Tome of Tranquilizing Shot]: 0<br />
[Ancient Petrified Leaf]: 71<br />
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
Auctionator<br />
BagBrother<br />
Bagnon<br />
BetterVendorPrice<br />
ccc<br />
CEPGP<br />
ClassicLootAssistant<br />
DebuffMonitor<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
EavesDrop<br />
ElvUI_ShadowSpellPower<br />
Guidelime<br />
Guidelime_Sage<br />
Memoria<br />
MissingBuffs<br />
ModernQuestWatch<br />
NeverLocky<br />
QuestLogEx<br />
RaidInviter<br />
ThreatClassic2<br />
VortexChat<br />
WeakAuras<br />
WeaponSwingTimer<br />
AddOnSkins<br />
ElvUI<br />
SpeedyAutoLoot<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Issue resolved in 1.12.12.
