### ISSUE TITLE
[Bug] Lua error when attempring to distribution loot 

### ISSUE THREAD

**Issue by Draugarnir** [Alumian/CEPGP-Retail#246]
I was in ZG yesterday as masterlooter and when I hit the boss corpse and try to clic on red square I got lua error - see screenshot. I cannot use this addon because of that and no windows appeared after clicking on red square. I had to disable addon and distribute loot manually.

Below is debug info from this day. 

Do you have any idea what was wrong?

<details><summary>Debug Info</summary><br />
Version: 1.12.12 Release<br />
Locale: enUS<br />
Poll Rate: 0.0001<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 50<br />
Base GP Decay Factor: true<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 100<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
Standby EP Whisper Keyphrase: bench<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: true<br />
Minimum EP: false, 50<br />
Reporting Channel: Raid<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 3<br />
Allow Force Sync: true, Warchief<br />
Hide Keyphrase Alternatives: False<br /><br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Vaelastrasz the Corrupt: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Bloodlord Mandokir: True<br />
Renataki: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
The Edge of Madness: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Firemaw: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
Baron Geddon: True<br />
High Priestess Arlokk: True<br />
Gri'lek: True<br />
The Twin Emperors: True<br />
Jin'do the Hexxer: True<br />
Gluth: True<br />
Viscidus: True<br />
Sapphiron: True<br />
Moam: True<br />
Emeriss: True<br />
Ouro: True<br />
Lord Kazzak: True<br />
Shazzrah: True<br />
Battleguard Sartura: True<br />
Lethon: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Kurinnaxx: True<br />
Hakkar: True<br />
Maexxna: True<br />
Ragnaros: True<br />
Broodlord Lashlayer: True<br />
The Four Horsemen: True<br />
Ysondre: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Sulfuron Harbinger: True<br />
Gahz'ranka: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 1<br />
Ragnaros: 8<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Silithid Royalty: 13<br />
Kurinnaxx: 3<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 17<br />
High Priestess Mar'li: 1<br />
Twin Emperors: 17<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 1<br />
Gehennas: 5<br />
Taerar: 20<br />
Vaelastrasz the Corrupt: 10<br />
High Priest Thekal: 1<br />
Noth the Plaguebringer: 15<br />
Bloodlord Mandokir: 2<br />
Moam: 3<br />
The Prophet Skeram: 13<br />
Sapphiron: 23<br />
C'Thun: 20<br />
General Rajaxx: 3<br />
The Edge of Madness: 2<br />
Princess Huhuran: 15<br />
Thaddius: 20<br />
Loatheb: 20<br />
The Silithid Royalty: 13<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 10<br />
Firemaw: 10<br />
Heigan the Unclean: 17<br />
Flamegor: 10<br />
Azuregos: 20<br />
Doom Lord Kazzak: 7<br />
Baron Geddon: 5<br />
Viscidus: 15<br />
Gri'lek: 2<br />
The Twin Emperors: 17<br />
Jin'do the Hexxer: 2<br />
Gothik the Harvester: 17<br />
Ouro: 15<br />
Gluth: 17<br />
Onyxia: 10<br />
Emeriss: 20<br />
Lord Kazzak: 20<br />
Shazzrah: 5<br />
Ossirian the Unscarred: 4<br />
Battleguard Sartura: 13<br />
Lethon: 20<br />
Kel'Thuzad: 25<br />
Nefarian: 15<br />
Fankriss the Unyielding: 13<br />
Lucifron: 5<br />
Anub'Rekhan: 15<br />
Hazza'rah: 2<br />
Ysondre: 20<br />
Maexxna: 20<br />
Sulfuron Harbinger: 5<br />
Hakkar: 5<br />
Broodlord Lashlayer: 10<br />
The Four Horsemen: 21<br />
Gahz'ranka: 2<br />
Grobbulus: 16<br />
Instructor Razuvious: 15<br />
Razorgore the Untamed: 10<br />
Magmadar: 5<br />
Patchwerk: 15<br />
High Priestess Arlokk: 1<br />
Renataki: 2<br />
Chromaggus: 10<br />
Garr: 5<br />
</details>
<details><summary>Loot Button Configuration</summary>
Loot Button 1<br />State: Enabled<br />Button Text: BiS<br />Discount: 0%<br />Keyphrase Alternative: need<br /><br />Loot Button 2<br />State: Enabled<br />Button Text: Minor upg.<br />Discount: 20%<br />Keyphrase Alternative: minor<br /><br />Loot Button 3<br />State: Enabled<br />Button Text: Alt / PvP / Off<br />Discount: 40%<br />Keyphrase Alternative: alt<br /><br />Loot Button 4<br />State: Enabled<br />Button Text: ZG<br />Discount: 90%<br />Keyphrase Alternative: zg<br /><br /></details><details><summary>Standby Guild Ranks</summary>
Warchief: False<br />
General: False<br />
Centurion: False<br />
Grunt: False<br />
Peon: False<br />
Alt: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2.5<br />
NECK: 1<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 2<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
THROWN: 0.5<br />
FEET: 0.75<br />
RANGED: 0.75<br />
EXCEPTION: 1<br />
WEAPONOFFHAND: 1<br />
TRINKET: 1.25<br />
WAND: 0.5<br />
LEGS: 1<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
FINGER: 1<br />
RELIC: 0.5<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
[Primal Hakkari Girdle]: 11<br />
[Head of Nefarian]: 0<br />
[Primal Hakkari Bindings]: 11<br />
[Primal Hakkari Aegis]: 11<br />
[Primal Hakkari Tabard]: 11<br />
[Primal Hakkari Armsplint]: 11<br />
[Heart of Hakkar]: 28<br />
[Primal Hakkari Stanchion]: 11<br />
[Onyxia Hide Backpack]: 9<br />
[Primal Hakkari Sash]: 11<br />
[Primal Hakkari Shawl]: 11<br />
[Primal Hakkari Idol]: 11<br />
[Head of Onyxia]: 30<br />
[Primal Hakkari Kossack]: 11<br />
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
CEPGP<br />
Decursive<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
ExRT<br />
GatherLite<br />
GatherMate2<br />
Leatrix_Maps<br />
Leatrix_Plus<br />
MapCoords<br />
NovaWorldBuffs<br />
OmniCC<br />
Stubby<br />
VendorPrice<br />
WeakAuras<br />
WideQuestLog<br />
CharacterStatsClassic<br />
TradeSkillMaster<br />
Tukui<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

<img width="527" alt="Screenshot 2020-04-16 20 05 40" src="https://user-images.githubusercontent.com/63852283/79563972-113b8680-80ae-11ea-8450-bfecb187c5a9.png">

**Comment by Alumian** [comment]
Could you please go to your CEPGP addon folder and upload the file Utility.lua for me?

**Comment by Draugarnir** [comment]
[Utility.lua-before -update.zip](https://github.com/Alumian/CEPGP-Retail/files/4492682/Utility.lua-before.-update.zip)

This is the file before I updated addon from yesterday's ZG. I tried update addon after ZG but I had no chance to try it since if it is ok or not.

**Comment by Alumian** [comment]
So is this the file that you were using when the error occurred?

**Comment by Draugarnir** [comment]
Correct, this is the file I was using while error occured.

**Comment by Alumian** [comment]
And what version of the addon were you using at the time?

**Comment by Draugarnir** [comment]
1.12.10 for sure. I updated to the last version 1.12.12 after that but did not have chance to try if it is ok.

**Comment by Alumian** [comment]
Ok then I'm going to close this bug report. If the issue persists **and it is the same **issue**, please comment here and I will reopen it.
