### ISSUE TITLE
Show/Hide ranks on Guild EPGP page [Request]

### ISSUE THREAD

**Issue by infernojack** [Alumian/CEPGP-Retail#249]
With the new addition of alt integration, when sorting by Priority, Alts fill the list and make quickly seeing who has high priority difficult.  Is a feature possible that lets only certain ranks show on that list?  My guild awards EP for alts but does not charge GP to them.  EX: of the top 16 characters when sorting by PR, only 9 are actual mains.

**Comment by MojoOli** [comment]
I programmed the feature already because it was bothering me as well. Can make a push request tomorrow.

**Comment by Alumian** [comment]
Implemented in 1.13.0.
