### ISSUE TITLE
[Request] Localization

### ISSUE THREAD

**Issue by NooBiToo** [Alumian/CEPGP-Retail#25]
Hello!
Could you add files for translation so that I can translate the addon into my language? and also help you in localization

**Comment by hbjose** [comment]
Depends on the language of @NooBiToo i would help too. My native language is german.

**Comment by Alumian** [comment]
Hey guys, sorry for the radio silence on this one. I have started implementing Russian localisation and it is available in the latest beta on the CEPGP discord.

**Comment by Alumian** [comment]
Localisation has been implemented in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.7.
If you would like your language added, please submit a new ticket and list your specific language.
