### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by YanniTV** [Alumian/CEPGP-Retail#250]
When I click the "options" button, the Interface Options screen pops up. 

Below is the Error:

Date: 2020-04-20 00:00:41
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\CEPGP\Utility.lua line 1728:
   attempt to concatenate global 'MOD' (a nil value)
Debug:
   [C]: ?
   CEPGP\Utility.lua:1728: CEPGP_getDebugInfo()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [C]: Show()
   CEPGP\Core.lua:387: ?()
   ..\FrameXML\ChatFrame.lua:4690: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4351: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4387: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdiBags, vv1.9.17-classic
  AdvancedInterfaceOptions, v1.3.4
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasDungeonLocs, vv1.47.00.11303.00
  AtlasLootClassic, vv1.5.0
  AtlasLootClassicData, vv1.5.0
  AtlasLootClassicDungeonsAndRaids, vv1.5.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bagnon, v8.3.5
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CallbackHandler10, v
  CEPGP, v
  ClassicGuildBank, v1.3
  ClickLinks, v1.0.8
  DBMCore, v1.13.43
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.2.1
  GatherMate2, v1.45.5
  GroupCalendar, v
  honorspy, v1.7.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.58
  LeatrixPlus, v1.13.58
  LibStub, v
  MoveAnything, v17.1.0
  Questie, v5.10.1
  ShadowedUnitFrames, vv4.2.3-Classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpeedyAutoLoot, v2.0.25
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.3.1
  TitanClassic, v1.2.2.11304
  TitanClassicAmmo, v1.2.2.11304
  TitanClassicBag, v1.2.2.11304
  TitanClassicClock, v1.2.2.11304
  TitanClassicGold, v1.2.2.11304
  TitanClassicLocation, v1.2.2.11304
  TitanClassicLootType, v1.2.2.11304
  TitanClassicPerformance, v1.2.2.11304
  TitanClassicRegen, v1.2.2.11304
  TitanClassicRepair, v1.2.2.11304
  TitanClassicVolume, v1.2.2.11304
  TitanClassicXP, v1.2.2.11304
  TradeSkillMaster, vv4.9.32
  TradeSkillMasterAppHelper, vv4.0.8
  VendorPrice, v1.3.5
  WeakAuras, v2.17.2
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=813)

**Comment by Alumian** [comment]
Type /cep debug and include that in your bug report please.

**Comment by YanniTV** [comment]
there is nothing showing in the window when I type /cep debug.

I am getting the string above upon log in.

**Comment by Alumian** [comment]
It's this your first time running CEPGP?

**Comment by YanniTV** [comment]
yes it is. So my apologies for the ignorance haha.

**Comment by Alumian** [comment]
No no not at all haha. I kind of screwed up in the last version which has caused this error. 
Type `/run CEPGP_force_sync_rank = 1; CHANNEL = "Guild";`, reload your UI and it should work.

**Comment by YanniTV** [comment]
that seemed to do it! Thank you for the quick response :D

**Comment by Alumian** [comment]
You're welcome :)
