### ISSUE TITLE
Sync merge and re-order TRAFFIC when multiple loot officers

### ISSUE THREAD

**Issue by nickedgar** [Alumian/CEPGP-Retail#251]
Our guild has two main loot officers who are not always online at the same time.

As a result our TRAFFIC may be missing entries depending on who was logged in at the time the traffic was sent.

This makes manually auditing and/or viewing TRAFFIC history problematic, with occasional raid awards missing depending who was online and when.

For example, we have done 2x2 ZG splits but only 3 are showing in TRAFFIC right now. Without comparing TRAFFIC from individual loot officers CEPGP.lua files I can't see if we missed awarding one of the ZG's or not.

An option to keep the guilds TRAFFIC synced and ordered by timestamp would be great.

**Comment by Alumian** [comment]
Thanks. I do plan to add this feature in the next major update anyway.
