### ISSUE TITLE
[Request] Time & Date stamps in EPGP traffic.

### ISSUE THREAD

**Issue by Droolster** [Alumian/CEPGP-Retail#255]
It would help when dealing with disputes over numbers and to generally reduce the number of queries from the raid teams if everyone could see the date and time that an item was awarded. Recording the server time would be the best option.

**Comment by Alumian** [comment]
Hi Droolster,
This feature is already available. If you put the cursor on a traffic entry it will show a tooltip with the time and date that the entry was logged.
