### ISSUE TITLE
[REQUEST] Offspec support

### ISSUE THREAD

**Issue by Anilusion** [Alumian/CEPGP-Retail#26]
Hey, I would love to see some kind of support for distributing offspec items. What I am looking for is a different whisper message than !need (!offspec perhaps?), and an optional price modifier for offspec items. We want offspec items to cost 50% of the item price, but they should only be given if nobody needs it for mainspec.

Right now the workaround for us is to start mainspec bidding, give people 10-15 seconds, and if nobody wants it for mainspec we let people bid for offspec. After the item is given out, we need to manually refund 50% of the gp cost to the winner. It works, but it is a lot of manual work that could be automated.

**Comment by jackie0100** [comment]
I would LOVE to see this feature aswell!

**Comment by Alumian** [comment]
Hi guys,
Sure I can work this in. However, I do have a bit of a queue at the moment for feature requests so it may take me a little while to catch up to this one. But yes, I'm happy to implement this feature.

**Comment by jackie0100** [comment]
> Hi guys,
> Sure I can work this in. However, I do have a bit of a queue at the moment for feature requests so it may take me a little while to catch up to this one. But yes, I'm happy to implement this feature.

I'm pretty rusty with my LUA but do you guys allow Pull requests and others to add features, or is this a project your guys prefer to work on alone? :)

**Comment by Alumian** [comment]
Hey Jackie, thanks for the offer but I'm thinking that I'll work this feature in with #23. So for this one it might be easier if I just tackle this myself :)

**Comment by Alumian** [comment]
Closing this request. Please keep an eye on #23 for updates.
