### ISSUE TITLE
[Bug] error during loot distribution via GUI

### ISSUE THREAD

**Issue by palm0n0** [Alumian/CEPGP-Retail#260]
**Errormessage:**
```
Message: Interface\AddOns\CEPGP\Handlers.lua:124: bad argument #1 to 'lower' (string expected, got nil)
Time: Sun May 17 17:10:47 2020
Count: 4
Stack: Interface\AddOns\CEPGP\Handlers.lua:124: bad argument #1 to 'lower' (string expected, got nil)
[C]: in function `lower'
Interface\AddOns\CEPGP\Handlers.lua:124: in function `CEPGP_handleComms'
Interface\AddOns\CEPGP\Communications.lua:756: in function `CEPGP_IncAddonMsg'
Interface\AddOns\CEPGP\Core.lua:305: in function `CEPGP_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = nil
(*temporary) = "string expected, got nil"
```

**Issue**
Almost every time that loot is distributed, I get the above error in a lua error frame.
The error does not impact the functionality, I can still need/pass on the item as expected.

I would say the error pops up about 80% of the time when loot is distributed but I'm not certain if any specific action is triggering it.
It get the feeling it could be related to hovering over the item's icon to see the item statistics, but I can't confirm that.

Based on your code line 124 and the error message, the error is an empty chat message.
As such I've tried with disabling Leatrix Plus to make sure it's not messing with the chat stuff, but this did not change anything.
> elseif event == "CHAT_MSG_WHISPER" and string.lower(arg1) == "!info" then

**DEBUG:**
<details><summary>Debug Info</summary><br />
Version: 1.12.14 Release<br />
Locale: enUS<br />
Poll Rate: 0.0001<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x10<br />Base GP: 950<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 100<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: true<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: true, 950<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 0<br />
Allow Force Sync: false, Guild Master<br />
Hide Keyphrase Alternatives: False<br /><br /><details><summary>Auto EP</summary>
High Priestess Jeklik: False<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: False<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: False<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: False<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
The Edge of Madness: False<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Gluth: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
High Priestess Arlokk: False<br />
Baron Geddon: True<br />
Sulfuron Harbinger: True<br />
Gri'lek: True<br />
Bloodlord Mandokir: False<br />
Jin'do the Hexxer: False<br />
The Twin Emperors: True<br />
Vaelastrasz the Corrupt: True<br />
Firemaw: True<br />
Gahz'ranka: False<br />
Emeriss: True<br />
Shazzrah: True<br />
Onyxia: True<br />
Battleguard Sartura: True<br />
Ouro: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Kurinnaxx: True<br />
Viscidus: True<br />
Maexxna: True<br />
Broodlord Lashlayer: True<br />
Hakkar: False<br />
The Four Horsemen: True<br />
Ragnaros: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Renataki: True<br />
Sapphiron: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 0<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Silithid Royalty: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 50<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 0<br />
Twin Emperors: 10<br />
Majordomo Executus: 50<br />
High Priest Venoxis: 0<br />
Gehennas: 50<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 0<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 100<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
The Edge of Madness: 0<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
The Silithid Royalty: 10<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 100<br />
Gluth: 12<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
High Priestess Arlokk: 0<br />
Baron Geddon: 50<br />
Sulfuron Harbinger: 50<br />
Gri'lek: 2<br />
Bloodlord Mandokir: 0<br />
Jin'do the Hexxer: 0<br />
The Twin Emperors: 10<br />
Vaelastrasz the Corrupt: 100<br />
Firemaw: 100<br />
Gahz'ranka: 0<br />
Emeriss: 7<br />
Shazzrah: 50<br />
Onyxia: 50<br />
Battleguard Sartura: 10<br />
Ouro: 10<br />
Kel'Thuzad: 15<br />
Nefarian: 200<br />
Fankriss the Unyielding: 10<br />
Lucifron: 50<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Kurinnaxx: 3<br />
Viscidus: 10<br />
Maexxna: 15<br />
Broodlord Lashlayer: 100<br />
Hakkar: 0<br />
The Four Horsemen: 15<br />
Ragnaros: 70<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 100<br />
Magmadar: 50<br />
Patchwerk: 12<br />
Renataki: 2<br />
Sapphiron: 15<br />
Chromaggus: 150<br />
Garr: 50<br />
</details>
<details><summary>Loot Button Configuration</summary>
Loot Button 1<br />State: Enabled<br />Button Text: Main Spec<br />Discount: 0%<br />Keyphrase Alternative: Need<br /><br />Loot Button 2<br />State: Enabled<br />Button Text: Off Spec<br />Discount: 0%<br />Keyphrase Alternative: Greed<br /><br />Loot Button 3<br />State: Disabled<br />Button Text: Disenchant<br />Discount: 0%<br />Keyphrase Alternative: Disenchant<br /><br />Loot Button 4<br />State: Disabled<br />Button Text: Minor Upgrade<br />Discount: 0%<br />Keyphrase Alternative: Minor<br /><br /></details><details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
Loot Officer: False<br />
Officer: False<br />
Member: False<br />
Initiate: False<br />
Alt: False<br />
Inactive: False<br />
Pleb: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 1.5<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
THROWN: 0.5<br />
FEET: 0.75<br />
RELIC: 0.5<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 1<br />
TRINKET: 0.75<br />
WAND: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
LEGS: 1<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
RANGED: 1<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
[Cloak of the Shrouded Mists]: 300<br />
[Taut Dragonhide Gloves]: 490<br />
[Pure Elementium Band]: 390<br />
[Ring of Spell Power]: 250<br />
[Circle of Applied Force]: 300<br />
[Bracers of Arcane Accuracy]: 370<br />
[Chromatically Tempered Sword]: 700<br />
[Robe of Volatile Power]: 610<br />
[Striker's Mark]: 380<br />
[Bloodfang Pants]: 540<br />
[Bloodfang Spaulders]: 410<br />
[Head of Nefarian]: 480<br />
[Dragonstalker's Bracers]: 270<br />
[Bloodfang Chestpiece]: 540<br />
[Styleen's Impeding Scarab]: 460<br />
[Wild Growth Spaulders]: 420<br />
[Dragonstalker's Gauntlets]: 410<br />
[Drake Fang Talisman]: 570<br />
[Nemesis Leggings]: 540<br />
[Wristguards of Stability]: 230<br />
[Lok'amir il Romathis]: 1160<br />
[Perdition's Blade]: 650<br />
[Bloodfang Gloves]: 410<br />
[Core Hound Tooth]: 580<br />
[Drake Talon Pauldrons]: 460<br />
[Band of Accuria]: 420<br />
[Rejuvenating Gem]: 570<br />
[Handguards of Transcendence]: 410<br />
[Mish'undare, Circlet of the Mind Flayer]: 960<br />
[Heavy Dark Iron Ring]: 250<br />
[Netherwind Gloves]: 410<br />
[Cauterizing Band]: 350<br />
[Cold Snap]: 390<br />
[Elementium Reinforced Bulwark]: 230<br />
[Dragon's Blood Cape]: 280<br />
[Doom's Edge]: 580<br />
[Azuresong Mageblade]: 600<br />
[Dragonstalker's Spaulders]: 410<br />
[Mind Quickening Gem]: 470<br />
[Bloodfang Bracers]: 270<br />
[Bloodfang Belt]: 410<br />
[Mantle of the Blackwing Cabal]: 550<br />
[Dragon's Touch]: 440<br />
[Empowered Leggings]: 650<br />
[Maladath, Runed Blade of the Black Flight]: 800<br />
[Staff of the Shadow Flame]: 1300<br />
[Head of Nefarian]: 480<br />
[Onslaught Girdle]: 490<br />
[Netherwind Pants]: 540<br />
[Quick Strike Ring]: 250<br />
[Boots of the Shadow Flame]: 580<br />
[Chromatic Boots]: 490<br />
[Band of Dark Dominion]: 260<br />
[Bloodfang Hood]: 540<br />
[Puissant Cape]: 260<br />
[Boots of Pure Thought]: 400<br />
[Empyrean Demolisher]: 630<br />
[Choker of the Fire Lord]: 420<br />
[Brutality Blade]: 580<br />
[Ringo's Blizzard Boots]: 420<br />
[Flameguard Gauntlets]: 390<br />
[Head of Onyxia]: 460<br />
[Ring of Blackrock]: 300<br />
[Lifegiving Gem]: 470<br />
[Belt of Transcendence]: 410<br />
[Fel Infused Leggings]: 560<br />
[Dragonstalker's Breastplate]: 540<br />
[Ebony Flame Gloves]: 460<br />
[Bloodfang Boots]: 410<br />
[Dragonstalker's Greaves]: 410<br />
[Bindings of Transcendence]: 270<br />
[Boots of Transcendence]: 410<br />
[Prestor's Talisman of Connivery]: 480<br />
[Talisman of Ephemeral Power]: 460<br />
[Stormrage Bracers]: 270<br />
[Legguards of the Fallen Crusader]: 610<br />
[Taut Dragonhide Shoulderpads]: 490<br />
[Snowblind Shoes]: 390<br />
[Firemaw's Clutch]: 460<br />
[Band of Forced Concentration]: 370<br />
[Neltharion's Tear]: 720<br />
[Mana Igniting Cord]: 420<br />
[Stormrage Handguards]: 410<br />
[Dragonstalker's Belt]: 410<br />
[Crul'shorukh, Edge of Chaos]: 780<br />
[Claw of Chromaggus]: 700<br />
[Nemesis Belt]: 410<br />
[Cloak of Firemaw]: 300<br />
[Shroud of Pure Thought]: 300<br />
[Crystal Adorned Crown]: 510<br />
[Amberseal Keeper]: 750<br />
[Ashjre'thul, Crossbow of Smiting]: 560<br />
[Ashkandi, Greatsword of the Brotherhood]: 900<br />
[Cloak of Draconic Might]: 260<br />
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
Auctionator<br />
CEPGP<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
Details<br />
Details_TinyThreat<br />
Dominos<br />
Dominos_Cast<br />
Dominos_Progress<br />
Dominos_Roll<br />
FishingBuddy<br />
ItemRack<br />
Leatrix_Plus<br />
LunaUnitFrames<br />
NovaWorldBuffs<br />
Skillet-Classic<br />
WeakAuras<br />
WeaponSwingTimer<br />
CharacterStatsClassic<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Resolved in 1.12.15.
