### ISSUE TITLE
[Bug] !infoguild not working properly

### ISSUE THREAD

**Issue by DevineLykan** [Alumian/CEPGP-Retail#261]
![Untitled](https://user-images.githubusercontent.com/46081455/82392939-040f1000-9a3d-11ea-8fd9-ec8d5806b7ff.png)
**The Error**
No Error

**Describe the bug**
The command replies the same to every person check attached picture. 

**To Reproduce**
just do a a !infoguild to any rank who has access to officer note and the addon running.

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.14 Release<br />
Locale: enUS<br />
Poll Rate: 0.0001<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1<br />
Base GP Decay Factor: true<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 25<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
Standby EP Whisper Keyphrase: !standby<br />
Auto Pass on Ineligible Items: true<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: true, 250<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 4<br />
Allow Force Sync: true, Leader<br />
Hide Keyphrase Alternatives: False<br /><br /><details><summary>Auto EP</summary>
High Priestess Jeklik: False<br />
Gothik the Harvester: True<br />
Buru the Gorger: False<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: False<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: False<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: False<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: False<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: False<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: False<br />
The Edge of Madness: False<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: False<br />
Ebonroc: True<br />
The Twin Emperors: True<br />
Heigan the Unclean: True<br />
Bloodlord Mandokir: False<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
Baron Geddon: True<br />
High Priestess Arlokk: False<br />
Gri'lek: True<br />
Vaelastrasz the Corrupt: True<br />
Jin'do the Hexxer: False<br />
Renataki: True<br />
Azuregos: True<br />
Firemaw: True<br />
Ragnaros: True<br />
Emeriss: True<br />
Shazzrah: True<br />
Lord Kazzak: True<br />
Gluth: True<br />
Battleguard Sartura: True<br />
Ouro: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Kurinnaxx: False<br />
Hakkar: False<br />
Maexxna: True<br />
Sapphiron: True<br />
Broodlord Lashlayer: True<br />
The Four Horsemen: True<br />
Viscidus: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Sulfuron Harbinger: True<br />
Gahz'ranka: False<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 0<br />
Gothik the Harvester: 20<br />
Buru the Gorger: 0<br />
Wushoolay: 20<br />
Silithid Royalty: 20<br />
Ossirian the Unscarred: 0<br />
Golemagg the Incinerator: 10<br />
Grand Widow Faerlina: 20<br />
High Priestess Mar'li: 0<br />
Twin Emperors: 20<br />
Majordomo Executus: 10<br />
High Priest Venoxis: 0<br />
Gehennas: 10<br />
Taerar: 20<br />
Ysondre: 20<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 0<br />
Noth the Plaguebringer: 20<br />
Lethon: 20<br />
Moam: 0<br />
The Prophet Skeram: 20<br />
Flamegor: 10<br />
C'Thun: 20<br />
General Rajaxx: 0<br />
The Edge of Madness: 0<br />
Princess Huhuran: 20<br />
Thaddius: 20<br />
Loatheb: 20<br />
The Silithid Royalty: 20<br />
Ayamiss the Hunter: 0<br />
Ebonroc: 10<br />
The Twin Emperors: 20<br />
Heigan the Unclean: 20<br />
Bloodlord Mandokir: 0<br />
Onyxia: 10<br />
Doom Lord Kazzak: 7<br />
Baron Geddon: 10<br />
High Priestess Arlokk: 0<br />
Gri'lek: 20<br />
Vaelastrasz the Corrupt: 10<br />
Jin'do the Hexxer: 0<br />
Renataki: 20<br />
Azuregos: 20<br />
Firemaw: 10<br />
Ragnaros: 10<br />
Emeriss: 20<br />
Shazzrah: 10<br />
Lord Kazzak: 20<br />
Gluth: 20<br />
Battleguard Sartura: 20<br />
Ouro: 20<br />
Kel'Thuzad: 20<br />
Nefarian: 10<br />
Fankriss the Unyielding: 20<br />
Lucifron: 10<br />
Anub'Rekhan: 20<br />
Hazza'rah: 20<br />
Kurinnaxx: 0<br />
Hakkar: 0<br />
Maexxna: 20<br />
Sapphiron: 20<br />
Broodlord Lashlayer: 10<br />
The Four Horsemen: 20<br />
Viscidus: 20<br />
Grobbulus: 20<br />
Instructor Razuvious: 20<br />
Razorgore the Untamed: 10<br />
Magmadar: 10<br />
Patchwerk: 20<br />
Sulfuron Harbinger: 10<br />
Gahz'ranka: 0<br />
Chromaggus: 10<br />
Garr: 10<br />
</details>
<details><summary>Loot Button Configuration</summary>
Loot Button 1<br />State: Enabled<br />Button Text: Main Spec<br />Discount: 0%<br />Keyphrase Alternative: MS<br /><br />Loot Button 2<br />State: Enabled<br />Button Text: Off Spec<br />Discount: 100%<br />Keyphrase Alternative: OS<br /><br />Loot Button 3<br />State: Enabled<br />Button Text: Minor Upgrade<br />Discount: 50%<br />Keyphrase Alternative: Minor<br /><br />Loot Button 4<br />State: Disabled<br />Button Text: Alt<br />Discount: 100%<br />Keyphrase Alternative: Alt<br /><br /></details><details><summary>Standby Guild Ranks</summary>
Leader: False<br />
Deputy Leader: False<br />
Officer: False<br />
Admin: False<br />
Core Raider: False<br />
Raider: False<br />
Casual Raider: False<br />
Trial: False<br />
Social: False<br />
Alt: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
THROWN: 0.5<br />
FEET: 0.75<br />
RELIC: 0.5<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 0.5<br />
TRINKET: 0.75<br />
WAND: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
LEGS: 1<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
RANGED: 0.5<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
Auctionator<br />
Capping<br />
CEPGP<br />
ClassicGuildBank<br />
Details<br />
Details_EncounterDetails<br />
Details_RaidCheck<br />
Details_Streamer<br />
Details_TinyThreat<br />
Details_Vanguard<br />
ExRT<br />
ExtendedCharacterStats<br />
GatherMate2<br />
ItemRack<br />
ItemTooltipProfessionIcons<br />
MikScrollingBattleText<br />
Necrosis<br />
OmniCC<br />
oRA3<br />
SexyMap<br />
ElvUI<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Hi Devine, thanks for submitting your bug report. Could you just clarify for me, is that you messaging yourself in the screenshot?

**Comment by laemoy** [comment]
same problem. i messaging myself !infoguild several times and give me ep 0 /gp (min gp i set in guild) / pr 0 / pr rank in guild (ramdon: 18 19 19 20).

also i did messaging other officer who has the addon or can read officer note, same result.

**Comment by Alumian** [comment]
Ok thanks I was going to ask about officer note visibility. I'll look into it.

**Comment by Alumian** [comment]
Fixed in the next update.

**Comment by Alumian** [comment]
Resolved.
