### ISSUE TITLE
[Bug]Error: Could not process changes to EPGP for "name"

### ISSUE THREAD

**Issue by Faergas** [Alumian/CEPGP-Retail#262]
**The Error**
What was the error message you received?
CEPGP: Error - Could not process changes to EPGP for Geitmage.
CEPGP: Error - Interaface\AddOns\CEPGP\Utility.lua:2664: attempt to index field '?' (a nil value)

**Describe the bug**
The addon won't allow me to change the EP nor GP for a player in guild named Geitmage. He is the only one in guild who I cannot give points. Manually through officer notes will works fine though, and the decay also works.

**To Reproduce**
How can this bug be reproduced?
By adding EP or GP to the player Geitmage.

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.
<details><summary>Debug Info</summary><br />
Version: 1.12.14 Release<br />
Locale: enUS<br />
Poll Rate: 0.0001<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 20<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 100<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: Raid<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 4<br />
Allow Force Sync: false, GM<br />
Hide Keyphrase Alternatives: False<br /><br /><details><summary>Auto EP</summary>
High Priestess Jeklik: False<br />
Ragnaros: True<br />
Buru the Gorger: False<br />
Ossirian the Unscarred: False<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: False<br />
Majordomo Executus: True<br />
High Priest Venoxis: False<br />
Gehennas: True<br />
Taerar: True<br />
Vaelastrasz the Corrupt: True<br />
High Priest Thekal: False<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: False<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: False<br />
The Edge of Madness: False<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: False<br />
Ebonroc: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Gothik the Harvester: True<br />
Baron Geddon: True<br />
Gahz'ranka: False<br />
High Priestess Arlokk: False<br />
Onyxia: False<br />
Jin'do the Hexxer: False<br />
Gluth: True<br />
Viscidus: True<br />
Firemaw: True<br />
Shazzrah: True<br />
Sulfuron Harbinger: True<br />
Battleguard Sartura: True<br />
Emeriss: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Kurinnaxx: False<br />
Ouro: True<br />
Ysondre: True<br />
Maexxna: True<br />
Hakkar: False<br />
Broodlord Lashlayer: True<br />
The Four Horsemen: True<br />
The Twin Emperors: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Bloodlord Mandokir: False<br />
Sapphiron: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Kurinnaxx: 3<br />
Golemagg the Incinerator: 4<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 8<br />
High Priest Venoxis: 2<br />
Gehennas: 4<br />
Taerar: 7<br />
Ysondre: 7<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Sapphiron: 15<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
The Edge of Madness: 2<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Ouro: 10<br />
The Silithid Royalty: 10<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 12<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Gahz'ranka: 2<br />
Baron Geddon: 4<br />
High Priestess Arlokk: 2<br />
Viscidus: 10<br />
Loatheb: 15<br />
Jin'do the Hexxer: 2<br />
Ragnaros: 10<br />
Onyxia: 10<br />
Shazzrah: 4<br />
Bloodlord Mandokir: 2<br />
Battleguard Sartura: 10<br />
Hakkar: 3<br />
Kel'Thuzad: 15<br />
Nefarian: 16<br />
Fankriss the Unyielding: 10<br />
Lucifron: 4<br />
Anub'Rekhan: 12<br />
Ossirian the Unscarred: 4<br />
Razorgore the Untamed: 12<br />
Vaelastrasz the Corrupt: 12<br />
Firemaw: 12<br />
Broodlord Lashlayer: 12<br />
Maexxna: 15<br />
The Four Horsemen: 15<br />
Gluth: 12<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 4<br />
Patchwerk: 12<br />
Flamegor: 12<br />
Sulfuron Harbinger: 4<br />
Chromaggus: 12<br />
Garr: 4<br />
</details>
<details><summary>Loot Button Configuration</summary>
Loot Button 1<br />State: Enabled<br />Button Text: Need (100%)<br />Discount: 0%<br />Keyphrase Alternative: Need (100%)<br /><br />Loot Button 2<br />State: Enabled<br />Button Text: Greed (60%)<br />Discount: 60%<br />Keyphrase Alternative: Greed (60%)<br /><br />Loot Button 3<br />State: Enabled<br />Button Text: Minor (30%)<br />Discount: 70%<br />Keyphrase Alternative: Minor (30%)<br /><br />Loot Button 4<br />State: Enabled<br />Button Text: Off-Spec (0%)<br />Discount: 0%<br />Keyphrase Alternative: Off-Spec (0%)<br /><br /></details><details><summary>Standby Guild Ranks</summary>
GM: True<br />
Co-GM: True<br />
Officer: True<br />
Class Leader: True<br />
Officer Alt: True<br />
Raider: True<br />
Member: True<br />
Alt: False<br />
Trial: False<br />
Inactive: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
RANGED: 2<br />
THROWN: 0.5<br />
FEET: 0.75<br />
RELIC: 0.5<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 0.5<br />
TRINKET: 0.75<br />
WAND: 0.5<br />
CLOAK: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
LEGS: 1<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
AuctionFaster<br />
BetterVendorPrice<br />
CEPGP<br />
ClassicAuraDurations<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
Dominos<br />
Dominos_Cast<br />
Dominos_Encounter<br />
Dominos_Progress<br />
Dominos_Roll<br />
FiveSecondRule<br />
GTFO<br />
HealCommClassic<br />
honorspy<br />
ItemRack<br />
LayerHopper<br />
LibHealComm-4.0<br />
MikScrollingBattleText<br />
MonolithDKP<br />
NovaWorldBuffs<br />
OmniCC<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
ShadowedUnitFrames<br />
SimpleMap<br />
Stubby<br />
!Swatter<br />
TotemTimers<br />
CharacterStatsClassic<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Hi Faergas,
I just released version 1.12.15 which contained a change to the import feature. Could you please download that version and let me know if the issue persists?

Thanks

**Comment by Faergas** [comment]
Hi Alumian,
Unfortunately the error is still occuring. I've downloaded version 1.12.16 and it is also not working. Somehow the name "Geitmage" is not working.

Thanks!

**Comment by Faergas** [comment]
Hi again Alumian,
Now it's working! I found the reason behind. It was because his character was linked as an alt.

Thank you for your time spent on this!

**Comment by Alumian** [comment]
> Hi again Alumian,
> Now it's working! I found the reason behind. It was because his character was linked as an alt.
> 
> Thank you for your time spent on this!

Awesome, thanks for the update. Glad it's working now 🙂
