### ISSUE TITLE
[Request] Report loot distribution list to channel

### ISSUE THREAD

**Issue by Andrioden** [Alumian/CEPGP-Retail#267]
**Problem**
We are atm trying out changes to our loot system, part of that is using secret bidding using 4 different treshold-buttons. On top of that we have some semi-complex logic attached to these (ie role priority only for 100% bid, using roll on 9% and 0%).

This works great, but gives us two problems on transparency:
1. No-one can see who is bidding what. This increases the chance the master looter does a mistake (since our system is semi-complex) and increases the needed trust.
2. The needs are not secret for the masterlooter himself on items he need. This can be countered by having the master loot need first. But the rest of the raid still has to trust he does this.

**Solution**
So, trust "solves" this task, and I understand if you dont want to implement it, but i ask anyway.

Is is possible to add an button that reports to raid chat the current list, as seen in the screenshot. This solves problem 1. And additionally it reports the order people clicked a button, this solves problem 2. Keep in mind, it would still be nice that its sorted by PR.

![image](https://user-images.githubusercontent.com/393376/85236154-764b8980-b41b-11ea-93a2-75e9058659d7.png)

This screenshot would report:
/raid (2) Archtastic - Raider - Main/Alt 9% - PR 1.16 - Roll 72
/raid (1) Lizter - Raider - Main/Alt 9% - PR 0.93 - Roll 69

Where the (1) and (2) indicate the order they clicked the button.

**Comment by Alumian** [comment]
Thanks for the feature request. Based on what you've described, it sounds a little bit too niche to be appropriate for the core add-on. Sounds like a great example of a plugin that you could write but at this stage I don't plan to implement this feature request.
