### ISSUE TITLE
[Bug] Record Snapshot seems to record max 40 players

### ISSUE THREAD

**Issue by JoesGab** [Alumian/CEPGP-Retail#270]
**The Error**
No Error Message. 

**Describe the bug**
"Record Snapshot" seems to only record a maximum number of 40 players. Every ZG I recorded so far contained all players in the raid as well as the list of standby players. Every 40 player raid only had 40 players in the attendance list. A raid with 39 players would have a maximum of 1 player on the standby list.

I also checked the LUA and the `CEPGP_raid_logs` part - only 40 people recorded max.

**To Reproduce**
1. Make full raid of 40 people
2. Add a person to the standby list
3. "Record Snapshot"
4. Check the "Raid Attendance" for the standby players and notice they're missing

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.16 Release<br />
Locale: enUS<br />
Poll Rate: 0.0001<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />
Base GP: 40<br />
Traffic Entries: 3102<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 100<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Roll for Passes: true<br />
Announce Rolls: true<br />
Resolve Duplicate Rolls: true<br />
Minimum EP: false, 35<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 4<br />
Allow Force Sync: true, Guild Master<br />
Hide Keyphrase Alternatives: False<br /><br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
The Edge of Madness: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Onyxia: True<br />
Heigan the Unclean: True<br />
Azuregos: True<br />
Doom Lord Kazzak: True<br />
Renataki: True<br />
Baron Geddon: True<br />
Viscidus: True<br />
Gri'lek: True<br />
Vaelastrasz the Corrupt: True<br />
Jin'do the Hexxer: True<br />
Firemaw: True<br />
High Priestess Arlokk: True<br />
The Twin Emperors: True<br />
Sulfuron Harbinger: True<br />
Emeriss: True<br />
Shazzrah: True<br />
Sapphiron: True<br />
Battleguard Sartura: True<br />
Bloodlord Mandokir: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Kurinnaxx: True<br />
Broodlord Lashlayer: True<br />
Maexxna: True<br />
Ragnaros: True<br />
Hakkar: True<br />
The Four Horsemen: True<br />
Ouro: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Gahz'ranka: True<br />
Gluth: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Silithid Royalty: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Twin Emperors: 10<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
The Edge of Madness: 2<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
The Silithid Royalty: 10<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 7<br />
Onyxia: 5<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Doom Lord Kazzak: 7<br />
Renataki: 2<br />
Baron Geddon: 5<br />
Viscidus: 10<br />
Gri'lek: 2<br />
Vaelastrasz the Corrupt: 7<br />
Jin'do the Hexxer: 2<br />
Firemaw: 7<br />
High Priestess Arlokk: 2<br />
The Twin Emperors: 10<br />
Sulfuron Harbinger: 5<br />
Emeriss: 7<br />
Shazzrah: 5<br />
Sapphiron: 15<br />
Battleguard Sartura: 10<br />
Bloodlord Mandokir: 2<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Kurinnaxx: 3<br />
Broodlord Lashlayer: 7<br />
Maexxna: 15<br />
Ragnaros: 7<br />
Hakkar: 3<br />
The Four Horsemen: 15<br />
Ouro: 10<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 7<br />
Magmadar: 5<br />
Patchwerk: 12<br />
Gahz'ranka: 2<br />
Gluth: 12<br />
Chromaggus: 7<br />
Garr: 5<br />
</details>
<details><summary>Loot Button Configuration</summary>
Loot Button 1<br />State: Enabled<br />Button Text: Main Spec<br />Discount: 0%<br />Keyphrase Alternative: need<br /><br />Loot Button 2<br />State: Enabled<br />Button Text: Off Spec<br />Discount: 100%<br />Keyphrase Alternative: greed<br /><br />Loot Button 3<br />State: Disabled<br />Button Text: Disenchant<br />Discount: 0%<br />Keyphrase Alternative: Disenchant<br /><br />Loot Button 4<br />State: Disabled<br />Button Text: Minor Upgrade<br />Discount: 0%<br />Keyphrase Alternative: Minor<br /><br /></details><details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
Master Officer: False<br />
Officer: False<br />
Officer Alt: False<br />
Core Raider: False<br />
Raider: False<br />
Trial Raider: False<br />
Raider Alt: False<br />
Social: False<br />
Alt: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
THROWN: 0.5<br />
FEET: 0.75<br />
RELIC: 0.5<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 0.5<br />
TRINKET: 0.75<br />
WAND: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
LEGS: 1<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
RANGED: 0.5<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
Altoholic<br />
AtlasLootClassic<br />
ATT-Classic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
BCT<br />
BeanCounter<br />
BijouRR<br />
CEPGP<br />
ClassicLootAssistant<br />
ClassicSpellActivations<br />
Clique<br />
DataStore<br />
DataStore_Auctions<br />
DataStore_Characters<br />
DataStore_Containers<br />
DataStore_Crafts<br />
DataStore_Inventory<br />
DataStore_Mails<br />
DataStore_Quests<br />
DataStore_Reputations<br />
Details<br />
Details_EncounterDetails<br />
Details_RaidCheck<br />
Details_Streamer<br />
Details_TinyThreat<br />
Details_Vanguard<br />
Enchantrix-Barker<br />
ExRT<br />
FloTotemBar<br />
GatherMate2<br />
Guild_Roster_Manager<br />
HealBot_Data<br />
HealBot_en<br />
HealBot_Options<br />
honorspy<br />
InFlight_Load<br />
InstanceCounter<br />
ItemRack<br />
Leatrix_Maps<br />
Leatrix_Plus<br />
MBB<br />
NovaWorldBuffs<br />
oRA3<br />
Raid-Helper<br />
ShowMeMyHeal<br />
SilverDragon<br />
SilverDragon_Classic<br />
SlideBar<br />
Stubby<br />
!Swatter<br />
TidyPlates_ThreatPlates<br />
ThreatClassic2<br />
TrinketMenu<br />
VuhDo<br />
VuhDoOptions<br />
WeakAuras<br />
WeaponSwingTimer<br />
CharacterStatsClassic<br />
TradeSkillMaster<br />
ElvUI<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment]
Should be resolved in the 1.12.19 release.
