### ISSUE TITLE
No loot window props up for CEPGP 1.12.16 [Bug]

### ISSUE THREAD

**Issue by lkat6** [Alumian/CEPGP-Retail#272]
**The Error**
What was the error message you received?
No message was sent
**Describe the bug**
As a raid member, no gear loot window showed up from epgp. Gears were announced in chat but nothing happened to my character and no loot selection window was provided. It seems the addon is not functioning.
**To Reproduce**
How can this bug be reproduced?
No, this happens to only one of my characters but not the other one.
**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.
<details><summary>Debug Info</summary><br />
Version: 1.12.16 Release<br />
Locale: enUS<br />
Poll Rate: 0.0001<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />
Base GP: 1<br />
Traffic Entries: 98<br />
Base GP Decay Factor: false<br />
Standby EP: False<br />

**Comment by Alumian** [comment]
If you type /console ScriptErrors 1 and then type /cep debug, does an error appear?

**Comment by Alumian** [comment]
Haven't heard back, assuming the issue has fixed itself.
