### ISSUE TITLE
[Request] Option to show distribution window for everyone while item is on roll

### ISSUE THREAD

**Issue by omggga** [Alumian/CEPGP-Retail#273]
When Raid Wide Loot Visibility is checked ON, you can also set some option like "Pop distribution window for everyone".

When ML start item roll, distribution window pops for everyone (not only ML and guys with fast hands). So the roll procedure became more clear and understandable for everyone - all ppl can see their PR/rolls/specs etc.

**Comment by Alumian** [comment]
Hi Omggga,

I feel as though this option may not be appealing to everyone. I'm happy to add this, but I won't add it as a loot master feature. I'm going to make this a personal feature so that players can enable this if they choose to.

**Comment by omggga** [comment]
Good idea.
So anyone, who think ML is cheat him, can see distrib window. Others - just play :D
