### ISSUE TITLE
[Question] Where is the minimum GP value stored? And how is it used?

### ISSUE THREAD

**Issue by aembke** [Alumian/CEPGP-Retail#276]
For this use case we're considering switching from EPGP-Classic, but had some questions on where the two addons intersect. 

It looks like both addons store their EP and GP values in officer notes and both addons support the notion of a minimum GP value. In EPGP-Classic the minimum GP value is not reflected in the officer notes, so a person's GP is calculated by adding their GP from officer notes with the minimum GP in the addon settings. 

Does this addon function in a similar way? Or is the minimum GP stored in officer notes? I would imagine it's likely stored separately since reflecting the minimum GP in officer notes would make it a nightmare to update GP whenever that value changed, but I wanted to make sure. If by chance the minimum GP value is reflected in officer notes then by changing that value in this addon we would be changing the GP in the other addon, making the switch a bit more difficult.

**Comment by Alumian** [comment]
Hi Aembke,
In CEPGP, the minimum GP is not publicly visible. You just configure it in the addon settings and it is stored in your saved variables. Then, whenever CEPGP needs to calculate any changes in terms of standings, it factors that number in to ensure that no one drops below the minimum.
CEPGP formats the officer notes in the following way: EP,GP or as an example: 212,618

Does that answer your question?

**Comment by aembke** [comment]
Yes I think it does. Thanks for getting back to me so quickly.

**Comment by aembke** [comment]
One update for anybody that stumbles across this.

It turns out this addon and EPGP-Classic calculate GP differently.

EPGP-Classic: `GP = gp_from_officer_notes + minimum_gp_from_settings`
CEPGP: `GP = max(gp_from_officer_notes, minimum_gp_from_settings)`
