### ISSUE TITLE
[Request] random raid loot distribution button

### ISSUE THREAD

**Issue by Nihlo** [Alumian/CEPGP-Retail#28]
Would be cool to have a button for raid random loot distribution for not so worthy items, like greens or bags.

Just a button which shuffles the raid members and announce it to raid chat, like:

"Loot goes to: AwesomeDamage in group: 2"

**Comment by Alumian** [comment]
Hi Nihlo,

Thanks for the feature request. Unfortunately as I can see potential for this setting to cause problems, especially if it is accidentally turned on and given that group loot is a thing, at this stage I will not be implementing this feature.

Please feel free to submit feature requests in future.

Thanks

**Comment by Nihlo** [comment]
I didn't mean this as a loot distribution function but only for roll and announce.
