### ISSUE TITLE
Standby whisper function not triggering[Bug]

### ISSUE THREAD

**Issue by Priestiest** [Alumian/CEPGP-Retail#288]
No error message
What was the error message you received?

Whispering the standby keyword does not add the user to the standby list.

Be in raid with CEPGP session open and have someone not in raid whisper "standby" to a CEPGP admin.
How can this bug be reproduced?

no error.
Type /cepgp debug and copy and paste the information into this bug report.

**Comment by Alumian** [comment]
Should be fixed in 1.13.0. Let me know if the issue persists.
