### ISSUE TITLE
WoW Classic: Error when attempting to add EP to the raid.

### ISSUE THREAD

**Issue by greppy** [Alumian/CEPGP-Retail#289]
Tried to add EP to the raid, and got an error about Scrollbar.lua.

Other officers also tried to award EP to the raid and also got errors.

<details><summary>Debug Info</summary><br />
Version: 1.12.25 Release<br />
Locale: enUS<br />
Poll Rate: 0.0001<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />
Base GP: 20<br />
Traffic Entries: 106<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 100<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Roll for Passes: false<br />
Announce Rolls: true<br />
Resolve Duplicate Rolls: true<br />
Minimum EP: true, 135<br />
Reporting Channel: Officer<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 2<br />
Allow Force Sync: false, Guild Leader<br />
Hide Keyphrase Alternatives: False<br /><br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Ragnaros: True<br />
Buru the Gorger: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Bloodlord Mandokir: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Heigan the Unclean: True<br />
Shazzrah: True<br />
Azuregos: True<br />
Gothik the Harvester: True<br />
Baron Geddon: True<br />
High Priestess Arlokk: True<br />
Edge of Madness: True<br />
Sapphiron: True<br />
Jin'do the Hexxer: True<br />
Gluth: True<br />
Kurinnaxx: True<br />
Gahz'ranka: True<br />
Lethon: True<br />
Lord Kazzak: True<br />
Viscidus: True<br />
Battleguard Sartura: True<br />
Emeriss: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Vaelastrasz the Corrupt: True<br />
The Twin Emperors: True<br />
Maexxna: True<br />
Hakkar: True<br />
Broodlord Lashlayer: True<br />
The Four Horsemen: True<br />
Onyxia: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Sulfuron Harbinger: True<br />
Patchwerk: True<br />
Ouro: True<br />
Firemaw: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Ragnaros: 8<br />
Buru the Gorger: 3<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 5<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 5<br />
High Priest Venoxis: 2<br />
Gehennas: 5<br />
Taerar: 7<br />
Ysondre: 7<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Bloodlord Mandokir: 2<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 7<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
The Silithid Royalty: 10<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 7<br />
Heigan the Unclean: 12<br />
Shazzrah: 5<br />
Azuregos: 7<br />
Gothik the Harvester: 12<br />
Baron Geddon: 5<br />
High Priestess Arlokk: 2<br />
Edge of Madness: 2<br />
Sapphiron: 15<br />
Jin'do the Hexxer: 2<br />
Gluth: 12<br />
Kurinnaxx: 3<br />
Gahz'ranka: 2<br />
Lethon: 7<br />
Lord Kazzak: 7<br />
Viscidus: 10<br />
Battleguard Sartura: 10<br />
Emeriss: 7<br />
Kel'Thuzad: 15<br />
Nefarian: 9<br />
Fankriss the Unyielding: 10<br />
Lucifron: 5<br />
Anub'Rekhan: 12<br />
Vaelastrasz the Corrupt: 7<br />
The Twin Emperors: 10<br />
Maexxna: 15<br />
Hakkar: 3<br />
Broodlord Lashlayer: 7<br />
The Four Horsemen: 15<br />
Onyxia: 5<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 7<br />
Magmadar: 5<br />
Sulfuron Harbinger: 5<br />
Patchwerk: 12<br />
Ouro: 10<br />
Firemaw: 7<br />
Chromaggus: 7<br />
Garr: 5<br />
</details>
<details><summary>Loot Button Configuration</summary>
Loot Button 1<br />State: Enabled<br />Button Text: Need<br />Discount: 0%<br />Keyphrase Alternative: Need<br /><br />Loot Button 2<br />State: Enabled<br />Button Text: Greed<br />Discount: 50%<br />Keyphrase Alternative: Greed<br /><br />Loot Button 3<br />State: Enabled<br />Button Text: Off Role<br />Discount: 100%<br />Keyphrase Alternative: offrole<br /><br />Loot Button 4<br />State: Enabled<br />Button Text: PVP/RP<br />Discount: 100%<br />Keyphrase Alternative: pvprp<br /><br /></details><details><summary>Standby Guild Ranks</summary>
Guild Leader: False<br />
GM ALT: False<br />
Officer: False<br />
Guild Bank: False<br />
Class Leader: False<br />
Raider: False<br />
Alt: False<br />
Member: False<br />
Trial Member: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
RANGED: 2<br />
THROWN: 0.5<br />
FEET: 0.75<br />
RELIC: 0.5<br />
FINGER: 0.5<br />
WEAPONOFFHAND: 0.5<br />
TRINKET: 0.75<br />
WAND: 0.5<br />
CLOAK: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
LEGS: 1<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
[Drake Fang Talisman]: 34<br />
[Neltharion's Tear]: 34<br />
</details>
<details><summary>Addons List</summary>
Armory<br />
Atlas<br />
Atlas_ClassicWoW<br />
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
BagBrother<br />
Bagnon<br />
BeanCounter<br />
CEPGP<br />
ClassicLootAssistant<br />
ClassicAuraDurations<br />
Clique<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
Dominos<br />
Dominos_Cast<br />
Dominos_Progress<br />
Dominos_Roll<br />
Enchantrix-Barker<br />
ExRT<br />
ExtendedCharacterStats<br />
FarmLog<br />
GatherMate2<br />
Grid2<br />
Grid2RaidDebuffs<br />
Grid2LDB<br />
GTFO<br />
Guild_Roster_Manager<br />
HandyNotes<br />
HandyNotes_DungeonLocations (Classic)<br />
HandyNotes_FlightMasters (Classic)<br />
ItemRack<br />
ItemTooltipProfessionIcons<br />
KKonferSK<br />
Mapster<br />
Necrosis<br />
OmniCC<br />
PallyPower<br />
Peddler<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
ShadowedUnitFrames<br />
SimpleCalc<br />
Skillet-Classic<br />
SlideBar<br />
SmartBuff<br />
Stubby<br />
!Swatter<br />
TidyPlates_ThreatPlates<br />
ThreatClassic2<br />
TomTom<br />
VendorPrice<br />
WeakAuras<br />
WideQuestLog<br />
WideQuestLogLevels<br />
+Wowhead_Looter<br />
Restocker<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

Date: 2020-09-02 21:16:02
ID: -1
Error occured in: Global
Count: 6
Message: ..\AddOns\CEPGP\Scrollbar.lua line 423:
   bad argument #1 to 'upper' (string expected, got nil)
Debug:
   [C]: upper()
   CEPGP\Scrollbar.lua:423: CEPGP_UpdateRaidScrollBar()
   CEPGP\Utility.lua:916: CEPGP_populateFrame()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11304
  Armory, vv1.7.0
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.5
  AtlasLootClassicData, vv1.5.5
  AtlasLootClassicDungeonsAndRaids, vv1.5.5
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.8
  BagnonConfig, v
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CEPGP, v
  ClassicAuraDurations, v1.13.61
  ClassicLootAssistant, v
  Clique, vv1.0.3-classic
  DBMCore, v1.13.58
  DBMDefaultSkin, v
  DBMMC, v
  DBMStatusBarTimers, v
  Details, v
  DetailsDataStorage, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v8.3.12
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4160
  ExtendedCharacterStats, v2.5.0
  FarmLog, vv1.19
  GatherMate2, v1.45.5
  Grid2, vr966
  Grid2LDB, vr966
  Grid2RaidDebuffs, vr966
  GTFO, v4.55
  GuildRosterManager, v1.88
  HandyNotes, vv1.5.10
  HandyNotesDungeonLocationsClassic, v1.03
  HandyNotesFlightMastersClassic, v1.06
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  ItemTooltipProfessionIcons, v1.1.6
  KKonferSK, v16
  Mapster, v1.8.5
  Necrosis, v7.3
  OmniCC, v8.3.6
  PallyPower, vv1.2.26-classic
  Peddler, v
  Prat30, v3.8.26
  Prat30Libraries, v
  Questie, v6.0.5
  Restocker, v6.2
  ShadowedUnitFrames, vv4.2.3-Classic
  SimpleCalc, v1.4.0a-classic
  SkilletClassic, v1.16
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SmartBuff, v1.13.2d
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.23
  TidyPlatesThreatPlates, v1.4.5
  TomTom, vv11305-1.1.4
  VendorPrice, v1.3.6
  WeakAuras, v2.18.2
  WideQuestLog, v
  WideQuestLogLevels, v
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=880)

**Comment by Alumian** [comment]
Should be fixed in 1.13.0. Please let me know if the issue persists.
