### ISSUE TITLE
Addon crashing game in a 1000 player guild [Bug] 

### ISSUE THREAD

**Issue by afonsohfontes** [Alumian/CEPGP-Retail#29]
**The Error**
Addon is getting the game stuck and sometimes crashing it when enabled in a guild with many members.

Hello @Alumian . I have a 1000 members guild, but only 60 raiders so far. The addon is setting values and managing every rank in the guild and I believe it is what is crashing it. Is it possible to config it to manage only the ranks that matter?

**To Reproduce**
How can this bug be reproduced?
I believe you need to be in a full guild. Feel free to join my guild on thalnos/horde and try to play with the addon. My btag is fonsas#1333

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.

<details><summary>Debug Info</summary><br />Version: 1.11.3<br /><br />GP Modifier: 1<br /><br />Base GP: 1<br /><br />Standby EP: False<br /><br />Standby Offline: False<br /><br />Standby Percent: 0<br /><br />Standby Accept Whispers: False<br /><br />Standby EP by Rank: True<br /><br />Standby EP Manual Delegation: False<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary><br /><details><summary>High Priestess Jeklik</summary>True</details><br /><details><summary>Gothik the Harvester</summary>True</details><br /><details><summary>Buru the Gorger</summary>True</details><br /><details><summary>Wushoolay</summary>True</details><br /><details><summary>Lord Kri</summary>True</details><br /><details><summary>Emperor Vek'nilash</summary>True</details><br /><details><summary>Ossirian the Unscarred</summary>True</details><br /><details><summary>Golemagg the Incinerator</summary>True</details><br /><details><summary>Grand Widow Faerlina</summary>True</details><br /><details><summary>High Priestess Mar'li</summary>True</details><br /><details><summary>Majordomo Executus</summary>True</details><br /><details><summary>High Priest Venoxis</summary>True</details><br /><details><summary>Gehennas</summary>True</details><br /><details><summary>Taerar</summary>True</details><br /><details><summary>Ysondre</summary>True</details><br /><details><summary>Thane Korth'azz</summary>True</details><br /><details><summary>High Priest Thekal</summary>True</details><br /><details><summary>Noth the Plaguebringer</summary>True</details><br /><details><summary>Lethon</summary>True</details><br /><details><summary>Moam</summary>True</details><br /><details><summary>The Prophet Skeram</summary>True</details><br /><details><summary>Flamegor</summary>True</details><br /><details><summary>C'Thun</summary>True</details><br /><details><summary>General Rajaxx</summary>True</details><br /><details><summary>Princess Huhuran</summary>True</details><br /><details><summary>Thaddius</summary>True</details><br /><details><summary>Loatheb</summary>True</details><br /><details><summary>Lady Blaumeux</summary>True</details><br /><details><summary>Highlord Mograine</summary>True</details><br /><details><summary>Heigan the Unclean</summary>True</details><br /><details><summary>Azuregos</summary>True</details><br /><details><summary>Doom Lord Kazzak</summary>True</details><br /><details><summary>Teremus the Devourer</summary>True</details><br /><details><summary>Chromaggus</summary>True</details><br /><details><summary>Baron Geddon</summary>True</details><br /><details><summary>Firemaw</summary>True</details><br /><details><summary>Sulfuron Harbinger</summary>True</details><br /><details><summary>Gri'lek</summary>True</details><br /><details><summary>High Priestess Arlokk</summary>True</details><br /><details><summary>Emperor Vek'lor</summary>True</details><br /><details><summary>Gahz'ranka</summary>True</details><br /><details><summary>Gluth</summary>True</details><br /><details><summary>Sapphiron</summary>True</details><br /><details><summary>Razorgore the Untamed</summary>True</details><br /><details><summary>Onyxia</summary>True</details><br /><details><summary>Princess Yauj</summary>True</details><br /><details><summary>Vem</summary>True</details><br /><details><summary>Shazzrah</summary>True</details><br /><details><summary>Ouro</summary>True</details><br /><details><summary>Battleguard Sartura</summary>True</details><br /><details><summary>Maexxna</summary>True</details><br /><details><summary>Kel'Thuzad</summary>True</details><br /><details><summary>Nefarian</summary>True</details><br /><details><summary>Fankriss the Unyielding</summary>True</details><br /><details><summary>Lucifron</summary>True</details><br /><details><summary>Anub'Rekhan</summary>True</details><br /><details><summary>Hazza'rah</summary>True</details><br /><details><summary>Ragnaros</summary>True</details><br /><details><summary>Ayamiss the Hunter</summary>True</details><br /><details><summary>Broodlord Lashlayer</summary>True</details><br /><details><summary>Viscidus</summary>True</details><br /><details><summary>Hakkar</summary>True</details><br /><details><summary>Ebonroc</summary>True</details><br /><details><summary>Kurinnaxx</summary>True</details><br /><details><summary>Grobbulus</summary>True</details><br /><details><summary>Instructor Razuvious</summary>True</details><br /><details><summary>Emeriss</summary>True</details><br /><details><summary>Magmadar</summary>True</details><br /><details><summary>Sir Zeliek</summary>True</details><br /><details><summary>Vaelastrasz the Corrupt</summary>True</details><br /><details><summary>Patchwerk</summary>True</details><br /><details><summary>Bloodlord Mandokir</summary>True</details><br /><details><summary>Renataki</summary>True</details><br /><details><summary>Jin'do the Hexxer</summary>True</details><br /><details><summary>Garr</summary>True</details><br /></details><br /><details><summary>EP Values</summary><br /><details><summary>High Priestess Jeklik</summary>2</details><br /><details><summary>Gothik the Harvester</summary>12</details><br /><details><summary>Buru the Gorger</summary>3</details><br /><details><summary>Wushoolay</summary>2</details><br /><details><summary>Lord Kri</summary>10</details><br /><details><summary>Emperor Vek'nilash</summary>10</details><br /><details><summary>Ossirian the Unscarred</summary>4</details><br /><details><summary>Golemagg the Incinerator</summary>5</details><br /><details><summary>Grand Widow Faerlina</summary>12</details><br /><details><summary>High Priestess Mar'li</summary>2</details><br /><details><summary>Majordomo Executus</summary>5</details><br /><details><summary>High Priest Venoxis</summary>2</details><br /><details><summary>Gehennas</summary>5</details><br /><details><summary>Taerar</summary>7</details><br /><details><summary>Ysondre</summary>7</details><br /><details><summary>Thane Korth'azz</summary>15</details><br /><details><summary>High Priest Thekal</summary>2</details><br /><details><summary>Noth the Plaguebringer</summary>12</details><br /><details><summary>Lethon</summary>7</details><br /><details><summary>Moam</summary>3</details><br /><details><summary>The Prophet Skeram</summary>10</details><br /><details><summary>Flamegor</summary>7</details><br /><details><summary>C'Thun</summary>12</details><br /><details><summary>General Rajaxx</summary>3</details><br /><details><summary>Princess Huhuran</summary>10</details><br /><details><summary>Thaddius</summary>15</details><br /><details><summary>Loatheb</summary>15</details><br /><details><summary>Lady Blaumeux</summary>15</details><br /><details><summary>Highlord Mograine</summary>15</details><br /><details><summary>Heigan the Unclean</summary>12</details><br /><details><summary>Azuregos</summary>7</details><br /><details><summary>Doom Lord Kazzak</summary>7</details><br /><details><summary>Teremus the Devourer</summary>7</details><br /><details><summary>Chromaggus</summary>7</details><br /><details><summary>Baron Geddon</summary>5</details><br /><details><summary>Firemaw</summary>7</details><br /><details><summary>Sulfuron Harbinger</summary>5</details><br /><details><summary>Gri'lek</summary>2</details><br /><details><summary>High Priestess Arlokk</summary>2</details><br /><details><summary>Emperor Vek'lor</summary>10</details><br /><details><summary>Gahz'ranka</summary>2</details><br /><details><summary>Gluth</summary>12</details><br /><details><summary>Sapphiron</summary>15</details><br /><details><summary>Razorgore the Untamed</summary>7</details><br /><details><summary>Onyxia</summary>5</details><br /><details><summary>Princess Yauj</summary>10</details><br /><details><summary>Vem</summary>10</details><br /><details><summary>Shazzrah</summary>5</details><br /><details><summary>Ouro</summary>10</details><br /><details><summary>Battleguard Sartura</summary>10</details><br /><details><summary>Maexxna</summary>15</details><br /><details><summary>Kel'Thuzad</summary>15</details><br /><details><summary>Nefarian</summary>10</details><br /><details><summary>Fankriss the Unyielding</summary>10</details><br /><details><summary>Lucifron</summary>5</details><br /><details><summary>Anub'Rekhan</summary>12</details><br /><details><summary>Hazza'rah</summary>2</details><br /><details><summary>Ragnaros</summary>7</details><br /><details><summary>Ayamiss the Hunter</summary>3</details><br /><details><summary>Broodlord Lashlayer</summary>7</details><br /><details><summary>Viscidus</summary>10</details><br /><details><summary>Hakkar</summary>3</details><br /><details><summary>Ebonroc</summary>7</details><br /><details><summary>Kurinnaxx</summary>3</details><br /><details><summary>Grobbulus</summary>12</details><br /><details><summary>Instructor Razuvious</summary>12</details><br /><details><summary>Emeriss</summary>7</details><br /><details><summary>Magmadar</summary>5</details><br /><details><summary>Sir Zeliek</summary>15</details><br /><details><summary>Vaelastrasz the Corrupt</summary>7</details><br /><details><summary>Patchwerk</summary>12</details><br /><details><summary>Bloodlord Mandokir</summary>2</details><br /><details><summary>Renataki</summary>2</details><br /><details><summary>Jin'do the Hexxer</summary>2</details><br /><details><summary>Garr</summary>5</details><br /></details><br /><details><summary>Standby Guild Ranks</summary><br /><details><summary>Guild Master</summary>False</details><br /><details><summary>Raid Leader</summary>False</details><br /><details><summary>Master Looter</summary>False</details><br /><details><summary>Officer</summary>False</details><br /><details><summary>Raider</summary>False</details><br /><details><summary>Membro</summary>False</details><br /><details><summary>Casual</summary>False</details><br /><details><summary>Trial</summary>False</details><br /><details><summary>Saci</summary>False</details><br /><details><summary>Saci</summary>False</details><br /></details><br /><details><summary>Slot Weights</summary><br /><details><summary>2HWEAPON</summary>2</details><br /><details><summary>NECK</summary>0.5</details><br /><details><summary>HEAD</summary>1</details><br /><details><summary>WEAPON</summary>1.5</details><br /><details><summary>WRIST</summary>0.5</details><br /><details><summary>WEAPONMAINHAND</summary>1.5</details><br /><details><summary>SHIELD</summary>0.5</details><br /><details><summary>HOLDABLE</summary>0.5</details><br /><details><summary>RANGED</summary>0.5</details><br /><details><summary>SHOULDER</summary>0.75</details><br /><details><summary>FEET</summary>0.75</details><br /><details><summary>LEGS</summary>1</details><br /><details><summary>EXCEPTION</summary>1</details><br /><details><summary>WAIST</summary>0.75</details><br /><details><summary>TRINKET</summary>0.75</details><br /><details><summary>HAND</summary>0.75</details><br /><details><summary>ROBE</summary>1</details><br /><details><summary>CHEST</summary>1</details><br /><details><summary>CLOAK</summary>0.5</details><br /><details><summary>FINGER</summary>0.5</details><br /><details><summary>WEAPONOFFHAND</summary>0.5</details><br /><details><summary>RANGEDRIGHT</summary>0.5</details><br /><details><summary>RELIC</summary>0.5</details><br /><details><summary>THROWN</summary>0.5</details><br /></details><br /></details>

**Comment by Alumian** [comment]
Hi Afonso,

Yeah, I've noticed this bug too. I'm current working on a solution. It shouldn't be crashing your game though, add-ons lack that capacity.

**Comment by Alumian** [comment]
Hi @afonsohfontes, I've tried contacting you in-game but I can't seem to get a hold of you. Is this issue only occurring while you're in a raid group and when changes are made to the raid group? For example, when a player joins/leaves or is moved to a different group.

**Comment by Alumian** [comment]
I have written a fix for this problem, assuming that it is only occurring while in a raid group. Please download the latest version of the addon and let me know if this has been resolved.

**Comment by Alumian** [comment]
Afonsohfontes has confirmed with me in-game that this issue has been resolved in https://github.com/Alumian/CEPGP-Retail/commit/37f854dd4bfc742498cb200d23f6e4e8f54c9c37
