### ISSUE TITLE
Award EP to people in the instance only. AOE EP

### ISSUE THREAD

**Issue by adam6806** [Alumian/CEPGP-Retail#291]
We want to award on time EP to only those who are ready to pull at start time. So if they are in the instance then they should get EP. If they are not in the instance they should not get EP. This would also work if it was based on some range so when we group up for debuffs it could check the range and either assign or not. This would only be for a manual add of course.

**Comment by kasperlandgren** [comment]
Seconded. We deal with this by awarding the entire raid and subtracting from latecomers, which is pretty clunky.

**Comment by ollema** [comment]
there is a plugin for that:

**CEPGP-Zone-Award**

> CEPGP Zone Award adds functionality to award raid wide EP to those who are both online and in the same zone as the player making the award. An additional check box can be found on the Raid Moderation window when awarding raid EPs which will enable this feature. Upon making the award messages (which can be suppressed) are sent highlighting those who did not qualify.

Source: [https://www.curseforge.com/wow/addons/cepgp-zone-award](https://www.curseforge.com/wow/addons/cepgp-zone-award)

also, why do you group up for debuffs? does not sound very smart

**Comment by Alumian** [comment]
As Ollema mentioned, there is now a plugin which supports this functionality.
