### ISSUE TITLE
[Question] Why does it not show player’s PR list when distribution?

### ISSUE THREAD

**Issue by zacharydong** [Alumian/CEPGP-Retail#292]
**Please describe your question below**
I used cepgp last year, when I loot, I tell all the team to send me !need if they need something, and I will see their PR on my loot list, then I give it to the highest PR. As long as I have the cepgp addon, it works.
Now, I upgrade to the newest release version, when the send me “!need”, yes, all the member will see their pr info, but I can not see it on my window, so I don’t know who has the highest PR, and no distribution button. Now each time I have to loot all and distribut at the end, and manually add gp to related member.

Does it require for all members to install Cepgp?

**Comment by Alumian** [comment]
Hi Zachary,

No, your members don't need to install CEPGP. What you're describing sounds very strange - you should definitely be able to see their PR. I recommend you jump onto the CEPGP discord so that I can look into this issue for you.

**Comment by zacharydong** [comment]
Now I tried sometimes, it show pr list, the problem is that members who whisper me with need, i did can see them on the list, but I can not distribute item to them. I can only distribute to ones who use cepgp and Choose mainspec. So I think it still needs all to install cepgp?
