### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Alabamarolltide** [Alumian/CEPGP-Retail#294]
Great Mod.   We are in classic wow.  We are running raids with other guilds on a regular basis.  Is there a way to add these non-guild members to our CEPGP mod permanently.  Right now it adds them for the raid but then once they leave the raid all the data is lost.   thanks

Alabama

**Comment by Alumian** [comment]
At this stage, you are not able to add non-guild members to CEPGP sorry.
