### ISSUE TITLE
Rolls aren't going through

### ISSUE THREAD

**Issue by VJiffy** [Alumian/CEPGP-Retail#295]
With the recent update many rolls aren't going through, as in people are clicking main spec, or off spec, or minor upgrade (our set options to roll with) and they dont show up in chat, or loot masters cepgp loot frame. As of right now were asking people to just watch chat and type when they notice that clicking the button didnt send the message.

**Comment by wromthrax** [comment]
Sometimes not even chat greed/need commands work.

**Comment by Alumian** [comment]
Resolved in 1.13.1
