### ISSUE TITLE
Current In-Slot Item Visibility for Assistants/Everyone

### ISSUE THREAD

**Issue by BurnHavoc** [Alumian/CEPGP-Retail#297]
EXCELLENT addon :D We'll be switching over to it in 2 weeks off of an SR system, excited to put it to use.

One quick Q: Is there any way for either the assists or everyone with access to the loot distribution window to also see the current in-slot item for the bidders? Or is that supposed to already occur and is currently bugged?

Thanks!

**Comment by Alumian** [comment]
To my understanding, this feature is working. However, it requires your raiders on be using the addon. It will not show items for anyone not running the addon.

**Comment by BurnHavoc** [comment]
I've been testing it with people using the addon and it doesn't appear to be working:

ML view: https://media.discordapp.net/attachments/598725044092272661/764939531849039923/unknown.png
Assistant view: https://images-ext-1.discordapp.net/external/YmiXL_rN1BLpMxZMWzU2b_HWyxGlBBcNzhAq46mQvZI/%3Fsource%3Dsocial%26v%3D98a1d758e163a3d56ca699235b9de72c/https/p190.p3.n0.cdn.getcloudapp.com/items/RBuWOLm2/Image%25202020-10-11%2520at%25202.56.23%2520PM.png
