### ISSUE TITLE
The list is just blank when I open it

### ISSUE THREAD

**Issue by bajsbender** [Alumian/CEPGP-Retail#299]
**The Error**
Date: 2020-10-13 23:08:05
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\CEPGP\Scrollbar.lua line 269:
   attempt to index field '?' (a nil value)
Debug:
   [C]: ?
   CEPGP\Scrollbar.lua:269:
      CEPGP\Scrollbar.lua:263
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AutoDismount, v1.0.3
  BagBrother, v
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BuffTimers, v1.0.2
  CEPGP, v
  CEPGPDistributionFromBags, v1.13.0
  CharacterStatsClassic, v3.6.5
  ClassicAuraDurations, v1.13.61
  ClassicCastbars, v1.3.12
  ClassicCastbarsOptions, v
  ClickMorph, v1.6.4
  Combuctor, v8.3.2
  DBMCore, v1.13.61
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaMark, v820r201
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExRT, v4330
  Informant, v8.2.6508 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.81
  LootAppraiserClassic, vv1.1
  LortiUIClassic, v1.1.0
  NovaInstanceTracker, v1.11
  NovaWorldBuffs, v1.82
  OmniCC, v9.0.0
  Prat30, v3.8.26
  Prat30Libraries, v
  Questie, v6.0.5
  Skada, v1.7.6
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v1.1.2
  Stubby, v8.2.6510 (SwimmingSeadragon)
  ThreatClassic2, v2.24
  TipTac, v20.03.12
  TipTacItemRef, v19.03.31
  TrackOMatic, v1.1.2
  TradeSkillMaster, vv4.10.7
  VendorPrice, v1.3.7
  Wardrobe, v2.0.0
  WeakAuras, v2.18.4
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=6bf)

**Describe the bug**
The guildlist is just blank, nothing there

**To Reproduce**
By just opening it, from the minimap

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.13.1 Release<br />
Locale: enUS<br />
Poll Rate: 0.0001<br />
GP Formula: (4.83x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />
Base GP: 15<br />
Traffic Entries: 1802<br />
Base GP Decay Factor: false<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Loot Visibility - Assists: true<br />
Loot Visibility - Raid-Wide: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: false<br />
Roll for Passes: false<br />
Announce Rolls: true<br />
Resolve Duplicate Rolls: true<br />
Minimum EP: false, 0<br />
Reporting Channel: Guild<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 2<br />
Hide Keyphrase Alternatives: False<br /><br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Sapphiron: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Ouro: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Heigan the Unclean: True<br />
Onyxia: True<br />
Bloodlord Mandokir: True<br />
Baron Geddon: True<br />
High Priestess Arlokk: True<br />
Loatheb: True<br />
Edge of Madness: False<br />
Firemaw: True<br />
Chromaggus: True<br />
Ragnaros: True<br />
Kurinnaxx: True<br />
Gluth: True<br />
Azuregos: True<br />
Lord Kazzak: True<br />
Flamegor: True<br />
Battleguard Sartura: True<br />
Razorgore the Untamed: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Sulfuron Harbinger: True<br />
Viscidus: True<br />
Maexxna: True<br />
Hakkar: True<br />
Broodlord Lashlayer: True<br />
The Four Horsemen: True<br />
Shazzrah: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Gahz'ranka: True<br />
Patchwerk: True<br />
Vaelastrasz the Corrupt: True<br />
The Twin Emperors: True<br />
Jin'do the Hexxer: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Ragnaros: 5<br />
Buru the Gorger: 3<br />
Kurinnaxx: 3<br />
Golemagg the Incinerator: 3<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Majordomo Executus: 3<br />
High Priest Venoxis: 2<br />
Gehennas: 3<br />
Taerar: 7<br />
Vaelastrasz the Corrupt: 7<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Bloodlord Mandokir: 2<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Sapphiron: 15<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
The Silithid Royalty: 10<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 7<br />
Heigan the Unclean: 12<br />
Azuregos: 7<br />
Ouro: 10<br />
Baron Geddon: 3<br />
High Priestess Arlokk: 2<br />
Lord Kazzak: 7<br />
Edge of Madness: 2<br />
Flamegor: 7<br />
Chromaggus: 7<br />
The Twin Emperors: 10<br />
Gluth: 12<br />
Firemaw: 7<br />
Viscidus: 10<br />
Shazzrah: 3<br />
Gothik the Harvester: 12<br />
Battleguard Sartura: 10<br />
Razorgore the Untamed: 7<br />
Kel'Thuzad: 15<br />
Nefarian: 10<br />
Fankriss the Unyielding: 10<br />
Lucifron: 3<br />
Anub'Rekhan: 12<br />
Gahz'ranka: 2<br />
Lethon: 7<br />
Hakkar: 3<br />
Broodlord Lashlayer: 7<br />
Maexxna: 15<br />
The Four Horsemen: 15<br />
Ysondre: 7<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 3<br />
Ossirian the Unscarred: 4<br />
Patchwerk: 12<br />
Onyxia: 3<br />
Sulfuron Harbinger: 3<br />
Jin'do the Hexxer: 2<br />
Garr: 3<br />
</details>
<details><summary>Loot Button Configuration</summary>
Loot Button 1<br />State: Enabled<br />Button Text: 100%<br />Discount: 0%<br />Keyphrase Alternative: need100<br /><br />Loot Button 2<br />State: Enabled<br />Button Text: 50%<br />Discount: 50%<br />Keyphrase Alternative: need50<br /><br />Loot Button 3<br />State: Enabled<br />Button Text: 10%<br />Discount: 90%<br />Keyphrase Alternative: need10<br /><br />Loot Button 4<br />State: Disabled<br />Button Text: Minor Upgrade<br />Discount: 0%<br />Keyphrase Alternative: Minor<br /><br /></details><details><summary>Standby Guild Ranks</summary>
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
SHOULDER: 0.75<br />
FEET: 0.75<br />
RANGED: 2<br />
FINGER: 0.5<br />
WAIST: 0.75<br />
TRINKET: 0.75<br />
WAND: 0.5<br />
LEGS: 1<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1<br />
WEAPONOFFHAND: 0.5<br />
EXCEPTION: 1<br />
RELIC: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
Atlas<br />
Atlas_ClassicWoW<br />
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
AutoDismount<br />
BagBrother<br />
BeanCounter<br />
BuffTimers<br />
CEPGP<br />
CEPGP_DistributionFromBags<br />
ClassicAuraDurations<br />
ClassicCastbars<br />
ClassicCastbars_Options<br />
ClickMorph<br />
Combuctor<br />
DejaMark<br />
Enchantrix-Barker<br />
ExRT<br />
ItemRack<br />
Leatrix_Maps<br />
Lorti-UI-Classic<br />
NovaInstanceTracker<br />
NovaWorldBuffs<br />
OmniCC<br />
Prat-3.0<br />
Prat-3.0_Libraries<br />
Skada<br />
SlideBar<br />
Spy<br />
Stubby<br />
!Swatter<br />
ThreatClassic2<br />
TipTac<br />
TipTacItemRef<br />
TrackOMatic<br />
VendorPrice<br />
WeakAuras<br />
WeaponSwingTimer<br />
CharacterStatsClassic<br />
LootAppraiserClassic<br />
TradeSkillMaster<br />
Wardrobe<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details

**Comment by Alumian** [comment]
Can you please send through a screenshot of your rank filtering settings in the guild menu?

**Comment by bajsbender** [comment]
> Can you please send through a screenshot of your rank filtering settings in the guild menu?

So when I open it and press "Guild" this is what happens:
![image](https://user-images.githubusercontent.com/72826941/95973037-77158a80-0e13-11eb-87df-d5570888a86c.png)


guildmenu:
![image](https://user-images.githubusercontent.com/72826941/95973225-a75d2900-0e13-11eb-8b3a-2f484bbd2421.png)

![image](https://user-images.githubusercontent.com/72826941/95973309-c2c83400-0e13-11eb-8a1d-4a6ccd63b998.png)


Thanks in advance! Appriciate the help, great addon otherwise.

OBS. It works perfectly fine with older versions.

**Comment by Alumian** [comment]
Untick the ranks in Guild List Filtering. That feature removes those ranks from view. I'll make an adjustment to ensure the error doesn't happen though.

**Comment by bajsbender** [comment]
> Untick the ranks in Guild List Filtering. That feature removes those ranks from view. I'll make an adjustment to ensure the error doesn't happen though.

Wow, it was that simply, lol. Thanks alot my man!
