### ISSUE TITLE
[Bug] EP is not being automatically awarded

### ISSUE THREAD

**Issue by Alumian** [Alumian/CEPGP-Retail#30]
**The Error**
No error message.

**Describe the bug**
When a boss is defeated that is present in the boss index, EP is not being automatically awarded.

**To Reproduce**
Defeat a boss -.-

**Comment by PibbzTV** [comment]
I have encountered this bug lately aswell. Neither bosskill will auto award EP anymore. I have a custom values of 10 EP instead of the default, in case that is of interest.

**Comment by Alumian** [comment]
Resolved in commit https://github.com/Alumian/CEPGP-Retail/commit/171519906c5a71170f73705f7b0e231d6724a1cd
