### ISSUE TITLE
[Bug] Bad loot assignment and gp credit

### ISSUE THREAD

**Issue by skombag** [Alumian/CEPGP-Retail#31]
**The Error**
No error message

**Describe the bug**
Boss drops item , we have 1 Druid only wanting the item the Master looter clicks give for GP , the item gets sent to a random hunter  and a random paladin gets credited GP for it.

Happened 4 times during a full Molten core clear , also worked fine on the other loot.

also using /w !inforaid , !infoclass returns random ppls values , yet !info returns the proper value

**Comment by Alumian** [comment]
Can you please type /cep debug and copy paste the string into this report?

**Comment by skombag** [comment]
<details><summary>Debug Info</summary><br />Version: 1.11.3<br /><br />GP Modifier: 1<br /><br />Base GP: 1<br /><br />Standby EP: True<br /><br />Standby Offline: True<br /><br />Standby Percent: 100<br /><br />Standby Accept Whispers: False<br /><br />Standby EP by Rank: False<br /><br />Standby EP Manual Delegation: True<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: wtf<br /><br /><details><summary>Auto EP</summary><br /><details><summary>High Priestess Jeklik</summary>True</details><br /><details><summary>Gothik the Harvester</summary>True</details><br /><details><summary>Buru the Gorger</summary>True</details><br /><details><summary>Wushoolay</summary>True</details><br /><details><summary>Lord Kri</summary>True</details><br /><details><summary>Emperor Vek'nilash</summary>True</details><br /><details><summary>Ossirian the Unscarred</summary>True</details><br /><details><summary>Golemagg the Incinerator</summary>True</details><br /><details><summary>Grand Widow Faerlina</summary>True</details><br /><details><summary>High Priestess Mar'li</summary>True</details><br /><details><summary>Majordomo Executus</summary>True</details><br /><details><summary>High Priest Venoxis</summary>True</details><br /><details><summary>Gehennas</summary>True</details><br /><details><summary>Taerar</summary>True</details><br /><details><summary>Ysondre</summary>True</details><br /><details><summary>Thane Korth'azz</summary>True</details><br /><details><summary>High Priest Thekal</summary>True</details><br /><details><summary>Noth the Plaguebringer</summary>True</details><br /><details><summary>Lethon</summary>True</details><br /><details><summary>Moam</summary>True</details><br /><details><summary>The Prophet Skeram</summary>True</details><br /><details><summary>Flamegor</summary>True</details><br /><details><summary>C'Thun</summary>True</details><br /><details><summary>General Rajaxx</summary>True</details><br /><details><summary>Princess Huhuran</summary>True</details><br /><details><summary>Thaddius</summary>True</details><br /><details><summary>Loatheb</summary>True</details><br /><details><summary>Lady Blaumeux</summary>True</details><br /><details><summary>Highlord Mograine</summary>True</details><br /><details><summary>Heigan the Unclean</summary>True</details><br /><details><summary>Azuregos</summary>True</details><br /><details><summary>Doom Lord Kazzak</summary>True</details><br /><details><summary>Teremus the Devourer</summary>True</details><br /><details><summary>Jin'do the Hexxer</summary>True</details><br /><details><summary>Baron Geddon</summary>True</details><br /><details><summary>Renataki</summary>True</details><br /><details><summary>Sulfuron Harbinger</summary>True</details><br /><details><summary>Gri'lek</summary>True</details><br /><details><summary>Bloodlord Mandokir</summary>True</details><br /><details><summary>Patchwerk</summary>True</details><br /><details><summary>Vaelastrasz the Corrupt</summary>True</details><br /><details><summary>Gluth</summary>True</details><br /><details><summary>Sapphiron</summary>True</details><br /><details><summary>Emeriss</summary>True</details><br /><details><summary>Onyxia</summary>True</details><br /><details><summary>Princess Yauj</summary>True</details><br /><details><summary>Kurinnaxx</summary>True</details><br /><details><summary>Shazzrah</summary>True</details><br /><details><summary>Ebonroc</summary>True</details><br /><details><summary>Battleguard Sartura</summary>True</details><br /><details><summary>Hakkar</summary>True</details><br /><details><summary>Kel'Thuzad</summary>True</details><br /><details><summary>Nefarian</summary>True</details><br /><details><summary>Fankriss the Unyielding</summary>True</details><br /><details><summary>Lucifron</summary>True</details><br /><details><summary>Anub'Rekhan</summary>True</details><br /><details><summary>Hazza'rah</summary>True</details><br /><details><summary>Viscidus</summary>True</details><br /><details><summary>Broodlord Lashlayer</summary>True</details><br /><details><summary>Ayamiss the Hunter</summary>True</details><br /><details><summary>Ragnaros</summary>True</details><br /><details><summary>Maexxna</summary>True</details><br /><details><summary>Ouro</summary>True</details><br /><details><summary>Vem</summary>True</details><br /><details><summary>Grobbulus</summary>True</details><br /><details><summary>Instructor Razuvious</summary>True</details><br /><details><summary>Razorgore the Untamed</summary>True</details><br /><details><summary>Magmadar</summary>True</details><br /><details><summary>Sir Zeliek</summary>True</details><br /><details><summary>Gahz'ranka</summary>True</details><br /><details><summary>Emperor Vek'lor</summary>True</details><br /><details><summary>High Priestess Arlokk</summary>True</details><br /><details><summary>Firemaw</summary>True</details><br /><details><summary>Chromaggus</summary>True</details><br /><details><summary>Garr</summary>True</details><br /></details><br /><details><summary>EP Values</summary><br /><details><summary>High Priestess Jeklik</summary>2</details><br /><details><summary>Gothik the Harvester</summary>12</details><br /><details><summary>Buru the Gorger</summary>3</details><br /><details><summary>Wushoolay</summary>2</details><br /><details><summary>Lord Kri</summary>10</details><br /><details><summary>Emperor Vek'nilash</summary>10</details><br /><details><summary>Ossirian the Unscarred</summary>4</details><br /><details><summary>Golemagg the Incinerator</summary>5</details><br /><details><summary>Grand Widow Faerlina</summary>12</details><br /><details><summary>High Priestess Mar'li</summary>2</details><br /><details><summary>Majordomo Executus</summary>5</details><br /><details><summary>High Priest Venoxis</summary>2</details><br /><details><summary>Gehennas</summary>5</details><br /><details><summary>Taerar</summary>7</details><br /><details><summary>Ysondre</summary>7</details><br /><details><summary>Thane Korth'azz</summary>15</details><br /><details><summary>High Priest Thekal</summary>2</details><br /><details><summary>Noth the Plaguebringer</summary>12</details><br /><details><summary>Lethon</summary>7</details><br /><details><summary>Moam</summary>3</details><br /><details><summary>The Prophet Skeram</summary>10</details><br /><details><summary>Flamegor</summary>7</details><br /><details><summary>C'Thun</summary>12</details><br /><details><summary>General Rajaxx</summary>3</details><br /><details><summary>Princess Huhuran</summary>10</details><br /><details><summary>Thaddius</summary>15</details><br /><details><summary>Loatheb</summary>15</details><br /><details><summary>Lady Blaumeux</summary>15</details><br /><details><summary>Highlord Mograine</summary>15</details><br /><details><summary>Heigan the Unclean</summary>12</details><br /><details><summary>Azuregos</summary>7</details><br /><details><summary>Doom Lord Kazzak</summary>7</details><br /><details><summary>Teremus the Devourer</summary>7</details><br /><details><summary>Jin'do the Hexxer</summary>2</details><br /><details><summary>Baron Geddon</summary>5</details><br /><details><summary>Renataki</summary>2</details><br /><details><summary>Sulfuron Harbinger</summary>5</details><br /><details><summary>Gri'lek</summary>2</details><br /><details><summary>Bloodlord Mandokir</summary>2</details><br /><details><summary>Patchwerk</summary>12</details><br /><details><summary>Vaelastrasz the Corrupt</summary>7</details><br /><details><summary>Gluth</summary>12</details><br /><details><summary>Sapphiron</summary>15</details><br /><details><summary>Emeriss</summary>7</details><br /><details><summary>Onyxia</summary>5</details><br /><details><summary>Princess Yauj</summary>10</details><br /><details><summary>Kurinnaxx</summary>3</details><br /><details><summary>Shazzrah</summary>5</details><br /><details><summary>Ebonroc</summary>7</details><br /><details><summary>Battleguard Sartura</summary>10</details><br /><details><summary>Hakkar</summary>3</details><br /><details><summary>Kel'Thuzad</summary>15</details><br /><details><summary>Nefarian</summary>10</details><br /><details><summary>Fankriss the Unyielding</summary>10</details><br /><details><summary>Lucifron</summary>5</details><br /><details><summary>Anub'Rekhan</summary>12</details><br /><details><summary>Hazza'rah</summary>2</details><br /><details><summary>Viscidus</summary>10</details><br /><details><summary>Broodlord Lashlayer</summary>7</details><br /><details><summary>Ayamiss the Hunter</summary>3</details><br /><details><summary>Ragnaros</summary>7</details><br /><details><summary>Maexxna</summary>15</details><br /><details><summary>Ouro</summary>10</details><br /><details><summary>Vem</summary>10</details><br /><details><summary>Grobbulus</summary>12</details><br /><details><summary>Instructor Razuvious</summary>12</details><br /><details><summary>Razorgore the Untamed</summary>7</details><br /><details><summary>Magmadar</summary>5</details><br /><details><summary>Sir Zeliek</summary>15</details><br /><details><summary>Gahz'ranka</summary>2</details><br /><details><summary>Emperor Vek'lor</summary>10</details><br /><details><summary>High Priestess Arlokk</summary>2</details><br /><details><summary>Firemaw</summary>7</details><br /><details><summary>Chromaggus</summary>7</details><br /><details><summary>Garr</summary>5</details><br /></details><br /><details><summary>Standby Guild Ranks</summary><br /><details><summary>Guild Master</summary>False</details><br /><details><summary>Officer</summary>False</details><br /><details><summary>Accounting</summary>False</details><br /><details><summary>Class Leader</summary>False</details><br /><details><summary>Raider</summary>False</details><br /><details><summary>Trial</summary>False</details><br /><details><summary>Social</summary>False</details><br /><details><summary>Alt</summary>False</details><br /><details><summary>Fresh Meat</summary>False</details><br /><details><summary></summary>False</details><br /></details><br /><details><summary>Slot Weights</summary><br /><details><summary>2HWEAPON</summary>2</details><br /><details><summary>NECK</summary>0.5</details><br /><details><summary>HEAD</summary>1</details><br /><details><summary>WEAPON</summary>1.5</details><br /><details><summary>WRIST</summary>0.5</details><br /><details><summary>WEAPONMAINHAND</summary>1.5</details><br /><details><summary>SHIELD</summary>0.5</details><br /><details><summary>HOLDABLE</summary>0.5</details><br /><details><summary>RANGED</summary>0.5</details><br /><details><summary>THROWN</summary>0.5</details><br /><details><summary>FEET</summary>0.75</details><br /><details><summary>RELIC</summary>0.5</details><br /><details><summary>RANGEDRIGHT</summary>0.5</details><br /><details><summary>WEAPONOFFHAND</summary>0.5</details><br /><details><summary>TRINKET</summary>0.75</details><br /><details><summary>FINGER</summary>0.5</details><br /><details><summary>CLOAK</summary>0.5</details><br /><details><summary>CHEST</summary>1</details><br /><details><summary>ROBE</summary>1</details><br /><details><summary>HAND</summary>0.75</details><br /><details><summary>WAIST</summary>0.75</details><br /><details><summary>EXCEPTION</summary>1</details><br /><details><summary>LEGS</summary>1</details><br /><details><summary>SHOULDER</summary>0.75</details><br /></details><br /></details>

**Comment by Alumian** [comment]
Ok thanks. This bug was observed in my raid last night, so I'll be looking into this shortly.
