### ISSUE TITLE
GP cost on tooltips

### ISSUE THREAD

**Issue by skombag** [Alumian/CEPGP-Retail#34]
Ok firstly i would like to explain an issue i had last raid.
we Raided onyxia and during the encounter some addon got a window stuck over my raidframes and i could not heal and i was forced to /reload during combat. After the reaload i got the question from CEPGP if i want to handle the raid with it pressed yes just like at the start , but the issue was when the boss was dead the ep awards went to everyone as it should just that when i Looted the corpse as ML there was no popup and it took me quite a while to figure out the itemcost to do the distribution manualy for the proper price .

So the request is if its posible for the addon to link itself to tooltips of items and show a GP cost with the selected settings it has for slot weight and the rest.
And maybe theres a command im not aware to make the ui popup for looting, but still GP costs would make life alot easier because then ppl would know the cost and ask less questions :P

Thank you.                                                                                             Skom <Epoch>- Razorgore

**Comment by mykkenny** [comment]
GP Cost on tooltips in general would be great for auditing purposes (if anything goes wrong I can just look at someone's gear and see the GP cost). Something that simply adds 'GP: XX' to the tooltip where XX is derived from the current formula would be awesome.

**Comment by Alumian** [comment]
Added in the next update.
