### ISSUE TITLE
[Question] How do i get the gui to appear for a playing wanting loot?

### ISSUE THREAD

**Issue by hardtofin** [Alumian/CEPGP-Retail#36]
Hi there.

First of all, love this addon, thank you for taking it on and fixing it for classic.

I tested this tonight in RFC just with 2 people.  I set myself as master looter and went in with one other member who also had cepgp installed.  I set the threshold to uncommon (green).

When a green item dropped, no gui appeared on the other players screen enabling them to declare an interest in the piece of gear.  We both have the gui option checked in options.

When i clicked it as master looter i did then get a ui pop up asking if i wanted to hand it to myself or the other player, but as i say, on the other players screen they had no way of declaring interest in the item.

Am i doing something stupidly wrong?

Many thanks!

EDIT:  Is it possible that this only works in the actual raids and not dungeons, is it looking for certain items to drop or something?

With the old epgp lootmaster addon, players would automatically get a window pop up when the loot master clicked on the boss after he was killed.

**Comment by Alumian** [comment]
Hey Hardtofin,
Thanks for the question. So just to clarify, everyone in the raid needs to have the add-on installed for the GUI to pop up. Also I think it's.important to know that this isn't a port of EPGP LootMaster so you shouldn't expect identical functionality. Could you please confirm if the other people in the party/raid have the add-on installed and running?
This feature will work both in and outside of normal raids

**Comment by hardtofin** [comment]
Hi Alumian,

Yes both players had the addon installed and had the gui option for loot enabled.  The master loot got a choice who to hand the loot to, but the other "normal" player didn't get anything appear on screen.

**Comment by Alumian** [comment]
Okay so I've just re-read your initial post, I'd just like to go through the steps for loot distribution just to ensure that we're on the same page.
1. While in a raid group and while you are master loot, you should type /cep show and go to the loot distribution window (if an item in the loot window is blue or rarer, the loot distribution window will automatically pop up). As you have mentioned in your initial post that you can see the GUI window, I can safely assume that you have enabled the option for GUI loot distribution.
2. Click the red 'announce' button next to the item you would like to distribute
3. All players currently running the addon of at least version 1.11.4 should see the GUI distribution window
Are those the steps that you have followed? Can you try again on another creature and tell me if it works? You can actually try it with any item if you type /cep debugmode but you won't be able to master loot it. If you do choose to use debugmode then do be careful, you can still award GP for items even if they are not actually given out.

**Comment by hardtofin** [comment]
I was only in a party in rage fire chasm.  Was this the problem then, that it was just a party?  Do you HAVE to be in a raid group?  If so i can test that for sure, and can i just test it anywhere, even in the open world, as long as it's a raid group and an item above the threshold drops?

**Comment by Alumian** [comment]
Okay so yeah, you need to be in a raid group. If you're not in a raid group and you click the announce button then the addon should show you a message in your chat frame something like "You must be in a raid group" or something along those lines.
Okay so to test, can you please group with someone, convert to raid, type /cep debugmode, go kill anything that drops something other than currency and click the announce button.

**Comment by Alumian** [comment]
Hey Hardtofin, any update on this?

**Comment by hardtofin** [comment]
hi there.   i haven't had chance to test this but i will do it today. i will report back as soon as i have.

**Comment by hardtofin** [comment]
hi there Alumian.  

Ok i have thoroughly tested this and i can't get it to work.  No matter what i do, i NEVER get an announce button appear, i dont even get a "loot distribution" button.  I tried this is a raid group outside of Org whith debugmode enabled.  I also entered RFC as a raid group, had a green drop which was the minimum threshold and could allocate it to someone, but never go an announce or loot distribution button either.  In RFC i tried this with debug mode both on and off :(

**Comment by hardtofin** [comment]
update, i have tested this addon in total isolation with nothing else installed and still dont see a loot distribution button
<img width="497" alt="Screenshot 2019-10-02 at 19 22 09" src="https://user-images.githubusercontent.com/29480666/66070845-f9eddf00-e549-11e9-8072-c9240e70dff8.png">

**Comment by bnich** [comment]
I stopped seeing any windows after the last update. I assume its something to do with ElvUI.

**Comment by hardtofin** [comment]
@bnich i have run it with elvui totally disabled, the only addon i had running was cepgp and i still didnt see the button for loot distribution

**Comment by Alumian** [comment]
And you're in a raid group?

**Comment by hardtofin** [comment]
<img width="542" alt="Screenshot 2019-10-02 at 21 26 41" src="https://user-images.githubusercontent.com/29480666/66079120-5b6a7980-e55b-11e9-829b-b1cac8741803.png">
raid group now, same :(

**Comment by hardtofin** [comment]
<details><summary>Debug Info</summary><br />Version: 1.11.5<br /><br />GP Modifier: 1<br /><br />Base GP: 1<br /><br />Standby EP: True<br /><br />Standby Offline: False<br /><br />Standby Percent: 0<br /><br />Standby Accept Whispers: False<br /><br />Standby EP by Rank: True<br /><br />Standby EP Manual Delegation: False<br /><br />GUI for Loot: True<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary><br /><details><summary>High Priestess Jeklik</summary>True</details><br /><details><summary>Gothik the Harvester</summary>True</details><br /><details><summary>Buru the Gorger</summary>True</details><br /><details><summary>Wushoolay</summary>True</details><br /><details><summary>Lord Kri</summary>True</details><br /><details><summary>Emperor Vek'nilash</summary>True</details><br /><details><summary>Ossirian the Unscarred</summary>True</details><br /><details><summary>Golemagg the Incinerator</summary>True</details><br /><details><summary>Grand Widow Faerlina</summary>True</details><br /><details><summary>High Priestess Mar'li</summary>True</details><br /><details><summary>Majordomo Executus</summary>True</details><br /><details><summary>High Priest Venoxis</summary>True</details><br /><details><summary>Gehennas</summary>True</details><br /><details><summary>Taerar</summary>True</details><br /><details><summary>Ysondre</summary>True</details><br /><details><summary>Thane Korth'azz</summary>True</details><br /><details><summary>High Priest Thekal</summary>True</details><br /><details><summary>Noth the Plaguebringer</summary>True</details><br /><details><summary>Lethon</summary>True</details><br /><details><summary>Moam</summary>True</details><br /><details><summary>The Prophet Skeram</summary>True</details><br /><details><summary>Flamegor</summary>True</details><br /><details><summary>C'Thun</summary>True</details><br /><details><summary>General Rajaxx</summary>True</details><br /><details><summary>Princess Huhuran</summary>True</details><br /><details><summary>Thaddius</summary>True</details><br /><details><summary>Loatheb</summary>True</details><br /><details><summary>Lady Blaumeux</summary>True</details><br /><details><summary>Highlord Mograine</summary>True</details><br /><details><summary>Heigan the Unclean</summary>True</details><br /><details><summary>Azuregos</summary>True</details><br /><details><summary>Doom Lord Kazzak</summary>True</details><br /><details><summary>Teremus the Devourer</summary>True</details><br /><details><summary>Jin'do the Hexxer</summary>True</details><br /><details><summary>Baron Geddon</summary>True</details><br /><details><summary>Renataki</summary>True</details><br /><details><summary>Sulfuron Harbinger</summary>True</details><br /><details><summary>Gri'lek</summary>True</details><br /><details><summary>Bloodlord Mandokir</summary>True</details><br /><details><summary>Patchwerk</summary>True</details><br /><details><summary>Vaelastrasz the Corrupt</summary>True</details><br /><details><summary>Gluth</summary>True</details><br /><details><summary>Sapphiron</summary>True</details><br /><details><summary>Emeriss</summary>True</details><br /><details><summary>Onyxia</summary>True</details><br /><details><summary>Princess Yauj</summary>True</details><br /><details><summary>Kurinnaxx</summary>True</details><br /><details><summary>Shazzrah</summary>True</details><br /><details><summary>Ebonroc</summary>True</details><br /><details><summary>Battleguard Sartura</summary>True</details><br /><details><summary>Hakkar</summary>True</details><br /><details><summary>Kel'Thuzad</summary>True</details><br /><details><summary>Nefarian</summary>True</details><br /><details><summary>Fankriss the Unyielding</summary>True</details><br /><details><summary>Lucifron</summary>True</details><br /><details><summary>Anub'Rekhan</summary>True</details><br /><details><summary>Hazza'rah</summary>True</details><br /><details><summary>Viscidus</summary>True</details><br /><details><summary>Broodlord Lashlayer</summary>True</details><br /><details><summary>Ayamiss the Hunter</summary>True</details><br /><details><summary>Ragnaros</summary>True</details><br /><details><summary>Maexxna</summary>True</details><br /><details><summary>Ouro</summary>True</details><br /><details><summary>Vem</summary>True</details><br /><details><summary>Grobbulus</summary>True</details><br /><details><summary>Instructor Razuvious</summary>True</details><br /><details><summary>Razorgore the Untamed</summary>True</details><br /><details><summary>Magmadar</summary>True</details><br /><details><summary>Sir Zeliek</summary>True</details><br /><details><summary>Gahz'ranka</summary>True</details><br /><details><summary>Emperor Vek'lor</summary>True</details><br /><details><summary>High Priestess Arlokk</summary>True</details><br /><details><summary>Firemaw</summary>True</details><br /><details><summary>Chromaggus</summary>True</details><br /><details><summary>Garr</summary>True</details><br /></details><br /><details><summary>EP Values</summary><br /><details><summary>High Priestess Jeklik</summary>2</details><br /><details><summary>Gothik the Harvester</summary>12</details><br /><details><summary>Buru the Gorger</summary>3</details><br /><details><summary>Wushoolay</summary>2</details><br /><details><summary>Lord Kri</summary>10</details><br /><details><summary>Emperor Vek'nilash</summary>10</details><br /><details><summary>Ossirian the Unscarred</summary>4</details><br /><details><summary>Golemagg the Incinerator</summary>5</details><br /><details><summary>Grand Widow Faerlina</summary>12</details><br /><details><summary>High Priestess Mar'li</summary>2</details><br /><details><summary>Majordomo Executus</summary>5</details><br /><details><summary>High Priest Venoxis</summary>2</details><br /><details><summary>Gehennas</summary>5</details><br /><details><summary>Taerar</summary>7</details><br /><details><summary>Ysondre</summary>7</details><br /><details><summary>Thane Korth'azz</summary>15</details><br /><details><summary>High Priest Thekal</summary>2</details><br /><details><summary>Noth the Plaguebringer</summary>12</details><br /><details><summary>Lethon</summary>7</details><br /><details><summary>Moam</summary>3</details><br /><details><summary>The Prophet Skeram</summary>10</details><br /><details><summary>Flamegor</summary>7</details><br /><details><summary>C'Thun</summary>12</details><br /><details><summary>General Rajaxx</summary>3</details><br /><details><summary>Princess Huhuran</summary>10</details><br /><details><summary>Thaddius</summary>15</details><br /><details><summary>Loatheb</summary>15</details><br /><details><summary>Lady Blaumeux</summary>15</details><br /><details><summary>Highlord Mograine</summary>15</details><br /><details><summary>Heigan the Unclean</summary>12</details><br /><details><summary>Azuregos</summary>7</details><br /><details><summary>Doom Lord Kazzak</summary>7</details><br /><details><summary>Teremus the Devourer</summary>7</details><br /><details><summary>Jin'do the Hexxer</summary>2</details><br /><details><summary>Baron Geddon</summary>5</details><br /><details><summary>Renataki</summary>2</details><br /><details><summary>Sulfuron Harbinger</summary>5</details><br /><details><summary>Gri'lek</summary>2</details><br /><details><summary>Bloodlord Mandokir</summary>2</details><br /><details><summary>Patchwerk</summary>12</details><br /><details><summary>Vaelastrasz the Corrupt</summary>7</details><br /><details><summary>Gluth</summary>12</details><br /><details><summary>Sapphiron</summary>15</details><br /><details><summary>Emeriss</summary>7</details><br /><details><summary>Onyxia</summary>5</details><br /><details><summary>Princess Yauj</summary>10</details><br /><details><summary>Kurinnaxx</summary>3</details><br /><details><summary>Shazzrah</summary>5</details><br /><details><summary>Ebonroc</summary>7</details><br /><details><summary>Battleguard Sartura</summary>10</details><br /><details><summary>Hakkar</summary>3</details><br /><details><summary>Kel'Thuzad</summary>15</details><br /><details><summary>Nefarian</summary>10</details><br /><details><summary>Fankriss the Unyielding</summary>10</details><br /><details><summary>Lucifron</summary>5</details><br /><details><summary>Anub'Rekhan</summary>12</details><br /><details><summary>Hazza'rah</summary>2</details><br /><details><summary>Viscidus</summary>10</details><br /><details><summary>Broodlord Lashlayer</summary>7</details><br /><details><summary>Ayamiss the Hunter</summary>3</details><br /><details><summary>Ragnaros</summary>7</details><br /><details><summary>Maexxna</summary>15</details><br /><details><summary>Ouro</summary>10</details><br /><details><summary>Vem</summary>10</details><br /><details><summary>Grobbulus</summary>12</details><br /><details><summary>Instructor Razuvious</summary>12</details><br /><details><summary>Razorgore the Untamed</summary>7</details><br /><details><summary>Magmadar</summary>5</details><br /><details><summary>Sir Zeliek</summary>15</details><br /><details><summary>Gahz'ranka</summary>2</details><br /><details><summary>Emperor Vek'lor</summary>10</details><br /><details><summary>High Priestess Arlokk</summary>2</details><br /><details><summary>Firemaw</summary>7</details><br /><details><summary>Chromaggus</summary>7</details><br /><details><summary>Garr</summary>5</details><br /></details><br /><details><summary>Standby Guild Ranks</summary><br /><details><summary>Guild Master</summary>False</details><br /><details><summary>Officer</summary>False</details><br /><details><summary>Officer Alt</summary>False</details><br /><details><summary>Raid Team</summary>False</details><br /><details><summary>Member</summary>False</details><br /><details><summary>Alt</summary>False</details><br /><details><summary>Class Leader</summary>False</details><br /><details><summary>Trial</summary>False</details><br /><details><summary>2</summary>False</details><br /><details><summary>3</summary>False</details><br /></details><br /><details><summary>Slot Weights</summary><br /><details><summary>2HWEAPON</summary>2</details><br /><details><summary>NECK</summary>0.5</details><br /><details><summary>HEAD</summary>1</details><br /><details><summary>WEAPON</summary>1.5</details><br /><details><summary>WRIST</summary>0.5</details><br /><details><summary>WEAPONMAINHAND</summary>1.5</details><br /><details><summary>SHIELD</summary>0.5</details><br /><details><summary>HOLDABLE</summary>0.5</details><br /><details><summary>RANGED</summary>0.5</details><br /><details><summary>THROWN</summary>0.5</details><br /><details><summary>FEET</summary>0.75</details><br /><details><summary>RELIC</summary>0.5</details><br /><details><summary>RANGEDRIGHT</summary>0.5</details><br /><details><summary>WEAPONOFFHAND</summary>0.5</details><br /><details><summary>TRINKET</summary>0.75</details><br /><details><summary>FINGER</summary>0.5</details><br /><details><summary>CLOAK</summary>0.5</details><br /><details><summary>CHEST</summary>1</details><br /><details><summary>ROBE</summary>1</details><br /><details><summary>HAND</summary>0.75</details><br /><details><summary>WAIST</summary>0.75</details><br /><details><summary>EXCEPTION</summary>1</details><br /><details><summary>LEGS</summary>1</details><br /><details><summary>SHOULDER</summary>0.75</details><br /></details><br /><details><summary>Addons List</summary><br />Accountant_Classic<br />AdiBags<br />AdiBags_Config<br />Ara_Broker_Guild_Friends<br />Ara_Broker_Reputations<br />Atlas<br />Atlas_ClassicWoW<br />AtlasLootClassic_Options<br />AtlasLootClassic_Collections<br />AtlasLootClassic_Crafting<br />AtlasLootClassic_DungeonsAndRaids<br />AtlasLootClassic_Factions<br />AtlasLootClassic_PvP<br />AtlasLootClassic<br />AtlasQuest<br />Auctionator<br />BetterVendorPrice<br />!BugGrabber<br />BugSack<br />CEPGP<br />Classic Quest Log<br />ClassicSpellActivations<br />ClassicThreatMeter<br />Details<br />Details_TinyThreat<br />FishingBuddy<br />GlobalIgnoreList<br />GnomishVendorShrinker<br />GTFO<br />GuildTracker<br />Immersion<br />InFlight<br />InFlight_Load<br />LetMeCast<br />LoseControl<br />MarketWatcher<br />OmniCC<br />OmniCC_Config<br />OPie_Classic<br />Plater<br />QuestLogEx<br />QuestXP<br />QuickLayer<br />Raven<br />Raven_Options<br />RealMobHealth<br />RingMenu<br />Skillet-Classic<br />Spy<br />Storyline<br />TinyTooltip<br />VanasKoS<br />WeakAuras<br />WeakAurasOptions<br />Whisp<br />WideQuestLog<br />XpTracker<br />shPerformance<br />ProjectAzilroka<br />AddOnSkins<br />ElvUI_DTBars2<br />ElvUI_QuestXP_Classic<br />ElvUI_SkullflowerTP<br />ElvUI_LocationPlus<br />ElvUI<br />ElvUI_OptionsUI<br />Questie<br /></details></details>

**Comment by Alumian** [comment]
This is gonna sound silly...but are you looking a corpse at the moment?

**Comment by hardtofin** [comment]
no

**Comment by Alumian** [comment]
Alright, you need to be looting something for the loot distribution button to appear, otherwise it doesn't have anything to show in the frame. Give that a try.

**Comment by hardtofin** [comment]
yeh but i have this problem even with no other addon running besides CEPGP.  Let me screenshot and send you a debug report

<img width="648" alt="Screenshot 2019-10-02 at 21 33 11" src="https://user-images.githubusercontent.com/29480666/66079620-4f32ec00-e55c-11e9-8913-d69630cd3889.png">


<details><summary>Debug Info</summary><br />Version: 1.11.5<br /><br />GP Modifier: 1<br /><br />Base GP: 1<br /><br />Standby EP: True<br /><br />Standby Offline: False<br /><br />Standby Percent: 0<br /><br />Standby Accept Whispers: False<br /><br />Standby EP by Rank: True<br /><br />Standby EP Manual Delegation: False<br /><br />GUI for Loot: True<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary><br /><details><summary>High Priestess Jeklik</summary>True</details><br /><details><summary>Gothik the Harvester</summary>True</details><br /><details><summary>Buru the Gorger</summary>True</details><br /><details><summary>Wushoolay</summary>True</details><br /><details><summary>Lord Kri</summary>True</details><br /><details><summary>Emperor Vek'nilash</summary>True</details><br /><details><summary>Ossirian the Unscarred</summary>True</details><br /><details><summary>Golemagg the Incinerator</summary>True</details><br /><details><summary>Grand Widow Faerlina</summary>True</details><br /><details><summary>High Priestess Mar'li</summary>True</details><br /><details><summary>Majordomo Executus</summary>True</details><br /><details><summary>High Priest Venoxis</summary>True</details><br /><details><summary>Gehennas</summary>True</details><br /><details><summary>Taerar</summary>True</details><br /><details><summary>Ysondre</summary>True</details><br /><details><summary>Thane Korth'azz</summary>True</details><br /><details><summary>High Priest Thekal</summary>True</details><br /><details><summary>Noth the Plaguebringer</summary>True</details><br /><details><summary>Lethon</summary>True</details><br /><details><summary>Moam</summary>True</details><br /><details><summary>The Prophet Skeram</summary>True</details><br /><details><summary>Flamegor</summary>True</details><br /><details><summary>C'Thun</summary>True</details><br /><details><summary>General Rajaxx</summary>True</details><br /><details><summary>Princess Huhuran</summary>True</details><br /><details><summary>Thaddius</summary>True</details><br /><details><summary>Loatheb</summary>True</details><br /><details><summary>Lady Blaumeux</summary>True</details><br /><details><summary>Highlord Mograine</summary>True</details><br /><details><summary>Heigan the Unclean</summary>True</details><br /><details><summary>Azuregos</summary>True</details><br /><details><summary>Doom Lord Kazzak</summary>True</details><br /><details><summary>Teremus the Devourer</summary>True</details><br /><details><summary>Chromaggus</summary>True</details><br /><details><summary>Baron Geddon</summary>True</details><br /><details><summary>Firemaw</summary>True</details><br /><details><summary>Sulfuron Harbinger</summary>True</details><br /><details><summary>Gri'lek</summary>True</details><br /><details><summary>High Priestess Arlokk</summary>True</details><br /><details><summary>Emperor Vek'lor</summary>True</details><br /><details><summary>Gahz'ranka</summary>True</details><br /><details><summary>Gluth</summary>True</details><br /><details><summary>Sapphiron</summary>True</details><br /><details><summary>Razorgore the Untamed</summary>True</details><br /><details><summary>Onyxia</summary>True</details><br /><details><summary>Princess Yauj</summary>True</details><br /><details><summary>Vem</summary>True</details><br /><details><summary>Shazzrah</summary>True</details><br /><details><summary>Ouro</summary>True</details><br /><details><summary>Battleguard Sartura</summary>True</details><br /><details><summary>Maexxna</summary>True</details><br /><details><summary>Kel'Thuzad</summary>True</details><br /><details><summary>Nefarian</summary>True</details><br /><details><summary>Fankriss the Unyielding</summary>True</details><br /><details><summary>Lucifron</summary>True</details><br /><details><summary>Anub'Rekhan</summary>True</details><br /><details><summary>Hazza'rah</summary>True</details><br /><details><summary>Ragnaros</summary>True</details><br /><details><summary>Ayamiss the Hunter</summary>True</details><br /><details><summary>Broodlord Lashlayer</summary>True</details><br /><details><summary>Viscidus</summary>True</details><br /><details><summary>Hakkar</summary>True</details><br /><details><summary>Ebonroc</summary>True</details><br /><details><summary>Kurinnaxx</summary>True</details><br /><details><summary>Grobbulus</summary>True</details><br /><details><summary>Instructor Razuvious</summary>True</details><br /><details><summary>Emeriss</summary>True</details><br /><details><summary>Magmadar</summary>True</details><br /><details><summary>Sir Zeliek</summary>True</details><br /><details><summary>Vaelastrasz the Corrupt</summary>True</details><br /><details><summary>Patchwerk</summary>True</details><br /><details><summary>Bloodlord Mandokir</summary>True</details><br /><details><summary>Renataki</summary>True</details><br /><details><summary>Jin'do the Hexxer</summary>True</details><br /><details><summary>Garr</summary>True</details><br /></details><br /><details><summary>EP Values</summary><br /><details><summary>High Priestess Jeklik</summary>2</details><br /><details><summary>Gothik the Harvester</summary>12</details><br /><details><summary>Buru the Gorger</summary>3</details><br /><details><summary>Wushoolay</summary>2</details><br /><details><summary>Lord Kri</summary>10</details><br /><details><summary>Emperor Vek'nilash</summary>10</details><br /><details><summary>Ossirian the Unscarred</summary>4</details><br /><details><summary>Golemagg the Incinerator</summary>5</details><br /><details><summary>Grand Widow Faerlina</summary>12</details><br /><details><summary>High Priestess Mar'li</summary>2</details><br /><details><summary>Majordomo Executus</summary>5</details><br /><details><summary>High Priest Venoxis</summary>2</details><br /><details><summary>Gehennas</summary>5</details><br /><details><summary>Taerar</summary>7</details><br /><details><summary>Ysondre</summary>7</details><br /><details><summary>Thane Korth'azz</summary>15</details><br /><details><summary>High Priest Thekal</summary>2</details><br /><details><summary>Noth the Plaguebringer</summary>12</details><br /><details><summary>Lethon</summary>7</details><br /><details><summary>Moam</summary>3</details><br /><details><summary>The Prophet Skeram</summary>10</details><br /><details><summary>Flamegor</summary>7</details><br /><details><summary>C'Thun</summary>12</details><br /><details><summary>General Rajaxx</summary>3</details><br /><details><summary>Princess Huhuran</summary>10</details><br /><details><summary>Thaddius</summary>15</details><br /><details><summary>Loatheb</summary>15</details><br /><details><summary>Lady Blaumeux</summary>15</details><br /><details><summary>Highlord Mograine</summary>15</details><br /><details><summary>Heigan the Unclean</summary>12</details><br /><details><summary>Azuregos</summary>7</details><br /><details><summary>Doom Lord Kazzak</summary>7</details><br /><details><summary>Teremus the Devourer</summary>7</details><br /><details><summary>Chromaggus</summary>7</details><br /><details><summary>Baron Geddon</summary>5</details><br /><details><summary>Firemaw</summary>7</details><br /><details><summary>Sulfuron Harbinger</summary>5</details><br /><details><summary>Gri'lek</summary>2</details><br /><details><summary>High Priestess Arlokk</summary>2</details><br /><details><summary>Emperor Vek'lor</summary>10</details><br /><details><summary>Gahz'ranka</summary>2</details><br /><details><summary>Gluth</summary>12</details><br /><details><summary>Sapphiron</summary>15</details><br /><details><summary>Razorgore the Untamed</summary>7</details><br /><details><summary>Onyxia</summary>5</details><br /><details><summary>Princess Yauj</summary>10</details><br /><details><summary>Vem</summary>10</details><br /><details><summary>Shazzrah</summary>5</details><br /><details><summary>Ouro</summary>10</details><br /><details><summary>Battleguard Sartura</summary>10</details><br /><details><summary>Maexxna</summary>15</details><br /><details><summary>Kel'Thuzad</summary>15</details><br /><details><summary>Nefarian</summary>10</details><br /><details><summary>Fankriss the Unyielding</summary>10</details><br /><details><summary>Lucifron</summary>5</details><br /><details><summary>Anub'Rekhan</summary>12</details><br /><details><summary>Hazza'rah</summary>2</details><br /><details><summary>Ragnaros</summary>7</details><br /><details><summary>Ayamiss the Hunter</summary>3</details><br /><details><summary>Broodlord Lashlayer</summary>7</details><br /><details><summary>Viscidus</summary>10</details><br /><details><summary>Hakkar</summary>3</details><br /><details><summary>Ebonroc</summary>7</details><br /><details><summary>Kurinnaxx</summary>3</details><br /><details><summary>Grobbulus</summary>12</details><br /><details><summary>Instructor Razuvious</summary>12</details><br /><details><summary>Emeriss</summary>7</details><br /><details><summary>Magmadar</summary>5</details><br /><details><summary>Sir Zeliek</summary>15</details><br /><details><summary>Vaelastrasz the Corrupt</summary>7</details><br /><details><summary>Patchwerk</summary>12</details><br /><details><summary>Bloodlord Mandokir</summary>2</details><br /><details><summary>Renataki</summary>2</details><br /><details><summary>Jin'do the Hexxer</summary>2</details><br /><details><summary>Garr</summary>5</details><br /></details><br /><details><summary>Standby Guild Ranks</summary><br /><details><summary>Guild Master</summary>False</details><br /><details><summary>Officer</summary>False</details><br /><details><summary>Officer Alt</summary>False</details><br /><details><summary>Raid Team</summary>False</details><br /><details><summary>Member</summary>False</details><br /><details><summary>Alt</summary>False</details><br /><details><summary>Class Leader</summary>False</details><br /><details><summary>Trial</summary>False</details><br /><details><summary>2</summary>False</details><br /><details><summary>3</summary>False</details><br /></details><br /><details><summary>Slot Weights</summary><br /><details><summary>2HWEAPON</summary>2</details><br /><details><summary>NECK</summary>0.5</details><br /><details><summary>HEAD</summary>1</details><br /><details><summary>WEAPON</summary>1.5</details><br /><details><summary>WRIST</summary>0.5</details><br /><details><summary>WEAPONMAINHAND</summary>1.5</details><br /><details><summary>SHIELD</summary>0.5</details><br /><details><summary>HOLDABLE</summary>0.5</details><br /><details><summary>RANGED</summary>0.5</details><br /><details><summary>SHOULDER</summary>0.75</details><br /><details><summary>FEET</summary>0.75</details><br /><details><summary>LEGS</summary>1</details><br /><details><summary>EXCEPTION</summary>1</details><br /><details><summary>WAIST</summary>0.75</details><br /><details><summary>TRINKET</summary>0.75</details><br /><details><summary>HAND</summary>0.75</details><br /><details><summary>ROBE</summary>1</details><br /><details><summary>CHEST</summary>1</details><br /><details><summary>CLOAK</summary>0.5</details><br /><details><summary>FINGER</summary>0.5</details><br /><details><summary>WEAPONOFFHAND</summary>0.5</details><br /><details><summary>RANGEDRIGHT</summary>0.5</details><br /><details><summary>RELIC</summary>0.5</details><br /><details><summary>THROWN</summary>0.5</details><br /></details><br /><details><summary>Addons List</summary><br />Accountant_Classic<br />AdiBags<br />AdiBags_Config<br />Ara_Broker_Guild_Friends<br />Ara_Broker_Reputations<br />Atlas<br />Atlas_ClassicWoW<br />AtlasLootClassic_Options<br />AtlasLootClassic_Collections<br />AtlasLootClassic_Crafting<br />AtlasLootClassic_DungeonsAndRaids<br />AtlasLootClassic_Factions<br />AtlasLootClassic_PvP<br />AtlasLootClassic<br />AtlasQuest<br />Auctionator<br />BetterVendorPrice<br />!BugGrabber<br />BugSack<br />CEPGP<br />Classic Quest Log<br />ClassicSpellActivations<br />ClassicThreatMeter<br />Details<br />Details_TinyThreat<br />FishingBuddy<br />GlobalIgnoreList<br />GnomishVendorShrinker<br />GTFO<br />GuildTracker<br />Immersion<br />InFlight<br />InFlight_Load<br />LetMeCast<br />LoseControl<br />MarketWatcher<br />OmniCC<br />OmniCC_Config<br />OPie_Classic<br />Plater<br />QuestLogEx<br />QuestXP<br />QuickLayer<br />Raven<br />Raven_Options<br />RealMobHealth<br />RingMenu<br />Skillet-Classic<br />Spy<br />Storyline<br />TinyTooltip<br />VanasKoS<br />WeakAuras<br />WeakAurasOptions<br />Whisp<br />WideQuestLog<br />XpTracker<br />shPerformance<br />ProjectAzilroka<br />AddOnSkins<br />ElvUI_DTBars2<br />ElvUI_QuestXP_Classic<br />ElvUI_SkullflowerTP<br />ElvUI_LocationPlus<br />ElvUI<br />ElvUI_OptionsUI<br />Questie<br /></details></details>

**Comment by Alumian** [comment]
Okay so try opening a loot window and let me know how that goes. If that doesn't work I'd like to screen share over discord or something so I can see what's going wrong.

**Comment by hardtofin** [comment]
in debug mode or just normally?

**Comment by hardtofin** [comment]
whats your discord mate, i can share now with you as im in game :)

**Comment by Alumian** [comment]
Just normally - debugmode only lets you announce sub-threshold items. My discord is Alumian#6465 but I'm about to head off to work. Can we do it in like an hour and a bit?

**Comment by hardtofin** [comment]
yes thats fine, i sent you a friend request on discord

**Comment by hardtofin** [comment]
for the loot window test, do i need to be master looter i assume?

**Comment by Alumian** [comment]
I spoke with Hardtofin earlier today. For anyone else experiencing this issue, please try the following:

- Ensure that you are in a raid group
- Ensure that the loot method is master looter
- Ensure that there are non-currency items on the corpse
- Ensure that when you select master loot as the loot method, that you click yes when the addon prompts you to use it

I am looking at producing a guide in the near future, a 'how-to' for CEPGP. I will post in the readme file when the guide has been produced. At the conclusion of our discussion, we found that no bug was present.
