### ISSUE TITLE
[Bug] AQ and Naxxramas auto award config dont save

### ISSUE THREAD

**Issue by Andrioden** [Alumian/CEPGP-Retail#38]
When I update the EP value or cross off Auto Award. The value is not saved, so when I go out and inn to the options its reverted back to the original value.
![image](https://user-images.githubusercontent.com/393376/66019355-4baf4e80-e4e3-11e9-8574-d360ecb5d2af.png)
![image](https://user-images.githubusercontent.com/393376/66019373-65e92c80-e4e3-11e9-865b-c90ff30ee83a.png)

Other than that, thanks for an great addon! We started using it for wow classic, and it works great.

**Comment by Alumian** [comment]
Hey Andrioden!
Thanks for submitting this report. Not a problem, I'll check that out when I get home today - I suspect I know the problem but I'll need to confirm. I'll keep you posted.

Thanks

**Comment by Alumian** [comment]
@Andrioden can you please type /cep debug and copy and paste that string into this thread? Thanks

**Comment by Alumian** [comment]
Nevermind....I just found the bug and it's the dumbest thing ever lol. I'll have it fixed in the next update.
