### ISSUE TITLE
[Bug] Unintended huge price difference between T1 Chestpieces?

### ISSUE THREAD

**Issue by PibbzTV** [Alumian/CEPGP-Retail#39]
Greetings Alumian, thanks again for this great addon!

Just wanted to report a finding from yesterdays MC raid. After Golemagg died, we noticed that there was a 10GP difference between the Cenarion chestpiece, and the Nightslayer chestpiece with our current slot weights and GP formula.

My initial thought is that they should be identical in price? The same thing happened later in our second raidgroup, but with Felheart Robes and Brestplate of Might.

Seems to be the first one looted that goes for 23, the second is priced at 33, don't know if that is valuable info.

Is this intended or not? 
![epgpbug](https://user-images.githubusercontent.com/51060651/66110407-019f9900-e5c7-11e9-9ffb-bc180289b4e2.jpg)
![epgpbug2](https://user-images.githubusercontent.com/51060651/66110408-019f9900-e5c7-11e9-80b9-1b0d8f1c5b81.jpg)
![slotweights](https://user-images.githubusercontent.com/51060651/66110412-0401f300-e5c7-11e9-86f0-52e5aa7c4da0.jpg)

**Comment by Alumian** [comment]
Hey Pibbz,
That's really odd - those items all have the same item level, rarity and slot type. Can you confirm if this issue was present when you announced the items? i.e. did they announce for 23 and 33? According to the calculation I ran based on your slot weights and formula, the value should have been 23 for all of the items.

**Comment by Alumian** [comment]
Okay so I've looked into this and it turns out that the items that were being undervalued were actually falling under the slot category "Robe" which is a technical subtype. I've accommodated for this and it has been packaged into the next update.

**Comment by PibbzTV** [comment]
Cool, good job! I have another potentially related issue aswell. The Tier 1 and tier 2 legs both seem to have the same price, despite the T2 legs being10ilvls higher. Any chance you can look into that aswell?

**Comment by PibbzTV** [comment]
![t1t2pants](https://user-images.githubusercontent.com/51060651/66372767-215c0600-e9a7-11e9-8641-ce75168b83a8.jpg)

**Comment by Alumian** [comment]
Ah yep, it has recently been raised with me that the default formula I put in renders item level differences, redundant. I suggest changing the second value in the formula, where the default formula is 4.83*(x^((ilvl/26.... - change x from 1 if you haven't already.
You can check in game what the GP for an item will be if you type:
`/script print(CEPGP_calcGP(_, 1, x));`
Just swap out x for the ID of an item an it'll tell you what the GP is based on your current formula. Let me know if you're not too sure on how to find an item ID.

**Comment by PibbzTV** [comment]
Perfect, this price check is exactly what i've been looking for. 
A quick comparison between Core Hound Tooth (1h Dagger) and Bonereaver's Edge (2h Sword) gives me a price of 50 GP for the dagger and 27 for the 2hander, even though 2hander is weighted at 0.8 and 1hander at 0.7 in my current weights. How can this be explained?

**Comment by Alumian** [comment]
Hmm.. can you please type /cep debug and paste the string into here?

**Comment by PibbzTV** [comment]
<details><summary>Debug Info</summary><br />Version: 1.11.5<br /><br />GP Modifier: 7<br /><br />Base GP: 5<br /><br />Standby EP: True<br /><br />Standby Offline: True<br /><br />Standby Percent: 100<br /><br />Standby Accept Whispers: True<br /><br />Standby EP by Rank: False<br /><br />Standby EP Manual Delegation: True<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: !standby<br /><br /><details><summary>Auto EP</summary><br /><details><summary>High Priestess Jeklik</summary>True</details><br /><details><summary>Gothik the Harvester</summary>True</details><br /><details><summary>Buru the Gorger</summary>True</details><br /><details><summary>Wushoolay</summary>True</details><br /><details><summary>Lord Kri</summary>True</details><br /><details><summary>Emperor Vek'nilash</summary>True</details><br /><details><summary>Ossirian the Unscarred</summary>True</details><br /><details><summary>Golemagg the Incinerator</summary>True</details><br /><details><summary>Grand Widow Faerlina</summary>True</details><br /><details><summary>High Priestess Mar'li</summary>True</details><br /><details><summary>Majordomo Executus</summary>True</details><br /><details><summary>High Priest Venoxis</summary>True</details><br /><details><summary>Gehennas</summary>True</details><br /><details><summary>Taerar</summary>True</details><br /><details><summary>Ysondre</summary>True</details><br /><details><summary>Thane Korth'azz</summary>True</details><br /><details><summary>High Priest Thekal</summary>True</details><br /><details><summary>Noth the Plaguebringer</summary>True</details><br /><details><summary>Lethon</summary>True</details><br /><details><summary>Moam</summary>True</details><br /><details><summary>The Prophet Skeram</summary>True</details><br /><details><summary>Flamegor</summary>True</details><br /><details><summary>C'Thun</summary>True</details><br /><details><summary>General Rajaxx</summary>True</details><br /><details><summary>Princess Huhuran</summary>True</details><br /><details><summary>Thaddius</summary>True</details><br /><details><summary>Loatheb</summary>True</details><br /><details><summary>Lady Blaumeux</summary>True</details><br /><details><summary>Highlord Mograine</summary>True</details><br /><details><summary>Heigan the Unclean</summary>True</details><br /><details><summary>Azuregos</summary>True</details><br /><details><summary>Doom Lord Kazzak</summary>True</details><br /><details><summary>Teremus the Devourer</summary>True</details><br /><details><summary>Chromaggus</summary>True</details><br /><details><summary>Baron Geddon</summary>True</details><br /><details><summary>Firemaw</summary>True</details><br /><details><summary>Sulfuron Harbinger</summary>True</details><br /><details><summary>Gri'lek</summary>True</details><br /><details><summary>High Priestess Arlokk</summary>True</details><br /><details><summary>Emperor Vek'lor</summary>True</details><br /><details><summary>Gahz'ranka</summary>True</details><br /><details><summary>Gluth</summary>True</details><br /><details><summary>Sapphiron</summary>True</details><br /><details><summary>Razorgore the Untamed</summary>True</details><br /><details><summary>Onyxia</summary>True</details><br /><details><summary>Princess Yauj</summary>True</details><br /><details><summary>Vem</summary>True</details><br /><details><summary>Shazzrah</summary>True</details><br /><details><summary>Ouro</summary>True</details><br /><details><summary>Battleguard Sartura</summary>True</details><br /><details><summary>Maexxna</summary>True</details><br /><details><summary>Kel'Thuzad</summary>True</details><br /><details><summary>Nefarian</summary>True</details><br /><details><summary>Fankriss the Unyielding</summary>True</details><br /><details><summary>Lucifron</summary>True</details><br /><details><summary>Anub'Rekhan</summary>True</details><br /><details><summary>Hazza'rah</summary>True</details><br /><details><summary>Ragnaros</summary>True</details><br /><details><summary>Ayamiss the Hunter</summary>True</details><br /><details><summary>Broodlord Lashlayer</summary>True</details><br /><details><summary>Viscidus</summary>True</details><br /><details><summary>Hakkar</summary>True</details><br /><details><summary>Ebonroc</summary>True</details><br /><details><summary>Kurinnaxx</summary>True</details><br /><details><summary>Grobbulus</summary>True</details><br /><details><summary>Instructor Razuvious</summary>True</details><br /><details><summary>Emeriss</summary>True</details><br /><details><summary>Magmadar</summary>True</details><br /><details><summary>Sir Zeliek</summary>True</details><br /><details><summary>Vaelastrasz the Corrupt</summary>True</details><br /><details><summary>Patchwerk</summary>True</details><br /><details><summary>Bloodlord Mandokir</summary>True</details><br /><details><summary>Renataki</summary>True</details><br /><details><summary>Jin'do the Hexxer</summary>True</details><br /><details><summary>Garr</summary>True</details><br /></details><br /><details><summary>EP Values</summary><br /><details><summary>High Priestess Jeklik</summary>2</details><br /><details><summary>Gothik the Harvester</summary>12</details><br /><details><summary>Buru the Gorger</summary>3</details><br /><details><summary>Wushoolay</summary>2</details><br /><details><summary>Lord Kri</summary>10</details><br /><details><summary>Emperor Vek'nilash</summary>10</details><br /><details><summary>Ossirian the Unscarred</summary>4</details><br /><details><summary>Golemagg the Incinerator</summary>10</details><br /><details><summary>Grand Widow Faerlina</summary>12</details><br /><details><summary>High Priestess Mar'li</summary>2</details><br /><details><summary>Majordomo Executus</summary>10</details><br /><details><summary>High Priest Venoxis</summary>2</details><br /><details><summary>Gehennas</summary>10</details><br /><details><summary>Taerar</summary>7</details><br /><details><summary>Ysondre</summary>7</details><br /><details><summary>Thane Korth'azz</summary>15</details><br /><details><summary>High Priest Thekal</summary>2</details><br /><details><summary>Noth the Plaguebringer</summary>12</details><br /><details><summary>Lethon</summary>7</details><br /><details><summary>Moam</summary>3</details><br /><details><summary>The Prophet Skeram</summary>10</details><br /><details><summary>Flamegor</summary>7</details><br /><details><summary>C'Thun</summary>12</details><br /><details><summary>General Rajaxx</summary>3</details><br /><details><summary>Princess Huhuran</summary>10</details><br /><details><summary>Thaddius</summary>15</details><br /><details><summary>Loatheb</summary>15</details><br /><details><summary>Lady Blaumeux</summary>15</details><br /><details><summary>Highlord Mograine</summary>15</details><br /><details><summary>Heigan the Unclean</summary>12</details><br /><details><summary>Azuregos</summary>7</details><br /><details><summary>Doom Lord Kazzak</summary>7</details><br /><details><summary>Teremus the Devourer</summary>7</details><br /><details><summary>Chromaggus</summary>7</details><br /><details><summary>Baron Geddon</summary>10</details><br /><details><summary>Firemaw</summary>7</details><br /><details><summary>Sulfuron Harbinger</summary>10</details><br /><details><summary>Gri'lek</summary>2</details><br /><details><summary>High Priestess Arlokk</summary>2</details><br /><details><summary>Emperor Vek'lor</summary>10</details><br /><details><summary>Gahz'ranka</summary>2</details><br /><details><summary>Gluth</summary>12</details><br /><details><summary>Sapphiron</summary>15</details><br /><details><summary>Razorgore the Untamed</summary>7</details><br /><details><summary>Onyxia</summary>10</details><br /><details><summary>Princess Yauj</summary>10</details><br /><details><summary>Vem</summary>10</details><br /><details><summary>Shazzrah</summary>10</details><br /><details><summary>Ouro</summary>10</details><br /><details><summary>Battleguard Sartura</summary>10</details><br /><details><summary>Maexxna</summary>15</details><br /><details><summary>Kel'Thuzad</summary>15</details><br /><details><summary>Nefarian</summary>10</details><br /><details><summary>Fankriss the Unyielding</summary>10</details><br /><details><summary>Lucifron</summary>10</details><br /><details><summary>Anub'Rekhan</summary>12</details><br /><details><summary>Hazza'rah</summary>2</details><br /><details><summary>Ragnaros</summary>10</details><br /><details><summary>Ayamiss the Hunter</summary>3</details><br /><details><summary>Broodlord Lashlayer</summary>7</details><br /><details><summary>Viscidus</summary>10</details><br /><details><summary>Hakkar</summary>3</details><br /><details><summary>Ebonroc</summary>7</details><br /><details><summary>Kurinnaxx</summary>3</details><br /><details><summary>Grobbulus</summary>12</details><br /><details><summary>Instructor Razuvious</summary>12</details><br /><details><summary>Emeriss</summary>7</details><br /><details><summary>Magmadar</summary>10</details><br /><details><summary>Sir Zeliek</summary>15</details><br /><details><summary>Vaelastrasz the Corrupt</summary>7</details><br /><details><summary>Patchwerk</summary>12</details><br /><details><summary>Bloodlord Mandokir</summary>2</details><br /><details><summary>Renataki</summary>2</details><br /><details><summary>Jin'do the Hexxer</summary>2</details><br /><details><summary>Garr</summary>10</details><br /></details><br /><details><summary>Standby Guild Ranks</summary><br /><details><summary>Guild Master</summary>False</details><br /><details><summary>Officer</summary>False</details><br /><details><summary>Veteran</summary>False</details><br /><details><summary>Member</summary>False</details><br /><details><summary>Initiate</summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /></details><br /><details><summary>Slot Weights</summary><br /><details><summary>2HWEAPON</summary>0.8</details><br /><details><summary>NECK</summary>0.5</details><br /><details><summary>HEAD</summary>0.7</details><br /><details><summary>WEAPON</summary>1.5</details><br /><details><summary>WRIST</summary>0.5</details><br /><details><summary>WEAPONMAINHAND</summary>0.7</details><br /><details><summary>SHIELD</summary>0.6</details><br /><details><summary>HOLDABLE</summary>0.5</details><br /><details><summary>RANGED</summary>0.6</details><br /><details><summary>SHOULDER</summary>0.6</details><br /><details><summary>FEET</summary>0.5</details><br /><details><summary>LEGS</summary>0.7</details><br /><details><summary>EXCEPTION</summary>1</details><br /><details><summary>WAIST</summary>0.5</details><br /><details><summary>TRINKET</summary>0.75</details><br /><details><summary>HAND</summary>0.5</details><br /><details><summary>ROBE</summary>1</details><br /><details><summary>CHEST</summary>0.7</details><br /><details><summary>CLOAK</summary>0.5</details><br /><details><summary>FINGER</summary>0.6</details><br /><details><summary>WEAPONOFFHAND</summary>0.6</details><br /><details><summary>RANGEDRIGHT</summary>0.5</details><br /><details><summary>RELIC</summary>0.5</details><br /><details><summary>THROWN</summary>0.5</details><br /></details><br /><details><summary>Addons List</summary><br />AdvancedOptions_Classic<br />Auc-Advanced<br />Auc-Filter-Basic<br />Auc-ScanData<br />Auc-Stat-Histogram<br />Auc-Stat-iLevel<br />Auc-Stat-Purchased<br />Auc-Stat-Simple<br />Auc-Stat-StdDev<br />Auc-Util-FixAH<br />Auctionator<br />AuctionValue<br />AutoLoggerClassic<br />BagBrother<br />Bagnon<br />Bagnon_Config<br />Bagnon_GuildBank<br />Bagnon_VoidStorage<br />BeanCounter<br />BetterAlign<br />BottomBar<br />BuffwatchClassic<br />Chatter<br />CEPGP<br />ClassicAuraDurations<br />ClassicThreatMeter<br />DashingDismount<br />Decursive<br />Dominos<br />Dominos_Config<br />Dominos_Encounter<br />Dominos_Progress<br />Dominos_Roll<br />eCastingBar<br />Enchantrix<br />Grid2<br />Grid2Options<br />Grid2RaidDebuffs<br />Grid2RaidDebuffsOptions<br />Grid2LDB<br />GuildBankClassic<br />HideXP<br />Informant<br />LunaUnitFrames<br />Masque<br />Masque_CleanIcons<br />MikScrollingBattleText<br />MissingTradeSkillsList<br />MSBTOptions<br />NugRunning<br />NugRunningOptions<br />OmniCC<br />OmniCC_Config<br />Prat-3.0<br />Prat-3.0_Libraries<br />QuestIconDesaturation<br />QuestFrameFixer<br />RealMobHealth<br />Recount<br />SellJunk<br />SharedMedia<br />SlideBar<br />Stubby<br />!Swatter<br />TipTac<br />TipTacItemRef<br />TipTacOptions<br />TitanAttributesMulti<br />TitanReputations<br />TitanClassicAmmo<br />TitanClassicBag<br />TitanClassicClock<br />TitanClassicGold<br />TitanClassicLocation<br />TitanClassicLootType<br />TitanClassicPerformance<br />TitanClassicRegen<br />TitanClassicRepair<br />TitanClassicVolume<br />TitanClassicXP<br />TitanClassic<br />tullaRange<br />tullaRange_Config<br />VendorPrice<br />WIM<br />ZoomerBegone<br />DejaClassicStats<br />TradeSkillMaster<br />EZQuest<br />DBM-Core<br />DBM-DefaultSkin<br />DBM-GUI<br />DBM-StatusBarTimers<br />DBM-Azeroth<br />DBM-BWL<br />DBM-Party-Classic<br />DBM-MC<br />DBM-Naxx<br />DBM-Onyxia<br />DBM-AQ20<br />DBM-AQ40<br />DBM-ZG<br />Questie<br /></details></details>

**Comment by PibbzTV** [comment]
I immidiately see here that there is a "Robe" slot that you mentioned earlier, that i cannot configure in the GUI. Same with "Weapon" with a default weight of 1.5.

**Comment by Alumian** [comment]
Okay so did you change the 2nd value in the GP formula to anything except 1?

**Comment by PibbzTV** [comment]
Yes, i now have both modifiers set to 2. These values will probably be tweaked to suit us, but this was done for testing purposes.

<details><summary>Debug Info</summary><br />Version: 1.11.5<br /><br />GP Modifier: 2<br /><br />Base GP: 5<br /><br />Standby EP: True<br /><br />Standby Offline: True<br /><br />Standby Percent: 100<br /><br />Standby Accept Whispers: True<br /><br />Standby EP by Rank: False<br /><br />Standby EP Manual Delegation: True<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: !standby<br /><br /><details><summary>Auto EP</summary><br /><details><summary>High Priestess Jeklik</summary>True</details><br /><details><summary>Gothik the Harvester</summary>True</details><br /><details><summary>Buru the Gorger</summary>True</details><br /><details><summary>Wushoolay</summary>True</details><br /><details><summary>Lord Kri</summary>True</details><br /><details><summary>Emperor Vek'nilash</summary>True</details><br /><details><summary>Ossirian the Unscarred</summary>True</details><br /><details><summary>Golemagg the Incinerator</summary>True</details><br /><details><summary>Grand Widow Faerlina</summary>True</details><br /><details><summary>High Priestess Mar'li</summary>True</details><br /><details><summary>Majordomo Executus</summary>True</details><br /><details><summary>High Priest Venoxis</summary>True</details><br /><details><summary>Gehennas</summary>True</details><br /><details><summary>Taerar</summary>True</details><br /><details><summary>Ysondre</summary>True</details><br /><details><summary>Thane Korth'azz</summary>True</details><br /><details><summary>High Priest Thekal</summary>True</details><br /><details><summary>Noth the Plaguebringer</summary>True</details><br /><details><summary>Lethon</summary>True</details><br /><details><summary>Moam</summary>True</details><br /><details><summary>The Prophet Skeram</summary>True</details><br /><details><summary>Flamegor</summary>True</details><br /><details><summary>C'Thun</summary>True</details><br /><details><summary>General Rajaxx</summary>True</details><br /><details><summary>Princess Huhuran</summary>True</details><br /><details><summary>Thaddius</summary>True</details><br /><details><summary>Loatheb</summary>True</details><br /><details><summary>Lady Blaumeux</summary>True</details><br /><details><summary>Highlord Mograine</summary>True</details><br /><details><summary>Heigan the Unclean</summary>True</details><br /><details><summary>Azuregos</summary>True</details><br /><details><summary>Doom Lord Kazzak</summary>True</details><br /><details><summary>Teremus the Devourer</summary>True</details><br /><details><summary>Jin'do the Hexxer</summary>True</details><br /><details><summary>Baron Geddon</summary>True</details><br /><details><summary>Renataki</summary>True</details><br /><details><summary>Sulfuron Harbinger</summary>True</details><br /><details><summary>Gri'lek</summary>True</details><br /><details><summary>Bloodlord Mandokir</summary>True</details><br /><details><summary>Patchwerk</summary>True</details><br /><details><summary>Vaelastrasz the Corrupt</summary>True</details><br /><details><summary>Gluth</summary>True</details><br /><details><summary>Sapphiron</summary>True</details><br /><details><summary>Emeriss</summary>True</details><br /><details><summary>Onyxia</summary>True</details><br /><details><summary>Princess Yauj</summary>True</details><br /><details><summary>Kurinnaxx</summary>True</details><br /><details><summary>Shazzrah</summary>True</details><br /><details><summary>Ebonroc</summary>True</details><br /><details><summary>Battleguard Sartura</summary>True</details><br /><details><summary>Hakkar</summary>True</details><br /><details><summary>Kel'Thuzad</summary>True</details><br /><details><summary>Nefarian</summary>True</details><br /><details><summary>Fankriss the Unyielding</summary>True</details><br /><details><summary>Lucifron</summary>True</details><br /><details><summary>Anub'Rekhan</summary>True</details><br /><details><summary>Hazza'rah</summary>True</details><br /><details><summary>Viscidus</summary>True</details><br /><details><summary>Broodlord Lashlayer</summary>True</details><br /><details><summary>Ayamiss the Hunter</summary>True</details><br /><details><summary>Ragnaros</summary>True</details><br /><details><summary>Maexxna</summary>True</details><br /><details><summary>Ouro</summary>True</details><br /><details><summary>Vem</summary>True</details><br /><details><summary>Grobbulus</summary>True</details><br /><details><summary>Instructor Razuvious</summary>True</details><br /><details><summary>Razorgore the Untamed</summary>True</details><br /><details><summary>Magmadar</summary>True</details><br /><details><summary>Sir Zeliek</summary>True</details><br /><details><summary>Gahz'ranka</summary>True</details><br /><details><summary>Emperor Vek'lor</summary>True</details><br /><details><summary>High Priestess Arlokk</summary>True</details><br /><details><summary>Firemaw</summary>True</details><br /><details><summary>Chromaggus</summary>True</details><br /><details><summary>Garr</summary>True</details><br /></details><br /><details><summary>EP Values</summary><br /><details><summary>High Priestess Jeklik</summary>2</details><br /><details><summary>Gothik the Harvester</summary>12</details><br /><details><summary>Buru the Gorger</summary>3</details><br /><details><summary>Wushoolay</summary>2</details><br /><details><summary>Lord Kri</summary>10</details><br /><details><summary>Emperor Vek'nilash</summary>10</details><br /><details><summary>Ossirian the Unscarred</summary>4</details><br /><details><summary>Golemagg the Incinerator</summary>10</details><br /><details><summary>Grand Widow Faerlina</summary>12</details><br /><details><summary>High Priestess Mar'li</summary>2</details><br /><details><summary>Majordomo Executus</summary>10</details><br /><details><summary>High Priest Venoxis</summary>2</details><br /><details><summary>Gehennas</summary>10</details><br /><details><summary>Taerar</summary>7</details><br /><details><summary>Ysondre</summary>7</details><br /><details><summary>Thane Korth'azz</summary>15</details><br /><details><summary>High Priest Thekal</summary>2</details><br /><details><summary>Noth the Plaguebringer</summary>12</details><br /><details><summary>Lethon</summary>7</details><br /><details><summary>Moam</summary>3</details><br /><details><summary>The Prophet Skeram</summary>10</details><br /><details><summary>Flamegor</summary>7</details><br /><details><summary>C'Thun</summary>12</details><br /><details><summary>General Rajaxx</summary>3</details><br /><details><summary>Princess Huhuran</summary>10</details><br /><details><summary>Thaddius</summary>15</details><br /><details><summary>Loatheb</summary>15</details><br /><details><summary>Lady Blaumeux</summary>15</details><br /><details><summary>Highlord Mograine</summary>15</details><br /><details><summary>Heigan the Unclean</summary>12</details><br /><details><summary>Azuregos</summary>7</details><br /><details><summary>Doom Lord Kazzak</summary>7</details><br /><details><summary>Teremus the Devourer</summary>7</details><br /><details><summary>Jin'do the Hexxer</summary>2</details><br /><details><summary>Baron Geddon</summary>10</details><br /><details><summary>Renataki</summary>2</details><br /><details><summary>Sulfuron Harbinger</summary>10</details><br /><details><summary>Gri'lek</summary>2</details><br /><details><summary>Bloodlord Mandokir</summary>2</details><br /><details><summary>Patchwerk</summary>12</details><br /><details><summary>Vaelastrasz the Corrupt</summary>7</details><br /><details><summary>Gluth</summary>12</details><br /><details><summary>Sapphiron</summary>15</details><br /><details><summary>Emeriss</summary>7</details><br /><details><summary>Onyxia</summary>10</details><br /><details><summary>Princess Yauj</summary>10</details><br /><details><summary>Kurinnaxx</summary>3</details><br /><details><summary>Shazzrah</summary>10</details><br /><details><summary>Ebonroc</summary>7</details><br /><details><summary>Battleguard Sartura</summary>10</details><br /><details><summary>Hakkar</summary>3</details><br /><details><summary>Kel'Thuzad</summary>15</details><br /><details><summary>Nefarian</summary>10</details><br /><details><summary>Fankriss the Unyielding</summary>10</details><br /><details><summary>Lucifron</summary>10</details><br /><details><summary>Anub'Rekhan</summary>12</details><br /><details><summary>Hazza'rah</summary>2</details><br /><details><summary>Viscidus</summary>10</details><br /><details><summary>Broodlord Lashlayer</summary>7</details><br /><details><summary>Ayamiss the Hunter</summary>3</details><br /><details><summary>Ragnaros</summary>10</details><br /><details><summary>Maexxna</summary>15</details><br /><details><summary>Ouro</summary>10</details><br /><details><summary>Vem</summary>10</details><br /><details><summary>Grobbulus</summary>12</details><br /><details><summary>Instructor Razuvious</summary>12</details><br /><details><summary>Razorgore the Untamed</summary>7</details><br /><details><summary>Magmadar</summary>10</details><br /><details><summary>Sir Zeliek</summary>15</details><br /><details><summary>Gahz'ranka</summary>2</details><br /><details><summary>Emperor Vek'lor</summary>10</details><br /><details><summary>High Priestess Arlokk</summary>2</details><br /><details><summary>Firemaw</summary>7</details><br /><details><summary>Chromaggus</summary>7</details><br /><details><summary>Garr</summary>10</details><br /></details><br /><details><summary>Standby Guild Ranks</summary><br /><details><summary>Guild Master</summary>False</details><br /><details><summary>Officer</summary>False</details><br /><details><summary>Veteran</summary>False</details><br /><details><summary>Member</summary>False</details><br /><details><summary>Initiate</summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /></details><br /><details><summary>Slot Weights</summary><br /><details><summary>2HWEAPON</summary>0.8</details><br /><details><summary>NECK</summary>0.5</details><br /><details><summary>HEAD</summary>0.7</details><br /><details><summary>WEAPON</summary>1.5</details><br /><details><summary>WRIST</summary>0.5</details><br /><details><summary>WEAPONMAINHAND</summary>0.7</details><br /><details><summary>SHIELD</summary>0.6</details><br /><details><summary>HOLDABLE</summary>0.5</details><br /><details><summary>RANGED</summary>0.6</details><br /><details><summary>THROWN</summary>0.5</details><br /><details><summary>FEET</summary>0.5</details><br /><details><summary>RELIC</summary>0.5</details><br /><details><summary>RANGEDRIGHT</summary>0.5</details><br /><details><summary>WEAPONOFFHAND</summary>0.6</details><br /><details><summary>TRINKET</summary>0.75</details><br /><details><summary>FINGER</summary>0.6</details><br /><details><summary>CLOAK</summary>0.5</details><br /><details><summary>CHEST</summary>0.7</details><br /><details><summary>ROBE</summary>1</details><br /><details><summary>HAND</summary>0.5</details><br /><details><summary>WAIST</summary>0.5</details><br /><details><summary>EXCEPTION</summary>1</details><br /><details><summary>LEGS</summary>0.7</details><br /><details><summary>SHOULDER</summary>0.6</details><br /></details><br /><details><summary>Addons List</summary><br />AdvancedOptions_Classic<br />Auc-Advanced<br />Auc-Filter-Basic<br />Auc-ScanData<br />Auc-Stat-Histogram<br />Auc-Stat-iLevel<br />Auc-Stat-Purchased<br />Auc-Stat-Simple<br />Auc-Stat-StdDev<br />Auc-Util-FixAH<br />Auctionator<br />AuctionValue<br />AutoLoggerClassic<br />BagBrother<br />Bagnon<br />Bagnon_Config<br />Bagnon_GuildBank<br />Bagnon_VoidStorage<br />BeanCounter<br />BetterAlign<br />BottomBar<br />BuffwatchClassic<br />Chatter<br />CEPGP<br />ClassicAuraDurations<br />ClassicThreatMeter<br />DashingDismount<br />Decursive<br />Dominos<br />Dominos_Config<br />Dominos_Encounter<br />Dominos_Progress<br />Dominos_Roll<br />eCastingBar<br />Enchantrix<br />Grid2<br />Grid2Options<br />Grid2RaidDebuffs<br />Grid2RaidDebuffsOptions<br />Grid2LDB<br />GuildBankClassic<br />HideXP<br />Informant<br />LunaUnitFrames<br />Masque<br />Masque_CleanIcons<br />MikScrollingBattleText<br />MissingTradeSkillsList<br />MSBTOptions<br />NugRunning<br />NugRunningOptions<br />OmniCC<br />OmniCC_Config<br />Prat-3.0<br />Prat-3.0_Libraries<br />QuestIconDesaturation<br />QuestFrameFixer<br />RealMobHealth<br />Recount<br />SellJunk<br />SharedMedia<br />SlideBar<br />Stubby<br />!Swatter<br />TipTac<br />TipTacItemRef<br />TipTacOptions<br />TitanAttributesMulti<br />TitanReputations<br />TitanClassicAmmo<br />TitanClassicBag<br />TitanClassicClock<br />TitanClassicGold<br />TitanClassicLocation<br />TitanClassicLootType<br />TitanClassicPerformance<br />TitanClassicRegen<br />TitanClassicRepair<br />TitanClassicVolume<br />TitanClassicXP<br />TitanClassic<br />tullaRange<br />tullaRange_Config<br />VendorPrice<br />WIM<br />ZoomerBegone<br />DejaClassicStats<br />TradeSkillMaster<br />EZQuest<br />DBM-Core<br />DBM-DefaultSkin<br />DBM-GUI<br />DBM-StatusBarTimers<br />DBM-Azeroth<br />DBM-BWL<br />DBM-Party-Classic<br />DBM-MC<br />DBM-Naxx<br />DBM-Onyxia<br />DBM-AQ20<br />DBM-AQ40<br />DBM-ZG<br />Questie<br /></details></details>

**Comment by Alumian** [comment]
Ok lemme check that out.

**Comment by PibbzTV** [comment]
Updated the previous comment just now :)

**Comment by Alumian** [comment]
Well, you were spot on haha. I honestly can't believe no one has ever raised that with me before. I've attached INVTYPE_WEAPON to INVTYPE_WEAPONOFFHAND now so it'll fall under the OH Weapon category. Does that sound like a good resolution? Please don't say it needs it's own slot weight lol

**Comment by PibbzTV** [comment]
Exactly the solution I wanted, but I didn't think it was that easy to attach them to eachother. This is perfect! When is the new build ready to be downloaded for testing? :)

**Comment by Alumian** [comment]
About now-ish. :)

**Comment by PibbzTV** [comment]
Seems perfect! Quick question for clarification tho. That  _/script print(CEPGP_calcGP(_, 1, x));_ thing, does not care about manual overrides? Or should it?

Reason being im trying to price The Eye of Divinity equal to the finished staff with an override, but the script seems to return the cost of the trinket regardless.

**Comment by PibbzTV** [comment]
Seems like the override adds a space at the end of each item name in the cepgp.lua file, that causes it to not work. When i manually removed the space from cepgp.lua, the script returned the overrided values :)

**Comment by PibbzTV** [comment]
Did you check out this override bug i mentioned? :)

**Comment by Alumian** [comment]
Yup. Nfi idea why that was happening but I've accommodated for it nonetheless. Should be fixed :)
