### ISSUE TITLE
[Request] Ability to master loot green items in raid

### ISSUE THREAD

**Issue by hardtofin** [Alumian/CEPGP-Retail#40]
Would it be possible to be able to masterloot greens items in raid.  Specifically for the ML to just pick them up without encountering the interface at all?

The reason being that lots of guilds hoover up greens in raids and sell/AH them for gold to go to the guild bank or pay for their main tanks repairs/respec costs etc.

So having the ability to do this would be extremely useful.

Thanks Alumian!

**Comment by Alumian** [comment]
Hey Hardtofin,
I have added a new feature which will assist with your request and it will be included in the next update. But I would like to clarify, the items that you are able to master loot, or freely pick up is dictated by your loot threshold. You can see your loot threshold if you right click your unit frame whilst in a party or raid. Any item that is a quality below the threshold can be picked up by anyone freely, but any item that meets or exceeds the threshold will be subject to the loot method you have selected. Having said that, CEPGP doesn't actually adjust the loot threshold at all - it piggybacks off it. Meaning that CEPGP is subject to which ever loot threshold you have selected. Although you may be able to announce an uncommon/rare item, if you set the threshold to epic, then you won't be able to actually distribute it.
So the feature I have just added is a way that you can choose what rarity items will make the CEPGP window automatically appears whilst being the master looter in a raid group. But for the rest of your question, that is subject to the loot threshold.

I hope that helps!
