### ISSUE TITLE
[Request] GP Rounding?

### ISSUE THREAD

**Issue by qrsu0203** [Alumian/CEPGP-Retail#41]
Hi Alumian -- first week running the addon in MC and it's working great.
Just noticing that all GP awards have been rounded down after their calculation. Wondering what the reasoning behind that was and if we could somehow change it to allow to say 1-3 decimal points in precision?

**Comment by Alumian** [comment]
Hey there, it was an original design choice and a bad one at that haha. I intend to remove the rounding as in hindsight, it's a silly decision. Please expect that change in the next update :)
