### ISSUE TITLE
[Bug] Whispering other person does not reflect his current EPGP

### ISSUE THREAD

**Issue by Lanly-Lanly** [Alumian/CEPGP-Retail#42]
**The Error**

**Describe the bug**
!info and !infoguild do not reflect one's current EPGP, but show the initial EPGP (EP 0, GP 1, RP 0).

**To Reproduce**
We installed CEPGP today. I added EP to a person, and whispered him, who has the current version of CEPGP and is able to view the Officer Notes. I tried !info and !infoguild. The whisper does not reflect his current EPGP, but shows his initial EPGP (EP 0, GP 1, RP 0).
<img width="258" alt="test3" src="https://user-images.githubusercontent.com/55506019/66261969-76302e80-e7a5-11e9-91b4-3175c7d14fdb.png">

**Debug Information**
<details><summary>Debug Info</summary><br />Version: 1.11.5<br /><br />GP Modifier: 1<br /><br />Base GP: 1<br /><br />Standby EP: False<br /><br />Standby Offline: False<br /><br />Standby Percent: 0<br /><br />Standby Accept Whispers: False<br /><br />Standby EP by Rank: True<br /><br />Standby EP Manual Delegation: False<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary><br /><details><summary>High Priestess Jeklik</summary>True</details><br /><details><summary>Gothik the Harvester</summary>True</details><br /><details><summary>Buru the Gorger</summary>True</details><br /><details><summary>Wushoolay</summary>True</details><br /><details><summary>Lord Kri</summary>True</details><br /><details><summary>Emperor Vek'nilash</summary>True</details><br /><details><summary>Ossirian the Unscarred</summary>True</details><br /><details><summary>Golemagg the Incinerator</summary>True</details><br /><details><summary>Grand Widow Faerlina</summary>True</details><br /><details><summary>High Priestess Mar'li</summary>True</details><br /><details><summary>Majordomo Executus</summary>True</details><br /><details><summary>High Priest Venoxis</summary>True</details><br /><details><summary>Gehennas</summary>True</details><br /><details><summary>Taerar</summary>True</details><br /><details><summary>Ysondre</summary>True</details><br /><details><summary>Thane Korth'azz</summary>True</details><br /><details><summary>High Priest Thekal</summary>True</details><br /><details><summary>Noth the Plaguebringer</summary>True</details><br /><details><summary>Lethon</summary>True</details><br /><details><summary>Moam</summary>True</details><br /><details><summary>The Prophet Skeram</summary>True</details><br /><details><summary>Flamegor</summary>True</details><br /><details><summary>C'Thun</summary>True</details><br /><details><summary>General Rajaxx</summary>True</details><br /><details><summary>Princess Huhuran</summary>True</details><br /><details><summary>Thaddius</summary>True</details><br /><details><summary>Loatheb</summary>True</details><br /><details><summary>Lady Blaumeux</summary>True</details><br /><details><summary>Highlord Mograine</summary>True</details><br /><details><summary>Heigan the Unclean</summary>True</details><br /><details><summary>Azuregos</summary>True</details><br /><details><summary>Doom Lord Kazzak</summary>True</details><br /><details><summary>Teremus the Devourer</summary>True</details><br /><details><summary>Jin'do the Hexxer</summary>True</details><br /><details><summary>Baron Geddon</summary>True</details><br /><details><summary>Renataki</summary>True</details><br /><details><summary>Sulfuron Harbinger</summary>True</details><br /><details><summary>Gri'lek</summary>True</details><br /><details><summary>Bloodlord Mandokir</summary>True</details><br /><details><summary>Patchwerk</summary>True</details><br /><details><summary>Vaelastrasz the Corrupt</summary>True</details><br /><details><summary>Gluth</summary>True</details><br /><details><summary>Sapphiron</summary>True</details><br /><details><summary>Emeriss</summary>True</details><br /><details><summary>Onyxia</summary>True</details><br /><details><summary>Princess Yauj</summary>True</details><br /><details><summary>Kurinnaxx</summary>True</details><br /><details><summary>Shazzrah</summary>True</details><br /><details><summary>Ebonroc</summary>True</details><br /><details><summary>Battleguard Sartura</summary>True</details><br /><details><summary>Hakkar</summary>True</details><br /><details><summary>Kel'Thuzad</summary>True</details><br /><details><summary>Nefarian</summary>True</details><br /><details><summary>Fankriss the Unyielding</summary>True</details><br /><details><summary>Lucifron</summary>True</details><br /><details><summary>Anub'Rekhan</summary>True</details><br /><details><summary>Hazza'rah</summary>True</details><br /><details><summary>Viscidus</summary>True</details><br /><details><summary>Broodlord Lashlayer</summary>True</details><br /><details><summary>Ayamiss the Hunter</summary>True</details><br /><details><summary>Ragnaros</summary>True</details><br /><details><summary>Maexxna</summary>True</details><br /><details><summary>Ouro</summary>True</details><br /><details><summary>Vem</summary>True</details><br /><details><summary>Grobbulus</summary>True</details><br /><details><summary>Instructor Razuvious</summary>True</details><br /><details><summary>Razorgore the Untamed</summary>True</details><br /><details><summary>Magmadar</summary>True</details><br /><details><summary>Sir Zeliek</summary>True</details><br /><details><summary>Gahz'ranka</summary>True</details><br /><details><summary>Emperor Vek'lor</summary>True</details><br /><details><summary>High Priestess Arlokk</summary>True</details><br /><details><summary>Firemaw</summary>True</details><br /><details><summary>Chromaggus</summary>True</details><br /><details><summary>Garr</summary>True</details><br /></details><br /><details><summary>EP Values</summary><br /><details><summary>High Priestess Jeklik</summary>2</details><br /><details><summary>Gothik the Harvester</summary>12</details><br /><details><summary>Buru the Gorger</summary>3</details><br /><details><summary>Wushoolay</summary>2</details><br /><details><summary>Lord Kri</summary>10</details><br /><details><summary>Emperor Vek'nilash</summary>10</details><br /><details><summary>Ossirian the Unscarred</summary>4</details><br /><details><summary>Golemagg the Incinerator</summary>5</details><br /><details><summary>Grand Widow Faerlina</summary>12</details><br /><details><summary>High Priestess Mar'li</summary>2</details><br /><details><summary>Majordomo Executus</summary>5</details><br /><details><summary>High Priest Venoxis</summary>2</details><br /><details><summary>Gehennas</summary>5</details><br /><details><summary>Taerar</summary>7</details><br /><details><summary>Ysondre</summary>7</details><br /><details><summary>Thane Korth'azz</summary>15</details><br /><details><summary>High Priest Thekal</summary>2</details><br /><details><summary>Noth the Plaguebringer</summary>12</details><br /><details><summary>Lethon</summary>7</details><br /><details><summary>Moam</summary>3</details><br /><details><summary>The Prophet Skeram</summary>10</details><br /><details><summary>Flamegor</summary>7</details><br /><details><summary>C'Thun</summary>12</details><br /><details><summary>General Rajaxx</summary>3</details><br /><details><summary>Princess Huhuran</summary>10</details><br /><details><summary>Thaddius</summary>15</details><br /><details><summary>Loatheb</summary>15</details><br /><details><summary>Lady Blaumeux</summary>15</details><br /><details><summary>Highlord Mograine</summary>15</details><br /><details><summary>Heigan the Unclean</summary>12</details><br /><details><summary>Azuregos</summary>7</details><br /><details><summary>Doom Lord Kazzak</summary>7</details><br /><details><summary>Teremus the Devourer</summary>7</details><br /><details><summary>Jin'do the Hexxer</summary>2</details><br /><details><summary>Baron Geddon</summary>5</details><br /><details><summary>Renataki</summary>2</details><br /><details><summary>Sulfuron Harbinger</summary>5</details><br /><details><summary>Gri'lek</summary>2</details><br /><details><summary>Bloodlord Mandokir</summary>2</details><br /><details><summary>Patchwerk</summary>12</details><br /><details><summary>Vaelastrasz the Corrupt</summary>7</details><br /><details><summary>Gluth</summary>12</details><br /><details><summary>Sapphiron</summary>15</details><br /><details><summary>Emeriss</summary>7</details><br /><details><summary>Onyxia</summary>5</details><br /><details><summary>Princess Yauj</summary>10</details><br /><details><summary>Kurinnaxx</summary>3</details><br /><details><summary>Shazzrah</summary>5</details><br /><details><summary>Ebonroc</summary>7</details><br /><details><summary>Battleguard Sartura</summary>10</details><br /><details><summary>Hakkar</summary>3</details><br /><details><summary>Kel'Thuzad</summary>15</details><br /><details><summary>Nefarian</summary>10</details><br /><details><summary>Fankriss the Unyielding</summary>10</details><br /><details><summary>Lucifron</summary>5</details><br /><details><summary>Anub'Rekhan</summary>12</details><br /><details><summary>Hazza'rah</summary>2</details><br /><details><summary>Viscidus</summary>10</details><br /><details><summary>Broodlord Lashlayer</summary>7</details><br /><details><summary>Ayamiss the Hunter</summary>3</details><br /><details><summary>Ragnaros</summary>7</details><br /><details><summary>Maexxna</summary>15</details><br /><details><summary>Ouro</summary>10</details><br /><details><summary>Vem</summary>10</details><br /><details><summary>Grobbulus</summary>12</details><br /><details><summary>Instructor Razuvious</summary>12</details><br /><details><summary>Razorgore the Untamed</summary>7</details><br /><details><summary>Magmadar</summary>5</details><br /><details><summary>Sir Zeliek</summary>15</details><br /><details><summary>Gahz'ranka</summary>2</details><br /><details><summary>Emperor Vek'lor</summary>10</details><br /><details><summary>High Priestess Arlokk</summary>2</details><br /><details><summary>Firemaw</summary>7</details><br /><details><summary>Chromaggus</summary>7</details><br /><details><summary>Garr</summary>5</details><br /></details><br /><details><summary>Standby Guild Ranks</summary><br /><details><summary>会长</summary>False</details><br /><details><summary>团长</summary>False</details><br /><details><summary>官员</summary>False</details><br /><details><summary>早间团</summary>False</details><br /><details><summary>精英</summary>False</details><br /><details><summary>会员</summary>False</details><br /><details><summary>小黑屋</summary>False</details><br /><details><summary>见习</summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /></details><br /><details><summary>Slot Weights</summary><br /><details><summary>2HWEAPON</summary>2</details><br /><details><summary>NECK</summary>0.5</details><br /><details><summary>HEAD</summary>1</details><br /><details><summary>WEAPON</summary>1.5</details><br /><details><summary>WRIST</summary>0.5</details><br /><details><summary>WEAPONMAINHAND</summary>1.5</details><br /><details><summary>SHIELD</summary>0.5</details><br /><details><summary>HOLDABLE</summary>0.5</details><br /><details><summary>RANGED</summary>0.5</details><br /><details><summary>THROWN</summary>0.5</details><br /><details><summary>FEET</summary>0.75</details><br /><details><summary>RELIC</summary>0.5</details><br /><details><summary>RANGEDRIGHT</summary>0.5</details><br /><details><summary>WEAPONOFFHAND</summary>0.5</details><br /><details><summary>TRINKET</summary>0.75</details><br /><details><summary>FINGER</summary>0.5</details><br /><details><summary>CLOAK</summary>0.5</details><br /><details><summary>CHEST</summary>1</details><br /><details><summary>ROBE</summary>1</details><br /><details><summary>HAND</summary>0.75</details><br /><details><summary>WAIST</summary>0.75</details><br /><details><summary>EXCEPTION</summary>1</details><br /><details><summary>LEGS</summary>1</details><br /><details><summary>SHOULDER</summary>0.75</details><br /></details><br /><details><summary>Addons List</summary><br />ACP<br />AdvancedInterfaceOptions<br />alaChat_Classic<br />Atlas<br />Atlas_Transportation<br />Atlas_DungeonLocs<br />Atlas_ClassicWoW<br />AtlasLootClassic_Options<br />AtlasLootClassic_Collections<br />AtlasLootClassic_Crafting<br />AtlasLootClassic_Factions<br />AtlasLootClassic_PvP<br />AtlasLootClassic_DungeonsAndRaids<br />AtlasLootClassic<br />AuctionMaster<br />BadBoy<br />BagBrother<br />Bagnon<br />Bagnon_Config<br />Bagnon_GuildBank<br />Bagnon_VoidStorage<br />Bartender4<br />CEPGP<br />ClassicCastbars<br />ClassicCastbars_Options<br />ClassicCodex<br />Details<br />Details_TinyThreat<br />eCastingBar<br />GatherMate2<br />GTFO<br />Leatrix_Maps<br />Mapster<br />MerInspect<br />ModernQuestWatch<br />MoveAnything<br />NeatPlates<br />NeatPlatesHub<br />NeatPlatesWidgets<br />NeatPlates_Alvara<br />NeatPlates_Graphite<br />NeatPlates_Grey<br />NeatPlates_Neon<br />NeatPlates_Quatre<br />NeatPlates_Roth<br />NeatPlates_Slim_Horizontal<br />NeatPlates_Slim_Vertical<br />NeatPlates_BlizzardPlates<br />NeatPlates_ClassicPlates<br />NeatPlates_Simple<br />NeatPlates_Renaitre<br />OmniCC<br />OmniCC_Config<br />Postal<br />Quartz<br />QuestIconDesaturation<br />QuestFrameFixer<br />RealMobHealth<br />SilverDragon<br />SilverDragon_Classic<br />SimpleInterruptAnnounce<br />SimpleInterruptAnnounce_Config<br />Simulationcraft<br />TinyTooltip<br />TomCats<br />TomTom<br />UnitFramesImproved<br />VendorPrice<br />WorldQuestsList<br />FriendsMenuXP<br />WoWPro<br />WoWPro_Leveling<br />DBM-Core<br />DBM-StatusBarTimers<br />DBM-GUI<br />DBM-Azeroth<br />DBM-AQ20<br />DBM-AQ40<br />DBM-ZG<br />DBM-Onyxia<br />DBM-MC<br />DBM-Naxx<br />DBM-Party-Classic<br />DBM-BWL<br />DBM-DefaultSkin<br />Questie<br /></details></details>

**Comment by Alumian** [comment]
Hi Lanly,
Thanks for submitting this report. How much time did you wait before you tried doing !info? The addon does need a little bit of time (usually no more than a couple of seconds) to update the roster.

**Comment by Lanly-Lanly** [comment]
Hi Alumian,

Thanks for your reply! I just whispered that person again, which is over 20 minutes after I changed his EPGP. !info and !infoguild still shown default numbers.

I tried on myself, and had the same condition as you did. !info worked great, and !infoguild did not.

**Comment by Alumian** [comment]
Okay so it only appears to be impacting other clients but works on our own ones when we message ourselves?

**Comment by Lanly-Lanly** [comment]
!info is good when I message myself, not good when I message others.
!infoguild is not good when I message myself or others.
Haven't tried !inforaid or !infoclass.

**Comment by Alumian** [comment]
Okay I feel like !infoguild might just be busted. I think !info is probably being interfered with due to realm names. I haven't touched that function in a while so it's probably just a matter of swapping out the arg that is being used to compare names. Leave it with me, I'll keep you posted :)

**Comment by Lanly-Lanly** [comment]
Thank you very much!

**Comment by skombag** [comment]
Had this issue last update , but i have checked with the latest one and this was no longer an issue, all returned values were correct on !info , !infoclass just not !infoguild

**Comment by Alumian** [comment]
Hey guys, have you tried this again recently? I just tried it and got a guildy to try !infoguild and it all worked fine.

**Comment by Alumian** [comment]
Fixed in the next update.
