### ISSUE TITLE
[Bug] Constant stuttering ingame while addon is active

### ISSUE THREAD

**Issue by Gholie** [Alumian/CEPGP-Retail#43]
**The Error**
Constant stutters on a ~10-30s interval

**Describe the bug**
Constant stutters on a ~10-30s interval
Guild size: 733 players
Guild rank: Member ( Cannot edit Officer notes )

**To Reproduce**
Constantly happens when the addon is on. Goes away as soon as I disable it

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.
<details><summary>Debug Info</summary><br />Version: 1.11.5<br /><br />GP Modifier: 1<br /><br />Base GP: 1<br /><br />Standby EP: False<br /><br />Standby Offline: False<br /><br />Standby Percent: 0<br /><br />Standby Accept Whispers: False<br /><br />Standby EP by Rank: True<br /><br />Standby EP Manual Delegation: False<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary><br /><details><summary>High Priestess Jeklik</summary>True</details><br /><details><summary>Gothik the Harvester</summary>True</details><br /><details><summary>Buru the Gorger</summary>True</details><br /><details><summary>Wushoolay</summary>True</details><br /><details><summary>Lord Kri</summary>True</details><br /><details><summary>Emperor Vek'nilash</summary>True</details><br /><details><summary>Ossirian the Unscarred</summary>True</details><br /><details><summary>Golemagg the Incinerator</summary>True</details><br /><details><summary>Grand Widow Faerlina</summary>True</details><br /><details><summary>High Priestess Mar'li</summary>True</details><br /><details><summary>Majordomo Executus</summary>True</details><br /><details><summary>High Priest Venoxis</summary>True</details><br /><details><summary>Gehennas</summary>True</details><br /><details><summary>Taerar</summary>True</details><br /><details><summary>Ysondre</summary>True</details><br /><details><summary>Thane Korth'azz</summary>True</details><br /><details><summary>High Priest Thekal</summary>True</details><br /><details><summary>Noth the Plaguebringer</summary>True</details><br /><details><summary>Lethon</summary>True</details><br /><details><summary>Moam</summary>True</details><br /><details><summary>The Prophet Skeram</summary>True</details><br /><details><summary>Flamegor</summary>True</details><br /><details><summary>C'Thun</summary>True</details><br /><details><summary>General Rajaxx</summary>True</details><br /><details><summary>Princess Huhuran</summary>True</details><br /><details><summary>Thaddius</summary>True</details><br /><details><summary>Loatheb</summary>True</details><br /><details><summary>Lady Blaumeux</summary>True</details><br /><details><summary>Highlord Mograine</summary>True</details><br /><details><summary>Heigan the Unclean</summary>True</details><br /><details><summary>Azuregos</summary>True</details><br /><details><summary>Doom Lord Kazzak</summary>True</details><br /><details><summary>Teremus the Devourer</summary>True</details><br /><details><summary>Chromaggus</summary>True</details><br /><details><summary>Baron Geddon</summary>True</details><br /><details><summary>Firemaw</summary>True</details><br /><details><summary>Sulfuron Harbinger</summary>True</details><br /><details><summary>Gri'lek</summary>True</details><br /><details><summary>High Priestess Arlokk</summary>True</details><br /><details><summary>Emperor Vek'lor</summary>True</details><br /><details><summary>Gahz'ranka</summary>True</details><br /><details><summary>Gluth</summary>True</details><br /><details><summary>Sapphiron</summary>True</details><br /><details><summary>Razorgore the Untamed</summary>True</details><br /><details><summary>Onyxia</summary>True</details><br /><details><summary>Princess Yauj</summary>True</details><br /><details><summary>Vem</summary>True</details><br /><details><summary>Shazzrah</summary>True</details><br /><details><summary>Ouro</summary>True</details><br /><details><summary>Battleguard Sartura</summary>True</details><br /><details><summary>Maexxna</summary>True</details><br /><details><summary>Kel'Thuzad</summary>True</details><br /><details><summary>Nefarian</summary>True</details><br /><details><summary>Fankriss the Unyielding</summary>True</details><br /><details><summary>Lucifron</summary>True</details><br /><details><summary>Anub'Rekhan</summary>True</details><br /><details><summary>Hazza'rah</summary>True</details><br /><details><summary>Ragnaros</summary>True</details><br /><details><summary>Ayamiss the Hunter</summary>True</details><br /><details><summary>Broodlord Lashlayer</summary>True</details><br /><details><summary>Viscidus</summary>True</details><br /><details><summary>Hakkar</summary>True</details><br /><details><summary>Ebonroc</summary>True</details><br /><details><summary>Kurinnaxx</summary>True</details><br /><details><summary>Grobbulus</summary>True</details><br /><details><summary>Instructor Razuvious</summary>True</details><br /><details><summary>Emeriss</summary>True</details><br /><details><summary>Magmadar</summary>True</details><br /><details><summary>Sir Zeliek</summary>True</details><br /><details><summary>Vaelastrasz the Corrupt</summary>True</details><br /><details><summary>Patchwerk</summary>True</details><br /><details><summary>Bloodlord Mandokir</summary>True</details><br /><details><summary>Renataki</summary>True</details><br /><details><summary>Jin'do the Hexxer</summary>True</details><br /><details><summary>Garr</summary>True</details><br /></details><br /><details><summary>EP Values</summary><br /><details><summary>High Priestess Jeklik</summary>2</details><br /><details><summary>Gothik the Harvester</summary>12</details><br /><details><summary>Buru the Gorger</summary>3</details><br /><details><summary>Wushoolay</summary>2</details><br /><details><summary>Lord Kri</summary>10</details><br /><details><summary>Emperor Vek'nilash</summary>10</details><br /><details><summary>Ossirian the Unscarred</summary>4</details><br /><details><summary>Golemagg the Incinerator</summary>5</details><br /><details><summary>Grand Widow Faerlina</summary>12</details><br /><details><summary>High Priestess Mar'li</summary>2</details><br /><details><summary>Majordomo Executus</summary>5</details><br /><details><summary>High Priest Venoxis</summary>2</details><br /><details><summary>Gehennas</summary>5</details><br /><details><summary>Taerar</summary>7</details><br /><details><summary>Ysondre</summary>7</details><br /><details><summary>Thane Korth'azz</summary>15</details><br /><details><summary>High Priest Thekal</summary>2</details><br /><details><summary>Noth the Plaguebringer</summary>12</details><br /><details><summary>Lethon</summary>7</details><br /><details><summary>Moam</summary>3</details><br /><details><summary>The Prophet Skeram</summary>10</details><br /><details><summary>Flamegor</summary>7</details><br /><details><summary>C'Thun</summary>12</details><br /><details><summary>General Rajaxx</summary>3</details><br /><details><summary>Princess Huhuran</summary>10</details><br /><details><summary>Thaddius</summary>15</details><br /><details><summary>Loatheb</summary>15</details><br /><details><summary>Lady Blaumeux</summary>15</details><br /><details><summary>Highlord Mograine</summary>15</details><br /><details><summary>Heigan the Unclean</summary>12</details><br /><details><summary>Azuregos</summary>7</details><br /><details><summary>Doom Lord Kazzak</summary>7</details><br /><details><summary>Teremus the Devourer</summary>7</details><br /><details><summary>Chromaggus</summary>7</details><br /><details><summary>Baron Geddon</summary>5</details><br /><details><summary>Firemaw</summary>7</details><br /><details><summary>Sulfuron Harbinger</summary>5</details><br /><details><summary>Gri'lek</summary>2</details><br /><details><summary>High Priestess Arlokk</summary>2</details><br /><details><summary>Emperor Vek'lor</summary>10</details><br /><details><summary>Gahz'ranka</summary>2</details><br /><details><summary>Gluth</summary>12</details><br /><details><summary>Sapphiron</summary>15</details><br /><details><summary>Razorgore the Untamed</summary>7</details><br /><details><summary>Onyxia</summary>5</details><br /><details><summary>Princess Yauj</summary>10</details><br /><details><summary>Vem</summary>10</details><br /><details><summary>Shazzrah</summary>5</details><br /><details><summary>Ouro</summary>10</details><br /><details><summary>Battleguard Sartura</summary>10</details><br /><details><summary>Maexxna</summary>15</details><br /><details><summary>Kel'Thuzad</summary>15</details><br /><details><summary>Nefarian</summary>10</details><br /><details><summary>Fankriss the Unyielding</summary>10</details><br /><details><summary>Lucifron</summary>5</details><br /><details><summary>Anub'Rekhan</summary>12</details><br /><details><summary>Hazza'rah</summary>2</details><br /><details><summary>Ragnaros</summary>7</details><br /><details><summary>Ayamiss the Hunter</summary>3</details><br /><details><summary>Broodlord Lashlayer</summary>7</details><br /><details><summary>Viscidus</summary>10</details><br /><details><summary>Hakkar</summary>3</details><br /><details><summary>Ebonroc</summary>7</details><br /><details><summary>Kurinnaxx</summary>3</details><br /><details><summary>Grobbulus</summary>12</details><br /><details><summary>Instructor Razuvious</summary>12</details><br /><details><summary>Emeriss</summary>7</details><br /><details><summary>Magmadar</summary>5</details><br /><details><summary>Sir Zeliek</summary>15</details><br /><details><summary>Vaelastrasz the Corrupt</summary>7</details><br /><details><summary>Patchwerk</summary>12</details><br /><details><summary>Bloodlord Mandokir</summary>2</details><br /><details><summary>Renataki</summary>2</details><br /><details><summary>Jin'do the Hexxer</summary>2</details><br /><details><summary>Garr</summary>5</details><br /></details><br /><details><summary>Standby Guild Ranks</summary><br /><details><summary>Matriarch</summary>False</details><br /><details><summary>Officer</summary>False</details><br /><details><summary>Veteran</summary>False</details><br /><details><summary>Member</summary>False</details><br /><details><summary>Social</summary>False</details><br /><details><summary>Alt</summary>False</details><br /><details><summary>Timeout</summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /></details><br /><details><summary>Slot Weights</summary><br /><details><summary>2HWEAPON</summary>2</details><br /><details><summary>NECK</summary>0.5</details><br /><details><summary>HEAD</summary>1</details><br /><details><summary>WEAPON</summary>1.5</details><br /><details><summary>WRIST</summary>0.5</details><br /><details><summary>WEAPONMAINHAND</summary>1.5</details><br /><details><summary>SHIELD</summary>0.5</details><br /><details><summary>HOLDABLE</summary>0.5</details><br /><details><summary>RANGED</summary>0.5</details><br /><details><summary>SHOULDER</summary>0.75</details><br /><details><summary>FEET</summary>0.75</details><br /><details><summary>LEGS</summary>1</details><br /><details><summary>EXCEPTION</summary>1</details><br /><details><summary>WAIST</summary>0.75</details><br /><details><summary>TRINKET</summary>0.75</details><br /><details><summary>HAND</summary>0.75</details><br /><details><summary>ROBE</summary>1</details><br /><details><summary>CHEST</summary>1</details><br /><details><summary>CLOAK</summary>0.5</details><br /><details><summary>FINGER</summary>0.5</details><br /><details><summary>WEAPONOFFHAND</summary>0.5</details><br /><details><summary>RANGEDRIGHT</summary>0.5</details><br /><details><summary>RELIC</summary>0.5</details><br /><details><summary>THROWN</summary>0.5</details><br /></details><br /><details><summary>Addons List</summary><br />AdvancedInterfaceOptions<br />AtlasLootClassic_Options<br />AtlasLootClassic_Maps<br />AtlasLootClassic_Collections<br />AtlasLootClassic_Crafting<br />AtlasLootClassic_DungeonsAndRaids<br />AtlasLootClassic_Factions<br />AtlasLootClassic_PvP<br />AtlasLootClassic<br />AAP-Classic<br />CEPGP<br />Details<br />Details_TinyThreat<br />GatherMate2<br />ItemRack<br />ItemRackOptions<br />Kui_Media<br />Kui_Nameplates<br />Kui_Nameplates_Core_Config<br />Kui_Nameplates_Core<br />LetMeCast<br />LittleWigs<br />OmniCC<br />OmniCC_Config<br />RealMobHealth<br />TitanClassicAmmo<br />TitanClassicBag<br />TitanClassicClock<br />TitanClassicGold<br />TitanClassicLocation<br />TitanClassicLootType<br />TitanClassicPerformance<br />TitanClassicRegen<br />TitanClassicRepair<br />TitanClassicVolume<br />TitanClassicXP<br />TitanClassic<br />WeakAuras<br />WeakAurasCompanion<br />WeakAurasOptions<br />WeaponSwingTimer<br />ZygorGuidesViewerClassic<br />DejaClassicStats<br />TradeSkillMaster<br />TradeSkillMaster_AppHelper<br />ElvUI<br />ElvUI_OptionsUI<br />DBM-Core<br />DBM-DefaultSkin<br />DBM-GUI<br />DBM-StatusBarTimers<br />DBM-Azeroth<br />DBM-BWL<br />DBM-Party-Classic<br />DBM-MC<br />DBM-Naxx<br />DBM-Onyxia<br />DBM-AQ20<br />DBM-AQ40<br />DBM-ZG<br />Questie<br /></details></details>

**Comment by Alumian** [comment]
Hi Gholie,

Thanks for the report. I am confident that this is due to my poor implementation of the guild scrollbar. It very inefficiently handles guilds and suffers greatly in large guilds. I have completely re-written the entire scrollbar for the next update, so I hope that fixes this problem.

**Comment by Gholie** [comment]
Keep in mind that this happens also when no window is shown. Does the addon try to compute the EPGP values at a set interval? If so that could coincide with the stutters I get when the addon is active

**Comment by Alumian** [comment]
Not so much a set interval, but when a change is detected. I'm going to see how I can reduce the impact and frequency of updates.

**Comment by Alumian** [comment]
Okay Gholie, I've worked out a solution, at least for when you add guild EP/raid EP/decay/reset standings/restore standings, but the only problem is I'm struggling to resolve the stuttering entirely. I've made it so it won't lock your game up for 10 seconds anymore, but the stutters are proving quite challenging to address. My partial solution is in the next update.

**Comment by Gholie** [comment]
Alright, thanks for the update! Looking forward to seeing it in practice :)

**Comment by Gholie** [comment]
Would it be possible to make it so only certain ranks have EPGP values attributed to them? Would be able to remove a lot of alts / socials from the equation

**Comment by Gholie** [comment]
I haven't noticed stuttering after the last update, so I'm closing this. Thanks for the great work!
