### ISSUE TITLE
[Request] Item Value display

### ISSUE THREAD

**Issue by Jozh89** [Alumian/CEPGP-Retail#44]
Hi Alumian,
Can we get a way to show the GP of a item. EG use the Slot and ilvl using the calculation for the stat weights in options like command slot ilvl
so tier 1 gloves that are a ilvl of 66 would be
/cepgp gloves 66

**Comment by Jozh89** [comment]
Could proberly close this off as /script print(CEPGP_calcGP(_, 1, x)); gives the result :)
@Alumian

**Comment by Alumian** [comment]
I'm happy to close this off if you're comfortable to use that script. It's not exactly the most user friendly option.
