### ISSUE TITLE
GP not being assigned when i use MasterLooter[Bug]

### ISSUE THREAD

**Issue by will5757** [Alumian/CEPGP-Retail#45]
Whenever i use the in game masterloot it doesn't assign any GP

<details><summary>Debug Info</summary><br />Version: 1.11.5<br /><br />GP Modifier: 1<br /><br />Base GP: 1<br /><br />Standby EP: True<br /><br />Standby Offline: False<br /><br />Standby Percent: 100<br /><br />Standby Accept Whispers: True<br /><br />Standby EP by Rank: False<br /><br />Standby EP Manual Delegation: True<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary><br /><details><summary>High Priestess Jeklik</summary>True</details><br /><details><summary>Gothik the Harvester</summary>True</details><br /><details><summary>Buru the Gorger</summary>True</details><br /><details><summary>Wushoolay</summary>True</details><br /><details><summary>Lord Kri</summary>True</details><br /><details><summary>Emperor Vek'nilash</summary>True</details><br /><details><summary>Ossirian the Unscarred</summary>True</details><br /><details><summary>Golemagg the Incinerator</summary>True</details><br /><details><summary>Grand Widow Faerlina</summary>True</details><br /><details><summary>High Priestess Mar'li</summary>True</details><br /><details><summary>Majordomo Executus</summary>True</details><br /><details><summary>High Priest Venoxis</summary>True</details><br /><details><summary>Gehennas</summary>True</details><br /><details><summary>Taerar</summary>True</details><br /><details><summary>Ysondre</summary>True</details><br /><details><summary>Thane Korth'azz</summary>True</details><br /><details><summary>High Priest Thekal</summary>True</details><br /><details><summary>Noth the Plaguebringer</summary>True</details><br /><details><summary>Lethon</summary>True</details><br /><details><summary>Moam</summary>True</details><br /><details><summary>The Prophet Skeram</summary>True</details><br /><details><summary>Flamegor</summary>True</details><br /><details><summary>C'Thun</summary>True</details><br /><details><summary>General Rajaxx</summary>True</details><br /><details><summary>Princess Huhuran</summary>True</details><br /><details><summary>Thaddius</summary>True</details><br /><details><summary>Loatheb</summary>True</details><br /><details><summary>Lady Blaumeux</summary>True</details><br /><details><summary>Highlord Mograine</summary>True</details><br /><details><summary>Heigan the Unclean</summary>True</details><br /><details><summary>Azuregos</summary>True</details><br /><details><summary>Doom Lord Kazzak</summary>True</details><br /><details><summary>Teremus the Devourer</summary>True</details><br /><details><summary>Chromaggus</summary>True</details><br /><details><summary>Baron Geddon</summary>True</details><br /><details><summary>Firemaw</summary>True</details><br /><details><summary>Sulfuron Harbinger</summary>True</details><br /><details><summary>Gri'lek</summary>True</details><br /><details><summary>High Priestess Arlokk</summary>True</details><br /><details><summary>Emperor Vek'lor</summary>True</details><br /><details><summary>Gahz'ranka</summary>True</details><br /><details><summary>Gluth</summary>True</details><br /><details><summary>Sapphiron</summary>True</details><br /><details><summary>Razorgore the Untamed</summary>True</details><br /><details><summary>Onyxia</summary>True</details><br /><details><summary>Princess Yauj</summary>True</details><br /><details><summary>Vem</summary>True</details><br /><details><summary>Shazzrah</summary>True</details><br /><details><summary>Ouro</summary>True</details><br /><details><summary>Battleguard Sartura</summary>True</details><br /><details><summary>Maexxna</summary>True</details><br /><details><summary>Kel'Thuzad</summary>True</details><br /><details><summary>Nefarian</summary>True</details><br /><details><summary>Fankriss the Unyielding</summary>True</details><br /><details><summary>Lucifron</summary>True</details><br /><details><summary>Anub'Rekhan</summary>True</details><br /><details><summary>Hazza'rah</summary>True</details><br /><details><summary>Ragnaros</summary>True</details><br /><details><summary>Ayamiss the Hunter</summary>True</details><br /><details><summary>Broodlord Lashlayer</summary>True</details><br /><details><summary>Viscidus</summary>True</details><br /><details><summary>Hakkar</summary>True</details><br /><details><summary>Ebonroc</summary>True</details><br /><details><summary>Kurinnaxx</summary>True</details><br /><details><summary>Grobbulus</summary>True</details><br /><details><summary>Instructor Razuvious</summary>True</details><br /><details><summary>Emeriss</summary>True</details><br /><details><summary>Magmadar</summary>True</details><br /><details><summary>Sir Zeliek</summary>True</details><br /><details><summary>Vaelastrasz the Corrupt</summary>True</details><br /><details><summary>Patchwerk</summary>True</details><br /><details><summary>Bloodlord Mandokir</summary>True</details><br /><details><summary>Renataki</summary>True</details><br /><details><summary>Jin'do the Hexxer</summary>True</details><br /><details><summary>Garr</summary>True</details><br /></details><br /><details><summary>EP Values</summary><br /><details><summary>High Priestess Jeklik</summary>2</details><br /><details><summary>Gothik the Harvester</summary>12</details><br /><details><summary>Buru the Gorger</summary>3</details><br /><details><summary>Wushoolay</summary>2</details><br /><details><summary>Lord Kri</summary>10</details><br /><details><summary>Emperor Vek'nilash</summary>10</details><br /><details><summary>Ossirian the Unscarred</summary>4</details><br /><details><summary>Golemagg the Incinerator</summary>5</details><br /><details><summary>Grand Widow Faerlina</summary>12</details><br /><details><summary>High Priestess Mar'li</summary>2</details><br /><details><summary>Majordomo Executus</summary>5</details><br /><details><summary>High Priest Venoxis</summary>2</details><br /><details><summary>Gehennas</summary>5</details><br /><details><summary>Taerar</summary>7</details><br /><details><summary>Ysondre</summary>7</details><br /><details><summary>Thane Korth'azz</summary>15</details><br /><details><summary>High Priest Thekal</summary>2</details><br /><details><summary>Noth the Plaguebringer</summary>12</details><br /><details><summary>Lethon</summary>7</details><br /><details><summary>Moam</summary>3</details><br /><details><summary>The Prophet Skeram</summary>10</details><br /><details><summary>Flamegor</summary>7</details><br /><details><summary>C'Thun</summary>12</details><br /><details><summary>General Rajaxx</summary>3</details><br /><details><summary>Princess Huhuran</summary>10</details><br /><details><summary>Thaddius</summary>15</details><br /><details><summary>Loatheb</summary>15</details><br /><details><summary>Lady Blaumeux</summary>15</details><br /><details><summary>Highlord Mograine</summary>15</details><br /><details><summary>Heigan the Unclean</summary>12</details><br /><details><summary>Azuregos</summary>7</details><br /><details><summary>Doom Lord Kazzak</summary>7</details><br /><details><summary>Teremus the Devourer</summary>7</details><br /><details><summary>Chromaggus</summary>7</details><br /><details><summary>Baron Geddon</summary>5</details><br /><details><summary>Firemaw</summary>7</details><br /><details><summary>Sulfuron Harbinger</summary>5</details><br /><details><summary>Gri'lek</summary>2</details><br /><details><summary>High Priestess Arlokk</summary>2</details><br /><details><summary>Emperor Vek'lor</summary>10</details><br /><details><summary>Gahz'ranka</summary>2</details><br /><details><summary>Gluth</summary>12</details><br /><details><summary>Sapphiron</summary>15</details><br /><details><summary>Razorgore the Untamed</summary>7</details><br /><details><summary>Onyxia</summary>5</details><br /><details><summary>Princess Yauj</summary>10</details><br /><details><summary>Vem</summary>10</details><br /><details><summary>Shazzrah</summary>5</details><br /><details><summary>Ouro</summary>10</details><br /><details><summary>Battleguard Sartura</summary>10</details><br /><details><summary>Maexxna</summary>15</details><br /><details><summary>Kel'Thuzad</summary>15</details><br /><details><summary>Nefarian</summary>10</details><br /><details><summary>Fankriss the Unyielding</summary>10</details><br /><details><summary>Lucifron</summary>5</details><br /><details><summary>Anub'Rekhan</summary>12</details><br /><details><summary>Hazza'rah</summary>2</details><br /><details><summary>Ragnaros</summary>7</details><br /><details><summary>Ayamiss the Hunter</summary>3</details><br /><details><summary>Broodlord Lashlayer</summary>7</details><br /><details><summary>Viscidus</summary>10</details><br /><details><summary>Hakkar</summary>3</details><br /><details><summary>Ebonroc</summary>7</details><br /><details><summary>Kurinnaxx</summary>3</details><br /><details><summary>Grobbulus</summary>12</details><br /><details><summary>Instructor Razuvious</summary>12</details><br /><details><summary>Emeriss</summary>7</details><br /><details><summary>Magmadar</summary>5</details><br /><details><summary>Sir Zeliek</summary>15</details><br /><details><summary>Vaelastrasz the Corrupt</summary>7</details><br /><details><summary>Patchwerk</summary>12</details><br /><details><summary>Bloodlord Mandokir</summary>2</details><br /><details><summary>Renataki</summary>2</details><br /><details><summary>Jin'do the Hexxer</summary>2</details><br /><details><summary>Garr</summary>5</details><br /></details><br /><details><summary>Standby Guild Ranks</summary><br /><details><summary>Raider</summary>False</details><br /><details><summary>Senior Officer</summary>False</details><br /><details><summary>Officer</summary>False</details><br /><details><summary>Raider</summary>False</details><br /><details><summary>Craftsman</summary>False</details><br /><details><summary>Alt</summary>False</details><br /><details><summary>Member</summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /><details><summary></summary>False</details><br /></details><br /><details><summary>Slot Weights</summary><br /><details><summary>2HWEAPON</summary>2</details><br /><details><summary>NECK</summary>0.5</details><br /><details><summary>HEAD</summary>1</details><br /><details><summary>WEAPON</summary>1.5</details><br /><details><summary>WRIST</summary>0.5</details><br /><details><summary>WEAPONMAINHAND</summary>1.5</details><br /><details><summary>SHIELD</summary>0.5</details><br /><details><summary>HOLDABLE</summary>0.5</details><br /><details><summary>RANGED</summary>0.5</details><br /><details><summary>SHOULDER</summary>0.75</details><br /><details><summary>FEET</summary>0.75</details><br /><details><summary>LEGS</summary>1</details><br /><details><summary>EXCEPTION</summary>1</details><br /><details><summary>WAIST</summary>0.75</details><br /><details><summary>TRINKET</summary>0.75</details><br /><details><summary>HAND</summary>0.75</details><br /><details><summary>ROBE</summary>1</details><br /><details><summary>CHEST</summary>1</details><br /><details><summary>CLOAK</summary>0.5</details><br /><details><summary>FINGER</summary>0.5</details><br /><details><summary>WEAPONOFFHAND</summary>0.5</details><br /><details><summary>RANGEDRIGHT</summary>0.5</details><br /><details><summary>RELIC</summary>0.5</details><br /><details><summary>THROWN</summary>0.5</details><br /></details><br /><details><summary>Addons List</summary><br />AdvancedInterfaceOptions<br />AtlasLootClassic_Options<br />AtlasLootClassic_Collections<br />AtlasLootClassic_Crafting<br />AtlasLootClassic_DungeonsAndRaids<br />AtlasLootClassic_Factions<br />AtlasLootClassic_PvP<br />AtlasLootClassic<br />Auctionator<br />BetterVendorPrice<br />BuffwatchClassic<br />CEPGP<br />ClassicThreatMeter<br />CT_BarMod<br />CT_BottomBar<br />CT_BuffMod<br />CT_Core<br />CT_ExpenseHistory<br />CT_Library<br />CT_MailMod<br />CT_MapMod<br />CT_PartyBuffs<br />CT_RaidAssist<br />CT_Timer<br />CT_UnitFrames<br />CT_Viewport<br />Details<br />Details_TinyThreat<br />ErrorFilter<br />ExtendedCharacterStats<br />FasterLooting<br />FieldGuide<br />GatherMate2<br />Grid2<br />Grid2Options<br />Grid2RaidDebuffs<br />Grid2RaidDebuffsOptions<br />Grid2LDB<br />GridStatusRaidDebuff<br />Leatrix_Plus<br />LetMeCast<br />CallbackHandler-1.0<br />LibClassicMobHealth-1.0<br />LibStub<br />LibClassicDurations<br />Mapster<br />MobInfo2<br />oRA3<br />out of range 1.3<br />QuestAnnounce<br />ReturnBuffTracker<br />TellMeWhen<br />TellMeWhen_Options<br />TinyTooltip<br />WIM<br />ElvUI<br />ElvUI_OptionsUI<br />ElvUI_RealMobHealth_Tags<br />DBM-Core<br />DBM-DefaultSkin<br />DBM-GUI<br />DBM-StatusBarTimers<br />DBM-Azeroth<br />DBM-BWL<br />DBM-Party-Classic<br />DBM-MC<br />DBM-Naxx<br />DBM-Onyxia<br />DBM-AQ20<br />DBM-AQ40<br />DBM-ZG<br />Questie<br /></details></details>

**Comment by Alumian** [comment]
How long has this been happening for and does it happen every time? Also does it say the message "[Itemname] has been awarded to playername for x GP"?

**Comment by will5757** [comment]
no message, nothing.  I only recently started using epgp, were still in the sort of testing phase? If i can't get GP to go to people automatically i'll have to do it manually (either by calculating gp myself, or just by useing a flat rate for everything)

I could try disabling some addons, but will GP be allocated for something like deadmines? I can't really justify turning off my ui and raiding addons during a actual raid to test it.  Were not currently using epgp to allocate loot, we are hopeing to on the 16th though

I've used the epgp addon for 2 runs of MC and a ony now, and there's been exactly 0 GP allocated to anyone unless i do it manually.  EP for boss kills works perfectly though

**Comment by Alumian** [comment]
Are you using ElvUI?

**Comment by will5757** [comment]
yes, is it incompatible?

**Comment by Alumian** [comment]
1.11.5 isn't but I'm going to push a new version with major changes. One of the changes includes a compatibility fix for ElvUI that lets CEPGP access the loot frame again.

**Comment by Alumian** [comment]
Version 1.12.0 has just been released. Please download the new version and try again and do please ensure that any of your guild members that use the addon also download the update.

**Comment by will5757** [comment]
I can now see the loot window, but the !need doesn't really work (i had one guy show up once)

do all the raiders need to be running the addon for that to work? i thought they would only need it for gear comparison or for the click to need functionality

**Comment by Alumian** [comment]
Related to https://github.com/Alumian/CEPGP-Retail/issues/51. It will be fixed in the next hotfix. I'm working on the last fix now and once that's done I'll push the update.

**Comment by will5757** [comment]
thanks a ton for your hard work btw.  Really appreciate it

**Comment by Alumian** [comment]
No problem :)

**Comment by Alumian** [comment]
Since this issue has now been resolved, I'm closing this ticket.
