### ISSUE TITLE
[Request] Option for Greed/Offspec Responses

### ISSUE THREAD

**Issue by Alumian** [Alumian/CEPGP-Retail#5]
**Describe the feature you'd like to see in this addon**
Requested by PibbzTV in ticket https://github.com/Alumian/CEPGP-Retail/issues/4, he has requested for the option for the loot master to allow greed/offspec rolls in raids.
He has referred to the addon EPGP_Lootmaster (https://www.curseforge.com/wow/addons/epgp_lootmaster/screenshots) as an example of what he would like implemented.

**Comment by PibbzTV** [comment]
To be honest, I would be perfectly fine if you did NOT implement this. I was just trying to make sure that IF you chose to do it, that the appearance of these buttons would be "toggleable" by the Master Looter.

Feel free to close this request :)

**Comment by Alumian** [comment]
No worries!
