### ISSUE TITLE
import csv[Request]

### ISSUE THREAD

**Issue by skombag** [Alumian/CEPGP-Retail#50]
Would be great if we could have import function that works with the exact format the export put out.

**Comment by Alumian** [comment]
Sounds easy enough, but I'm just wondering what value this feature will add? Just because, normally people wouldn't modify EPGP externally and import it to the game, it's usually the other way round. Do you foresee your guild doing this?

**Comment by skombag** [comment]
yes very much, needed been planning with it in mind. So to explain , we will have out of raid EP gains via gb donations that we will calculate once a week and to keep track of this  we made a spreadsheet which we will use on an export of epgp and after that will import back to the game , otherwise going 1 by 1 on a big roster would be insane time sink.

**Comment by Alumian** [comment]
I see I see. Alright fair enough, like I said it should be easy enough as long as it's something simple like a CSV format. Leave it with me and once I get these bugs under control I'll look into it.

**Comment by Alumian** [comment]
Implemented in the next beta.
