### ISSUE TITLE
!need not recognized from BattleTag friend whisper [Bug]

### ISSUE THREAD

**Issue by Belter1** [Alumian/CEPGP-Retail#54]
**The Error**
No error message

**Describe the bug**
When I get a light blue colored whisper from a battletag friend the addon does not report that !need tell or add them to the distribution list.

**To Reproduce**
Have a battletag friend try to !need for an item (light blue colored chat, not purple).

**Debug Information**
Not available at the moment. I can try to capture this when I am on this evening and post.

**Comment by Alumian** [comment]
It won't work for a battle tag friend because the add-on is trying to read the players character name. This isn't a bug, it's just incompatible features.

**Comment by Alumian** [comment]
Alrighty, I found a solution for this and it'll be included in the next hotfix which will hopefully be today.

**Comment by Belter1** [comment]
thank you!
