### ISSUE TITLE
giving ep and gp to wrong person

### ISSUE THREAD

**Issue by daiqll** [Alumian/CEPGP-Retail#57]
During today's raid, I assigned EP to a member and traffic shows it is added to that person, but the EP was actually assigned to another raid member.
I suspect it does the same to GP because a lot raid member had problems with their ep or gp during today's raid.
This only start happening this week after the recent update. didn't have any problem last week.

**Comment by Alumian** [comment]
Post your /cep debug.

**Comment by daiqll** [comment]
<details><summary>Debug Info</summary><br />Version: 1.12.0<br /><br />GP Modifier: 1<br /><br />Base GP: 100<br /><br />Standby EP: False<br /><br />Standby Offline: False<br /><br />Standby Percent: 100<br /><br />Standby Accept Whispers: False<br /><br />Standby EP by Rank: False<br /><br />Standby EP Manual Delegation: True<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary>High Priestess Jeklik: True<br />Gothik the Harvester: True<br />Buru the Gorger: True<br />Wushoolay: True<br />Lord Kri: True<br />Emperor Vek'nilash: True<br />Ossirian the Unscarred: True<br />Golemagg the Incinerator: True<br />Grand Widow Faerlina: True<br />High Priestess Mar'li: True<br />Majordomo Executus: True<br />High Priest Venoxis: True<br />Gehennas: True<br />Taerar: True<br />Ysondre: True<br />Thane Korth'azz: True<br />High Priest Thekal: True<br />Noth the Plaguebringer: True<br />Lethon: True<br />Moam: True<br />The Prophet Skeram: True<br />Flamegor: True<br />C'Thun: True<br />General Rajaxx: True<br />Princess Huhuran: True<br />Thaddius: True<br />Loatheb: True<br />Lady Blaumeux: True<br />Highlord Mograine: True<br />Heigan the Unclean: True<br />Azuregos: True<br />Doom Lord Kazzak: True<br />Teremus the Devourer: True<br />Chromaggus: True<br />Baron Geddon: True<br />Firemaw: True<br />Sulfuron Harbinger: True<br />Gri'lek: True<br />High Priestess Arlokk: True<br />Emperor Vek'lor: True<br />Gahz'ranka: True<br />Gluth: True<br />Sapphiron: True<br />Razorgore the Untamed: True<br />Onyxia: True<br />Princess Yauj: True<br />Vem: True<br />Shazzrah: True<br />Ouro: True<br />Battleguard Sartura: True<br />Maexxna: True<br />Kel'Thuzad: True<br />Nefarian: True<br />Fankriss the Unyielding: True<br />Lucifron: True<br />Anub'Rekhan: True<br />Hazza'rah: True<br />Ragnaros: True<br />Ayamiss the Hunter: True<br />Broodlord Lashlayer: True<br />Viscidus: True<br />Hakkar: True<br />Ebonroc: True<br />Kurinnaxx: True<br />Grobbulus: True<br />Instructor Razuvious: True<br />Emeriss: True<br />Magmadar: True<br />Sir Zeliek: True<br />Vaelastrasz the Corrupt: True<br />Patchwerk: True<br />Bloodlord Mandokir: True<br />Renataki: True<br />Jin'do the Hexxer: True<br />Garr: True<br /></details><br /><details><summary>EP Values</summary>High Priestess Jeklik: 2<br />Gothik the Harvester: 12<br />Buru the Gorger: 3<br />Wushoolay: 2<br />Lord Kri: 10<br />Emperor Vek'nilash: 10<br />Ossirian the Unscarred: 4<br />Golemagg the Incinerator: 100<br />Grand Widow Faerlina: 12<br />High Priestess Mar'li: 2<br />Majordomo Executus: 100<br />High Priest Venoxis: 2<br />Gehennas: 100<br />Taerar: 7<br />Ysondre: 7<br />Thane Korth'azz: 15<br />High Priest Thekal: 2<br />Noth the Plaguebringer: 12<br />Lethon: 7<br />Moam: 3<br />The Prophet Skeram: 10<br />Flamegor: 7<br />C'Thun: 12<br />General Rajaxx: 3<br />Princess Huhuran: 10<br />Thaddius: 15<br />Loatheb: 15<br />Lady Blaumeux: 15<br />Highlord Mograine: 15<br />Heigan the Unclean: 12<br />Azuregos: 7<br />Doom Lord Kazzak: 7<br />Teremus the Devourer: 7<br />Chromaggus: 7<br />Baron Geddon: 100<br />Firemaw: 7<br />Sulfuron Harbinger: 100<br />Gri'lek: 2<br />High Priestess Arlokk: 2<br />Emperor Vek'lor: 10<br />Gahz'ranka: 2<br />Gluth: 12<br />Sapphiron: 15<br />Razorgore the Untamed: 7<br />Onyxia: 200<br />Princess Yauj: 10<br />Vem: 10<br />Shazzrah: 100<br />Ouro: 10<br />Battleguard Sartura: 10<br />Maexxna: 15<br />Kel'Thuzad: 15<br />Nefarian: 10<br />Fankriss the Unyielding: 10<br />Lucifron: 100<br />Anub'Rekhan: 12<br />Hazza'rah: 2<br />Ragnaros: 200<br />Ayamiss the Hunter: 3<br />Broodlord Lashlayer: 7<br />Viscidus: 10<br />Hakkar: 3<br />Ebonroc: 7<br />Kurinnaxx: 3<br />Grobbulus: 12<br />Instructor Razuvious: 12<br />Emeriss: 7<br />Magmadar: 100<br />Sir Zeliek: 15<br />Vaelastrasz the Corrupt: 7<br />Patchwerk: 12<br />Bloodlord Mandokir: 2<br />Renataki: 2<br />Jin'do the Hexxer: 2<br />Garr: 100<br /></details><br /><details><summary>Standby Guild Ranks</summary>Guild Master: False<br />Raid Leader: False<br />Officer: False<br />Verified: False<br />Unverified: False<br />Initiate: False<br /></details><br /><details><summary>Slot Weights</summary>2HWEAPON: 2<br />NECK: 0.5<br />HEAD: 1<br />WEAPON: 1.5<br />WRIST: 0.5<br />WEAPONMAINHAND: 1.5<br />SHIELD: 0.5<br />HOLDABLE: 0.5<br />RANGED: 0.5<br />SHOULDER: 0.75<br />FEET: 0.75<br />LEGS: 1<br />EXCEPTION: 1<br />WAIST: 0.75<br />TRINKET: 0.75<br />HAND: 0.75<br />ROBE: 1<br />CHEST: 1<br />CLOAK: 0.5<br />FINGER: 0.5<br />WEAPONOFFHAND: 0.5<br />RANGEDRIGHT: 0.5<br />RELIC: 0.5<br />THROWN: 0.5<br /></details><br /><details><summary>Override List</summary>Blastershot Launcher: 100<br />Earthfury Legguards: 50<br />Stormrage Cover: 100<br />Talisman of Ephemeral Power: 150<br />Lawbringer Chestguard: 50<br />Sabatons of Might: 50<br />Felheart Glvoes: 50<br />Felheart Slippers: 50<br />Arcanist Robes: 50<br />Shadowstrike: 25<br />Crimson Shocker: 25<br />Lawbringer Gauntlets: 50<br />Salamander Scale Pants: 25<br />Onslaught Girdle: 100<br />Pants of Prophecy: 50<br />Pauldrons of Might: 50<br />Helm of the Lifegiver: 50<br />Giantstalker's Gloves: 50<br />Magma Tempered Boots: 25<br />Boots of Prophecy: 50<br />Aged Core Leather Gloves: 50<br />Sapphiron Drape: 50<br />Fireproof Cloak: 25<br />Felheart Shoulder Pads: 50<br />Netherwind Pants: 100<br />Nightslayer Boots: 50<br />Dragon's Blood Cape: 25<br />Nightslayer Pants: 50<br />Bindings of the Windseeker: 500<br />The Eye of Divinity: 200<br />Sabatons of the Flamewalker: 50<br />Aurastone Hammer: 100<br />Bloodfang Pants: 100<br />Vis'kag the Bloodletter: 150<br />Felheart Pants: 50<br />Choker of the Fire Lord: 100<br />Gloves of Prophecy: 50<br />[Helm of Wrath]: 100<br />Lawbringer Helm: 50<br />Quick Strike Ring: 100<br />Earthfury Boots: 50<br />Earthfury Helmet: 50<br />Helm of Might: 50<br />Ring of Binding: 25<br />Heavy Dark Iron Ring: 50<br />Manastorm Leggings: 50<br />[Stormrage Cover]: 100<br />Obsidian Edged Blade: 100<br />Core Forged Greaves: 25<br />Arcanist Mantle: 50<br />Netherwind Crown: 100<br />Head of Onyxia: 100<br />Fireguard Shoulders: 25<br />Earthfury Vestments: 50<br />Gloves of the Hypnotic Flame: 25<br />Gutgore Ripper: 100<br />Judgement Legplates: 100<br />Cenarion Gloves: 50<br />Choker of Enlightenment: 50<br />Nightslayer Shoulder Pads: 50<br />Halo of Transcendence: 100<br />Dragonstalker's Helm: 100<br />Giantstalker's Boots: 50<br />Breastplate of Might: 50<br />Ancient Petrified Leaf: 200<br />Fire Runed Grimoire: 50<br />[Core Forged Greaves]: 25<br />Lawbringer Boots: 50<br />Giantstalker's Breastplate: 50<br />Eye of Sulfuras: 500<br />Nemesis Skullcap: 100<br />Cenarion Spaulders: 50<br />Cenarion Helm: 50<br />Cenarion Leggings: 50<br />Giantstalker's Helmet: 50<br />Legplates of Might: 50<br />Legplates of Ten Storms: 100<br />Shard of the Scale: 50<br />Nightslayer Gloves: 50<br />Lawbringer Legplates: 50<br />Striker's Mark: 100<br />Helmet of Ten Storms: 100<br />Giantstalker's Leggings: 50<br />Mature Black Dragon Sinew: 50<br />Arcanist Leggings: 50<br />Flameguard Gauntlets: 50<br />Gauntlets of Might: 50<br />Deathbringer: 150<br />Seal of the Archmagus: 25<br />Onyxia Hide Backpack: 50<br />Nemesis Leggings: 100<br />Stormrage Legguards: 100<br />Arcanist Gloves: 50<br />Leggings of Transcendence: 100<br />Nightslayer Chestpiece: 50<br />Earthshaker: 25<br />Deep Earth Spaulders: 50<br />Felheart Horns: 50<br />Malistar's Defender: 100<br />Mana Igniting Cord: 100<br />Arcanist Boots: 50<br />Sash of Whispered Secrets: 25<br />Wristguards of True Flight: 50<br />Band of Sulfuras: 50<br />Earthfury Epaulets: 50<br />Spinal Reaper: 150<br />Bloodfang Hood: 100<br />Drillborer Disk: 50<br />Staff of Dominance: 150<br />Circlet of Prophecy: 50<br />Shard of the Flame: 25<br />Legplates of Wrath: 100<br />Dragonstalker's Legguards: 100<br />Finkle's Lava Dredger: 50<br />Cenarion Vestments: 50<br />Core Hound Tooth: 100<br />Judgement Crown: 100<br />Felheart Robes: 50<br />Cenarion Boots: 50<br />Cauterizing Band: 100<br />Essence of the Pure Flame: 25<br />Earthfury Gauntlets: 50<br />Lawbringer Spaulders: 50<br />Robe of Volatile Power: 50<br />Eskhandar's Right Claw: 100<br />Nightslayer Cover: 50<br />Azuresong Mageblade: 150<br />Band of Accuria: 100<br />Ring of Spell Power: 100<br />Perdition's Blade: 200<br />Cloak of the Shrouded Mists: 100<br />Wristguards of Stability: 50<br />Sorcerous Dagger: 100<br />Wild Growth Spaulders: 50<br />Bonereaver's Edge: 250<br />Crown of Destruction: 150<br />Mantle of Prophecy: 50<br />Giantstalker's Epaulets: 50<br />Ancient Cornerstone Grimoire: 25<br />Flamewaker Legplates: 25<br />Arcanist Crown: 50<br />Eskhandar's Collar: 50<br />Medallion of Steadfast Might: 50<br />Brutality Blade: 100<br />Robes of Prophecy: 50<br />Robe of Volatile Power : 100<br /></details><br /><details><summary>Addons List</summary><br />AdvancedInterfaceOptions<br />Atlas<br />Atlas_ClassicWoW<br />AtlasLootClassic<br />Auctionator<br />AutoLoggerClassic<br />BiSTracker<br />BuffwatchClassic<br />BuyEmAll<br />CEPGP<br />ClassicAuraDurations<br />ClassicThreatMeter<br />Decursive<br />Details<br />Details_TinyThreat<br />ExRT<br />Fizzle<br />GambleClassic<br />HealComm<br />InFlight_Load<br />ItemRack<br />ItemTooltipProfessionIcons<br />LibItems<br />LibClassicDurations<br />LoseControl<br />MaxCam<br />MBB<br />!MoncaiCompare<br />OmniCC<br />Pawn<br />Postal<br />RCLootCouncil_Classic<br />RealMobHealth<br />RollTrackerClassic<br />SharedMedia<br />SharedMedia_MyMedia<br />SmartBuff<br />TidyPlates_ThreatPlates<br />TomTom<br />TownsfolkTracker<br />VendorPrice<br />WeakAuras<br />CharacterStatsClassic<br />DejaClassicStats<br />TradeSkillMaster<br />TradeSkillMaster_AppHelper<br />ElvUI<br />WoWPro<br />WoWPro_Leveling<br />DBM-Core<br />DBM-DefaultSkin<br />DBM-StatusBarTimers<br />DBM-VPMuxia<br />DBM-VPYike<br />Questie<br /></details></details>

**Comment by Alumian** [comment]
This issue was resolved in version 1.12.2 (commit https://github.com/Alumian/CEPGP-Retail/commit/27352ebc6b55f0d37222182a2ed18731857a23b8). Download the latest version.

**Comment by daiqll** [comment]
i was using it, and it only happened after i update yesterday

**Comment by daiqll** [comment]
i see there is a 1.12.13 now i will try that again tmr

**Comment by Alumian** [comment]
Well I need the debug info of the version you're using. Re-download the new version and post the debug info if it happens again.
