### ISSUE TITLE
[Request] Subtract EP

### ISSUE THREAD

**Issue by dkworldentertainment** [Alumian/CEPGP-Retail#6]
Could you allow to put negative values in the Give EP window, or a button to subtract EP?

Thank you so much

**Comment by Alumian** [comment]
Hi Dkworldentertainment,
I should be able to work on/implement this during the next stress test (don't hold me to that though since I do have a few other features that have been requested).

Thanks,
Alumian

**Comment by Alumian** [comment]
Hi Dkworldentertainment,

Just giving you an update on this. I had a request on my original addon for this exact same feature, so I've already implemented it in that version. When the stress test happens I should be able to just move the changes over so it shouldn't take long.

Thanks

**Comment by Alumian** [comment]
Hi Dkworldentertainment,

Just letting you know that your feature request has now been implemented in version 1.11.0 which was just pushed out.

Thanks,
Alumian
