### ISSUE TITLE
[Request] make the Raid Attendance table sort by attendance starting with 100% at the top

### ISSUE THREAD

**Issue by mykkenny** [Alumian/CEPGP-Retail#60]
Great feature but in a large guild it's unusable without sorting. 

If you wanted to go further allow us to make the attendance % column reflect attendance in the last 7/14/30/60/90 days.

Also maybe move the button for it out of the options page and put it next to the View EPGP Traffic button. Move the two standings buttons to the right so that Save, Export and Restore are together.

**Comment by Alumian** [comment]
Makes sense. I'll look into this.

**Comment by mykkenny** [comment]
Option to restrict to certain ranks is also desirable / alternate solution to sorting. Be happy just to see the raiders and officers.

**Comment by Alumian** [comment]
Okay that feature might take a little bit longer to add.
