### ISSUE TITLE
[Question]Raid wide decay

### ISSUE THREAD

**Issue by miketonny** [Alumian/CEPGP-Retail#63]
Is there a way i could decay the EP points for my raid rather than for the entire guild? 
What i noticed when i decay a 10% EP for entire guild is, some of the raid members will be set to wrong points, either their GP were cleared to default (1), or their EP was cleared to 0, which makes it practically unusable unless I decay them manually one by one.

**Comment by Alumian** [comment]
What version of the add-on are you using?

**Comment by miketonny** [comment]
1.12.3, i also tried this on 2 different PCs, both not working and different players are affected each time i decay. The size of guild is around 800, there are a handful of names with special characters which addon cannot recognize, not sure if this is related.

**Comment by miketonny** [comment]
seems to be alright with latest version now
