### ISSUE TITLE
[Bug] Initial GP is not being enforced on new guild members

### ISSUE THREAD

**Issue by sostoked** [Alumian/CEPGP-Retail#65]
**The Error**

None

**Describe the bug**

When new members join my guild. Even though our starting gp is listed as 10 in the add-on, their gp is showing as 1 on the list. All members have been synced 

**To Reproduce**

Initial/Minimum Player GP: 10 and invite a new member to the guild. 

**Debug Information**
<details><summary>Debug Info</summary><br />Version: 1.12.3<br /><br />GP Modifier: 1<br /><br />Base GP: 10<br /><br />Standby EP: True<br /><br />Standby Offline: False<br /><br />Standby Percent: 100<br /><br />Standby Accept Whispers: False<br /><br />Standby EP by Rank: False<br /><br />Standby EP Manual Delegation: True<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary>High Priestess Jeklik: True<br />Gothik the Harvester: True<br />Buru the Gorger: True<br />Wushoolay: True<br />Lord Kri: True<br />Emperor Vek'nilash: True<br />Ossirian the Unscarred: True<br />Golemagg the Incinerator: True<br />Grand Widow Faerlina: True<br />High Priestess Mar'li: True<br />Majordomo Executus: True<br />High Priest Venoxis: True<br />Gehennas: True<br />Taerar: True<br />Ysondre: True<br />Thane Korth'azz: True<br />High Priest Thekal: True<br />Noth the Plaguebringer: True<br />Lethon: True<br />Moam: True<br />The Prophet Skeram: True<br />Flamegor: True<br />C'Thun: True<br />General Rajaxx: True<br />Princess Huhuran: True<br />Thaddius: True<br />Loatheb: True<br />Lady Blaumeux: True<br />Highlord Mograine: True<br />Heigan the Unclean: True<br />Azuregos: True<br />Doom Lord Kazzak: True<br />Teremus the Devourer: True<br />Chromaggus: True<br />Baron Geddon: True<br />Firemaw: True<br />Sulfuron Harbinger: True<br />Gri'lek: True<br />High Priestess Arlokk: True<br />Emperor Vek'lor: True<br />Gahz'ranka: True<br />Gluth: True<br />Sapphiron: True<br />Razorgore the Untamed: True<br />Onyxia: True<br />Princess Yauj: True<br />Vem: True<br />Shazzrah: True<br />Ouro: True<br />Battleguard Sartura: True<br />Maexxna: True<br />Kel'Thuzad: True<br />Nefarian: True<br />Fankriss the Unyielding: True<br />Lucifron: True<br />Anub'Rekhan: True<br />Hazza'rah: True<br />Ragnaros: True<br />Ayamiss the Hunter: True<br />Broodlord Lashlayer: True<br />Viscidus: True<br />Hakkar: True<br />Ebonroc: True<br />Kurinnaxx: True<br />Grobbulus: True<br />Instructor Razuvious: True<br />Emeriss: True<br />Magmadar: True<br />Sir Zeliek: True<br />Vaelastrasz the Corrupt: True<br />Patchwerk: True<br />Bloodlord Mandokir: True<br />Renataki: True<br />Jin'do the Hexxer: True<br />Garr: True<br /></details><br /><details><summary>EP Values</summary>High Priestess Jeklik: 2<br />Gothik the Harvester: 12<br />Buru the Gorger: 3<br />Wushoolay: 2<br />Lord Kri: 10<br />Emperor Vek'nilash: 10<br />Ossirian the Unscarred: 4<br />Golemagg the Incinerator: 5<br />Grand Widow Faerlina: 12<br />High Priestess Mar'li: 2<br />Majordomo Executus: 5<br />High Priest Venoxis: 2<br />Gehennas: 5<br />Taerar: 7<br />Ysondre: 7<br />Thane Korth'azz: 15<br />High Priest Thekal: 2<br />Noth the Plaguebringer: 12<br />Lethon: 7<br />Moam: 3<br />The Prophet Skeram: 10<br />Flamegor: 7<br />C'Thun: 12<br />General Rajaxx: 3<br />Princess Huhuran: 10<br />Thaddius: 15<br />Loatheb: 15<br />Lady Blaumeux: 15<br />Highlord Mograine: 15<br />Heigan the Unclean: 12<br />Azuregos: 7<br />Doom Lord Kazzak: 7<br />Teremus the Devourer: 7<br />Chromaggus: 7<br />Baron Geddon: 5<br />Firemaw: 7<br />Sulfuron Harbinger: 5<br />Gri'lek: 2<br />High Priestess Arlokk: 2<br />Emperor Vek'lor: 10<br />Gahz'ranka: 2<br />Gluth: 12<br />Sapphiron: 15<br />Razorgore the Untamed: 7<br />Onyxia: 5<br />Princess Yauj: 10<br />Vem: 10<br />Shazzrah: 5<br />Ouro: 10<br />Battleguard Sartura: 10<br />Maexxna: 15<br />Kel'Thuzad: 15<br />Nefarian: 10<br />Fankriss the Unyielding: 10<br />Lucifron: 5<br />Anub'Rekhan: 12<br />Hazza'rah: 2<br />Ragnaros: 7<br />Ayamiss the Hunter: 3<br />Broodlord Lashlayer: 7<br />Viscidus: 10<br />Hakkar: 3<br />Ebonroc: 7<br />Kurinnaxx: 3<br />Grobbulus: 12<br />Instructor Razuvious: 12<br />Emeriss: 7<br />Magmadar: 5<br />Sir Zeliek: 15<br />Vaelastrasz the Corrupt: 7<br />Patchwerk: 12<br />Bloodlord Mandokir: 2<br />Renataki: 2<br />Jin'do the Hexxer: 2<br />Garr: 5<br /></details><br /><details><summary>Standby Guild Ranks</summary>GM: False<br />AGM: False<br />Officer: False<br />Officer's Alts: False<br />Founder: False<br />Alts: False<br />Members: False<br /></details><br /><details><summary>Slot Weights</summary>2HWEAPON: 2<br />NECK: 0.5<br />HEAD: 1<br />WEAPON: 1.5<br />WRIST: 0.5<br />WEAPONMAINHAND: 1.5<br />SHIELD: 0.5<br />HOLDABLE: 0.5<br />RANGED: 0.5<br />SHOULDER: 0.75<br />FEET: 0.75<br />LEGS: 1<br />EXCEPTION: 1<br />WAIST: 0.75<br />TRINKET: 0.75<br />HAND: 0.75<br />ROBE: 1<br />CHEST: 1<br />CLOAK: 0.5<br />FINGER: 0.5<br />WEAPONOFFHAND: 0.5<br />RANGEDRIGHT: 0.5<br />RELIC: 0.5<br />THROWN: 0.5<br /></details><br /><details><summary>Override List</summary>Ring of binding : 8<br /></details><br /><details><summary>Addons List</summary><br />Atlas<br />Atlas_ClassicWoW<br />AtlasLootClassic<br />AtlasQuest<br />Auctionator<br />Bartender4<br />CEPGP<br />Details<br />Details_TinyThreat<br />GatherMate2<br />ItemRack<br />Kui_Media<br />Kui_Nameplates<br />Kui_Nameplates_Core<br />Leatrix_Maps<br />MikScrollingBattleText<br />MoveAnything<br />TomPoints<br />TomTom<br />WeakAuras<br />XpTracker<br />ZygorGuidesViewerClassic<br />ElvUI<br />DBM-Core<br />DBM-DefaultSkin<br />DBM-StatusBarTimers<br />Questie<br **/></details></details>**

**Comment by skombag** [comment]
can confirm same issue here but i can also explain why it happened, an officer with addon settings reset was only online for the new invited ppl so their base gp is at default, this can be solved by making sure everyone has synced settings.

**Comment by Alumian** [comment]
I think I've fixed this issue in the version I've been working on, just need to test it.

**Comment by Alumian** [comment]
Confirmed resolved in https://github.com/Alumian/CEPGP-Retail/releases/tag/1.12.4
