### ISSUE TITLE
[Request] Import settings also imports traffic

### ISSUE THREAD

**Issue by Andrioden** [Alumian/CEPGP-Retail#67]
Using the import settings function should also import traffic history (change list). Ill give two perspectives why this is important:

1. Non-officers that only view the epgp data has no way to verify what has happened to the system, increasing the level of trust needed.
2. Allow sync between officers/managers of the epgp, so they can verify eachothers work and avoid duplicate (both decaying, both giving x or y, etc).

**Comment by Alumian** [comment]
Traffic can now be shared in 1.12.15, however it remains a separate function.

**Comment by Andrioden** [comment]
@Alumian - Suberb that you have added this! <3

We tested it now, and we are getting duplicates. Here is what we did:
1. I was masterlooter
2. Syrric did some manuall masterlooting as you can see.
3. I crashed while dragging the view traffic window and lost 3 of the 4 top logs in the screenshot.
4. I logged back on, and Syrric clicked share all entries. So i would get those 3.

The result is that I got the 3 i lost, but also duplicate of everything before. Maybe a looser "uniqueness" check needs to be done for each row.

![image](https://user-images.githubusercontent.com/393376/84604635-afbe4b00-ae97-11ea-838a-7206af6560d9.png)

Also, remove them with "X" dont work either.

**Comment by Alumian** [comment]
@Andrioden could you please send me your saved variables file on Discord? Or you can upload it here if you like, idm. I'll check out your traffic log and see if I can work out what went wrong.

**Comment by Andrioden** [comment]
Here!

[CEPGP.lua.txt](https://github.com/Alumian/CEPGP-Retail/files/4777268/CEPGP.lua.txt)

**Comment by Alumian** [comment]
Thanks for sending that through. I've checked your traffic log and I only found one traffic entry with the description `Add Raid EP +29 (BWL+MC Speed 20:00-22:50)`.
Could you please try reloading your UI and let me know if the issue persists? This may just be a visual bug.

**Comment by Andrioden** [comment]
My bad, seems like i didnt upload an updated file. Here it is, i checked myself. Its duplicate rows.

[CEPGP.lua.txt](https://github.com/Alumian/CEPGP-Retail/files/4777295/CEPGP.lua.txt)

**Comment by Alumian** [comment]
Were these logs shared one by one? Or all at once?

**Comment by Andrioden** [comment]
All at once

**Comment by Alumian** [comment]
Ok thanks. I'm looking into it.

**Comment by Andrioden** [comment]
Maybe you should reopen this issue? : >

**Comment by Alumian** [comment]
> Maybe you should reopen this issue? : >

This ticket was the request for the feature, not a bug report. But to update you on the status of this, I have performed slight refactoring of this module and results are promising. Other features are also being testing along side it before being packaged into a release.
