### ISSUE TITLE
[Request] Can initiate need request without masterlooting a boss

### ISSUE THREAD

**Issue by Andrioden** [Alumian/CEPGP-Retail#68]
Sometimes you need to redistribute loot, or distribute boe's after the item was looted. Today it is not possible to do this through the very nice and practical loot/need gui that pops up when you master loot a boss/mob with an epic, but instead have to be manually done outside of it.

My request is either
A) An button in the Raid part of the gui to distribute something based on a text.
B) A /cep command. Like /cep announce [item]

**Comment by Alumian** [comment]
Thanks for the feature request. Unfortunately, this addon relies on slot numbers and confirmation events to ensure the correct allocation of GP. As these are not present in trades, I cannot guarantee accuracy. At this stage, this feature will not be added.
