### ISSUE TITLE
[Request] Greater Customisation of GP Formula

### ISSUE THREAD

**Issue by hbjose** [Alumian/CEPGP-Retail#7]
Hi,

is it possible to enable editing of the formula?

I want to edit the formula from GP = "0.483 x **2** ilvl/26" into "0.483 x **4** ilvl/26"

I see some discrepancies between the value of the items and the GP. 

f.e. with "x2" Eye of Sulfuras costs more GP than the bindings and with "x4" the differences between the items are larger and therefore more accurate.

**Comment by Alumian** [comment]
Hi Hbjose,

Shouldn't be too difficult to implement. Just to confirm, are you proposing that more parts of the GP formula could be modified? Or are you proposing that a custom formula could be used?

Thanks

**Comment by hbjose** [comment]
No, i only want to change this modifier. I think the rest of the formular makes sense. 

Thanks for the fast answer

**Comment by Alumian** [comment]
Okay no problem, easy to implement. I'll try to get that done during the stress test but I've got a couple of other feature requests that I need to work on too, but yeah I can definitely put that in for you - and no worries haha.

**Comment by Alumian** [comment]
Hi hbjose,

Just letting you know that your request has been implemented in version 1.11.0 which has just been pushed out.

Thanks,
Alumian
