### ISSUE TITLE
[Bug] Unexpected change in officer's notes for people who are not in the raid

### ISSUE THREAD

**Issue by leinstay** [Alumian/CEPGP-Retail#71]
![Screenshot_1](https://user-images.githubusercontent.com/8215580/67015329-0e5fd900-f0ff-11e9-88e8-935df91f2c42.png)
![Screenshot_2](https://user-images.githubusercontent.com/8215580/67014781-19fed000-f0fe-11e9-95d1-162ab6418ee7.png)
[Russian client]

Yestarday I found out that after we gave EP for time in raid (we use Raid menu for that), our random guild members received EP too (1-40 guys that doesn't even raid with us) and even more importantly, some EPs have been reduced randomly, and in some cases GP was reverted to 1.

We collect the entire history of the guild's notes, so we can keep track of such things. Examples:

Guild member 1 was not in raid and his note changed from 0,1 to 8061,1, he now have more EP than anyone
Guild member 2 was in raid and his note changed from 7961,1 to 8011,1, this is okay
Guild member 3 was in another raid (second guild group) and his note changed from 3000,43 to 1850,1

**Comment by leinstay** [comment]
I think the problem is in the index. Looking at the changes in the notes, I see that the EPGPs were read from one person and recorded for other person. At just 11:29 p.m. we had 39 operations with notes (+50 GP to Raid), just as many as the raiders. And in 12 situations the note was writen in the wrong place.

**Comment by Alumian** [comment]
Uhhh type /cep debug and copy paste the string into here please.

**Comment by leinstay** [comment]
<details><summary>Debug Info</summary><br />Version: 1.12.0<br /><br />GP Modifier: 2<br /><br />Base GP: 1<br /><br />Standby EP: False<br /><br />Standby Offline: False<br /><br />Standby Percent: 50<br /><br />Standby Accept Whispers: False<br /><br />Standby EP by Rank: True<br /><br />Standby EP Manual Delegation: False<br /><br />GUI for Loot: True<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary>High Priestess Jeklik: True<br />Gothik the Harvester: True<br />Buru the Gorger: True<br />Wushoolay: True<br />Lord Kri: True<br />Emperor Vek'nilash: True<br />Ossirian the Unscarred: True<br />Golemagg the Incinerator: True<br />Grand Widow Faerlina: True<br />High Priestess Mar'li: True<br />Majordomo Executus: True<br />High Priest Venoxis: True<br />Gehennas: True<br />Taerar: True<br />Ysondre: True<br />Thane Korth'azz: True<br />High Priest Thekal: True<br />Noth the Plaguebringer: True<br />Lethon: True<br />Moam: True<br />The Prophet Skeram: True<br />Flamegor: True<br />C'Thun: True<br />General Rajaxx: True<br />Princess Huhuran: True<br />Thaddius: True<br />Loatheb: True<br />Lady Blaumeux: True<br />Highlord Mograine: True<br />Heigan the Unclean: True<br />Azuregos: True<br />Doom Lord Kazzak: True<br />Teremus the Devourer: True<br />Jin'do the Hexxer: True<br />Baron Geddon: True<br />Renataki: True<br />Sulfuron Harbinger: True<br />Gri'lek: True<br />Bloodlord Mandokir: True<br />Patchwerk: True<br />Vaelastrasz the Corrupt: True<br />Gluth: True<br />Sapphiron: True<br />Emeriss: True<br />Onyxia: True<br />Princess Yauj: True<br />Kurinnaxx: True<br />Shazzrah: True<br />Ebonroc: True<br />Battleguard Sartura: True<br />Hakkar: True<br />Kel'Thuzad: True<br />Nefarian: True<br />Fankriss the Unyielding: True<br />Lucifron: True<br />Anub'Rekhan: True<br />Hazza'rah: True<br />Viscidus: True<br />Broodlord Lashlayer: True<br />Ayamiss the Hunter: True<br />Ragnaros: True<br />Maexxna: True<br />Ouro: True<br />Vem: True<br />Grobbulus: True<br />Instructor Razuvious: True<br />Razorgore the Untamed: True<br />Magmadar: True<br />Sir Zeliek: True<br />Gahz'ranka: True<br />Emperor Vek'lor: True<br />High Priestess Arlokk: True<br />Firemaw: True<br />Chromaggus: True<br />Garr: True<br /></details><br /><details><summary>EP Values</summary>High Priestess Jeklik: 2<br />Gothik the Harvester: 12<br />Buru the Gorger: 3<br />Wushoolay: 2<br />Lord Kri: 10<br />Emperor Vek'nilash: 10<br />Kurinnaxx: 3<br />Golemagg the Incinerator: 300<br />Grand Widow Faerlina: 12<br />High Priestess Mar'li: 2<br />Majordomo Executus: 300<br />High Priest Venoxis: 2<br />Gehennas: 300<br />Taerar: 7<br />Teremus the Devourer: 7<br />Thane Korth'azz: 15<br />High Priest Thekal: 2<br />Noth the Plaguebringer: 12<br />Lethon: 7<br />Renataki: 2<br />The Prophet Skeram: 10<br />Flamegor: 7<br />C'Thun: 12<br />General Rajaxx: 3<br />Princess Huhuran: 10<br />Thaddius: 15<br />Loatheb: 15<br />Lady Blaumeux: 15<br />Highlord Mograine: 15<br />Heigan the Unclean: 12<br />Onyxia: 400<br />Doom Lord Kazzak: 7<br />Firemaw: 7<br />Chromaggus: 7<br />Baron Geddon: 300<br />Sulfuron Harbinger: 300<br />High Priestess Arlokk: 2<br />Gri'lek: 2<br />Gahz'ranka: 2<br />Emperor Vek'lor: 10<br />Gluth: 12<br />Sapphiron: 15<br />Ysondre: 7<br />Razorgore the Untamed: 7<br />Vem: 10<br />Ouro: 10<br />Ayamiss the Hunter: 3<br />Shazzrah: 300<br />Ragnaros: 500<br />Battleguard Sartura: 10<br />Maexxna: 15<br />Kel'Thuzad: 15<br />Nefarian: 10<br />Fankriss the Unyielding: 10<br />Lucifron: 300<br />Anub'Rekhan: 12<br />Hazza'rah: 2<br />Broodlord Lashlayer: 7<br />Viscidus: 10<br />Ossirian the Unscarred: 4<br />Bloodlord Mandokir: 2<br />Hakkar: 3<br />Ebonroc: 7<br />Princess Yauj: 10<br />Grobbulus: 12<br />Instructor Razuvious: 12<br />Emeriss: 7<br />Magmadar: 300<br />Sir Zeliek: 15<br />Vaelastrasz the Corrupt: 7<br />Patchwerk: 12<br />Moam: 3<br />Azuregos: 7<br />Jin'do the Hexxer: 2<br />Garr: 300<br /></details><br /><details><summary>Standby Guild Ranks</summary>Вождь: False<br />Рейд Лидер: False<br />Офицер: False<br />Класс лидер: False<br />Рейдер: False<br />Участник: False<br />Новичок: False<br />Штрафник: False<br /></details><br /><details><summary>Slot Weights</summary>2HWEAPON: 2<br />NECK: 0.5<br />HEAD: 1<br />WEAPON: 1.5<br />WRIST: 0.5<br />WEAPONMAINHAND: 1.5<br />SHIELD: 0.5<br />HOLDABLE: 0.5<br />RANGED: 0.5<br />SHOULDER: 0.75<br />FEET: 0.75<br />LEGS: 1<br />EXCEPTION: 1<br />WAIST: 0.75<br />TRINKET: 0.75<br />HAND: 0.75<br />ROBE: 1<br />CHEST: 1<br />CLOAK: 0.5<br />FINGER: 0.5<br />WEAPONOFFHAND: 0.5<br />RANGEDRIGHT: 0.5<br />RELIC: 0.5<br />THROWN: 0.5<br /></details><br /><details><summary>Override List</summary></details><br /><details><summary>Addons List</summary><br />AtlasLootClassic<br />Auc-Advanced<br />Auc-Filter-Basic<br />Auc-Stat-Histogram<br />Auc-Stat-iLevel<br />Auc-Stat-Purchased<br />Auc-Stat-Simple<br />Auc-Stat-StdDev<br />Auc-Util-FixAH<br />BigWigs<br />Capping<br />CEPGP<br />ClassicCodex<br />ClassicThreatMeter<br />Decursive<br />Details<br />Details_TinyThreat<br />Guild_Roster_Manager<br />HandyNotes<br />HandyNotes_DungeonLocations (Classic)<br />Immersion<br />Mapster<br />MikScrollingBattleText<br />RealMobHealth<br />Stubby<br />TidyPlates_ThreatPlates<br />TomTom<br />VanasKoS<br />VendorPrice<br />CharacterStatsClassic<br />DSM<br />ElvUI<br /></details></details>

**Comment by Alumian** [comment]
Ah yep, you're an out of date version and that particular version is quite unstable. Update your addon to the latest version and it won't happen again.
