### ISSUE TITLE
[Request] Online database

### ISSUE THREAD

**Issue by killes007** [Alumian/CEPGP-Retail#75]
If it's possible make the exportable output suitable to import into EPGPWeb site.

**Comment by Alumian** [comment]
What format does it accept?

**Comment by killes007** [comment]
http://www.epgpweb.com/upload/
some kind of JSON data, doesn't know the original retail wow addon source code

**Comment by Alumian** [comment]
Alright well I need you to tell me what kind of format you want it in. That link you posted doesn't tell me anything lol. Give me an example of an entry that I can use as a guide.

**Comment by Alumian** [comment]
Rejecting due to lack of information.
