### ISSUE TITLE
[Bug] EPGP Modifications Not Being Shared

### ISSUE THREAD

**Issue by afonsohfontes** [Alumian/CEPGP-Retail#83]
It would be great to have a report on guild chat for every EP/GP change that happens. Today the addons is only reporting item distributions, decays, resets and mass awards.

This would be great so everyone knows exactly the master looter is individually changing on a player's score. Sometimes I distribute loot with a wrong GP value. To fix that I simple click on the player and add/remove GP points. But the fact this 'fix' isn't reported in the guild chat leads to confusion.

**Comment by Alumian** [comment]
This is actually a bug - EPGP modifications are supposed to be shared but they're not at the moment. I'm investigating.

**Comment by Alumian** [comment]
Fixed in the next update.
