### ISSUE TITLE
Report/reply when players are added/removed to the standby list.[Request]

### ISSUE THREAD

**Issue by afonsohfontes** [Alumian/CEPGP-Retail#85]
Repling to players when they are added to the standby list would be great. I get a lot of "did it work?" every raid night.

Reporting in the guild or whisper when a player is removed to the standby list would also be great. As in order to check if our standby is not AFK, we keep removing them from the list from time to time.

**Comment by Alumian** [comment]
Happy to add this, but I'm going to add it as an addon message rather than a game message to avoid spam. The implication of this is that the recipient needs to have the addon installed to receive the message.

**Comment by Alumian** [comment]
Added in the new beta. Check the discord for this version.

**Comment by afonsohfontes** [comment]
Great news! Many thanks!

**Comment by Alumian** [comment]
Added in https://github.com/Alumian/CEPGP-Retail/commit/0b4fe36e59a22cf154a95da8ba4aac0a741540a3.
