### ISSUE TITLE
[Bug] CEPGP.lua OVERRIDE_INDEX entries with extra space

### ISSUE THREAD

**Issue by Andrioden** [Alumian/CEPGP-Retail#89]
The OVERRIDE_INDEX entries are saved with an extra space after the name, not sure the consequence of this, but thought I should report it!

``` lua
OVERRIDE_INDEX = {
	["Aurastone hammer "] = 100,
	["Aged core leather gloves "] = 112,
}
```
```C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\[YOURACC]\SavedVariables\CEPGP.lua```

**Comment by Alumian** [comment]
Yeah I saw that. No idea why it's happening atm. I wrote a fix a few versions ago to accommodate for it but I'm trying to find the problem.

**Comment by PibbzTV** [comment]
The consequence is that the override won't work. We've tried it, the item won't be recognized.
A workaround is to remove the extra space and save the file. It works perfectly then :)

**Comment by Alumian** [comment]
Fixed in the current beta version.
