### ISSUE TITLE
Response Window for Players when Loot Drops.  Similar to RC Lootcouncil

### ISSUE THREAD

**Issue by TheGreekOne** [Alumian/CEPGP-Retail#9]
I would like for a response window to populate for players when loot drops.

I would like it to have options for Need/Greed/Minor Upgrade/Pass and the option to leave a Note for the Loot Council.  It would be nice if you could also change the response options.  You could also have options for Main Spec/Off Spec/2 Piece/4 Piece.... etc.  It would be nice if you could choose what options you wanted available for players.

This is similar functionality to RC Lootcouncil.

Attached I have shown an example of the response window I was referring to.

![LC Response Window](https://user-images.githubusercontent.com/33552209/62848396-79c59e80-bca9-11e9-85b7-d05348a24f08.PNG)

**Comment by hbjose** [comment]
Haha, i asked that yesterday at curseforge. Thanks TheGreekOne for the request :)

This would be awesome.
Another addon, which could do this, was EPGP_Lootmaster.

**Comment by Alumian** [comment]
Hey guys,

Thanks for submitting this request. I managed to squeeze this feature in before the stress test closed, but it's not exactly in a state that I'm happy with. It's functional, but not pretty and the implementation isn't exactly the most intricate. I'll continue work on it once classic wow is released.

Thanks!

**Comment by TheGreekOne** [comment]
You are the man!  For real this is going to help so many guilds.  If you want us to test anything in particular please let me know, thanks!

**Comment by Alumian** [comment]
@hbjose I was thinking for my implementation, I was just going to do one item at a time rather than all items like what is seen in the screenshot you provided. Does that faze you at all?

**Comment by TheGreekOne** [comment]
I think that is totally fine.  I am thinking and I don't see why that would be an issue.  If it ever became one in the future then I guess we could re-visit.

**Comment by Alumian** [comment]
Hi @TheGreekOne,
I just wanted to let you know that your feature has reached a functional state and is ready for implementation. Although it's not the prettiest, I'll work to clean it up once I've gotten through the rest of the feature requests.
Your feature is scheduled for release in the next update.

Thanks

**Comment by TheGreekOne** [comment]
No worries @Alumian !!!

You are the man, seriously appreciate it.  This is a major piece of functionality that will make loot distribution much easier.  

Thank you!!
