### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Scarfony** [Alumian/CEPGP-Retail#90]
**The Error**
Date: 2019-10-23 21:57:13
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\cepgp\Utility.lua line 1177:
   Usage: GuildControlGetRankName(index)
Debug:
   [C]: GuildControlGetRankName()
   cepgp\Utility.lua:1177: CEPGP_button_options_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
(*temporary) = nil

**Describe the bug**
When I /cep show it gives me this message. Additionally, it wont let me import my GMs stuff and when I /cep version it shows that everyone in my guild doesn't have their enable, but they do, and it shows me that I am on 1.12.4 version. 

**To Reproduce**
By /cep show

**Debug Information**
Date: 2019-10-23 22:06:19
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\cepgp\Utility.lua line 1267:
   attempt to concatenate global 'STANDBYPERCENT' (a nil value)
Debug:
   cepgp\Utility.lua:1267: CEPGP_getDebugInfo()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [C]: Show()
   cepgp\Core.lua:246: ?()
   ..\FrameXML\ChatFrame.lua:4609: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4270: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4306: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
info = "<details><summary>Debug Info</summary><br />
Version: 1.12.4<br />
GP Formula: (4.83x(3^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 100<br />
Standby EP: False<br />
Standby Offline: False<br />
"
(*temporary) = "<details><summary>Debug Info</summary><br />
Version: 1.12.4<br />
GP Formula: (4.83x(3^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 100<br />
Standby EP: False<br />
Standby Offline: False<br />
"
(*temporary) = "Standby Percent: "
(*temporary) = nil
(*temporary) = "<br />
"
(*temporary) = "3"
(*temporary) = "^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x"
(*temporary) = "1"
(*temporary) = "<br />"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate global 'STANDBYPERCENT' (a nil value)"

**Comment by Alumian** [comment]
Will it bother you if you lose your CEPGP settings?

**Comment by Scarfony** [comment]
Lose it?

**Comment by Alumian** [comment]
Yes - if it says that STANDBYPERCENT is a nil value that means:
1. The add-on did not initialise successfully
2. Your saved variables for CEPGP either didn't initialise or are malformed.

**Comment by Scarfony** [comment]
Oh yea, I ended up adding values in those places based off what my other guildies had. I was getting these errors before I changed the values.

**Comment by Scarfony** [comment]
I am going to redownload the addon again and see what happens. This will be my forth time redownloading it haha I have also tried downloading it from Cureforge and from this website.

**Comment by Alumian** [comment]
Yeah, I can see from your debug info that your saved variables are completely fried. Go to ../WTF/Account/Accountname/Realmname/SavedVariables/ and delete CEPGP.lua **while your game is closed**

**Comment by Scarfony** [comment]
I just redownloaded it again and it seems like it worked!

**Comment by Alumian** [comment]
Redownloading the add-on isn't going to do anything right now because your saved variables are malformed. You need to delete them or you're going to keep getting this error.

**Comment by Scarfony** [comment]
My other guildies were having issues with it before as well. I think just deleteing it and redownloading it a couple time works

**Comment by Scarfony** [comment]
thank you for the help. I will let you know if anything else comes up.

**Comment by Alumian** [comment]
Alright well glad to see that it's working now, you may encounter issues later which would be related to those variables. If you do, I do recommend that you delete them but hey, if it's working I won't complain.
