### ISSUE TITLE
[Request] Online/Offline Status on standby list

### ISSUE THREAD

**Issue by PibbzTV** [Alumian/CEPGP-Retail#91]
I'd love to see an Online/Offline status in the standby list window. That would make it much easier to add everyone on standby in advance, and when the invite window has closed we can remove the ones that are offline. That means they didnt show up on time and are not eligible for standby EP.

**Comment by Alumian** [comment]
Added in the next version. When a player is offline their entry in the standby frame will go grey and if you mouse over them, it will say "Player Offline".
