### ISSUE TITLE
[Bug] EPGP Traffic List not always showing the item being distributed.

### ISSUE THREAD

**Issue by PibbzTV** [Alumian/CEPGP-Retail#92]
We are running multiple raids, and while the items are being reported correctly in guild chat, they sometimes fail to show up in the traffic list.

![LootList](https://user-images.githubusercontent.com/51060651/67466046-ae10f000-f646-11e9-80c5-6afe9f031fce.jpg)

**Comment by Alumian** [comment]
I've just made a beta release, give that a try and let me know how it goes.

**Comment by Alumian** [comment]
My potential solution is in the 1.12.5 release. If the issue persists after trying with that version, please let me know.

**Comment by PibbzTV** [comment]
Will every masterlooter in every raid need to have this enabled for it to work? Or is it enough that I have it? I'm the one keeping track on loot records anyway.

**Comment by Alumian** [comment]
The person who hands out the loot needs to have it installed. Their client is the one that shares the traffic.

**Comment by PibbzTV** [comment]
Confirmed fixed for 1.12.5.
