### ISSUE TITLE
[Request] View guild EPGP traffic, not just for the raids you've been in

### ISSUE THREAD

**Issue by VidyaViking** [Alumian/CEPGP-Retail#93]
Pretty straightforward concept, we're running splitraids and would like to view the traffic for both our raids in the addon not just the one that each member participated in.
Not sure if it's technically plausible right now but would love to see it.

**Comment by skombag** [comment]
We run 3 way split raids and EPGP traffic is visible from any group. The only issue i encountered was that the new lines of traffic from others get stacked ontop eachother on the top line , gets fixed by /reload.

**Comment by Alumian** [comment]
The frame stacking was fixed in the latest beta and this feature request is actually a bug. Atm the traffic is not being shared by the raid lead. I'm investigating.

**Comment by Alumian** [comment]
There is already a request open for this bug, so I'm going to close this ticket. Please see #83
