### ISSUE TITLE
[Request] Sorting filters

### ISSUE THREAD

**Issue by sostoked** [Alumian/CEPGP-Retail#96]
**Describe the feature you'd like to see in this addon**
More of a QOL feature than anything but it would be really nice to be able to filter the guild or raid view similar to a spreadsheet. On each column allow the header (Class, Rank, etc.) to have a drop-down allowing you to select or deselect individual types or select all. We have a lot of guild alts and they take up so much of the sheet. It would be nice to deselect them or to focus on a specific class or rank etc. 

If that's not feasable would it be possible to have the sorting contain memory so if I press the class header and then press the PR header could it maintain the class sorting with them in order of PR? 

Loving everything so far!

**Comment by Alumian** [comment]
Sounds simple enough, I'll look into it.

**Comment by Alumian** [comment]
Implemented in 1.13.0.
